### ISSUE TITLE
How to enable user and password protection (WSS)？

### ISSUE THREAD

**Issue by seyama-daisuke** [DigDes/SoapCore#1000]
Thank you for this great application developpers.

I want to enable user/password protection on SOAP server that used this SoapCore.

I checked some tech blog and this site, but I did not understand how to that.

Could you please？

**Comment by andersjonsson** [comment]
I've never used it myself, but if I'm correct you can use `.AddSoapWsSecurityFilter(username, password) to enable this.
If you need another behavior you can implement your own filter.

See
https://github.com/DigDes/SoapCore/blob/0f2901846b7eb806ff494c0d2a0e2a5b78ae90c5/src/SoapCore/SoapEndpointExtensions.cs#L409-L412
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/WsMessageFilter.cs
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/MessageFilter/WsMessageFilterTests.cs

**Comment by seyama-daisuke** [comment]
Thank you @andersjonsson  san!
With the information you gave me, I was able to enable it without any problem.
