### ISSUE TITLE
Bindings won't be set on SoapSerializer.DataContractSerializer

### ISSUE THREAD

**Issue by Amir-Keshtkar** [DigDes/SoapCore#1001]
I have a service which I want it to have two bindings. something like this (on client side)
![image](https://github.com/DigDes/SoapCore/assets/51176150/f7c5c38d-6983-44aa-b949-dc9032678ec7)

this is my config code :

```csharp
((IEndpointRouteBuilder)app).UseSoapEndpoint<IService>(opt =>
{
    opt.Path = "/Service.svc";
    opt.EncoderOptions = new[]
    {
        new SoapEncoderOptions() { BindingName = "v1Soap", PortName = "v1Soap", MessageVersion = MessageVersion.Soap11WSAddressingAugust2004},
        new SoapEncoderOptions() { BindingName = "v1Soap12", PortName = "v1Soap12", MessageVersion = MessageVersion.Soap12WSAddressingAugust2004 }
    };
    opt.SoapSerializer = SoapSerializer.DataContractSerializer;
});
```
this is the xml binding it create: it appears that the second binding name has not been set.
![image](https://github.com/DigDes/SoapCore/assets/51176150/b51fde4a-8585-41ba-a6ec-cbc0c64689c2)

on the client side (consumer) it returns an error on adding WCF web service reference for having two different bindings:
![image](https://github.com/DigDes/SoapCore/assets/51176150/d0a640f6-e82c-4d15-8433-5c9af45fcc8b)

when i change `SoapSerializer` to `XmlSerializer`, it works like a charm.

**Comment by andersjonsson** [comment]
I think I found the bug responsible for this. I don't use DataContractSerializer myself though. Could you pull https://github.com/andersjonsson/SoapCore.git and test my branch `fix-bindingname-wcf`?

**Comment by Amir-Keshtkar** [comment]
Yes 
I tested it and it is now working.
you fixed it tnx ❤🙏 @andersjonsson

**Comment by andersjonsson** [comment]
A package with the fix (as well as few other features) is now published on nuget.
