### ISSUE TITLE
How to customize response header to client from Soap server side ?

### ISSUE THREAD

**Issue by seyama-daisuke** [DigDes/SoapCore#1004]
We'd like to add custom data into response header in Soap Server.
Could you tell me how to do this ?

**Comment by andersjonsson** [comment]
I haven't tested this myself but you should be able to use [MessageHeader]-attribute in a [MessageContract].
See https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/Serialization/MessageHeadersTests.cs
