### ISSUE TITLE
Connecting  BasicHttpsBinding

### ISSUE THREAD

**Issue by jmperezluna** [DigDes/SoapCore#102]
Hi,

I'm trying to implement a wcf with a BasicHttpsBinding and a https uri. 
I am able to watch the contracts at the browser but I'm not able to add the server reference in a project from visual studio

This is the code im using when i create the endpoint: 

`  BasicHttpsBinding binding = new BasicHttpsBinding(BasicHttpsSecurityMode.Transport);
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
            binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;          
            Api.Configuration.Configure(
              app,
              host => host
                  .UseIf(env.IsDevelopment(), appBuilder => appBuilder.UseDeveloperExceptionPage())
                  .UseHttpsRedirection()
                  .UseStaticFiles()
                   .UseSession(new SessionOptions()
                   {
                       IdleTimeout = TimeSpan.FromMinutes(120)
                   })
                  .UseSoapEndpoint<wsGA>("/wsga.svc", binding, SoapSerializer.XmlSerializer)
                           
            );`

I receive this error : 
Error: Cannot obtain Metadata from https://localhost:5050/Service.svc

I couldn´t find any documentation about it,

Thanks in advance.

**Comment by kotovaleksandr** [comment]
Please share client and server code sample with this case, i can to try reproduce issue on my machine.

**Comment by kotovaleksandr** [comment]
Need sample project
