### ISSUE TITLE
Upgrade the supported frameworks to .NET 8.0 

### ISSUE THREAD

**Issue by PoDaC** [DigDes/SoapCore#1020]
Hi Team,

I have been searching for way to use the SoapCore package with .Net 8.0 and I haven't found any articles useful.
Nothing here as well?

Do we have a plan for it or any workaround?

Thank you,
Daniel

**Comment by PoDaC** [comment]
Hi Team, 

I think that I have found was I was needing.

Thank you! Keep up the good work!

**Comment by jamespfluger-ava** [comment]
@PoDaC please share what you have found!

**Comment by LuciferSam86** [comment]
> Hi Team,
> 
> I think that I have found was I was needing.
> 
> Thank you! Keep up the good work!

What did you find? I am in the same situation, and please respect some netiquette :)

**Comment by PoDaC** [comment]
@LuciferSam86, @jamespfluger-ava  
Hello, I was trying to update our solution to .NET8 and I had a failure calling "UseSoapEndpoint" and I was thinking that I would need this package "SoapCore" supporting .Net8 and I was wrong I had to change and to call it from app builder not under endpoints:
Removed:
    `app.UseEndpoints(endpoints => {
                endpoints.MapSubscribeHandler();
                - endpoints.UseSoapEndpoint<ILRRequest>("/LRRequest.asmx", new BasicHttpBinding());
            });`
Added:
   `app.UseSoapEndpoint<ILRRequest>(
                   "/LRRequest.asmx",
                   new SoapEncoderOptions()
                   );`
Not sure if still works, I couldn't test it yet, but builds, so I moved on.

**Comment by andersjonsson** [comment]
There are too many overloads, unfortunately so some of them collide. I'm hoping that some of them can be removed in future releases. I prefer the ones that has a single Action<SoapCoreOptions> parameter.

You can use SoapCore on endpoints just fine. This is how it looks in my own legacy service

```
app.UseEndpoints(endpoints =>
{
	endpoints.UseSoapEndpoint<IMyService>(opt => 
	{
		opt.Path = "MyService.asmx";
		opt.SoapSerializer = SoapSerializer.XmlSerializer;
		//etc..
	
	});
});
```

or you can call UseEndpoint on IApplicationBuilder directly

```
app.UseSoapEndpoint<IRentalApiService>(opt => {
		opt.Path = "MyService.asmx";
		opt.SoapSerializer = SoapSerializer.XmlSerializer;
		//etc..
	
	});
```

Either of them should work, but I'm personally using the first one

**Comment by Krupek20** [comment]
Hi,

Is upgrade of the supported frameworks to include .NET 8.0 abandoned completely or is there a chance it will be addressed soon?

I am also asking in the context of the current SoapCore release targeting .NET 6.0, which uses dependency system.servicemodel.http, v4.8.1 which is reported as having vulnerabilities (which I found is removed in system.servicemodel.http, v8.1.1).

It would be perfect if both upgrades (of .NET and dependency) are performed.

Thank you.
