### ISSUE TITLE
performance issue as well while reading the body for the soap request, i got the memory dump, and this is the img

### ISSUE THREAD

**Issue by akshaybheda** [DigDes/SoapCore#1026]
some performance issue as well while reading the body for the soap request, i got the memory dump, and this is the img 
![image](https://github.com/DigDes/SoapCore/assets/22575879/aa048d28-98e2-4476-af05-4c743f32eabe)

_Originally posted by @akshaybheda in https://github.com/DigDes/SoapCore/issues/1021#issuecomment-1964225916_

**Comment by andersjonsson** [comment]
Hmm... If the problem truly lies in `ReadMessageAsync` you could try to asynchronously copy the content of stream to a memorystream up top and use that instead.
That will result in more memory usage but might be a worthwhile change anyway.

**Comment by akshaybheda** [comment]
you mean like the PR i created?

**Comment by andersjonsson** [comment]
> you mean like the PR i created?

Yes. Can you test your service with the new code and see if that helped with your performance issues?

**Comment by akshaybheda** [comment]
So, i tested the service locally by referencing through the project, but the real performance i can only test once i have that build on a web app and run load test against it from different regions. 

What i noticed when i ran locally is the cpu percentage was lower compared to current version. I can only tell about if this worked is once i deploy it in production, but anyways this is better since it is async, and does not block threads

**Comment by akshaybheda** [comment]
Also meaning to ask, is there any thing that logs request body only if its bad request or something?

**Comment by andersjonsson** [comment]
> Also meaning to ask, is there any thing that logs request body only if its bad request or something?

Nope. It's certainly possible to do that in a middleware or an ISoapMessageProcessor but there is nothing built in

**Comment by akshaybheda** [comment]
Is there any config to get Content-Length header for net6 application? I always get the Transfer-Encoding but no content length header, in the soapcore lib, in WriteMessageAsync i am able to see that its setting contentLength header, but in my response i dont get that

**Comment by andersjonsson** [comment]
In asp.net core it's left out by design for performance reasons but it is set in WriteMessageAsync, as you've noted.
I have never checked for it myself, so I don't know if there is a bug in SoapCore or if you're running into another issue

**Comment by andersjonsson** [comment]
A new nuget package is on its way now

**Comment by akshaybheda** [comment]
@andersjonsson merge failed due to csproj version needs to be updated

**Comment by akshaybheda** [comment]
https://github.com/DigDes/SoapCore/pull/1028

**Comment by andersjonsson** [comment]
I’ll try to get this sorted later tonight

**Comment by akshaybheda** [comment]
appreciate it

**Comment by andersjonsson** [comment]
The new nuget package should be available now

**Comment by akshaybheda** [comment]
I was able to do a deployment to prod and the results were good, only thing thats being a problem is bunch of Microsoft.AspNetCore.Connections.ConnectionResetException showing up. 

I think thats the same issue as this  https://github.com/dotnet/aspnetcore/issues/45086 . Anything we could do to suppress these? I believe these were 400 bad requests earlier

**Comment by akshaybheda** [comment]
@andersjonsson Microsoft hasn't made any progress about the noise generated by ComExceptions, with that being said, in the middleware, we are logging the errors and that is adding noise to the actual issues if any, you think we should supress the comexceptions as 400 till msft makes any progress

**Comment by akshaybheda** [comment]
![image](https://github.com/DigDes/SoapCore/assets/22575879/09b3c3cc-63a6-4dc9-bf6b-73583340cb83)

These are only for few hours but with lot of traffic, this is generating noise for logs.

**Comment by akshaybheda** [comment]
https://github.com/DigDes/SoapCore/pull/1035

**Comment by akshaybheda** [comment]
I deployed it in prod and it works great. Thanks for all the help
