### ISSUE TITLE
Response of 'HttpGet' requests does not return the response

### ISSUE THREAD

**Issue by utkupub** [DigDes/SoapCore#1038]
hello, 
"HttpGet" requests does not return the response. 

I debugged the project.
in SoapCore project SoapEndpointMiddleware.cs 

at end of the function
private async Task ProcessHttpOperation(HttpContext context, IServiceProvider serviceProvider, string methodName)

Right before the end of the function .. the memory stream need to be seek to beginning. (line 443)
The seek on memory stream helped me. 
			dictionaryWriter.Flush();
			ms.Seek(0, SeekOrigin.Begin);
			await ms.CopyToAsync(context.Response.Body);

NOTE: My function was if helps,
[OperationContract]
public XmlDocument ActivateFlowDef(string authenticationTicket, string domainName, string flowName)
{
    return SrvHelper.SuccessDoc();
}

Regards,
Thank you for your effort..

**Comment by andersjonsson** [comment]
That's odd. Thanks for catching this.
I was just checking something out in the codebase so I could investigate immediately
