### ISSUE TITLE
Starting point for automation

### ISSUE THREAD

**Issue by chrgraefe** [DigDes/SoapCore#104]
Hi,

what is a good starting point to get into automation with a contract first approach.
I've 1 wsdl and 2 xsd's and I'm looking for a good way to generate the parameter classes and the interface.

any idea is appreciated

**Comment by kotovaleksandr** [comment]
Hi, why not wsdl.exe?
https://stackoverflow.com/questions/1394930/how-to-generate-web-service-out-of-wsdl

**Comment by chrgraefe** [comment]
Sorry, but this didn't helped me much. I tried a lot with wsdl.exe and svcutil, but the genrated code isnt usable without editing. I also tried to reverse engineer your ping service via the generated wsdl, but the methods were sligthly different. Can you add an example to your repo. Am I missing something?
The idea behind this issue is to generate a service stub based on a wsdl(contract first). Only the concrete service has to be implemented afterwards.

**Comment by MrJerB** [comment]
I would love to know how to get around this also. The generated code depends heavily on System.Web.Services (which is not available in .NET Core as of writing)
