### ISSUE TITLE
Complex data types

### ISSUE THREAD

**Issue by edsuncor** [DigDes/SoapCore#1057]
Is there a way to not include xsi:type for data types like double using XmlSerializer?

Currently outputting:
`<num xsi:type="Double" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">0</num>`

Would like to get:
`<num>0</num>`

I can see ServiceBodyWriter is checking for types guid, bool, string, enum, but not other types.
Is there an option available to produce this output?

Thanks.

**Comment by andersjonsson** [comment]
There is no built in way to do that.
You could implement it with an ISoapMessageProcessor that modifies the response messages.

Otherwise you are more than welcome to submit a PR
