### ISSUE TITLE
Using AdditionalEnvelopeXmlnsAttributes does not work.

### ISSUE THREAD

**Issue by feseniusstevej** [DigDes/SoapCore#1061]
Is the "opt.AdditionalEnvelopeXmlnsAttributes" no longer working. When I try using code as in your example:

endpoints.UseSoapEndpoint<IService>(opt =>
{
	opt.Path = "/ServiceWithAdditionalEnvelopeXmlnsAttributes.asmx";
	opt.AdditionalEnvelopeXmlnsAttributes = new Dictionary<string, string>()
	{
		{ "myNS", "http://schemas.someting.org" },
		{ "arr", "http://schemas.microsoft.com/2003/10/Serialization/Arrays" }
	};
});

I get the error: "IEndpointRoutBuilder does not contain a definition for AdditionalEnvelopeXmlnsAttributes..... "

**Comment by andersjonsson** [comment]
You need a Type-argument for the method.

I just pasted your code into one of the unit tests in this repo, added a type-argument and then it worked straight away.
https://github.com/DigDes/SoapCore/blob/18cb2db305df1a219e85c61bcd8949324fdf6c70/src/SoapCore.Tests/SoapMessageProcessor/Startup.cs#L52-L57

```
app.UseEndpoints(x =>
			{
				x.UseSoapEndpoint<TestService>(opt =>
				{
					opt.Path = "/ServiceWithAdditionalEnvelopeXmlnsAttributes.asmx";
					opt.AdditionalEnvelopeXmlnsAttributes = new Dictionary<string, string>()
					{
						{ "myNS", "http://schemas.someting.org" },
						{ "arr", "http://schemas.microsoft.com/2003/10/Serialization/Arrays" }
					};
				});

				x.UseSoapEndpoint<TestService>("/ServiceWithProcessor.svc", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);
				x.UseSoapEndpoint<TestService>("/ServiceWithPongProcessor.svc", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);
				x.UseSoapEndpoint<TestService>("/Service.svc", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);
			});
```
