### ISSUE TITLE
Can't use webmethod with accent

### ISSUE THREAD

**Issue by raphadesa** [DigDes/SoapCore#1062]
Hello,

I have an issue on SoapCore when I try tu use a webmethod with an accent, e.g: setTerminée.

I need to use the accent because we are migrating a project from .NET Framework to .NET Core and with .NET Framework this works.

Can you help me with this issue ?

Many thanks, and congrats for this awesome project !!!

Raphaël

**Comment by andersjonsson** [comment]
What issue are you running into?
As far as I can tell it should work if you add a Name or Action with accent to your OperationContractAttribute
![image](https://github.com/DigDes/SoapCore/assets/516834/9014f94d-97dc-435f-b7fb-a2d56cc41240)

**Comment by raphadesa** [comment]
Hello,

Thanks for your reply but I already tried that, when calling the webservice both with SOAPUI and through program call.

I get a HTTP/1.1 400 Bad Request

Thank you !

Raphaël

**Comment by andersjonsson** [comment]
That's odd. 400 should only occur when you get an XmlException.
When I tried it everything worked as it should, so there's most likely an edge case in there somewhere

My recommendation is to clone the repo, make a small unit test that mimics your scenario and debug into the code.

**Comment by raphadesa** [comment]
Hello,

Before I clone the repo here's the configuration I'm using : 


app.UseEndpoints(endpoints =>
{
    endpoints.UseSoapEndpoint<IChronoManagementService>("/ChronoManagement.asmx", new SoapEncoderOptions { BindingName = "ChronoManagementSoap" }, SoapSerializer.XmlSerializer, caseInsensitivePath:true, soapModelBounder:null, wsdlFileOptions:null, indentXml:true, omitXmlDeclaration:true);
}

If you can test this on your side I would be grateful !

Many thanks,

Raphaël

**Comment by raphadesa** [comment]
Hello, if it helps I got it working either by checking "Skip SOAP Action" in SOAP UI or either calling the webservice in GET, which is not a good solution...

Thanks,

Raphaël

**Comment by andersjonsson** [comment]
Unfortunately I can't reproduce your error in a unit test. I've tried with your configuration and with/without SOAPAction header.

Investigate on your end and please report if you find a bug in the SoapCore code (or better yet, submit a PR)

**Comment by raphadesa** [comment]
Hello,

Thanks for your answer !

If seems to be a .NET issue, I'll close that topic because it's a silly idea to include accents into method names, I could get around it by invoking the method as GET.

Thanks for your time !

Raphaël
