### ISSUE TITLE
ambiguous method for UseSoapEndpoint

### ISSUE THREAD

**Issue by ilaurensnl** [DigDes/SoapCore#1065]
There seems to be an issue with ambiguous methods, when using more than default methods for UseSoapEndpoint.

![image](https://github.com/DigDes/SoapCore/assets/6596439/82b67bbd-1476-4479-b301-7e58fef9d70a)

Using version: 1.1.0.49
Framework: .NET 8 (also tried .NET 6)

Is there any workaround for this? It seems to happen when changing the soapserializer.

**Comment by andersjonsson** [comment]
Yes, you can get around it by casting app to one of the mentioned interfaces.
For example: `((IApplicationBuilder)app).UseSoapEndpoint()`

Either that or wrap it in a UseEndpoints call

```
app.UseEndpoints(eb =>
{
    eb.UseSoapEndpoint();
});
```

**Comment by ilaurensnl** [comment]
Thanks, that seems to do the trick! I truly did not think about casting :-)

Will close this item, though it would have been nice being able to find this in the documentation, Thanks!
