### ISSUE TITLE
missing complex out params on client-side when return type is present

### ISSUE THREAD

**Issue by DmitryBryluk** [DigDes/SoapCore#108]
```
    [ServiceContract]
    public interface ISampleService
    {
        [OperationContract]
        bool PingComplexModelOut(ComplexModelInput inputModel, out ComplexModelResponse responseModel, out ComplexModelResponse responseModel2); // responseModel is null for bool, fine for void

        [OperationContract]
        bool EnumMethod(out MyEnum e); // e is not changed for bool, ok for void
    }
```

complex out params are missing when calling on client-side while return type is present in service method. when method is void, it is ok.

the problem is only client-side - while calling with SoapUI, raw xml output is fine

upd: when using [XmlAttribute] on fields of complex out param - these fields are missing even through SoapUI call

is it SoapCore intrinsic problem (i.e. can fix by myself)?

**Comment by DmitryBryluk** [comment]
seems gone with these fixes: https://github.com/DigDes/SoapCore/pull/111 https://github.com/DigDes/SoapCore/pull/112

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.8.4
