### ISSUE TITLE
Question: How to use a custom attribute on a SoapCore service class?

### ISSUE THREAD

**Issue by raminmjj** [DigDes/SoapCore#1080]
I want to create a custom attribute to apply to a SoapCore service class as a filter, specifically for implementing custom authorization. How can I achieve this?

**Comment by andersjonsson** [comment]
You could implement your own IAsyncMessageFilter. See https://github.com/DigDes/SoapCore/blob/a2bcb47e8924efe44a245919a8b48e9101f4dd90/src/SoapCore/WsMessageFilter.cs#L13

Another option would be to use a ISoapMessageProcessor (https://github.com/DigDes/SoapCore?tab=readme-ov-file#using-isoapmessageprocessor) to implement the custom authorization
