### ISSUE TITLE
Newly introduced soap:header attributes are not rendered in documentation

### ISSUE THREAD

**Issue by PFAR** [DigDes/SoapCore#1087]
*.asmx?documentation renders HTML documentation for the soap service. The newly introduced SoapHeaderAttribute shows correctly in the WSDL, but not in the Request Body examples in the HTML documentation

**Comment by andersjonsson** [comment]
Nice catch! Feel like submitting a PR?

The WSDL is deserialized into a SoapDefinition and then the `GenerateDocumentation` is used to build the documentation html. So it should be quite straightforward to add the SoapHeaders
