### ISSUE TITLE
can't serialize fields as xml attributes

### ISSUE THREAD

**Issue by DmitryBryluk** [DigDes/SoapCore#109]
this is needed for making legacy-compatible code in .net core
```
    [XmlType(Namespace = ServiceNamespace.Value)]
    [Serializable]
    public class SomeInfo
    {
        [XmlAttribute]
        public string SomeValue; // need this as xml attribute
    }
```

using DataContractSerializer fields are always xml elements

using XmlSerializer fields are just skipped from output (for the reference - this is out param as in [previous issue](https://github.com/DigDes/SoapCore/issues/108)) upd: this is actual for complex out types, when using old-style single request/response param, it is almost ok (however extra response xml element, as in [this issue](https://github.com/DigDes/SoapCore/issues/98))

is it SoapCore intrinsic problem (i.e. can fix by myself)?

**Comment by DmitryBryluk** [comment]
the problem is inside ServiceBodyWriter.OnWriteBodyContents here:
```value = reader.ReadInnerXml();```
it just skips attributes, will fix it asap

**Comment by DmitryBryluk** [comment]
fix for this: https://github.com/DigDes/SoapCore/pull/112

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.8.4
