### ISSUE TITLE
WSDL served from file with 'import' tag can't be parsed because of '&' character

### ISSUE THREAD

**Issue by kick2nick** [DigDes/SoapCore#1090]
There is '&' in schemaLocation attribute added during schema loading: https://github.com/DigDes/SoapCore/blob/6d9a2d4a4de34b16273e10112b9d4545fe4709ef/src/SoapCore/Meta/MetaFromFile.cs#L111
Attempts to parse such wsdl are failing. After removing 'import' tags from file wsdl parsed successfully.
Suggestions: 
Replace `&` with `&amp;`
Dont't generate schemaLocation for import tags that already have schema url in namespace attribute.

**Comment by andersjonsson** [comment]
Nice catch! Can you submit a PR?

**Comment by kick2nick** [comment]
Yes, I'll submit 
What do you think about this `Dont't generate schemaLocation for import tags that already have schema url in namespace attribute.` ?

**Comment by andersjonsson** [comment]
> What do you think about this `Dont't generate schemaLocation for import tags that already have schema url in namespace attribute.` ?

I agree with your reasoning. Not sure if it can have other side-effects but it seems unlikely

**Comment by andersjonsson** [comment]
I'll close this since your PR is merged
