### ISSUE TITLE
how to change xml namespaces on xml request (servicecontract, messagecontract and operationcontract)

### ISSUE THREAD

**Issue by juliotovar19** [DigDes/SoapCore#1093]
how can I change the default xml namespace to my own namespace instead of using “xmlns:tem=”http://tempuri.org/”, and how can I change the prefix in the request name elements and add namespaces to the request element tag, all of this in the request xml

**Comment by andersjonsson** [comment]
You can set the namespace in your ServiceContractAttribute
![image](https://github.com/user-attachments/assets/4308bb1e-300c-427d-b287-45ff55ab928c)

Namespaces of the request- and response-objects can be set on the respective object with different serialization-attributes

Prefixes can be altered with XmlNamespacePrefixOverrides in SoapCoreOptions when you set up your endpoints
