### ISSUE TITLE
Question: How to add soap:header to the wsdl:input of an soap:operation?

### ISSUE THREAD

**Issue by equipatuequipo** [DigDes/SoapCore#1094]
I am trying to change my SOAP API from .NET Framework to .NET Core. It is currently in use by external agents that I cannot change, so the structure of the calls must remain the same as before to avoid failures, even though internally it will point to a different database. My problem is that I cannot replicate this:

`<wsdl:operation name="Ping">
    <soap12:operation soapAction="ADD/Ping" style="document"/> 
    <wsdl:input>
        <soap12:body use="literal"/>
        <soap12:header message="tns:PingAutentication" part="HeaderAuth" use="literal"/> 
    </wsdl:input>
    <wsdl:output>
        <soap12:body use="literal"/>
    </wsdl:output>
</wsdl:operation>`

I cannot find any documentation on how to make the header go in the input of required values. Is there any way to do this? I tried to do what it says here #1063 , but it did not work.

Thank you.

**Comment by andersjonsson** [comment]
Will the external agents update automatically?

In my own case (when we moved to SoapCore) the wsdl changed but that was ok as long as we could handle the legacy method calls.

You could keep the old wsdl by using it as an external wsdl
https://github.com/DigDes/SoapCore?tab=readme-ov-file#using-with-external-wsdl--xsd-schemas

**Comment by equipatuequipo** [comment]
No, they do not update automatically. The external agents should not notice that anything has changed; they will continue pointing to the same location, making the same calls, and getting the same results.

Are you telling me that even if the headers input doesn’t appear, they will still be sent? I’ve tried doing this, and it’s true that they arrive, but since it’s not defined in the WSDL, when I use SoapUI to create the request template, it doesn’t come with the options that need to be sent in the header you have to know you need to send them.

As for using the old WSDL, I’m not sure if that convinces me because if I need to add a new endpoint, it won’t be added automatically.

From the code in this [line](https://github.com/Yozer/SoapCore/blob/4072dadab304b53cb028d8eccff138e696e1970b/src/SoapCore/Meta/MetaBodyWriter.cs#L724) and the [merge I mentioned in my first message](https://github.com/DigDes/SoapCore/pull/1063), it does seem that this is implemented in what I want to do, but I can’t get it to work. I do the same thing as is done [here](https://github.com/Yozer/SoapCore/blob/4072dadab304b53cb028d8eccff138e696e1970b/src/SoapCore.Tests/Wsdl/Services/IServiceWithSoapHeaders.cs), and this does not generate that tag in the WSDL.

**Comment by andersjonsson** [comment]
If the clients doesn't update according to the new wsdl they will keep sending headers etc. in the same manner as before.

You could use an ISoapMessageProcessor to rewrite old payloads to fit the new service. If a new client connects, or if one of the older ones updates, they'll need to change their payloads according to the new wsdl.

If you only want to use the ISoapMessageProcessor for the older clients you can use a separate endpoint for new clients.

Please note that I'm just thinking out loud here. Based on my own migration of two large legacy services, changes to the wsdl wasn't that big of a deal

**Comment by equipatuequipo** [comment]
Thank you, @andersjonsson, for your help.
But what I really want is to add soap:header to the wsdl:input, as I mentioned in the title.

What do I need to configure in my contract to reach [this](https://github.com/Yozer/SoapCore/blob/4072dadab304b53cb028d8eccff138e696e1970b/src/SoapCore/Meta/MetaBodyWriter.cs#L724) line? I don't understand when operation.HeaderType is not null. 
I have seen that you accepted the merge that adds the header feature; I understand that you will understand how it works and that it functions as it should.

**Comment by andersjonsson** [comment]
I dont know, tbh
Check the code that creates the operations-list. Im guessing that there’s a attribute involved

**Comment by equipatuequipo** [comment]
Okay, thank you anyway, @andersjonsson. I'm going to debug the SoapCore test code involved in this to see how it works.

**Comment by equipatuequipo** [comment]
Achieved, while debugging I discovered that it's necessary to set SoapSerializer.XmlSerializer in the SoapSerializer options to include the header in the input of the WSDL.
