### ISSUE TITLE
sample server :5050/Service.svc - client SOAP UI 

### ISSUE THREAD

**Issue by vrestihnat** [DigDes/SoapCore#116]
Hi.
I tried your sample server on the SOAP UI.
Ping works fine, but PingComplexModel doesn't.
Req:
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:arr="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:sys="http://schemas.datacontract.org/2004/07/System">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:PingComplexModel>
         
         <tem:inputModel>
            
            <tem:StringProperty>oooooooooo</tem:StringProperty>
            <tem:IntProperty>5</tem:IntProperty>
            
            <tem:ListProperty>
               
               <arr:string>x</arr:string>
            </tem:ListProperty>
            <tem:DateTimeOffsetProperty>
               <sys:DateTime>2017-01-01T12:00:00Z</sys:DateTime>
               <sys:OffsetMinutes>30</sys:OffsetMinutes>
            </tem:DateTimeOffsetProperty>
            
            <tem:ComplexListProperty>
               
               <tem:ComplexObject>
                  
                  <tem:StringProperty>t</tem:StringProperty>
                  <tem:IntProperty>6</tem:IntProperty>
               </tem:ComplexObject>
            </tem:ComplexListProperty>
         </tem:inputModel>
      </tem:PingComplexModel>
   </soapenv:Body>
</soapenv:Envelope>`

Res:
`<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <PingComplexModelResponse xmlns="http://tempuri.org/">
         <PingComplexModelResult xmlns:a="http://schemas.datacontract.org/2004/07/Models" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <a:DateTimeOffsetProperty xmlns:b="http://schemas.datacontract.org/2004/07/System">
               <b:DateTime>0001-01-01T00:00:00Z</b:DateTime>
               <b:OffsetMinutes>0</b:OffsetMinutes>
            </a:DateTimeOffsetProperty>
            <a:FloatProperty>1.70141173E+38</a:FloatProperty>
            <a:ListProperty i:nil="true" xmlns:b="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
            <a:StringProperty i:nil="true"/>
         </PingComplexModelResult>
      </PingComplexModelResponse>
   </s:Body>
</s:Envelope>`

From console I got:
`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://it-zaruba:5050/Service.svc text/xml;charset=UTF-8 1388
info: SoapCore.SoapEndpointMiddleware[0]
      Request for operation ISampleService.PingComplexModel received
Input data. IntProperty: 0, StringProperty:
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 279.7362ms 200 text/xml;charset=UTF-8`

Thank you

**Comment by DmitryBryluk** [comment]
try previous versions, I will explore this

**Comment by DmitryBryluk** [comment]
checked just now - svc/DataContractSerializer ok, but XmlSerializer results in exception. it is strange

btw, are you trying sample cs client, or using own-generated wrapper from running service? if last, wrapper is generated incorrectly, see issues how to deal with it. or use sample client, or construct wrapper manually.

**Comment by vrestihnat** [comment]
'asmx' works ok
`app.UseSoapEndpoint<SampleService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);`
I do not understand why you are removing wrapper when xmlserializer is being used.
See bodywriter:
'// do not wrap old-style single element response into additional xml element for xml serializer
var needResponseEnvelope = _serializer != SoapSerializer.XmlSerializer .........
' 
Would it be possible to control it from the higher layer manually?

**Comment by DmitryBryluk** [comment]
> I do not understand why you are removing wrapper when xmlserializer is being used

compare [new style](https://github.com/DigDes/SoapCore/pull/115/commits/203c3d442596a5eeea01fcde6455d3784483f53c#diff-ed0fe1422fb97e84a0ce45349c9fe7a1R21) and [old style](https://github.com/DigDes/SoapCore/pull/115/commits/203c3d442596a5eeea01fcde6455d3784483f53c#diff-ed0fe1422fb97e84a0ce45349c9fe7a1R33) operations

they have to produce same response, but without recent fix, old-style signature will produce extra tag, which brokes compatibility.

what is this compatibility? the old-style operation is written exactly the same as in legacy wcf/ws, su supposed to produce/consume the same response as in legacy, so the legacy clients/services may be interacted with SoapCore

this extra envelope is removed only when no additional out/ref elements are present in operation, so single object is output. may be it worth to clarify the condition for simple types to keep resultName instead of type name, have not checked this.

> Would it be possible to control it from the higher layer manually?

yes, you may implement some switch

**Comment by DmitryBryluk** [comment]
perhaps I will implement something like [LegacyCompatibility] attribute to control additional envelope, need a bit more exploration. indeed other operations may be broken.

**Comment by vrestihnat** [comment]
Hi, 
SOAP UI after update I got invalid wsdl: Error: The value 'ComplexModelResponse&' is an invalid name.

**Comment by DmitryBryluk** [comment]
before, out and ref params were just skipped from wsdl generation. now they are present, but still have the issue to remove '&' chars. btw wsdl generation originally is incomplete and hardly can be used to make contracts.

**Comment by kotovaleksandr** [comment]
Can you check latest from my fork?
https://github.com/kotovaleksandr/SoapCore/commit/82f27661ea143e0221f8a123da2cfd3de0ab6daa
SOAP UI successfully imported wsdl for sample project.

**Comment by DmitryBryluk** [comment]
no '&' in wsdl as I see for my projects too

**Comment by kotovaleksandr** [comment]
@vrestihnat please check on latest sources

**Comment by DmitryBryluk** [comment]
seems DataContract and XmlSerializer attributes are incompatible, so when introducing XmlSerializer attributes on PingComplexModel, it stops working for DataContractSerializer. so just remove XmlSerializer attributes and it should be fine. further will make separate samples for different serialization, have no much time to explore why this happens.

also now handling extra wrapper only when response type have [MessageContractAttribute]

still in progress [here](https://github.com/DmitryBryluk/SoapCore/tree/fix_datacontract_compatibility)

**Comment by DmitryBryluk** [comment]
finished, try it now and see extended samples under serialization tests
