### ISSUE TITLE
xmlReader reads wrong start element?

### ISSUE THREAD

**Issue by tomskarasha** [DigDes/SoapCore#117]
Hi!
I have an issue on SoapCore reading XML body it's first element!
Here is the XML I'm using:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:a="https://someAddress.com/address/AddressSOME" xmlns:b="https://someAddress.com/objectos/ObjectSome">
   <s:Header>
   </s:Header>
   <s:Body>
      <a:someRequest>
         <b:SomeObject>
			<b:DataOne>Once upon a time</b:DataOne>
		</b:SomeObject>
	  </a:someRequest>
	</s:Body>
</s:Envelope>

And these are the models:

    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [XmlRoot(Namespace = "https://someAddress.com/address/AddressSOME", IsNullable = false)]
    [XmlType(AnonymousType = true, Namespace = "https://someAddress.com/address/AddressSOME")]
    public class someRequest
    {
        public someRequest();
        [XmlElement(Namespace = "https://someAddress.com/objectos/ObjectSome")]
        public SomeObject SomeObject { get; set; }
    }

    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [XmlRoot(Namespace = "https://someAddress.com/objectos/ObjectSome", IsNullable = false)]
    [XmlType(AnonymousType = true, Namespace = "https://someAddress.com/objectos/ObjectSome")]
    public class SomeObject
    {
        public SomeObject ();
        public string DataOne{ get; set; }
    }
```
My service interface:
```
    [ServiceContract(Namespace = "https://someAddress.com/address/AddressSOME")]
    public interface ISomeRequestService
    {
        [OperationContract(Action = "https://actionos.com/action/Operation", ReplyAction = "*")]
        ObjectResponse SomeRequest(someRequest someRequest);
    }
```
It calls service just fine, but the `someRequest`  is null, always null!

Then I started to debug and turns out that it reads wrong start element in:
            `xmlReader.ReadStartElement(operation.Name, operation.Contract.Namespace);`
`xmlReader` thinks that `SomeObject ` is the start element, in `someRequest` xml tag it is, but in the body it's not. I think that it should read/take the first, after body not whats in `someRequest` because `someRequest` is first element which needs to be taken.

When I comment out this line:
            `// xmlReader.ReadStartElement(operation.Name, operation.Contract.Namespace);`
Works like a charm, read, deserealized, delivered to operation!

What do you think guys @kotovaleksandr @DmitryBryluk is it fixable different way or not?

**Comment by tomskarasha** [comment]
Did as you told, and received XML as expected with all its elements.
I don't know but looks like when this `xmlReader.ReadStartElement` is called then it shifts `xmlReader` to next element and when it comes to `IsStartElement` then this `xmlReader` shows next element.
hmm...

**Comment by DmitryBryluk** [comment]
some fixes [here](https://github.com/DigDes/SoapCore/pull/120)
I implemented handling of [MessageContract] attribute for request/response, so in provided samples (see tests) it is working. also with these tests you can easier explore what is happening.

**Comment by DmitryBryluk** [comment]
completed, merged to master. try it now and see extended samples under serialization tests

**Comment by tomskarasha** [comment]
Yeah, I see, good solution for issue. 
Only thing is that I can't change that contract to add that `MessageContract` attribute, request contract is generated from XSDs that comes from other system(s).
Is there a possibility to add/mark it somehow differently? hmm...

**Comment by jrummell** [comment]
I added a PR that fixes this issue for me. #239
