### ISSUE TITLE
Using complex models as parameters for service methods

### ISSUE THREAD

**Issue by duszakpawel** [DigDes/SoapCore#12]
Hi guys,

is there a possibility to use complex models as parameters in service methods? I get some errors on deserialization. For example:

`<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" soap:encodingStyle="http://www.w3.org/2003/05/soap-encoding">
<soap:Header>
</soap:Header>
<soap:Body>
	<Reverse>
		<ComplexModel xmlns="http://tempuri.org/">
			<Palindrome>kobyłamamałybok</Palindrome>
		</ComplexModel>
	</Reverse>
</soap:Body>
</soap:Envelope>`

Content-Type: text/xml
SOAPAction: /IPingService/Reverse

With corresponding body model:
`    [DataContract]
    public class ComplexModel
    {
        [DataMember]
        public string Palindrome { get; set; }
    }`

I get an error:
`Exception thrown: 'System.Runtime.Serialization.SerializationException' in System.Runtime.Serialization.dll
Additional information: Error in line 3 position 139. 'EndElement' 'ComplexModel' from namespace 'http://tempuri.org/' is not expected. Expecting element 'Palindrome'.`

**Comment by kotovaleksandr** [comment]
Yes, its possible. I tried you model sample - works fine. Can you provide full sample with client and server code? Serialization exception thrown from client or server?

**Comment by duszakpawel** [comment]
Actually... never mind. It works. I changes some things in the code and it was my fault.
