### ISSUE TITLE
i use faultcontract sucessfully,but cant see fault tag in wsdl

### ISSUE THREAD

**Issue by huxuelin709** [DigDes/SoapCore#124]
As my program has a webservice demand with .netcore2，soapcore is a helpful tool for me, thank you.
In the demand ,i need to create custom fault and show it in wsdl,now i write a sample that use faultcontract and catch the faultException.But when i  request the wsdl ,there aren't the fault tag.I check the source ,i dont find faultDescription.cs, is soapcore support to the fault tag?

**Comment by kotovaleksandr** [comment]
Hi @huxuelin709 !
Yes, FaultContract attribute supported and works fine, you can throw FaultException and generic FaultException with details.
 ```csharp
[OperationContract]
[FaultContract(typeof(FaultDetails))]
void FaultWithDetailsTest(string detais);
```

```csharp
try
{
	serviceClient.FaultWithDetailsTest("fault details test");
}
catch (FaultException<FaultDetails> e)
{
	Console.WriteLine("Fault details: {0}", e.Detail.Message);
}
```

But SoapCore does't support FaultContract in wsdl generation.

**Comment by huxuelin709** [comment]
i cant get custom fault in faultcontractAttribute,so i cant write fault infomation in wsdl,maybe .netcore2.0 isnt support for this,so i close this issue
