### ISSUE TITLE
Adding the contract name should be optional in the soapAction

### ISSUE THREAD

**Issue by scottieslg** [DigDes/SoapCore#134]
I am attempting to use Quickbooks Web Connector to call my ASP.Net Core app.  The webservice action quickbooks is requesting is `soapAction="http://developer.intuit.com/authenticate"`.

Currently, the soapAction is always set to `http://developer.intuit.com/myServiceName/authenticate`

I need a way to customize the soapAction for each OperationContract.

**Comment by sandhyachinta** [comment]
Did you try using ContractAttribute?
like [OperationContract(Action = "http://developer.intuit.com/authenticate")]
