### ISSUE TITLE
Empty SoapAction not skipped

### ISSUE THREAD

**Issue by ms007** [DigDes/SoapCore#135]
Hi

I have to implement a SOAP Server where the WSDL is not under my control. 
In this WSDL there is an empty SoapAction like this: <soap:operation soapAction=""/>

I don't know if this is valid according to the WSDL specification, but it leads to the SoapAction not being found by SoapCore. 

When I'm importing the WSDL to SOAPUI the sample requests are adding the SoapAction Header with SoapAction="". 

The problem ist now that in the GetSoapAction Method inside SoapEndpointMiddleware.cs the SoapAction is not found (because the header is not empty, but "".) [here](https://github.com/DigDes/SoapCore/blob/3f3fdb4f44e0b21f549afc7c71c1f82251306eb8/src/SoapCore/SoapEndpointMiddleware.cs#L80)

And it's resulting in an InvalidOperationException (No operation found for specified action)

At the end of the GetSoapAction method the " are trimmed [see here](https://github.com/DigDes/SoapCore/blob/3f3fdb4f44e0b21f549afc7c71c1f82251306eb8/src/SoapCore/SoapEndpointMiddleware.cs#L156), but then it's too late. Shouldn't the " not be trimmed earlier?

How can I contribute?

**Comment by kotovaleksandr** [comment]
Hi!
Send PR to me.
