### ISSUE TITLE
Multiple bindings

### ISSUE THREAD

**Issue by sandhyachinta** [DigDes/SoapCore#143]
Is` it possible to use multiple bindings for a service? Like soap11 and soap12. My service in .net framework supports both 11 and 12. I added custom binding like below 
`var messageElement = new TextMessageEncodingBindingElement();
            messageElement.MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap11, AddressingVersion.None);

            var messageElement2 = new TextMessageEncodingBindingElement();
            messageElement2.MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.None);

            CustomBinding binding = new CustomBinding(messageElement, messageElement2);`
But it always assigns the first one in the custom binding to the service. Could be because of line `binding.CreateBindingElements().Find<MessageEncodingBindingElement>()` in SoapEndpointExtensions. It works fine with Soap11 requests and error out with soap12. When i change the order i custom binding, The soap12 requests works fine and soap11 request error out.

I get below error:
`The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages.`

**Comment by andres-carrilloAdapt2** [comment]
this error went away after i realized that DataTable serialization is not supported in soapcore and removed the methods that use datatables
