### ISSUE TITLE
the FaultException in soapcore

### ISSUE THREAD

**Issue by HuangWeidong1** [DigDes/SoapCore#146]
it throw a FaultException in service , but I can't catch the FaultException error.  
To catch the FaultException, Do I need to modify the soapcore sound code or modify following code ?

**service code**
public TestResponse GetList()
        {
            Error er = Errors.UnknownError;
            throw new FaultException<MyError>(er, new FaultReason("reason"), new FaultCode("code"), "EvtRead");
        }
**client code**
try
{
ServiceReference.SoapClient soapClient = new ServiceReference.SoapClient();

                var result2 = soapClient .GetList();
}
catch (FaultException<MyError> ex)
            {

                Console.WriteLine(ex);
            }

**Comment by kotovaleksandr** [comment]
Hi! What kind of Exception your catch on client?
