### ISSUE TITLE
Make lib compatible with .net 451 and .net standard 1.6

### ISSUE THREAD

**Issue by ti24horas** [DigDes/SoapCore#15]
To facilitate migration, it must be possible to use this lib with .net451 and lower versions of standard.

**Comment by kotovaleksandr** [comment]
Thank you for contributing. Newest version of package with your changes: [https://www.nuget.org/packages/SoapCore/0.9.0](https://www.nuget.org/packages/SoapCore/0.9.0)

**Comment by ti24horas** [comment]
Thanks @kotovaleksandr keep up the good work!
