### ISSUE TITLE
How to implement an async service method

### ISSUE THREAD

**Issue by mstavrev** [DigDes/SoapCore#152]
Hello,

I'm trying to port an old ASMX based web service to ASP.NET Core, without breaking clients that were generated against the original web service's definition.
I managed to port almost all methods, but I have one method I cannot cover.

The original ASMX definition looks like:

> [WebMethod]
> public bool ApiQueryUserInfo(string userName, out UserInfo userInfo, out string strResult)
> {
> ...
> } 

The semantic is that on success, the service returns true (then the strResult is null or empty string). In case of some failure, the result is false and strResult contains descriptive error information. I know it is not very clever, but this is legacy and I cannot force the clients to change their implemetation.

I have no problem to port it as-is, using SoapCore, but only when the implementation is synchronous.
How can I define it in SoapCore so I can make the implementation to be Task-based, asynchronous.
I tried doing something like:

> 
> public class ApiQueryUserInfoResponse
> {
>     public bool ApiQueryUserInfoResult {get;set;}
>     public UserInfo userInfo {get;set;}
>     public string strResult {get;set;}
> }
> 
> Task \<ApiQueryUserInfoResponse\> ApiQueryUserInfo(string userName);

Unfortunately, it does not produce the same response body as the original ASMX web service and breaks the client.

Is there any notation when creating the Task based interface methods and/or response object class that will make SoapCore generate the same output as for a synchronous version with out parameter(s)?

**Comment by Code-DJ** [comment]
@mstavrev why not have 2 different methods one for sync and another for async. Haven't tried it, just written off the top of my head.

```C#
[WebMethod]
public bool ApiQueryUserInfo(string userName, out UserInfo userInfo, out string strResult)
{
    var task = ApiQueryUserInfoAsync(userName);
    task.Wait();

    var response = task.Result;
    strResult = response.strResult;

    return response.ApiQueryUserInfoResult;
}

[WebMethod]
public async Task<ApiQueryUserInfoResponse> ApiQueryUserInfoAsync(string userName)
{
    // do async work here.
}
```

**Comment by mstavrev** [comment]
If I do that, all incoming requests from old (existing) clients are going to end up calling the sync method. That one shall still consume one thread from the pool on waiting for the async version to complete. I want to have fully async pattern and not waste thread pool threads.

**Comment by andyphilpotts** [comment]
async and out parameters just doesn't work, this is a general async limitation, can you return a class with the bool and the two results (or a tuple)?

**Comment by mstavrev** [comment]
Hello,

I am aware of all async specifics including the impossibility to use out
and/or ref parameters. This is not what I am requesting on the thread.
What I need is a way to write my async method - most likely return a Tuple
as you suggest that would yield the same WSDL as my old ASMX web service,
so it becomes a drop-in replacement.

Right now, this is 100% possible, but only if the method is *not* async.

Best Regards
M. Stavrev

**Comment by mstavrev** [comment]
Any update on this case?
