### ISSUE TITLE
Fault exception handling in BeforeSendReply

### ISSUE THREAD

**Issue by aadurson** [DigDes/SoapCore#157]
When there are some fault exception is coming due to some bad data, repsonse message does not received in  BeforeSendReply method in IMessageInspector.cs.
Example: a model which having a datetime property
	[DataContract]
	public class TestReponse
	{
		[DataMember]
		public DateTime ResponseTime { get; set; }
	}

When we consumed service by client(SOAPUI) and passed ResponseTime  value as blank , it thrown some fault exception like value cannot be string '' from allxsd etc, but did not received response in IMessageInspector.cs class under BeforeSendReply method.

void BeforeSendReply(ref Message reply, object correlationState);

Is there a way to get the fault exception detail for these repose?

Thanks in advance.

Thanks,
Aadurson

**Comment by gorillapower** [comment]
We are also looking for this functionality in the `IMessageInspector.cs`. 

It seems the inspectors are not wrapped in a try-catch and not being formatted using `WriteErrorResponseMessage()` as is happening in other areas like in message filters.

https://github.com/DigDes/SoapCore/blob/e34f9b14478056fa15f2013081a79e8bc7d08bb7/src/SoapCore/SoapEndpointMiddleware.cs#L245

This could be easily wrapped in a try-catch, I could submit a PR for this?

**Comment by Simon-Campbell** [comment]
I have come across this myself and am not sure what the expected outcome is in the following scenario --

1. Unexpected exception is thrown
2. Standard FaultMessage is generated by SoapCore
3. MessageInspector.BeforeSendReply is called with generated FaultMessage
4. MessageInspector.BeforeSendReply throws an exception
5. ???

At the moment SoapCore will try-catch BeforeSendReply, generate a FaultMessage and generate another FaultMessage. 

Should that second, unexpected FaultMessage be routed through to BeforeSendReply? Does this behaviour differ with the fact that SoapCore supports multiple message inspectors?

The other inspectors may not be aware of the failure occurring.
