### ISSUE TITLE
How to remove extra response tag from DataContractSerialized responses

### ISSUE THREAD

**Issue by Mozcatel** [DigDes/SoapCore#163]
I have implemented a soap service, and its respective message contracts accordingly, having svcutil generating only the data contracts, however soapCore's middleware is adding an extra element "WSRequestSiteBlockResult" to the original response message

In short, according to the logic of the program, the following response:

```
<s:Envelope>
   <s:Body>
      <WSRequestSiteBlockResponse>
         <WSRequestSiteBlockResult>
            <a:msgHdr>
            </a:msgHdr>
         </WSRequestSiteBlockResult>
      </WSRequestSiteBlockResponse>
   </s:Body>
</s:Envelope>
```

Should be , in truth:
```
<s:Envelope>
   <s:Body>
      <WSRequestSiteBlockResponse>
            <a:msgHdr>
            </a:msgHdr>
      </WSRequestSiteBlockResponse>
   </s:Body>
</s:Envelope>
```

Any suggestions on what may be causing this to take effect?

**Comment by pep30cula** [comment]
I have same problem
My C# models:
`    [ServiceContract]
    public interface IService
    {
        [OperationContract]
        getActiveServicesResponse getActiveServices();
    }`

`    public class getActiveServicesResponse
    {
        [DataMember]
        public string[] getActiveServicesReturn { get; set; }
    }`

I expect below response:

`<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <getActiveServicesResponse xmlns="http://tempuri.org/">
            <a:getActiveServicesReturn >
               string1
            </a:getActiveServicesReturn>
            <a:getActiveServicesReturn >
               string2
            </a:getActiveServicesReturn>
      </getActiveServicesResponse>
   </s:Body>
</s:Envelope>`

But my response is:

`<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <getActiveServicesResponse xmlns="http://tempuri.org/">
         <getActiveServicesResult xmlns:a="http://schemas.datacontract.org/2004/07/My.Namespace" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <a:getActiveServicesReturn>
               <b:string>string1</b:string>
               <b:string>string2</b:string>
            </a:getActiveServicesReturn>
         </getActiveServicesResult>
      </getActiveServicesResponse>
   </s:Body>
</s:Envelope>`

The final response has some extra tags like getActiveServicesResult and b:string.
What can I do?
