### ISSUE TITLE
Publish latest code to Nuget

### ISSUE THREAD

**Issue by gallivantor** [DigDes/SoapCore#170]
Hi,

There have been various commits since the last 0.9.9 release to Nuget on October 16th

Could we publish the latest code to Nuget at this point?

**Comment by kotovaleksandr** [comment]
Hi! This week, please wait:)

**Comment by kotovaleksandr** [comment]
Please, check: https://www.nuget.org/packages/SoapCore/0.9.9.1
Thanks for help and your PRs, this changes can help to many people.

**Comment by MikelThief** [comment]
Hello, I don't want to create a new issue for same reason. Could you push code again to Nuget? Soap 1.2 is pretty critical for me and using a package would be much more convienient :)

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.9.2 Enjoy:)
