### ISSUE TITLE
Handling Session

### ISSUE THREAD

**Issue by sumantfordev** [DigDes/SoapCore#174]
SOAP usage in ASP.net using Webservice class allowed to create sessions for each SOAP client. IS it possible in .net core as well?
https://docs.microsoft.com/en-us/dotnet/api/system.web.services.webservice?view=netframework-4.7.2
https://docs.microsoft.com/en-us/dotnet/api/system.web.services.webservice.session?view=netframework-4.7.2#System_Web_Services_WebService_Session

**Comment by osmedd** [comment]
I would like this as well, Session handling and authentication are mixed in with a legacy WCF application I am trying to port.

Looking at the stack, SoapCore.SoapEndpointMiddleWare.ProcessOperation has a fully populated HttpContext, which has the Session information in it (assuming you configured things in Startup).  What I have not been able to figure out is how to get these into the SOAP service.  I tried making the service a "scoped" dependency so a new service object is created on each request and then use dependency injection to try and pick up ISession or IHttpContextAccessor.  Both of these attempts failed, though IDistributedCache seems to work.

Obviously I don't understand where these are configured in DI... but it seems like it should be simple to get them...

**Comment by osmedd** [comment]
After a day of poking around I see this all works if you know the correct incantations and review the previous issues on this subject.  Just so the answers are in one place, here we go...

In your Startup.cs, you need the right stuff in ConfigureServices() and Configure().  I used the following for ConfigureServices() (adding the DI for IHttpContextAccessor is critical):
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.TryAddSingleton<IMyService, MyService>();

            services.AddDistributedMemoryCache();

            services.AddSession(options =>
            {
                options.Cookie.Name = "MyLittleSession";
                options.Cookie.IsEssential = true;
            });

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            // services.AddSoapCore();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
```

For Configure():
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseSession();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            // app.UseHttpsRedirection();
            app.UseCookiePolicy();
            app.UseSoapEndpoint<IMyService>("/MyService", new BasicHttpBinding());
            app.UseMvc();
        }
```
In your service implementation, you need to get the IHttpContextAccessor injected.  Note I left the service as a singleton, the HttpContextAccessor you get handed gets you to the right HttpContext.Session for each service invocation:
```
        private ILogger<IMyService> Logger { get; }
        private IDistributedCache Cache { get; }
        private IHttpContextAccessor HttpContextAccessor { get; }
        private ISession Session => HttpContextAccessor.HttpContext.Session;

        public MyService(IDistributedCache cache, IHttpContextAccessor httpContextAccessor, ILogger<IMyService> logger)
        {
            Logger = logger;
            Cache = cache;
            HttpContextAccessor = httpContextAccessor;
        }
```

Finally, in your client code, setup the connection to the service like this:
```
            var binding = new BasicHttpBinding();
            binding.AllowCookies = true;
            var endpoint = new EndpointAddress(new Uri(string.Format("http://{0}:5050/MyService", Environment.MachineName)));
            var channelFactory = new ChannelFactory<IMyService>(binding, endpoint);
            var serviceClient = channelFactory.CreateChannel();

            var sessionId = serviceClient.SessionID();
            Console.WriteLine($"Session Id: '{sessionId}'");
```

One critical point I did not immediately grasp was that if you do not update the session cache, the session cookie is NOT transmitted to the client.  I ended up poking a value into the session just to make sure it stayed around.  It made things easier to test against, at least in my opinion.

I think this issue can be closed.

**Comment by kotovaleksandr** [comment]
@osmedd Thanks!
