### ISSUE TITLE
DataTable

### ISSUE THREAD

**Issue by andres-carrilloAdapt2** [DigDes/SoapCore#176]
Trying to use DataTable type in my Contracts cause the wsdl not to show up and also prevents me from creating client proxies. 

I can overcome this error by checking the type and adding wsdl tags in soapcore project code, but I'm not sure if this is the correct way to go.

**Comment by kotovaleksandr** [comment]
check on my fork: https://github.com/kotovaleksandr/SoapCore

**Comment by kotovaleksandr** [comment]
Resolved in #242
