### ISSUE TITLE
XmlArrayItemAttribute is not honored

### ISSUE THREAD

**Issue by comburo** [DigDes/SoapCore#180]
I'm trying to port an existing .NET Framework WCF service to .NET Core using SOAP Core. Most of it seems to work as-is, which is great! But I just ran into an issue where the original service has an array of strings, but defines the name of the seperate items using an [XmlArryItem] attribute.

I've created a simple test service to illustrate the point.

Consider this Operation Contract:
``` C#
[ServiceContract(Namespace ="urn:test:1")]
public interface ITestService
{
    [OperationContract]
    TestResult ExecuteFunction(string firstParameter, [XmlArrayItem("item")]string[] parameterArray);
}
```

And the result object (not important, but for completeness):
``` C#
public class TestResult
{
    public string Message { get; set; }
}
```

This services uses the XmlSerializer:
``` C#
app.UseSoapEndpoint<TestService>("/Test.svc", new BasicHttpBinding(), SoapSerializer.XmlSerializer, false);
```

The WSDL will look like this (displaying only the relevant part):
``` XML
<xs:element name="ExecuteFunction">
    <xs:complexType>
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="firstParameter" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="1" name="parameterArray" type="tns:ArrayOfString"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="ArrayOfString">
    <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="string" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<xs:element name="ArrayOfString" nillable="true" type="tns:ArrayOfString"/>
```

But with WCF, the WSDL would look like this (displaying only the array):
``` XML
<xs:complexType name="ArrayOfString">
    <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="item" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
<xs:element name="ArrayOfString" nillable="true" type="tns:ArrayOfString"/>
```

Notice how the "name" of an individual array item is different.

I'll try to see if I can track down the issue, fix it and submit a PR, but I have no idea where to start looking. So any pointers would be appreciated :-)

**Comment by kotovaleksandr** [comment]
Hi @comburo! By WCF you mean SoapSerializer.DataContractSerializer?
@andradf Maybe you can help?

**Comment by comburo** [comment]
@kotovaleksandr Hi, no, as mentioned in the issue I'm using the XmlSerializer.

**Comment by cubidobusinesssolutions** [comment]
@kotovaleksandr I think this can be referenced (and closed) in latest [Release 0.9.9.5](https://github.com/DigDes/SoapCore/releases/tag/0.9.9.5), right?

**Comment by cubidobusinesssolutions** [comment]
@comburo This should be released and ready for testing ;)

**Comment by comburo** [comment]
Cool, thanks!
I see a lot of changes have been made so time to plan a re-evaluation :-)

**Comment by comburo** [comment]
I've verified and it now works as expected. Thanks!

**Comment by Eddenn** [comment]
Hello, 
I have the exact same issue with SoapCore 1.1.0.51 in a .NET 8 project.

To summary, this code : 
```c#
[OperationContract]
public Result DeleteEntities(UserToken user,
                             [XmlArray("EntityCodes", IsNullable = true)] 
                             [XmlArrayItem("EntityCode", IsNullable = true)] 
                             List<string> entityCodeList)
``` 
result in WSDL : 
```html
<xsd:element name="DeleteEntities">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="1" name="user" type="tns:UserToken"/>
      <xsd:element minOccurs="0" maxOccurs="1" name="entityCodeList" nillable="true" type="tns:ArrayOfString"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
``` 
instead of : 
```html
<xsd:element name="DeleteEntities">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="1" name="user" type="tns:UserToken"/>
      <xsd:element minOccurs="0" maxOccurs="1" name="EntityCodes" nillable="true" type="tns:ArrayOfEntityCode"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
```

**Comment by Eddenn** [comment]
I created a new issue here : https://github.com/DigDes/SoapCore/issues/1106
