### ISSUE TITLE
SOAP 1.2 WSDL

### ISSUE THREAD

**Issue by giannicic** [DigDes/SoapCore#181]
Hi all,

I'm using this package to create a SOAP service but the customer required me to generate a SOAP 1.2 WSDL (because they have a tool that sends SOAP requests only with this format).
I've used the following code in order to generate it (taken from one of your tests):
```
var transportBinding = new HttpTransportBindingElement();
var textEncodingBinding = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressing10, System.Text.Encoding.UTF8);
var customBinding = new CustomBinding(transportBinding, textEncodingBinding);
app.UseSoapEndpoint<MyService>("/MyService", customBinding, SoapSerializer.DataContractSerializer);
```

But he said that this is not good because the soap namespace of the WSDL is still at 1.1 version. It should be `http://schemas.xmlsoap.org/wsdl/soap12/` instead it's `http://schemas.xmlsoap.org/wsdl/soap/`

Looking at the [code](https://github.com/DigDes/SoapCore/blob/master/src/SoapCore/MetaMessage.cs#L37) it seems that the soap namespace is not dependent on the binding, it's always a SOAP 1.1 namespace regardless of the binding used.

Is it a bug?

I've also tried to do a test client using the Add Web Reference Wizard and, when calling the methods i got the following error:
`ArgumentException: The envelope version of the incoming message (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)) does not match that of the encoder (Soap12 (http://www.w3.org/2003/05/soap-envelope)). Make sure the binding is configured with the same version as the expected messages.`

**Comment by TheDevKnight** [comment]
Hi, 
i updated to Swashbuckle.AspNetCore Version="6.2.3" and get now the error that the app.UseSoapEndpoint did not support the signature with the CustomBinding.

```
public static CustomBinding GetSoap12Binding()
{
    var textBindingElement = new TextMessageEncodingBindingElement(MessageVersion.Soap12WSAddressingAugust2004, System.Text.Encoding.UTF8);
    var httpBindingElement = new HttpTransportBindingElement();
    return new CustomBinding(textBindingElement, httpBindingElement);
}

...

// Works with 6.2.3
app.UseSoapEndpoint<Legacy.Service>("/Service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
app.UseSoapEndpoint<Legacy.Service>("/Service/", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);

// ??? 
app.UseSoapEndpoint<Legacy.Service>("/Service2.asmx", Legacy.Service.GetSoap12Binding(), SoapSerializer.XmlSerializer);
app.UseSoapEndpoint<Legacy.Service>("/Service2/", Legacy.Service.GetSoap12Binding(), SoapSerializer.XmlSerializer);

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
```
What is the best and simple way to migrate my code to work with 6.2.3?

Regards
