### ISSUE TITLE
Access RequestMessage from Service Instance

### ISSUE THREAD

**Issue by MrJerB** [DigDes/SoapCore#188]
I tried registering my IMessageFilter as scoped (not using AddSoapMessageFilter extension method) and then tried to access the same scoped instance from my service instance. The result was that the filter was never used by the middleware and the instance even turned up null from my service instance.

Even when registered as a singleton using AddSoapMessageFilter, the instance is not available through constructor injection in my service instance.

I might not need to use the filter at all but I would like a way to (per request) read the SOAP header (same ones as Message.Headers accessible in OnRequestExecuting in IMessageFilter) from within my service instance. What is the recommended way to do this?

Thanks in advance!

**Comment by rokjoana** [comment]
For me it's also happening this problem, and unfortunately there's some services that require custom elements to soap headers in their requests. ¯\_(ツ)_/¯

**Comment by MrJerB** [comment]
> For me it's also happening this problem, and unfortunately there's some services that require custom elements to soap headers in their requests. ¯_(ツ)_/¯

Yep, unfortunately, sometimes we are only implementing contracts not designing them.

**Comment by rokjoana** [comment]
I managed to inspect the message implementing [this](https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/how-to-inspect-or-modify-messages-on-the-client) example and then registering those classes to DI in `ConfigureServices`. I hope it helps you or the next one that stumbles on this issue :)

**Comment by MrJerB** [comment]
I am actually writing the infrastructural bits for a service, using SoapCore middleware for part of it. From my understanding then, your problem was different in that you were actually consuming a service using WCF client. I might have misunderstood you though.

**Comment by rokjoana** [comment]
Yes, I was consuming the service using SoapCore but had to resort to WCF to inspect the messages.
