### ISSUE TITLE
0.9.9.3 breaks WSDL for enums

### ISSUE THREAD

**Issue by MathiasRonnblom** [DigDes/SoapCore#189]
In either 0.9.9.2 or 0.9.9.3 the WSDL-generation seems to have changed quite a bit, and now enums end up like this:
`<xs:element nillable="true" type="tns:MyFunkyEnum"/>`

This is invalid since the element is missing "name", generating an error if you try to create a client.
With 0.9.9.1 this becomes:
`<xs:element minOccurs="1" maxOccurs="1" name="MyFunkyEnum" type="tns:MyFunkyEnum"/>`

This is for code similar to:
```
[DataMember(Order = 3)]
public Enums.MyFunkyEnum MyFunkyEnum { get; set; }
```

I also tried setting a name explicitly, but to no avail:
```
[DataMember(Order = 3, Name = "MyFunkyEnum")]
public Enums.MyFunkyEnum MyFunkyEnum { get; set; }
```

**Comment by kotovaleksandr** [comment]
@MathiasRonnblom Hi! You can check on latest version of master branch?

**Comment by MathiasRonnblom** [comment]
@kotovaleksandr Yes, it works nicely!
