### ISSUE TITLE
Running WCF Test Client not supported

### ISSUE THREAD

**Issue by wbestloanbright** [DigDes/SoapCore#19]
I cloned the latest SoapCore repository; ran the Server project; and tied to connect to it with the WFC Test Client. I received the error: Failed to add the service. Does your solution not support the full Soap protocol? How hard would it be to implement code to connect with WCF Test Client and show the WSDL in the browser at the URL?

Error: Cannot obtain Metadata from http://localhost:5050/Service.svc If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.WS-Metadata Exchange Error    URI: http://localhost:5050/Service.svc    Metadata contains a reference that cannot be resolved: 'http://localhost:5050/Service.svc'.    The content type text/html; charset=utf-8 of the response message does not match the content type of the binding (application/soap+xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: '<!DOCTYPE html><html lang="en" xmlns="http://www.w3.org/1999/xhtml">    <head>        <meta charset="utf-8" />        <title>Internal Server Error</title>        <style>            body {    font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;    font-size: .813em;    color: #222;    background-color: #fff;}h1, h2, h3, h4, h5 {    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/    font-weight: 100;}h1 {    color: #44525e;    margin: 15px 0 15px 0;}h2 {    margin: 10px 5px 0 0;}h3 {    color: #363636;    margin: 5px 5px 0 0;}code {    font-family: Consolas, "Courier New", courier, monospace;}body .titleerror {    padding: 3px 3px 6px 3px;    display: block;    font-size: 1.5em;    font-weight: 100;}body .location {    margin: 3px 0 10px 30px;}#header {    font-size: 18px;    padding: 15px 0;    border-top: 1px #ddd solid;    border-bottom: 1px #ddd solid;    margin-bottom: 0;}    #header li {        display: inline;        ma'.    The remote server returned an error: (500) Internal Server Error.HTTP GET Error    URI: http://localhost:5050/Service.svc    There was an error downloading 'http://localhost:5050/Service.svc'.    The request failed with the error message:--<!DOCTYPE html><html lang="en" xmlns="http://www.w3.org/1999/xhtml">    <head>        <meta charset="utf-8" />        <title>Internal Server Error</title>        <style>            body {    font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;    font-size: .813em;    color: #222;    background-color: #fff;}h1, h2, h3, h4, h5 {    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/    font-weight: 100;}h1 {    color: #44525e;    margin: 15px 0 15px 0;}h2 {    margin: 10px 5px 0 0;}h3 {    color: #363636;    margin: 5px 5px 0 0;}code {    font-family: Consolas, "Courier New", courier, monospace;}body .titleerror {    padding: 3px 3px 6px 3px;    display: block;    font-size: 1.5em;    font-weight: 100;}body .location {    margin: 3px 0 10px 30px;}#header {    font-size: 18px;    padding: 15px 0;    border-top: 1px #ddd solid;    border-bottom: 1px #ddd solid;    margin-bottom: 0;}    #header li {        display: inline;        margin: 5px;        padding: 5px;        color: #a0a0a0;        cursor: pointer;    }    #header .selected {        background: #44c5f2;        color: #fff;    }#stackpage ul {    list-style: none;    padding-left: 0;    margin: 0;    /*border-bottom: 1px #ddd solid;*/}#stackpage .details {    font-size: 1.2em;    padding: 3px;    color: #000;}#stackpage .stackerror {    padding: 5px;    border-bottom: 1px #ddd solid;}#stackpage .frame {    padding: 0;    margin: 0 0 0 30px;}    #stackpage .frame h3 {        padding: 2px;        margin: 0;    }#stackpage .source {    padding: 0 0 0 30px;}    #stackpage .source ol li {        font-family: Consolas, "Courier New", courier, monospace;        white-space: pre;        background-color: #fbfbfb;    }#stackpage .frame .source .highlight li span {    color: #FF0000;}#stackpage .source ol.collapsible li {    color: #888;}    #stackpage .source ol.collapsible li span {        color: #606060;    }.page table {    border-collapse: separate;    border-spacing: 0;    margin: 0 0 20px;}.page th {    vertical-align: bottom;    padding: 10px 5px 5px 5px;    font-weight: 400;    color: #a0a0a0;    text-align: left;}.page td {    padding: 3px 10px;}.page th, .page td {    border-right: 1px #ddd solid;    border-bottom: 1px #ddd solid;    border-left: 1px transparent solid;    border-top: 1px transparent solid;    box-sizing: border-box;}    .page th:last-child, .page td:last-child {        border-right: 1px transparent solid;    }.page .length {    text-align: right;}a {    color: #1ba1e2;    text-decoration: none;}    a:hover {        color: #13709e;        text-decoration: underline;    }.showRawException {    cursor: pointer;    color: #44c5f2;    background-color: transparent;    font-size: 1.2em;    text-align: left;    text-decoration: none;    display: inline-block;    border: 0;    padding: 0;}.rawExceptionStackTrace {    font-size: 1.2em;}.rawExceptionBlock {    border-top: 1px #ddd solid;    border-bottom: 1px #ddd solid;}.showRawExceptionContainer {    margin-top: 10px;    margin-bottom: 10px;}.expandCollapseButton {    cursor: pointer;    float: left;    height: 16px;    width: 16px;    font-size: 10px;    position: absolute;    left: 10px;    background-color: #eee;    padding: 0;    border: 0;    margin: 0;}        </style>    </head>    <body>        <h1>An unhandled exception occurred while processing the request.</h1>            <div class="titleerror">XmlException: Unexpected end of file.</div>                <p class="location">System.Xml.EncodingStreamWrapper.ReadBOMEncoding(bool notOutOfBand)</p>        <ul id="header">            <li id="stack" tabindex="1" class="selected">                Stack            </li>            <li id="query" tabindex="2">                Query            </li>            <li id="cookies" tabindex="3">                Cookies            </li>            <li id="headers" tabindex="4">                Headers            </li>        </ul>        <div id="stackpage" class="page">            <ul>                                    <li>                        <h2 class="stackerror">XmlException: Unexpected end of file.</h2>                        <ul>                            <li class="frame" id="frame1">                                    <h3>System.Xml.EncodingStreamWrapper.ReadBOMEncoding(bool notOutOfBand)</h3>                            </li>                            <li class="frame" id="frame2">                                    <h3>System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)</h3>                            </li>                            <li class="frame" id="frame3">                                    <h3>System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)</h3>                            </li>                            <li class="frame" id="frame4">                                    <h3>System.ServiceModel.Channels.TextMessageEncoderFactory+TextMessageEncoder.ReadMessage(Stream stream, int maxSizeOfHeaders, string contentType)</h3>                            </li>                            <li class="frame" id="frame5">                                    <h3>SoapCore.SoapEndpointMiddleware+<ProcessOperation>d__7.MoveNext() in <code title="C:\git\CEA\SoapCore\SoapEndpointMiddleware.cs">SoapEndpointMiddleware.cs</code></h3>                                    <button class="expandCollapseButton" data-frameId="frame5">+</button>                                    <div class="source">                                            <ol start="67" class="collapsible">                                                    <li><span></span></li>                                                    <li><span>		private async Task<Message> ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)</span></li>                                                    <li><span>		{</span></li>                                                    <li><span>			Message responseMessage;</span></li>                                                    <li><span></span></li>                                                    <li><span>			// Read request message</span></li>                                            </ol>                                        <ol start="73" class="highlight">                                                <li><span>			var requestMessage = _messageEncoder.ReadMessage(httpContext.Request.Body, 0x10000, httpContext.Request.ContentType);</span></li>                                        </ol>                                            <ol start='74' class="collapsible">                                                    <li><span></span></li>                                                    <li><span>			var soapAction = httpContext.Request.Headers["SOAPAction"].ToString().Trim('\"');</span></li>                                                    <li><span>			if (!string.IsNullOrEmpty(soapAction))</span></li>                                                    <li><span>			{</span></li>                                                    <li><span>				requestMessage.Headers.Action = soapAction;</span></li>                                                    <li><span>			}</span></li>                                            </ol>                                    </div>                            </li>                            <li class="frame" id="frame6">                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>                            </li>                            <li class="frame" id="frame7">                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>                            </li>                            <li class="frame" id="frame8">                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.GetResult()</h3>                            </li>                            <li class="frame" id="frame9">                                    <h3>SoapCore.SoapEndpointMiddleware+<Invoke>d__5.MoveNext() in <code title="C:\git\CEA\SoapCore\SoapEndpointMiddleware.cs">SoapEndpointMiddleware.cs</code></h3>                                    <button class="expandCollapseButton" data-frameId="frame9">+</button>                                    <div class="source">                                            <ol start="36" class="collapsible">                                                    <li><span>				if (httpContext.Request.Query.ContainsKey("wsdl"))</span></li>                                                    <li><span>				{</span></li>                                                    <li><span>					responseMessage = ProcessMeta(httpContext, serviceProvider);</span></li>                                                    <li><span>				}</span></li>                                                    <li><span>				else</span></li>                                                    <li><span>				{</span></li>                                            </ol>                                        <ol start="42" class="highlight">                                                <li><span>					responseMessage = await ProcessOperation(httpContext, serviceProvider);</span></li>                                        </ol>                                            <ol start='43' class="collapsible">                                                    <li><span>				}</span></li>                                                    <li><span>			}</span></li>                                                    <li><span>			else</span></li>                                                    <li><span>			{</span></li>                                                    <li><span>				await _next(httpContext);</span></li>                                                    <li><span>			}</span></li>                                            </ol>                                    </div>                            </li>                            <li class="frame" id="frame10">                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>                            </li>                            <li class="frame" id="frame11">                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>                            </li>                            <li class="frame" id="frame12">                                    <h3>Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()</h3>                            </li>                            <li class="frame" id="frame13">                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>                            </li>                            <li class="frame" id="frame14">                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>                            </li>                            <li class="frame" id="frame15">                                    <h3>Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()</h3>                            </li>                            <li class="frame" id="frame16">                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>                            </li>                            <li class="frame" id="frame17">                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>                            </li>                            <li class="frame" id="frame18">                                    <h3>Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()</h3>                            </li>                        </ul>                    </li>                    <li>                        <br/>                        <div class="rawExceptionBlock">                            <div class="showRawExceptionContainer">                                <button class="showRawException" data-exceptionDetailId="exceptionDetail1">Show raw exception details</button>                            </div>                            <div id="exceptionDetail1" class="rawExceptionDetails">                                <pre class="rawExceptionStackTrace">System.Xml.XmlException: Unexpected end of file.   at System.Xml.EncodingStreamWrapper.ReadBOMEncoding(Boolean notOutOfBand)   at System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)   at System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.ReadMessage(Stream stream, Int32 maxSizeOfHeaders, String contentType)   at SoapCore.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext() in C:\git\CEA\SoapCore\SoapEndpointMiddleware.cs:line 73--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()   at SoapCore.SoapEndpointMiddleware.<Invoke>d__5.MoveNext() in C:\git\CEA\SoapCore\SoapEndpointMiddleware.cs:line 42--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()</pre>                            </div>                        </div>                    </li>            </ul>        </div>        <div id="querypage" class="page">                <p>No QueryString data.</p>        </div>        <div id="cookiespage" class="page">                <p>No cookie data.</p>        </div>        <div id="headerspage" class="page">                <table>                    <thead>                        <tr>                            <th>Variable</th>                            <th>Value</th>                        </tr>                    </thead>                    <tbody>                                <tr>                                    <td>Connection</td>                                    <td>Keep-Alive</td>                                </tr>                                <tr>                                    <td>Host</td>                                    <td>localhost:35536</td>                                </tr>                                <tr>                                    <td>MS-ASPNETCORE-TOKEN</td>                                    <td>5448f21e-e110-4c41-91f1-5962096ad4be</td>                                </tr>                                <tr>                                    <td>User-Agent</td>                                    <td>Mozilla/4.0 (compatible; MSIE 6.0; MS Web Services Client Protocol 2.0.50727.8794)</td>                                </tr>                                <tr>                                    <td>X-Original-For</td>                                    <td>127.0.0.1:48602</td>                                </tr>                                <tr>                                    <td>X-Original-Proto</td>                                    <td>http</td>                                </tr>                    </tbody>                </table>        </div>        <script>            //        </script>    </body></html>--.

Going to the URL /Server.svc in a browser I get the Error:
An unhandled exception occurred while processing the request.

XmlException: Unexpected end of file.
System.Xml.EncodingStreamWrapper.ReadBOMEncoding(bool notOutOfBand)

Stack Query Cookies Headers
XmlException: Unexpected end of file.
System.Xml.EncodingStreamWrapper.ReadBOMEncoding(bool notOutOfBand)
System.Xml.EncodingStreamWrapper..ctor(Stream stream, Encoding encoding)
System.Xml.XmlUTF8TextReader.SetInput(Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose)
System.ServiceModel.Channels.TextMessageEncoderFactory+TextMessageEncoder.ReadMessage(Stream stream, int maxSizeOfHeaders, string contentType)
SoapCore.SoapEndpointMiddleware+<ProcessOperation>d__7.MoveNext() in SoapEndpointMiddleware.cs
+
			var requestMessage = _messageEncoder.ReadMessage(httpContext.Request.Body, 0x10000, httpContext.Request.ContentType);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
SoapCore.SoapEndpointMiddleware+<Invoke>d__5.MoveNext() in SoapEndpointMiddleware.cs
+
					responseMessage = await ProcessOperation(httpContext, serviceProvider);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Show raw exception details

**Comment by EricJilot** [comment]
I have been getting the same thing. Is there a resolution as of yet?

**Comment by MFinkBK** [comment]
It seems someone made pull request #45, which could fix this issue, too. I also use WCF Soap WebService from Xamarin app where SoapCore also didn't work yet.

**Comment by kotovaleksandr** [comment]
![image](https://user-images.githubusercontent.com/2936914/43509626-d7ac5ddc-957b-11e8-8b6b-0cc1e2029865.png)
WCF Test Client works fine, thanks community for help!
