### ISSUE TITLE
Simple responses always wrapped

### ISSUE THREAD

**Issue by aschweiz** [DigDes/SoapCore#191]
I found no way to place a simple result directly below the SOAP body as expected by the consumer of the web service:

    <s:Body>
        <ns2:StatusDataOut xmlns:ns2="http://...">true</ns2:StatusDataOut>
    </s:Body>

Simple return types like string trigger needResponseEnvelope in the ServiceBodyWriter's OnWriteBodyContents because there's no MessageContract attribute on the result:

    var needResponseEnvelope = _serializer != SoapSerializer.XmlSerializer || _result == null || (_outResults != null && _outResults.Count > 0) || !_operation.IsMessageContractResponse;

Putting the result in a wrapper class and setting the MessageContractAttribute's parameter IsWrapped to false also doesn't help. The XML serializer includes a node for the wrapper class in between the body and the result.

I've implemented a work-around in ServiceBodyWriter.OnWriteBodyContents to unwrap the result if IsWrapped is set to false, like so:

    var messageContractAttribute = resultType.GetCustomAttribute<MessageContractAttribute>();
        if (messageContractAttribute == null || messageContractAttribute.IsWrapped) {
            serializer.Serialize(writer, _result);
        } else {
            using (var ms = new MemoryStream())
            using (var stream = new BufferedStream(ms)) {
                serializer.Serialize(stream, _result);
                // Remove the wrapper generated by the serializer
                stream.Position = 0;
                XmlDocument xdoc = new XmlDocument();
                xdoc.Load(stream);
                foreach (XmlNode n in xdoc.ChildNodes[1].ChildNodes) {
                     writer.WriteRaw(n.OuterXml);
                }
            }
        }

But I'm not quite sure if I'm missing something here...?

**Comment by uchinago** [comment]
Where is this sitting?   I have the same issue.

**Comment by shanerogers** [comment]
Hey all. @uchinago and @aschweiz, or anyone else. I am having issues with the wrapping class.
Do you know if there is a solution? I'd like to know more about the code you posted. 
How did you use it? The ServiceBodyWriter is an internal class, and not in DI so I cannot change the implementation:
