### ISSUE TITLE
WSDL generation does not generate Name property for Enumeration types.

### ISSUE THREAD

**Issue by uchinago** [DigDes/SoapCore#194]
<xs:element minOccurs="0" name="GroupKey" nillable="true" type="xs:string"/>
 <xs:element nillable="true" type="tns:StatusTypes"/>

The type StatusTypes needs a name, SoapUi fails for missing name/ref on elements.

Just wanted to say you are doing a great job in this code.

**Comment by kotovaleksandr** [comment]
Hi @uchinago ! #189 your case?

**Comment by kotovaleksandr** [comment]
Fixed in #189
