### ISSUE TITLE
Making a testclient. Wsdl generation?

### ISSUE THREAD

**Issue by jphellemons** [DigDes/SoapCore#196]
Hi, I have tried Visual Studio 2019 (16.0.0 preview 2.2) but the add connected service seems broken so I tried: Visual Studio 2017 (15.9.6) which does have the screen. But when I enter the url `https://localhost:5001/myasmx.asmx` it gives a 404. I also tried to add `?wsdl` to the full url.
So do you need the command line wsdl.exe to generate it? Or am I doing something wrong? ps. I have the service running without a debugger and it does display xml/soap on the url.

**Comment by kotovaleksandr** [comment]
Hi, @jphellemons! Show your UseSoapEndpoint call with service url. Url can be case sensitive, you consider it?

**Comment by jphellemons** [comment]
var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
    binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Certificate;
    app.UseSoapEndpoint<IFileController>("/myasmx.asmx", binding, SoapSerializer.XmlSerializer);

I have a method `GetVersion()` with no input parameters which works. But my `Log_on(string username, string password)` does not. I am converting an old vb.net to C# so do parameters have to match casing? I also have an interface to abstract the main class (for unittesting etc.) and have applied `[OperationContract]` on the contracts there. I was re-using the old testtool for the vb.net asmx and wanted to make a new testtool but the _add connected service_ does not seem to work for me. Navigating directly to the asmx endpoint gives me a soap/wsdl in the browser.

**Comment by kotovaleksandr** [comment]
Please, capture http traffic with Fiddler (use full machine name against localhost when add service). Attach log to this issue and service log. If you can create minimal sample with you case - its great, attach it too.

And, may be problem in transport certificate-security?

**Comment by kotovaleksandr** [comment]
Also, you tried use WcfTestClient or SoapUI for you service?

**Comment by jphellemons** [comment]
I used the original (test)client for the old full framework asmx, but also tried SoapUI and got this:
![2019-02-22 08_58_23-soapui 5 4 0](https://user-images.githubusercontent.com/1119134/53227965-1d7dac80-3680-11e9-8b05-c8c3c095e715.png)
Perhaps it's because of our LAN's proxy. Will start looking into WcfTestClient. Strange thing is that I do have a method that works. It's just not taking input parameters. The other method with input parameters does not work (yet)

**Comment by jphellemons** [comment]
The WcfTestClient says:

> Error: Cannot obtain Metadata from https://localhost:5001/myasmx.asmx If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.WS-Metadata Exchange Error    URI: https://localhost:5001/myasmx.asmx    
> Metadata contains a reference that cannot be resolved: 'https://localhost:5001/myasmx.asmx'.    An error occurred while making the HTTP request to https://localhost:5001/myasmx.asmx. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server.    The underlying connection was closed: An unexpected error occurred on a send.    
> Authentication failed because the remote party has closed the transport stream.HTTP GET Error    URI: https://localhost:5001/myasmx.asmx    There was an error downloading 'https://localhost:5001/myasmx.asmx'.    The underlying connection was closed: An unexpected error occurred on a send.    Authentication failed because the remote party has closed the transport stream.

**Comment by kotovaleksandr** [comment]
Looking like transport level error:
* Check with http only, without https
* Check with disabled certificate auth
* Service print errors to log?
