### ISSUE TITLE
WSDL Printing operations twice

### ISSUE THREAD

**Issue by neilsimp1** [DigDes/SoapCore#197]
If I call my service with `/Service.svc?wsdl` to get the WSDL, this prints out a WSDL where each of the SOAP operations are listed two times. I believe this is due to the XmlSerializer going into the implementation class
AND into the interface and creating the XML for both, but I have not done the proper debugging to verify this.

Either way, I did find a solution.

Original:
```
services.AddScoped<ServiceContractImpl>();
```
This worked but generates the WSDL with the operations listed two times.

```
services.AddScoped<IServiceContractImpl>();
```
This corrected the WSDL, but callign any SOAP operations failed since it could not instantiate a service of type `IServiceContractImpl`.

```
services.AddScoped<IServiceContractImpl, ServiceContractImpl>();
```
Combining the two here is what fixed it for me. Both the WSDL and SOAP calls are all working now.

As a side not, I am using `.AddScoped()` instead of a singleton as per the README, since using `.AddSingleton()` gave me runtime errors.

**Comment by kotovaleksandr** [comment]
Hi @neilsimp1 Please attach full example with service registration and UseSoapEndpoint call. Very strange behavior, can't reproduce.

**Comment by smg-bg** [comment]
We are experiencing the same with version 1.0.0.3-alpha. I will try to setup an example.
