### ISSUE TITLE
NuGet : Unable to find package 'SoapCore'

### ISSUE THREAD

**Issue by hungrydev** [DigDes/SoapCore#198]
I am trying to install the NuGet package and get the following. 
I have tried to specify the version but that also fails.   

PM> Install-Package SoapCore
Install-Package : Unable to find package 'SoapCore' at source ''.
At line:1 char:1
+ Install-Package SoapCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.5011841
PM>

**Comment by kotovaleksandr** [comment]
Hi, @hungrydev ! Check package source server, should be nuget.org:
![image](https://user-images.githubusercontent.com/2936914/52853732-84094480-312d-11e9-9423-fdea44af8eff.png)
