### ISSUE TITLE
WSDL attribute “nillable” generate twice

### ISSUE THREAD

**Issue by ntlei** [DigDes/SoapCore#199]
Hi,
i find there is an error  when  input parameter include  an  array type in an action,
I use XmlSerializer.
For example:
 ``` 
public partial class HeaderType  {

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any   {   get;  set;       }
         .......
}
```
  the  generated WSDL ：
```
     <xs:complexType name="ArrayOfXmlElement">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="XmlElement" nillable="true" type="tns:ArrayOfObject"/>
        </xs:sequence>
      </xs:complexType>
```
there are two "nillable" attribute generated and cause an error
I checked the source and   comment  line 470 out in MetaBodyWriter.cs, it works.
Maybe you could fix it.
```
			if (isArray)
				{
					writer.WriteAttributeString("maxOccurs", "unbounded");

					\\writer.WriteAttributeString("nillable", "true");
				}
```
Thanks your great job!

**Comment by kotovaleksandr** [comment]
Hi, @ntlei! Please, check on my fork https://github.com/kotovaleksandr/SoapCore if this fix solve your problem i can merge to main branch and publish new version of nuget package.

**Comment by ntlei** [comment]
> Hi, @ntlei! Please, check on my fork https://github.com/kotovaleksandr/SoapCore if this fix solve your problem i can merge to main branch and publish new version of nuget package.

@kotovaleksandr ,i checked your modification,and test with my project,it works, thank you!
