### ISSUE TITLE
Targeting of 2.2.0?

### ISSUE THREAD

**Issue by phillip-haydon** [DigDes/SoapCore#200]
I'm using this in an AWS .NET Core Lambda, but I'm stuck on 0.9.9 because the latest version targets 2.2.0, while AWS currently only supports 2.1.6

https://github.com/aws/aws-lambda-dotnet/blob/master/README.md#version-status

I downloaded the project and retargeted 2.1.0 and it appears to work perfectly fine. 

I don't want to fork it and host it myself so was wondering if you would be ok with re-targeting so AWS Lambda's can be supported?

**Comment by kotovaleksandr** [comment]
Hi! SoapCore compiled to netstandard2.0 and to netcoreapp2.0. 
```xml
<TargetFrameworks>net461;netstandard2.0;netcoreapp2.0;netcoreapp2.1</TargetFrameworks>
```
For compatibility with .NET Core 2.1.6 netstandard2.0 should be enough. Please, check what version used in project reference, should be netstandard2.0.
Fork its bad idea, if we can't resolve issue on your side - i add new target framework version to SoapCore in nearest release.

**Comment by phillip-haydon** [comment]
Sorry, my bad, I wasn't clear enough. Too early and hadn't had coffee yet.

The issue is AWS Lambda targets:

`<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.6" />`

This includes a reference to `Microsoft.AspNetCore.Http` version `2.1.0`

However https://github.com/DigDes/SoapCore/blob/master/src/SoapCore/SoapCore.csproj currently targets `2.2.0`

```
<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.2.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.2.0" />
```

This is what's causing my issue.

So what I did was drop these back to 2.1.0 and re-compile it locally, then dropped the assembly in and uploaded it to AWS Lambda, and it worked without issue. 

AWS Lambda is a little bit of a pain in this regard. This will hopefully be resolved in the future with Layers

https://github.com/aws/aws-extensions-for-dotnet-cli/issues/58

Which looks like they may be able to support people deploying their own runtimes so we can stay on bleeding edge. But for now I'm stuck :(

**Comment by kotovaleksandr** [comment]
How i can help to you?:) You can use SoapCore as submodule and reference to project until aws will update to latest .NET core and ASP.NET Core.

**Comment by phillip-haydon** [comment]
I was _hoping_ that maybe you would accept dropping the version of those assemblies down. :)

If not, that's totally fine, then I will just compile it myself until AWS supports the newer version of .NET Core. 

Regardless I still appreciate the effort you've put into this project because it's helped me!

I commented on another (closed) thread in regards to authentication, would be good to get auth policies into the contract.
