### ISSUE TITLE
SoapFaults not included in metadata

### ISSUE THREAD

**Issue by MathiasRonnblom** [DigDes/SoapCore#207]
I noticed that SoapCore can handle typed SoapFaults in the response, at least for synchronous methods. Unfortunately, it doesn't work for async methods where it just throws a non-generic FaultException. Also, the faults are not included in the metadata, making it hard to use them on the client side. I have written modifications for the SoapCore code with support for both async and metadata. It would be great to get this incorporated into SoapCore, and I can imagine that more users could use that feature. How would I go about contributing to the repo?

**Details**
Defining this fault in your code:
```
[DataContract(Namespace = "http://mynamespace/IMyService")] // This *must* be the same namespace as on the ServiceContract
public class FieldTooLongFault
{
	[DataMember]
	public int MaximumFieldLength { get; set; }
}
```
And adding it to an operation:
```
[ServiceContract(Namespace = "http://mynamespace/IMyService"))]
public interface IMyService
{
	[OperationContract]
	[FaultContract(typeof(Faults.FieldTooLongFault))]
	Task<Person> GetPerson(GetPersonRequest request);
...
```

Will with my added code produce the following four WSDL segments:
```
<xs:complexType name="FieldTooLongFault">
  <xs:sequence>
    <xs:element minOccurs="0" name="MaximumFieldLength" type="xs:int"/>
  </xs:sequence>
</xs:complexType>
<xs:element name="FieldTooLongFault" nillable="true" type="tns:FieldTooLongFault"/>

<wsdl:message name="IMyService_GetPerson_FieldTooLongFaultFault_FaultMessage">
  <wsdl:part name="detail" element="tns:FieldTooLongFault"/>
</wsdl:message>

<wsdl:fault wsam:Action="http://mynamespace/IMyService/GetPersonFieldTooLongFaultFault" name="FieldTooLongFaultFault" message="tns:IMyService_GetPerson_FieldTooLongFaultFault_FaultMessage"/>

<wsdl:fault name="FieldTooLongFaultFault">
  <soap:fault use="literal" name="FieldTooLongFaultFault"/>
</wsdl:fault>
```

Letting you catch the typed fault in a generated client application:
```
try
{
	var client = new MyServiceClient();
        await client.CallMyServiceWhichThrowsTheFault();
}
catch (FaultException<PersonNotSpecifiedFault> fault)
{
	var faultDetail = fault.Detail;
        int maxFieldLength = faultDetail.MaximumFieldLength;
}
```

**Comment by agpreynolds** [comment]
This looks like a useful feature. To raise a PR you need to do the following:

1. Fork the repo
2. Clone a local copy
3. Make your changes
4. Run the tests making sure they all pass
5. Commit and push your changes
6. Raise a PR, select compare across forks and find your fork

**Comment by MathiasRonnblom** [comment]
@agpreynolds I have created a PR now. Note that I have only added SoapFault support for the MetaWCFBodyWriter, not the MetaBodyWriter since I only use DataContractSerializer and didn't want to add something I haven't tested myself. But it looks very similar, so might be to just copy my changes over..?
