### ISSUE TITLE
Complex model with namespaces does not work

### ISSUE THREAD

**Issue by adriangoneill** [DigDes/SoapCore#210]
Hi,
Using SoapCore 0.9.9.4
I have got a custom object, with a custom namespace:

```
[assembly: ContractNamespace("http://soaptest.net/test",
    ClrNamespace = "SoapTest.Custom")]

namespace SoapTest.Custom
{
    [DataContract]
    public class CustomObject
```

I then have an interface that returns one of those:

```
    [ServiceContract(Name = "SoapTest",
        Namespace = "http://soaptest.net/test")]
    public interface ISoapService
    {
        [OperationContract] CustomObject GetObject();`

```
If I bind to the generated WSDL with a standard C# web reference this doesn't work.  I suspect it relates to the namespace of the returned objects, via SoapUI I can see that XMLSchema-instance is used:

```
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <GetObjectsResponse xmlns="http://soaptest.net/test">
         <GetObjectsResult xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <CustomObject>

```

Any ideas?  Full server, client example code + generated WSDL attached.

[SoapTest.zip](https://github.com/DigDes/SoapCore/files/2950051/SoapTest.zip)

[WSDL.zip](https://github.com/DigDes/SoapCore/files/2950052/WSDL.zip)

**Comment by kotovaleksandr** [comment]
Whats serializer do you use: DataContractSerializer or XmlSerializer? Visual Studio when adding reference show any error message with details? Can you try add service to WCF Test Client?

**Comment by adriangoneill** [comment]
Hi,
This is using the DataContractSeriazer.  VS shows no error when adding reference.  Adding the service to WCF test client fails with the below error, not sure what that means!

```Client.cs(71,18) : error CS0101: The namespace '<global namespace>' already contains a definition for 'SoapTest'
```

However, switching to the XmlSerializer seems to be working - so thanks for that!  I'll experiment tomorrow and see if that resolves the issue.  Thanks!

**Comment by kotovaleksandr** [comment]
Hi @adriangoneill ! Please check you project with latest version on my fork https://github.com/kotovaleksandr/SoapCore. Recently i work on WSDL generation code and on my machine you sample works fine with WCFTestClient.

**Comment by adriangoneill** [comment]
Hi
Thanks for looking at this - it looks like it's partially better, as in some objects are coming across the wire now, but the actual serializatoin doesn't seem to be fully working - see the attached

![noworky](https://user-images.githubusercontent.com/41650559/55192795-458b8e80-519d-11e9-9f63-832d7c76c115.png)
[SoapTest.zip](https://github.com/DigDes/SoapCore/files/3020140/SoapTest.zip)

**Comment by kotovaleksandr** [comment]
Uncomment [DataMember] attribute:
```csharp
[DataMember]
[XmlAttribute]
public string Id { get; set; }

[DataMember]
[XmlAttribute]
public string Name { get; set; }
```

And properties will be sended to client:
![image](https://user-images.githubusercontent.com/2936914/55323835-ebcee100-5488-11e9-9b8a-3537d562fccd.png)

**Comment by adriangoneill** [comment]
Hi, of course, I left that in when I was testing the XmlSerialiser.  Yes, that all works in the sample and in my original solution - thanks!
