### ISSUE TITLE
browsing /Service.svc causes StackOverflowException

### ISSUE THREAD

**Issue by resulguldibi** [DigDes/SoapCore#214]
Now listening on: http://[::]:5050                                               Application started. Press Ctrl+C to shut down.                                  info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]                                 Request starting HTTP/1.1 GET http://localhost:5050/Service.svc                                                                                             Process is terminating due to StackOverflowException.
--

**Comment by kotovaleksandr** [comment]
Can you share you data contract interface with models?

**Comment by resulguldibi** [comment]
I did not change anything in sample project, just run it and browse http://localhost:5050/Service.svc
