### ISSUE TITLE
Is it possible to add soap method that returns DataTable

### ISSUE THREAD

**Issue by resulguldibi** [DigDes/SoapCore#215]
I add sample method to ISampleService interface that returns DataTable, and implement it in SampleService. When I browse /Service.asmx to generate wsdl, I get "System.ArgumentException: .NET type RuntimeTypeHandle cannot be resolved into XML schema type" exception.

**Comment by resulguldibi** [comment]
There is no problem when I replace DataTable with DataSet. But I need to use DataTable.

**Comment by YaroslavKormushyn** [comment]
Seems related to #176

**Comment by kotovaleksandr** [comment]
Please check on my fork https://github.com/kotovaleksandr/SoapCore

**Comment by kotovaleksandr** [comment]
Resolved in #242
