### ISSUE TITLE
Support null arguments

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [DigDes/SoapCore#22]
Hi, 

please support arguments of type `class` passed `null` thus not present in soap message.

Best regards, 
Markus Hartmair

Code example:
Server (ASP.NET Core 2)
```cs
[ServiceContract(Name = "MyService.asmx")]
public interface IMyService
{
    int SomeMethod(int arg1, MyModel arg2, int arg3);
}
```
Client (WebService Reference)
```cs
using (var client = new MySoapService.MyService())
    client.SomeMethod(42, null, 42);
```

Server Exception: 
```
System.Xml.XmlException: Start element 'arg2' from namespace '...' expected. Found element 'arg3' from namespace '...'. Line 1, position 246.
     at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
     at System.Xml.XmlDictionaryReader.MoveToStartElement(String localName, String namespaceUri)
     at SoapCore.SoapEndpointMiddleware.GetRequestArguments(Message requestMessage, OperationDescription operation, Dictionary`2& outArgs)
     at SoapCore.SoapEndpointMiddleware.<ProcessOperation>d__7.MoveNext()
```
Possible fix working for me:
`SoapEndpointMiddleware.cs:GetRequestArguments:160`
```cs
xmlReader.MoveToStartElement(/* no parameters */);
if (xmlReader.IsStartElement(parameterName, operation.Contract.Namespace))
{
    ...
}
else /* handle parameter not present */
{
    arguments.Add(null);
}
```

**Comment by kotovaleksandr** [comment]
I tried to reproduce this issue on latest version, everything works fine. Please, check on latest package: https://www.nuget.org/packages/SoapCore/0.9.4

**Comment by cubidobusinesssolutions** [comment]
Hi, 

@kotovaleksandr still getting the exact same exception. I modified the sample in order to providing a failing test case. Therefore, I created a new console app (.NET Framework 4.6.1) and referenced SampleService from http://localhost:5050/Service.svc via ServiceReference option, see [Client461.zip](https://github.com/DigDes/SoapCore/files/1516976/Client461.zip)

Best regards
Markus

**Comment by kotovaleksandr** [comment]
I fix server code like you say (problem in 4.6.1 wcf client, if argument equals null client not serialized them to message) and server works fine. But, client cant read message with error: 
> 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://tempuri.org/:PingComplexModelResponse. The InnerException message was 'Error in line 1 position 544. 'EndElement' 'PingComplexModelResult' from namespace 'http://tempuri.org/' is not expected. Expecting element 'FloatProperty'.'.  Please see InnerException for more details.'

May be problem in WSDL and Server Reference generate not correct client code.
I can't investigate this problem today, may be you can research this case and make PR?

**Comment by cubidobusinesssolutions** [comment]
Hi,

@kotovaleksandr regarding server error: latest source works for me without any error (the wsdl i generated it from comes from some external source)
Regarding client error: I tried to find out what causes the error and didn't succeed, sry.

Best regards
Markus

**Comment by cubidobusinesssolutions** [comment]
Hi, 

@kotovaleksandr I finally found out what causes the issue with soap clients (see [StackOverflow answer](https://stackoverflow.com/a/2468182/8706545)). However, this fix breaks `new ChannelFactory<ISampleService>`. Therefore, I introduced a configuration option to support both client types. 
```
app.UseSoapEndpoint<SampleService>("/Service.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);
app.UseSoapEndpoint<SampleService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);

```
See pull request #45 

Best regards,
Markus
