### ISSUE TITLE
wsdl adding name prefix tem: to namespace http://tempuri.org.  Want it to be ns1:

### ISSUE THREAD

**Issue by rogerskk** [DigDes/SoapCore#227]

**Comment by rogerskk** [comment]
How can I change the prefix for the namespace in the Soap envelope header to either be ns1:"http://tempuri.org" or no namespace at all?

**Comment by douglassimaodev** [comment]
any update on thins?

**Comment by arogerspro** [comment]
I think I was able to work around it by adding a data annotation above the class for the message like:
[DataContract(Namespace ="http://tempuri.org")]

And for the Message contract:
 [Serializable]
    [MessageContract(IsWrapped = true, WrapperNamespace ="http://tempuri.org")]
