### ISSUE TITLE
XmlAttribute is ignored when wsdl is constructing

### ISSUE THREAD

**Issue by perfectdaemon** [DigDes/SoapCore#238]
Hello!

I'm trying to recreate a SOAP service with existing WSDL-schema. I'm using `XmlSerializer`

I have request class:

```csharp
    [DataContract]
    [MessageContract(WrapperName = "applicationDataRequest", IsWrapped = false)]
    public class ApplicationDataRequestType
    {
        [XmlAttribute("ticketId")]
        public string TicketId { get; set; }

        [XmlAttribute("requestFrom")]
        public string RequestFrom { get; set; }
    }
```
It expected to have schema like this:

```xml
<xs:complexType name="ApplicationDataRequestType">
    <xs:attribute name="ticketId" type="xs:string" use="required" />
    <xs:attribute name="requestFrom" type="xs:string" use="required" />
</xs:complexType>
```

Request processing (when params are passed as attributes) is correct, but WSDL generate this one:
```xml
<xs:complexType name="ApplicationDataRequestType">
    <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" name="TicketId" type="xs:string"/>
        <xs:element minOccurs="0" maxOccurs="1" name="RequestFrom" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
```

I found that `MetaBodyWriter` class completly ignores `XmlAttribute` while constructing WSDL-schema.

**Comment by AloysA** [comment]
I concur, I have the same issue. There is another attribute that is ignored: `[XmlArray()]`

Note that `XmlArrayItem` appears to be used, so I'm surprised `XmlArray` is missing.

``` csharp
        [XmlArray("CompanyImages")]
        [XmlArrayItem("CompanyImage", Type = typeof(CompanyImage))]
        public CompanyImage[] images { get; set; }
```

This yields:
``` xml
<xs:element minOccurs="0" maxOccurs="1" name="images" type="tns:ArrayOfCompanyImage"/>
```

But I would expect it to be:
``` xml
<xs:element minOccurs="0" maxOccurs="1" name="CompanyImages" type="tns:ArrayOfCompanyImage"/>
```

**Comment by AloysA** [comment]
#244 This PR appears to cover the attributes that are mentioned.

Note that there is another missing attribute: `[XmlAttribute]`. If applied to some property, the property should not be an XML element but an attribute on its containing element.
