### ISSUE TITLE
Optional namespace import.

### ISSUE THREAD

**Issue by Ayrat-Kh** [DigDes/SoapCore#245]
Hi, I'm sorry for my English. I am working on some integration with strange system over SOAP. The strange system was written on specific language and while doesn't understand <wsdl:import namespace="namespace-name-of-the-WSDL-definition-to-be-imported"> construction. As I understand import can be optional. If I create PR making import tags optional instead of hardcode, does it make sense? Of course, I will left existing code as is. By default will generate <wsdl:import ... tags, but we will able to add or remove imports.

**Comment by kotovaleksandr** [comment]
Hi! You can create PR with new SoapOptions property like a SkipImportNamespaceTagInWsdl with default value is false.

**Comment by KamranShahid** [comment]
> SkipImportNamespaceTagInWsdl

Where it is. How to initialize it?
