### ISSUE TITLE
Any plans for Nuget release? (0.9.9.5)

### ISSUE THREAD

**Issue by MathiasRonnblom** [DigDes/SoapCore#246]
Are there plans for releasing the next version of SoapCore on Nuget.org? A lot has happened in master since 0.9.9.4. :)

**Comment by kotovaleksandr** [comment]
Hi @MathiasRonnblom!
Welcome https://www.nuget.org/packages/SoapCore/0.9.9.5
Please check your PRs in this release:)

**Comment by MathiasRonnblom** [comment]
@kotovaleksandr Sorry for the delay. I have now verified that 0.9.9.5 works for my application. Thanks!
