### ISSUE TITLE
Enum apear as empty class

### ISSUE THREAD

**Issue by CapitanPlanet** [DigDes/SoapCore#256]
Hi
I cannot host enum field in my ervice. 
In model:
`public Currency Currency { get; set; }`

In declaration:
`public enum Currency
{
        PLN = 0
}`

Result wsdl:
<xs:complexType name="Amount">
< xs:sequence>
< xs:element minOccurs="0" maxOccurs="1" name="Currency" type="tns:Currency"/>
< /xs:sequence>
</xs:complexType>
<xs:element name="Amount" nillable="true" type="tns:Amount"/>
<xs:complexType name="Currency">
< xs:sequence/>
< /xs:complexType>
<xs:element name="Currency" nillable="true" type="tns:Currency"/>

**Comment by CapitanPlanet** [comment]
Ok
error in line 409 in file MetaBodyWriter
`else if (typeInfo.IsValueType && typeInfo.Namespace.StartsWith("System"))`
repleace with
`else if (typeInfo.IsValueType && typeInfo.BaseType.Namespace.StartsWith("System"))`
and it is working fine

**Comment by Simon-Campbell** [comment]
This code change definitely helps. I am trying to understand why the original check was added

**Comment by kotovaleksandr** [comment]
@CapitanPlanet @Simon-Campbell Maybe you can do PR with tests?:)
