### ISSUE TITLE
Changes between WCF (Interface and Models) and SoapCore

### ISSUE THREAD

**Issue by GeordieStew** [DigDes/SoapCore#259]
I've tried to do a simple migration from WCF to SoapCore using the same Interface and Models but it hasn't worked. Is there somewhere I can learn about what I'll need to change?

I have some XML I'm using SoapUI to send to my WCF service app which works. It doesn't work in SoapCore. 

The XML seems incorrect, in that the parent element is missing (Communicate > CameraToInstation in the model, just CameraToInstation in the XML). But it works fine in WCF. 

<Envelope>
  <Body>
    <CameraToInstation> is the XML I'm sending.

First error was: System.InvalidOperationException: No operation found for specified action: CameraToInstation

So, I added an Action="CameraToInstation" to my OperationContract and then.

Start element 'Communicate' from namespace 'http://utmc.uk.com/anpr/schema_1-2' expected. Found element 'CameraToInstation' from namespace 'http://utmc.uk.com/anpr/schema_1-2'.

I guess I need to modify my model/attributes, the model is quite complex, so just checking if there's an easier way! 

Thanks

**Comment by jhaygood86** [comment]
Are you using the 0.9.9.5 nuget, or custom built from develop branch?

There's been a handful of PRs in the last few week or so that makes it more 1:1 replacement

**Comment by GeordieStew** [comment]
0.9.9.5 although I did try the alpha release too.

Which branch would I be best trying with?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jhaygood86** [comment]
develop

**Comment by GeordieStew** [comment]
Still the same issue.

`var operation = _service.Operations.FirstOrDefault(o => o.SoapAction.Equals(soapAction, StringComparison.Ordinal) || o.Name.Equals(soapAction, StringComparison.Ordinal));`

This the line returning no operations. It's due to the payload not containing a <Communicate> tag. 

It doesn't explain why the payload works fine in WCF. I'm tempted to fork your code and "fix" it for me. It's a one of use case.

**Comment by AloysA** [comment]
Try to setup SoapCore in a different way:

```
app.UseSoapEndpoint<ISomeService>("/SomeService", binding, SoapSerializer.XmlSerializer);
```
Note the usage of **SoapSerializer.XmlSerializer**. We had some issues going from WCF to SoapCore as well, this fixed it.

**Comment by GeordieStew** [comment]
> Try to setup SoapCore in a different way:
> 
> ```
> app.UseSoapEndpoint<ISomeService>("/SomeService", binding, SoapSerializer.XmlSerializer);
> ```
> 
> Note the usage of **SoapSerializer.XmlSerializer**. We had some issues going from WCF to SoapCore as well, this fixed it.

Thanks, already tried this and still the same.

It may be some peculiarity with the model and the payload. But still works in WCF.

I think I'll either need to hack or stick with Framework 4.8 for now.

**Comment by kotovaleksandr** [comment]
Hi @GeordieStew! Can you give example of your service and model? And whats application consume your service: classic .NET application, .NET Core application or application developed on other technologies?

**Comment by nicostubi** [comment]
Hello,

I have the same issue.

Here is my service:

```
[ServiceContract(Namespace = "http://www.example.com")]
    [XmlSerializerFormat]
    public interface IFeService
    {

        [OperationContract(Action = "message")]
        MsgResponse RequestData(MsgRequest message);
```

My model:

```
[XmlRoot(ElementName = "message", Namespace = "http://www.example.com")]
    public class MsgRequest 
    {

        [XmlAttribute("version")]
        public string Version { get; set; }
        [XmlElement(ElementName = "req")]
        public MyRequest MyRequest { get; set; }
    }
```

The exception, returned by the service when launching the request from SoapUI:

`Start element 'RequestData' from namespace 'http://www.example.com' expected. Found element 'ex:message' from namespace 'http://www.example'. Line 1, position 197.`

When adding a root element "RequestData" in my XML request in SoapUI, it works like a charm.
But I want to get rid of this root element...

BR
Nicolas
