### ISSUE TITLE
How to handle parameters without namespaces?

### ISSUE THREAD

**Issue by edyrli** [DigDes/SoapCore#267]
am building a new endpoint for an old soap client. This client produces the request like this:
```xml
<soapenv:Envelope` xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://no.reportinghub/services/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:DrillingReport>
		<user>myusername</user>
		<password>mypassword</password>
      </ser:DrillingReport>
  </soapenv:Body>
</soapenv:Envelope>
```
As you can see the <user> and <password> does not contain any namespace reference. And becuase of this the parser fails in this line:
if (xmlReader.IsStartElement(parameterName, parameterNs))
The parameter namespace is http://no.reportinghub/services but the current namespace in the parameter read by xmlReader is empty.

Because i dont own the client software i cant change the request but i have made a bad workaround by simply setting the parameterNs to the namespace coming from xmlReader.

parameterNs = xmlReader.NamespaceURI;
if (xmlReader.IsStartElement(parameterName, parameterNs))

Is there any better way of getting past this?

**Comment by edyrli** [comment]
I was able to get the MessageInspector to do what i needed.

**Comment by kellyprankin** [comment]
@edyrli what did you do to deal with parameters with no namespace?
