### ISSUE TITLE
What's the ETA for an ASP.NET Core 3.0 version?

### ISSUE THREAD

**Issue by IvanFarkas** [DigDes/SoapCore#268]

**Comment by IvanFarkas** [comment]
Any news?

**Comment by kotovaleksandr** [comment]
Hi @IvanFarkas! Whats problem to use current version SoapCore with AspNet Core 3?

**Comment by IvanFarkas** [comment]
Hi @kotovaleksandr. Thank you very much for the quick response and your effort on SoapCore.
My first attempt is at [SoapCoreTest](https://github.com/IvanFarkas/SoapCoreTest) replicating your sample in .NET Core 3.0.
I also would like to offer my help to accomplish the following:

**SoapCore NuGet package To Do**
1. All tests and samples should work seamlessly with .NET Core 3.0 without additional research.
1. Fix ```PingComplexModel()``` method.
1. Use ```app.UseEndpoints()``` instead of ```app.UseSoapEndpoint()```.
```CSharp
app.UseEndpoints(endpoints =>
{
	endpoints.SoapEndpoint<ISampleService>("/Service.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);
	endpoints.SoapEndpoint<ISampleService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);
});
```
1. Update to .NET Core 3.0 for performance and portability.

**Comment by kotovaleksandr** [comment]
Hi Ivan! SoapCore currently compiled for netstandard2.0 and you can use it with .NET Core 3.0 project now. I have this configuration on my work project, everything works fine with all .NET Core 3.0 performance improvements. netcoreapp3.0 target we can add to package when TravisCI start support them. You can make any changes that you consider necessary in PR, they will definitely be accepted.

**Comment by MCFHTAGENTS** [comment]
So I have just tried .NET Core 3.0 and get it all to compile but see this stack trace on loading:
`TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<TStateMachine>(ref TStateMachine stateMachine)
SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)`

Please note I am using version 0.9.9.4 as waiting on #248 to be fixed.

**Comment by kotovaleksandr** [comment]
@MCFHTAGENTS try latest beta version https://www.nuget.org/packages/SoapCore/0.9.9.8-beta

**Comment by MCFHTAGENTS** [comment]
Agreed - this fixes it.
Thank you
Mark

**Comment by ershadnozari** [comment]
Hi gents, is there an example of Program.cs and Startup.cs configuration for Core 3.0? Cheers

**Comment by IvanFarkas** [comment]
Thank you very much for your contribution.
