### ISSUE TITLE
Thoughts on new .NET foundation sponsored implementation?

### ISSUE THREAD

**Issue by richardgavel** [DigDes/SoapCore#271]
What are you thoughts on the recent contribution by the .NET foundation of CoreWCF?

https://devblogs.microsoft.com/dotnet/supporting-the-community-with-wf-and-wcf-oss-projects/

**Comment by kotovaleksandr** [comment]
This is very good news! I want to believe that Microsoft will finish the job and release the production version of the WCF. In this case, I will recommend to all SoapCore users to switch to a Microsoft solution, while the project will be active for existing users and those whom the Microsoft implementation did not suit.
