### ISSUE TITLE
How SoapCore compares to CoreWCF?

### ISSUE THREAD

**Issue by IvanFarkas** [DigDes/SoapCore#273]
### How SoapCore compares to [CoreWCF](https://github.com/CoreWCF/CoreWCF)? ###
See: [How CoreWCF compares to SoapCore?](https://github.com/CoreWCF/CoreWCF/issues/14)

**Comment by kotovaleksandr** [comment]
answered in https://github.com/CoreWCF/CoreWCF/issues/14
