### ISSUE TITLE
Calling SoapCore Wcf service always returns wsdl

### ISSUE THREAD

**Issue by zelenskyMA** [DigDes/SoapCore#275]
.Net Core 2.2 Project .  Adding soapCore (by nuget 0.9.9.5) within Startup
 app.UseSoapEndpoint<IQbContract>("/QbwcService.svc", new BasicHttpsBinding() { Namespace = "http://developer.intuit.com/" } , SoapSerializer.DataContractSerializer);
 app.UseSoapEndpoint<IQbContract>("/QbwcService.asmx", new BasicHttpsBinding() { Namespace = "http://developer.intuit.com/" } , SoapSerializer.XmlSerializer);

Request : https://localhost:10125/QbwcService.asmx (or svc, does not matter)

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:dev="http://developer.intuit.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <dev:authenticate>
         <dev:strUserName>Tester</dev:strUserName>
         <dev:strPassword>test</dev:strPassword>
      </dev:authenticate>
   </soapenv:Body>
</soapenv:Envelope>

When same code added to .net framework in wcf project , same request returns
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <authenticateResponse xmlns="http://developer.intuit.com/">
         <authenticateResult xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <a:string>d6a6bcdf-8075-4f4b-9874-ff20414a93c2</a:string>
            <a:string>C:\Users\Public\Documents\Intuit\QuickBooks\Company Files\FAM17\Sample Retail Company.qbw</a:string>
         </authenticateResult>
      </authenticateResponse>
   </s:Body>
</s:Envelope>

Same is expected from SoapCore project but only wsdl  is returned, no matter what request is made.   Any ideas?

**Comment by Simon-Campbell** [comment]
There is some logic which returns the WSDL in response to providing no request body --

```
			//Return metadata if no request
			if (httpContext.Request.Body.Length == 0)
			{
				return ProcessMeta(httpContext);
			}
```

Double check that your request body is being sent over the network. The other scenario is when you have "wsdl" in your query string *and* doing HTTP get. 

It quite clearly looks like it's the first scenario however (empty request body)
