### ISSUE TITLE
Consider using Routing replace SoapEndpointMiddleware

### ISSUE THREAD

**Issue by pengweiqhca** [DigDes/SoapCore#289]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing#use-routing-middleware

**Comment by Simon-Campbell** [comment]
Hi! 

It would be good to highlight a use-case that this *may* impact. I add middleware on the same routes that SOAP Core services e.g.

```WSDL Provider (I have a custom one to produce from static files) -> XML Schema Validation -> SOAP Core```

Would using the routing middleware interfere with the ability to do this at all? I assume it does not but it would be great if this was confirmed.
