### ISSUE TITLE
Object as parameter is not populated on service side

### ISSUE THREAD

**Issue by waldimen** [DigDes/SoapCore#29]
I have a simple object as a Input Parameter in service call but values  from the client are not filled on the server side. 
So all the properties have default values. The class has [DataContract] and each property has [DataMember] attribute.

Do I need anything special to make it work ?

**Comment by kotovaleksandr** [comment]
Hi, can you provide code sample? Whats difference in your case with samples: https://github.com/DigDes/SoapCore/tree/master/samples

**Comment by waldimen** [comment]
That not seem to be much different,  but adding  [DataContract(Namespace = "http://tempuri.org/")] attribute and putting properties in alpabetical order seems to resolve the issue. 
I will play with sample and let you know.

**Comment by waldimen** [comment]
I was using SoapUI and requests generated from returned wsdl did not have proper data contract namespace and also the order of properties. 
Setting the Namespace in DataContract and putting the properties in alpabetical makes it working now but I thing the wsdl returned is not correct.
