### ISSUE TITLE
More Samples

### ISSUE THREAD

**Issue by spas906** [DigDes/SoapCore#3]
Hi Can we provides sample project?

**Comment by kotovaleksandr** [comment]
Hi, yes: [https://github.com/DigDes/SoapCore/tree/master/samples]()

**Comment by spas906** [comment]
Big thanks Kotov , how about an ASMX sample?

**Comment by kotovaleksandr** [comment]
What is the difference for client? Its soap over http in both cases. You can change service url to service.asmx.
