### ISSUE TITLE
OperationContext.Current is null in .net core

### ISSUE THREAD

**Issue by AnReZa** [DigDes/SoapCore#300]
I'm providing a WCF service in my .net core project via *SoapCore*. In one of the methods, I want to access the SOAP envelope header info. To test that, I've added the following code:

```c#
[ServiceContract]
public interface IDataService {
    [OperationContract]
    string TransmitObject(XElement node);
}

// -------------------------------------------------------------------------

public string TransmitObject(XElement node) {
    foreach(var header in OperationContext.Current.IncomingMessageHeaders) {
        Console.WriteLine(header.ToString());
    }

    return JsonConvert.SerializeXNode(node, Formatting.None);
}
```

However, in this case, the OperationContext.Current attribute is always `null`. What do I need to change in order to make that work?

**Comment by M-Koers** [comment]
Hi, just wondering if you have made any progress regarding this issue, as I am currently running into the same problem.

**Comment by AnReZa** [comment]
@M-Koers Kind of. You can work around the problem by building your own message inspector. I've attached a modified copy of our current source code.
[DataService.txt](https://github.com/DigDes/SoapCore/files/3777700/DataService.txt)

**Comment by M-Koers** [comment]
@AnReZa Thanks for the quick reply and answer! I've also found a work around using a custom IServiceOperationTuner. In the Tune method you get the HttpContext object which also contains the message headers which works for me :)
