### ISSUE TITLE
Model with MessageHeader 

### ISSUE THREAD

**Issue by delianenchev** [DigDes/SoapCore#309]
I'm trying to implement SOAP 1.2. The issue comes from poor interpretation of the MessageHeader attribute. Properties with MessageHeader should be in header, but they are not. 

My demo model with the MessageHeader and MessageBodyMember attributes.
```
[MessageContract]
public class MessageModelRequest
{
[MessageHeader]
public string Id { get; set; }
[MessageBodyMember]
public string Name { get; set; }
[MessageBodyMember]
public string Email { get; set; }
}
```

I test API with SoapUI.

This is my API under ASP.NET core with SoapCore. [OcppDemo](https://github.com/delianenchev/OcppDemo/tree/master/OcppDemo)
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/" xmlns:mod="http://schemas.datacontract.org/2004/07/Models">
   <soap:Header/>
   <soap:Body>
      <tem:TestMessageModel>
         <!--Optional:-->
         <tem:inputModel>
            <!--Optional:-->
            <mod:Email>?</mod:Email>
            <!--Optional:-->
            <mod:Id>1</mod:Id>
            <!--Optional:-->
            <mod:Name>?</mod:Name>
         </tem:inputModel>
      </tem:TestMessageModel>
   </soap:Body>
</soap:Envelope>
```

Correct API from WCF project for IIS. [WCF](https://github.com/delianenchev/OcppDemo/tree/master/WcfInIIS)

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header>
      <tem:Id>34</tem:Id>
   </soapenv:Header>
   <soapenv:Body>
      <tem:MessageModelRequest>
         <!--Optional:-->
         <tem:Email>3</tem:Email>
         <!--Optional:-->
         <tem:Name>4</tem:Name>
      </tem:MessageModelRequest>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by vinguan** [comment]
Have you managed to fix this?

**Comment by delianenchev** [comment]
Unfortunately i didn't do it with SoapCore, i used WCF service for my project.

**Comment by kotovaleksandr** [comment]
@delianenchev Please check your service with latest version https://www.nuget.org/packages/SoapCore/1.0.0-alpha

**Comment by ZlobnyiSerg** [comment]
I can confirm that latest version has 
> NullReferenceException: Object reference not set to an instance of an object

Simple example:
`
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [MessageContract(IsWrapped = false)]
    public class TestMessage
    {
        [MessageHeader]
        public string Security;

        [MessageBodyMember]
        public string Body;

        public TestMessage()
        {
        }

        public TestMessage(string security, string body)
        {
            Security = security;
            Body = body;
        }
    }

    [ServiceContract]
    public interface ITestService
    {
        [OperationContract]
        void Operation(TestMessage message);
    }
`
And it fails with NRE.

Fix is to add commented line:
`private static Type GetMessageContractBodyType(Type type)
		{
			var messageContractAttribute = type.GetCustomAttribute<MessageContractAttribute>();

			if (messageContractAttribute != null && !messageContractAttribute.IsWrapped)
			{
				var messageBodyMembers =
					type
						.GetPropertyOrFieldMembers()
						.Select(mi => new
						{
							Member = mi,
							MessageBodyMemberAttribute = mi.GetCustomAttribute<MessageBodyMemberAttribute>()
						})
						//.Where(x => x.MessageBodyMemberAttribute != null)
						.OrderBy(x => x.MessageBodyMemberAttribute.Order)
						.ToList();

				return messageBodyMembers[0].Member.GetPropertyOrFieldType();
			}

			return type;
		}`

**Comment by kotovaleksandr** [comment]
@ZlobnyiSerg https://www.nuget.org/packages/SoapCore/1.0.0-alpha.1

**Comment by douglassimaodev** [comment]
any idea how to get this sorted? https://stackoverflow.com/questions/66432054/soapcore-asp-net-core-3-1-header
