### ISSUE TITLE
Add possibility to forbid access to WSDL

### ISSUE THREAD

**Issue by apatenotre** [DigDes/SoapCore#320]
The idea is to implement the following property, currently available in a WCF project
* https://docs.microsoft.com/fr-fr/dotnet/api/system.servicemodel.description.servicemetadatabehavior.httpgetenabled?view=netframework-4.8

This allows server to reject GET request on WSDL, and is useful when the service contract should be hidden from the user

**Comment by Simon-Campbell** [comment]
An alternative method for people looking for some work whilst the related PR is in progress: add middleware in-front of SOAP core and intercept the WSDL providing scenarios, those are:

1. GET {ServiceUrl}?wsdl {ServiceUrl} ?singleWsdl
2. The tricky variant: {ServiceUrl} but it has a 0-byte request body. 

You can return whatever you like using the ASP.NET Core middleware pipeline.
