### ISSUE TITLE
Backwards compatibility issue

### ISSUE THREAD

**Issue by VasTheGreek** [DigDes/SoapCore#344]
I am trying to understand some odd behaviour regarding backwards compatibility, so the versions of the projects in the solution are specific. I am trying to get this to work by ONLY changing the endpoint if possible (i.e. not updating the WSDL definition file).

The attached solution represents my scenario.
- There is a test project written in .Net 4.0. This could be the client code and I only wish to change the endpoint IP/Port from it on the config file to connect to the new web service implementation.
- There is the WebApplication project representing the current web services implementation written in .Net 4.0.
- There is the WebApplicationNetCore project which represents the new implementation of the same web services but re-written in .Net Core 2.2.
- The web service definitions are imported to the Test project from the .Net 4.0 implementation. 

How to replicate:
- Run the .Net 4.0 web services project. Then run the unit test and that passes.
- Change the app.config to the new port (8734) used by the .Net Core implementation.
- Run the .Net Core services implementation. Then run the unit test and notice that although the definitions seem to be correct the SOAP object being returned is NULL.

Interesting Observation:
- If I use the .Net Core to import the service definitions to my client (i.e. Tests project) and switch between both service implementations (.Net 4.0 and .Net core) the test passes every time.

So why is it that when using the .Net 4.0 services for the initial service reference the compatibility is broken when replaced by the Core services project (using SoapCore)?

[WebApplication2.zip](https://github.com/DigDes/SoapCore/files/3761371/WebApplication2.zip)

**Comment by kotovaleksandr** [comment]
Hi @VasTheGreek. Sorry for delayed response, i see your project: after update .NET Core version and version of SoapCore (to latest alpha) - test passed.
Initial project doesn't compile on my machine - not installed necessary .NET Core version, because i should update version.
![image](https://user-images.githubusercontent.com/2936914/70531486-1586ee80-1b66-11ea-966a-8eef258c024c.png)

Try on latest version, if your get error on server side - send me full exception message.

**Comment by VasTheGreek** [comment]
> 
> 
> Hi @VasTheGreek. Sorry for delayed response, i see your project: after update .NET Core version and version of SoapCore (to latest alpha) - test passed.
> Initial project doesn't compile on my machine - not installed necessary .NET Core version, because i should update version.
> ![image](https://user-images.githubusercontent.com/2936914/70531486-1586ee80-1b66-11ea-966a-8eef258c024c.png)
> 
> Try on latest version, if your get error on server side - send me full exception message.

I would like to confirm that 1.0.0-alpha.2 release does work just fine.
