### ISSUE TITLE
how to handle Header, soap SecurityHeader, in SoapCore? supported?

### ISSUE THREAD

**Issue by proplanlava** [DigDes/SoapCore#35]
I need my webservice to handle SecurityHeader like this: 
` <soap:Header>
    <SecurityHeader xmlns="http://mydomain.com/myService/">
      <Username>string</Username>
      <Password>string</Password>
`
Very many old client installations we have in our company deliver soap messages with this header in place. I can't see how to make a service wth SoapCore to handle this. Or is there a way?

Have anybody managed to use this SoapCore towards webservices made with dotnet *.asmx files?
Edit: I have managed to create a webservice with SoapCore doing what old *asmx files are doing. Old dotnet clients are communicating ok on simple parameters. But securityheader is not used, so it's unsafe. Also, passing custom objects went well, but not when they have custom sub objects. All is null on those parameters...

**Comment by kotovaleksandr** [comment]
I think SoapCore skip this header, but i can't check it. If you want read this header you can access to source message from HttpContext or write custom middleware and read raw message with all headers.

**Comment by proplanlava** [comment]
thank you for that good feedback. 
I have trouble finding how to get access på httpcontext. Not beeig in a apicontroller and so.
do you have a tip on how?

**Comment by kotovaleksandr** [comment]
Check it http://www.carlrippon.com/?p=757 so sample
