### ISSUE TITLE
Don't use interpolated logging strings as the message

### ISSUE THREAD

**Issue by daniel-white** [DigDes/SoapCore#356]
In order to take advantage of structured logging, using interpolated C# strings are a bad idea.

For instance
```
_logger.LogInformation($"This is bad number {number}");
```

needs to be
```
_logger.LogInformation("This is good number {number}", number);
```

**Comment by julealgon** [comment]
Any updates here?

I just ran into a scenario where I wanted to have a log event property in my logs to tell which operation was being called. I'm using Serilog to split the logs into different files based on the operation name.

Then I noticed the middleware already logs this information, but doesn't do it correctly (it uses interpolated strings as described in this issue):

https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/SoapEndpointMiddleware.cs#L288

If this same line was using proper structured logging, I could take advantage of it. Now I'm having to create a custom `IOperationInvoker` decorator to declare a very similar property, which is less than ideal considering there is already a log call there with what I needed 😢
