### ISSUE TITLE
Refactor for ASP.NET Core 3.0 Endpoint Routing

### ISSUE THREAD

**Issue by IvanFarkas** [DigDes/SoapCore#357]
### Refactor for ASP.NET Core 3.0 Endpoint Routing

Would it be possible to refactor for **[Endpoint Routing in ASP.NET Core 3.0](https://wildermuth.com/2019/09/09/Endpoint-Routing-in-ASP-NET-Core-3-0)**, please?

```csharp
app.UseEndpoints(endpoints =>
  {
    . . .
  });
```

**Comment by kotovaleksandr** [comment]
Already implemented https://github.com/DigDes/SoapCore/pull/347
Release will take place in the next 2 weeks.

**Comment by IvanFarkas** [comment]
You are the **BESTEST**!
