### ISSUE TITLE
Support for async IO ?

### ISSUE THREAD

**Issue by ejwoerlee** [DigDes/SoapCore#363]
I'm using SoapCore 0.9.8.8-beta. 
Are there any developments regarding the support for async IO ?

Starting from dotnet 3.0.0-preview3 AllowSynchronousIO  is disabled by default for all servers (see https://github.com/aspnet/AspNetCore/issues/7644)

**Comment by kotovaleksandr** [comment]
Hi! Already done:
https://github.com/DigDes/SoapCore/pull/347
Please, wait for some time. I publish new nuget package as soon possible.

**Comment by ejwoerlee** [comment]
OK, great! 
Thanks for this information, looking forward to the coming NuGet package.

**Comment by kotovaleksandr** [comment]
@ejwoerlee Welcome https://www.nuget.org/packages/SoapCore/1.0.0-alpha
