### ISSUE TITLE
Different namespaces method and argument

### ISSUE THREAD

**Issue by BorisVezhyk** [DigDes/SoapCore#379]
I need to get and deserialize xml request from client.

```
<s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Status xmlns="http://www.somesite.com/fax/">
<Parameters xmlns="http://xxx.company.yyy.Applications.Fax.Core.Schemas.StatusRequest"><TokenName xmlns="">1</TokenName>
<TokenID xmlns="">1</TokenID>
<RequestID xmlns="">1</RequestID>
</Parameters></Status></s:Body></s:Envelope>
```

I use the next contract for mapping client request.

```
[ServiceContract(Name = "EntryPoint", Namespace = "http://www.somesite.com/fax/")]
	public interface IFaxService
	{	
		
		[OperationContract]
		void Status([XmlElement(Namespace = "http://xxx.company.yyy.Applications.Fax.Core.Schemas.StatusRequest", ElementName = "Parameters")]StatusRequestParameters part);
	}
```
And it works in 0.9.9.6 and mapping correct, but does not work in 1.0.0....

**Comment by kotovaleksandr** [comment]
@BorisVezhyk I can't write test for this case. Situation where namespace of service not equal namespace of models - works, covered by tests. I can't reproduce request like yours by WCF client.
Can check your service on my fork https://github.com/kotovaleksandr/SoapCore ?

**Comment by BorisVezhyk** [comment]
> @BorisVezhyk I can't write test for this case. Situation where namespace of service not equal namespace of models - works, covered by tests. I can't reproduce request like yours by WCF client.
> Can check your service on my fork https://github.com/kotovaleksandr/SoapCore ?

I checked it. My service works well with this code.
