### ISSUE TITLE
Include out parameters in wsdl

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [DigDes/SoapCore#38]
Hi, 

out parameters are missing in created wsdl. See sample `SampleService.VoidMethod(out var stringValue)`. For testing, I created a .NET Framework 4.6.1 client project using ServiceReference to create a client from wsdl. There, the out parameter is missing, see 
[Client461.zip](https://github.com/DigDes/SoapCore/files/1516983/Client461.zip).

Best regards,
Markus

**Comment by MFinkBK** [comment]
Does SOAP support .NET out parameters at all? I was under the impression that everything you want to return from a SOAP call must be in the returned object.

**Comment by cubidobusinesssolutions** [comment]
Yes it does! At least the non-wcf SOAP client/server. The following snippet should help generating wsdl. Note that TService must not be an interface. 
```cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Services.Description;

/// <summary>Writes a WSDL for the XML Web service at the specified URL.</summary>
/// <typeparam name="TService">A concrete implementation of the XML Web service</typeparam>
/// <param name="output">The stream to which you want to write.</param>
/// <param name="url">The address (URL) of the XML Web service.</param>
public static void Write<TService>(Stream output, string url) where TService : class
{
    var reflector = new ServiceDescriptionReflector();
    reflector.Reflect(typeof(TService), url);
    var serviceDescription = reflector.ServiceDescriptions.Cast<ServiceDescription>().Single();
    serviceDescription.Write(output);
}

/// <summary>Creates a WSDL for the XML Web service at the specified URL.</summary>
/// <typeparam name="TService">A concrete implementation of the XML Web service</typeparam>
/// <param name="url">The address (URL) of the XML Web service.</param>
public async static Task<byte[]> CreateAsync<TService>(string url) where TService : class
{
    using (var output = new MemoryStream())
    {
        await Task.Run(() => Write<TService>(output, url));
        return output.ToArray();
    }
}
```

**Comment by abalykov** [comment]
Where is the place for this code?

**Comment by MJunghenn** [comment]
What the result of this issue? Does smbd. have an example for this?

**Comment by cubidobusinesssolutions** [comment]
Sry for my late answer: The code snippet is a workaround for .wsdl generation and mimics the non-wcf SOAP clients' behaviour. For example, generating .wsdl for the sample: 

```cs
public async Task<string> GetWsdl()
{
  const string url = string.Format("http://{0}:5050/Service.asmx", Environment.MachineName);
  var wsdl = await CreateAsync<SampleService.SampleServiceClient>(url);
  return System.Text.Encoding.Default.GetString(wsdl);
}
```

**Comment by cubidobusinesssolutions** [comment]
See also [samples/Client461/Programcs:29](https://github.com/DigDes/SoapCore/blob/master/samples/Client461/Program.cs#L29) where this makes problems.

**Comment by DmitryBryluk** [comment]
try it now and see extended samples under serialization tests

**Comment by cubidobusinesssolutions** [comment]
Works as  expected :+1:

**Comment by cubidobusinesssolutions** [comment]
I updates samples regarding this change #121
