### ISSUE TITLE
XML header in response

### ISSUE THREAD

**Issue by IvanFarkas** [DigDes/SoapCore#386]
The latest version in .NET Core 3.0 adds `﻿<?xml version="1.0" encoding="utf-8"?>` to the response.
I am testing with SoapUI and the response is in one line, that is super annoying.
How can I remove the XML header `﻿<?xml version="1.0" encoding="utf-8"?>`, please?

**Comment by ershadnozari** [comment]
I have the same issue.

**Comment by kotovaleksandr** [comment]
@ershadnozari @IvanFarkas Please check your services against develop branch version.

**Comment by ershadnozari** [comment]
@kotovaleksandr @IvanFarkas it works fine thanks.

**Comment by IvanFarkas** [comment]
@kotovaleksandr @ershadnozari  **Fixed**. Thx for the quick response.
