### ISSUE TITLE
How do I define an XML node of a simpleType?

### ISSUE THREAD

**Issue by JaneConan** [DigDes/SoapCore#389]
Recently, we'll be doing a SOAP WebService with the DNC, and we need to define simpleType and complexType XML nodes. We see that you have the AddType method defined in your project, but not in the demo and test. Can you tell us how to use it?
Thx

**Comment by kotovaleksandr** [comment]
Hi @JaneConan ! That you mean? If you want create SOAP web service just define service contract interface with attributes and implementation.

**Comment by JaneConan** [comment]
Thx a lot, but I want to know how can we define simpleType node, such as 
<xs:simpleType name="aaa">
    <xs:restriction base="xs:string">
        <xs:enumeration value="SYS">
            <xs:annotation>
                <xs:documentation>XXX</xs:documentation>
            </xs:annotation>
        </xs:enumeration>
    </xs:restriction>
</xs:simpleType>

We find the funcation AddTypes incloud simpleType, but how can we use it?
![image](https://user-images.githubusercontent.com/26090153/71363034-c499e000-25d2-11ea-837d-c164e077684b.png)
THX

**Comment by kotovaleksandr** [comment]
Use where? You want use SoapCore WSDL generator in other project?

**Comment by JaneConan** [comment]
Yes, I want to use SoapCore WSDL generator in our project. And Now we've done it with your reference, but some types of nodes can't output. Like simpleType and complexType, we know you can do it in your project, so i'd like to ask you how to use it. Thank you

**Comment by kotovaleksandr** [comment]
WSDL generation is internal code in library. You cannot use them as is, it is not intended for this. I can recommend only copy-paste code.

**Comment by JaneConan** [comment]
OK, thank you for your advice. Let's have a try.
