### ISSUE TITLE
Customize CustomMessage class

### ISSUE THREAD

**Issue by bolivernoguera** [DigDes/SoapCore#406]
Hi,

Currently there is no way to modify the class CustomMessage.
I am migrating a wcf service to soapCore and I need to modify that class to make the response  completely equal to the wcf service (envelope namespaces are not completely equal ). 

I created a PR  [405](https://github.com/DigDes/SoapCore/pull/405)

Best

**Comment by douglassimaodev** [comment]
no updates?
