### ISSUE TITLE
How do you use SoapCore with a webservice?

### ISSUE THREAD

**Issue by learn9969** [DigDes/SoapCore#41]
Hi 
came across this project in the search for something that I could call old webservices.

Now provided I have a webservice that I have no control over  EG http://www.dneonline.com/calculator.asmx

how do I code soapcore from my webapi(vs2017) to call this webservice?
also in some of these old webservices there are out parameters . 
Does it handle them?

thanks for your time

**Comment by kotovaleksandr** [comment]
If you need client library to consume soap service (like vin65) you should use [WCF client](https://github.com/dotnet/wcf). SoapCore its server side library to create web-services over SOAP with ASP.NET Core.
