### ISSUE TITLE
message.Headers.Action is empty in MessageInspector

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [DigDes/SoapCore#414]
The following code invokes any IMessageInspectors that are registered 
https://github.com/DigDes/SoapCore/blob/e34f9b14478056fa15f2013081a79e8bc7d08bb7/src/SoapCore/SoapEndpointMiddleware.cs#L240

unfortenatlly the Action property of the header is null.. this is due to the fact that the action is parsed only after the IMessageInspector is invoked.

is there a problem to move this code after this section i.e.
https://github.com/DigDes/SoapCore/blob/e34f9b14478056fa15f2013081a79e8bc7d08bb7/src/SoapCore/SoapEndpointMiddleware.cs#L253

**Comment by ThisBytes5** [comment]
This is affecting me as well, any chance it's going to be fixed
