### ISSUE TITLE
SoapMessageEncoder works incorrect

### ISSUE THREAD

**Issue by BorisVezhyk** [DigDes/SoapCore#425]
I found a problem. If we have custom binding with a couple message encoders (soap12 and soap11) and send soap request from SOAPUI we can get exception 

> The envelope version of the incoming message (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)) does not match that of the encoder (Soap12 (http://www.w3.org/2003/05/soap-envelope)). Make sure the binding is configured with the same version as the expected messages.

If we send from SOUPUI using soap12 it will work fine. If we swap Soap12 and 11 when registered custom binding, SOAPUI will work with soap11 and will be exception with soap12.
But if we send a request from the client, this works in different situations well. After research, I determined a reason. This depends on contentType.
Client sents request with contentType such "text/xml; charset=utf-8", soapUI has contentType ""text/xml;charset=utf-8", The main difference soapUI has contentType without space before charset. 

I started to research code and found an issue. 
Class SoapMessageEncoder has a method. This method works incorrectly.
`internal virtual bool IsCharSetSupported(string charset)
{
 return false;
}`

 I strongly believe, it must work like this 
`internal virtual bool IsCharSetSupported(string charset)
{
return _writeEncoding.WebName.Equals(charset, StringComparison.OrdinalIgnoreCase);
}`

I checked out it. SoapUI and client work well.

**Comment by shelusb** [comment]
Hi @BorisVezhyk , 
I have the same issue. How did you modify internal virtual bool IsCharSetSupported(string charset) { return false; }? 
I've added SoapCore using the NuGet package manager and don't know how I can access the code and change it.

Thanks!
Shahab
