### ISSUE TITLE
Remove wsdl information for security reasons

### ISSUE THREAD

**Issue by btrouwers** [DigDes/SoapCore#426]
Hi 
I want to remove the wsdl information for security reasons by setting extra information in the web.config file. Unfortunately it does not seem to work. 

It used to work in older ASP.NET projects:
https://support.microsoft.com/en-us/help/815149/how-to-disable-the-documentation-protocol-for-asp-net-web-services

<webServices>
    <protocols>
        <remove name="Documentation"/> 
    </protocols>
</webServices>

Can someone have a look at it please?
Thank you

**Comment by tibel** [comment]
Set `SoapCoreOptions.HttpGetEnabled ` and `SoapCoreOptions.HttpsGetEnabled` to `false`.
