### ISSUE TITLE
WSDL Attribute IsRequired, ignored

### ISSUE THREAD

**Issue by emmeesse79** [DigDes/SoapCore#428]
Hi team,

We're working on project with some complex types in requests and responses.
Everything works like a charm, but, going deeper in usage of WSDL attributes we found out that:
- wsdl IsRequired attribute seems to be ignored
- when message is processed, the attribute that has been marked as "isRequired", is initialized to default value.

For example, if I set IsRequired on a string field, the wsdl is generated with "minoccurs" set to 0 for that  field.
Another example: if I set IsRequired on a numeric field, the wsdl is generated with "minoccurs" set to 1, but if the fields is not passed, it field is automatically initilized to 0 (or numeric default value). We excpect to manage a 400 Bad Request exception.

May you have a suggestion on how to manage IsRequired fields?
Thank you so much.

Regards
Mario

**Comment by blazknuplez** [comment]
I am having the same issue.
