### ISSUE TITLE
How to create dot net core https server with soapcore

### ISSUE THREAD

**Issue by koujiangheng** [DigDes/SoapCore#431]
the example you guys provided is for http, how to create https with soapcore?

**Comment by koujiangheng** [comment]
can i have http and https in one project?

**Comment by kotovaleksandr** [comment]
You can use SoapCore with https like a anyone web service on ASP.NET Core https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio
or you can place nginx with http/https before your SOAP web service.
