### ISSUE TITLE
How to set faultCode and faultString?

### ISSUE THREAD

**Issue by damzajac** [DigDes/SoapCore#432]
When there is an exception in my app, it's parsing to such a response like below. Exception message is put into **faultstring**, but how to set the **faultcode**?

<s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>Something went wrong</faultstring>
</s:Fault>

I have read about the extension method:

AddSoapExceptionTransformer(this IServiceCollection serviceCollection, Func<Exception, string> transformer)

but with this, I can only return message that will be put into faulstring. How can I set the faultcode by myself?

**Comment by damzajac** [comment]
Even when I throw exception by hand in Service like this:

throw new System.ServiceModel.FaultException(new FaultReason("faultString1"), new FaultCode("faultCode1", "faultNamespace1"), "action1");

the faultCode field in response is still "s:Client".

**Comment by jahav** [comment]
Not sure if still interested, but: There are two ways to do this:

- You can register your own `IFaultExceptionTransformer` that translates exceptions thrown into faults. This replaces [DefaultFaultExceptionTransformer](https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/DefaultFaultExceptionTransformer.cs) with your own.
- Throw your `FaultException` and the fault code and reason in the FaultException should be used for the fault. [See example in the code](https://github.com/DigDes/SoapCore/blob/ddbf04de4c7b7dad688a2f6d467f1dd99b0b26f0/src/SoapCore/FaultBodyWriter.cs#L86)
