### ISSUE TITLE
Log Error/Critical instead of Warning

### ISSUE THREAD

**Issue by huf1** [DigDes/SoapCore#433]
Could this logging level changed to error/critical?
In this case something bad happens and this should be logged more present :) 

https://github.com/DigDes/SoapCore/blob/12e364d42c4b4e0c2bc61e5383890c81004feba2/src/SoapCore/SoapEndpointMiddleware.cs#L336

Greetings,

huf1

**Comment by huf1** [comment]
> Could this logging level changed to error/critical?
> In this case something bad happens and this should be logged more present :)
> 
> https://github.com/DigDes/SoapCore/blob/12e364d42c4b4e0c2bc61e5383890c81004feba2/src/SoapCore/SoapEndpointMiddleware.cs#L336
> 
> Greetings,
> 
> huf1

Could you please fix this. This change would help us a lot
Thanks!

**Comment by kotovaleksandr** [comment]
@huf1 No problem:)
https://github.com/DigDes/SoapCore/commit/58027f7f7988e0938b08b721563baccc069b9977

**Comment by huf1** [comment]
> @huf1 No problem:)
> [58027f7](https://github.com/DigDes/SoapCore/commit/58027f7f7988e0938b08b721563baccc069b9977)

thank you ;)
