### ISSUE TITLE
Unable to generate Proxy for the given sample service project.

### ISSUE THREAD

**Issue by sagarbharath-poojala** [DigDes/SoapCore#434]
I am trying to generate a new proxy using the sample service provided in the Sample project and I am facing issue.(I am using the same configuration and startup.cs with out any changes).
Incase I comment out methods the following methods and data members,I am not getting any error.
Methods:
VoidMethod,AsyncMethod 
Datamembers:
ComplexModelResponse.ListProperty,
ComplexModelResponse.TestEnum,
ComplexModelResponse.DateTimeOffsetProperty,
ComplexModelInput.ListProperty,
ComplexModelInput.DateTimeOffsetProperty,
ComplexModelInput.ComplexListProperty

By using asmx reference I am getting below error:

Error: Cannot obtain Metadata from http://hsee-alb-tstw10:5050/Service.asmx

If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.

WS-Metadata Exchange Error
    URI: http://hsee-alb-tstw10:5050/Service.asmx

    Metadata contains a reference that cannot be resolved: 'http://hsee-alb-tstw10:5050/Service.asmx'.

    The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.

HTTP GET Error
    URI: http://hsee-alb-tstw10:5050/Service.asmx

    The document at the url http://hsee-alb-tstw10:5050/Service.asmx was not recognized as a known document type.
The error message from each known type may help you fix the problem:
- Report from 'XML Schema' is 'The root element of a W3C XML Schema should be <schema> and its namespace should be 'http://www.w3.org/2001/XMLSchema'.'.
- Report from 'DISCO Document' is 'Discovery document at the URL http://hsee-alb-tstw10:5050/Service.asmx could not be found.'.
  - The document format is not recognized.
- Report from 'WSDL Document' is 'There is an error in XML document (44, 9).'.
  - The element was not expected in this context: <xsd:complexType xmlns:xsd='http://www.w3.org/2001/XMLSchema'>..</xsd:complexType>. Expected elements: http://www.w3.org/2001/XMLSchema:annotation, http://www.w3.org/2001/XMLSchema:simpleType, http://www.w3.org/2001/XMLSchema:complexType, http://www.w3.org/2001/XMLSchema:key, http://www.w3.org/2001/XMLSchema:unique, http://www.w3.org/2001/XMLSchema:keyref.

By using svc reference I am getting below error:
Error: Cannot obtain Metadata from http://hsee-alb-tstw10:5050/Service.svc

If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.

WS-Metadata Exchange Error
    URI: http://hsee-alb-tstw10:5050/Service.svc

    Metadata contains a reference that cannot be resolved: 'http://hsee-alb-tstw10:5050/Service.svc'.

    The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.

HTTP GET Error
    URI: http://hsee-alb-tstw10:5050/Service.svc

    There was an error downloading 'http://hsee-alb-tstw10:5050/Service.svc'.

    The request failed with an empty response.

Any help appreciated!!!

**Comment by kotovaleksandr** [comment]
Attach service log
