### ISSUE TITLE
Streamline and document extensibility points

### ISSUE THREAD

**Issue by jahav** [DigDes/SoapCore#446]
As is, the extensibility points of SoapCore from `SoapCore.Extensibility` are not well documented and could stand some design improvements.

I have been evaluating SoapCore extensibility and you basically have to go through the source code. The documentation should 
- include documenting parameters of each extensibility interface (e.g. `IModelBindingFilter` parameter output is not really used). 
- document a purpose of each extensibility point along with an example. 
- contain a diagram similar to MVC pipeline how does the extensibility works (order of execution, what happens with error)

I have been evaluating SoapCore for our project and created an example from #442. 

I think extensibility points should be significantly streamlined, that would be a breaking change of course. Since API is not even property documented, it might be possible to get away with it, use [Obsolete]/[EditorBrowsableAttribute] or to create a SoapCore.Extensibility.Legacy nuget package that would keep old interfaces mapped to the streamlined API.

My basic idea is that extensibility pipeline should be clear and easy to use without unnecessary clutter or hidden dependencies.

Some points I have come across:
### ModelTypes

IModelBindingFilter is using a property ModelTypes to check is a parameter can be bound by the filter. This property has a setter, it should be removed and it requires a List<Type>, but it should use some kind of read only collection interface (so that filters can return array, set, list whatever without need for `ToList()`). Ideadlly, this property should be replaced with `CanBind(Type)` method, because current design doesn't deal with generic types (e.g. I have a class Page<T> that can have unlimited and amount of types that would need to be found through reflection and returned from the `ModelTypes` property).

Using CanBind(Type) method on interface offloads logic to the implementing filter that knows best how to check if it can or cant bind the model. That is a common practice, e.g. type serializers from Json.Net.

### serviceProvider parameter
The serviceProvider is passed to the IModelBindingFilter.OnModelBound. The parameter should be removed, because it has nothing to do with model binding and encourages service locator anti-pattern.

The filters themselves are resolved just before use and if they need some dependency, they shouldn't resolve it through a service locator passed as an argument but through constructor injection. If they need serviceProvider, they can request it through constructor injection of the filter.

### output out parameter
Since this is an out parameter, it has to be set by each filter, so the final instance that is passed to the OnSoapActionExecuting method is from the last model binding filter and the rest is thrown away (i.e. wasted calculations).

TBH, I am unclear about use case of the output parameter.

### consider single parameter
It might be preferable to introduce a special class ModelBindingContext and pass it to the OnModelBound. With a separate class, it would be much easier to add new properties in a backward compatible fasion (that is MVC does it) .

## Async API
There are two interfaces for message filters, IAsyncMessageFilter and IMessageFilter. These interfaces are resolved separately and executed one after another. Sync version should be replaces with abstract class that implements async version. 

This change will enable single processing of the filters, instead of first run sync filters then run all async filters. 

There is a real benefit to a single interface:

1. That is a hidden dependency, you can't have asyn filter run before sync filter. Having to change the interface and implementation just to change order is wrong.
2. The processing order of filters is currently wrong, so even programmers get it wrong with not unstreamlined. In OnRequestExecuting the sync are run first and then async, while in OnResponseExecuting, the order is also sync filters (in same order as on the input) and then async are run, but correctly reversed. So filters are SYN1, SYN2, ASYN1 ASYN2 - perform operation - SYN1 SYN2, ASYN2 ASYN1 (order should be reversed: ASYN2 ASYN1, SYN2, SYN1).

[Link](https://github.com/jbogard/MediatR/blob/master/src/MediatR/IRequestHandler.cs#L60) to how is it done in MediatR.

### Add an interface
This was supposed to be an equivalent of ActionFilter. There is no interface in the  `SoapCore.Extensibility`.  Currently, it just looks for an attribute on the operation and executes the `OnSoapActionExecuting` method via reflection.

Having an interface will make the extension point explicit and thus documented and usable.

### Too many parameters.
I am not convinces of use case for modelBindingOutput argument, but anyway, the method already has 4 parameters. There should be a single parameters (e.g. SoapActionFilterContext), just like in MVC ActionFilter. It allows for possible addition of another property without code breakage.

## Merge IMessageInspector into IMessageInspector2.
IMessageInspector should be removed/put into legacy package with an adapter. I have seen the PR and it was explicitely done for compatibility reason, but even so.
The same point as for other methods, here was introduced another interface just to add a parameters to a method. With a separate parameter type, that wouldn't be necessary (of course seal all such types). 

There are probably others, but this is just what I have seen so far, if this is going to happen, it should be once change, so API is not changed often.

I am OK with making a PR, if you approve the changes.

**Comment by kotovaleksandr** [comment]
Hi @jahav! Thank you for effort! Extensibility features developed chaotically rather, not as a way to extend functionality, but a set of hacks to maintain compatibility with legacy code. I think SoapCore.Extensibility.Legacy not necessary, we can break compatibility with major release, its not a problem, Obsolete attribute for old code should be enough. In the feature we can remove them.
I have no objections, waiting for your PR:) Thanks!

**Comment by jahav** [comment]
It is taking slightly longer thank I thought. I have looked over all extension points and concluded that many of them redundant. So far I have created `ISoapMessageFilter` and adapters for 

* `IMessageFilter`
* `IAsyncMessageFilter`
* `IMessageInspector`
* `IMessageInspector`

Anyway, the pipeline for the extensions should look like this:
![SoapCore-pipeline](https://user-images.githubusercontent.com/7634052/76582146-b8d50000-64d5-11ea-807e-28b9ed778f59.jpg)

**Comment by pantosha** [comment]
@jahav maybe you have some progress in your PR?
