### ISSUE TITLE
Throw FaultException<T> in SoapCore service, client gets untyped FaultException

### ISSUE THREAD

**Issue by MZar2019** [DigDes/SoapCore#448]
I see issues that state typed FaultExceptions are supported, however ...

I started with a WSDL and used svcutil.exe to create my C# classes. The Services and Clients are all built off these classes.

I have 2 SOAP services, WCF and SoapCore (using the Server code from Sample.sln).
I have 2 SOAP clients, WCF and .NET Core.

When I throw FaultException&lt;T&gt; from the WCF service, both SOAP clients catch the correct, typed exception.

When I use throw FaultException&lt;T&gt; from the SoapCore service, both SOAP clients catch an untyped FaultException.

Is FaultException&lt;T&gt; really supported?

**Comment by MZar2019** [comment]
The response from the WCF service has the namespace included in the detail element:

&lt;detail&gt;&lt;InvalidRequest xmlns="http://com.xxxx"/&gt; &lt;/detail&gt; 

But the response from the SoapCore service does not:

&lt;detail&gt;
&lt;InvalidRequest /&gt;
&lt;/detail&gt;

I wonder if this is the actual problem?

**Comment by MZar2019** [comment]
Well, that was an interesting two days...

IFaultExceptionTransformer is a nice idea but poorly implemented because the Message and NamespaceManager field setters in CustomMessage are internal:

    public class CustomMessage : Message
    {
        public Message Message { get; internal set; }
        public XmlNamespaceManager NamespaceManager { get; internal set; }

so you can't actually create your own one IFaultExceptionTransformer outside of the SoapCore project.

Cut to the chase, replacing the DataContractSerializer in ExtractFaultDetailsAsXmlElement() with an XmlSerializer fixed the missing namespace but since IFaultExceptionTransformer is not operational, I just hardcoded the namespace for all of our FaultExceptions.

    private XmlElement ExtractFaultDetailsAsXmlElement(Exception ex)
    {
        // Zarlenga
        using (var ms = new MemoryStream())
        {
            //var serializer = new DataContractSerializer(detailObject.GetType());
            //serializer.WriteObject(ms, detailObject);
            var serializer = new XmlSerializer(detailObject.GetType(), "http://com.xxx");
            serializer.Serialize(ms, detailObject);
            ...

Hopefully, this helps someone else save a few days.

**Comment by tyagibharat** [comment]
I am facing the same issue. I am always getting untyped fault exception, **is there anyway I can get the typed exception?**

PS: I am using xml serialization as being working on a legacy service migration to .netCore and can't change the serializer.

**Comment by tyagibharat** [comment]
> Well, that was an interesting two days...
> 
> IFaultExceptionTransformer is a nice idea but poorly implemented because the Message and NamespaceManager field setters in CustomMessage are internal:
> 
> ```
> public class CustomMessage : Message
> {
>     public Message Message { get; internal set; }
>     public XmlNamespaceManager NamespaceManager { get; internal set; }
> ```
> 
> so you can't actually create your own one IFaultExceptionTransformer outside of the SoapCore project.
> 
> Cut to the chase, replacing the DataContractSerializer in ExtractFaultDetailsAsXmlElement() with an XmlSerializer fixed the missing namespace but since IFaultExceptionTransformer is not operational, I just hardcoded the namespace for all of our FaultExceptions.
> 
> ```
> private XmlElement ExtractFaultDetailsAsXmlElement(Exception ex)
> {
>     // Zarlenga
>     using (var ms = new MemoryStream())
>     {
>         //var serializer = new DataContractSerializer(detailObject.GetType());
>         //serializer.WriteObject(ms, detailObject);
>         var serializer = new XmlSerializer(detailObject.GetType(), "http://com.xxx");
>         serializer.Serialize(ms, detailObject);
>         ...
> ```
> 
> Hopefully, this helps someone else save a few days.



> I see issues that state typed FaultExceptions are supported, however ...
> 
> I started with a WSDL and used svcutil.exe to create my C# classes. The Services and Clients are all built off these classes.
> 
> I have 2 SOAP services, WCF and SoapCore (using the Server code from Sample.sln).
> I have 2 SOAP clients, WCF and .NET Core.
> 
> When I throw FaultException<T> from the WCF service, both SOAP clients catch the correct, typed exception.
> 
> When I use throw FaultException<T> from the SoapCore service, both SOAP clients catch an untyped FaultException.
> 
> Is FaultException<T> really supported?

I am facing the same issue. I am always getting untyped fault exception, **is there anyway I can get the typed exception?**

PS: I am using xml serialization as being working on a legacy service migration to .netCore and can't change the serializer.

**Comment by tyagibharat** [comment]
> I see issues that state typed FaultExceptions are supported, however ...
> 
> I started with a WSDL and used svcutil.exe to create my C# classes. The Services and Clients are all built off these classes.
> 
> I have 2 SOAP services, WCF and SoapCore (using the Server code from Sample.sln).
> I have 2 SOAP clients, WCF and .NET Core.
> 
> When I throw FaultException<T> from the WCF service, both SOAP clients catch the correct, typed exception.
> 
> When I use throw FaultException<T> from the SoapCore service, both SOAP clients catch an untyped FaultException.
> 
> Is FaultException<T> really supported?


I am facing the same issue. I am always getting untyped fault exception, **is there anyway I can get the typed exception?**

PS: I am using xml serialization as being working on a legacy service migration to .netCore and can't change the serializer.
