### ISSUE TITLE
using scoped service instead of singleton

### ISSUE THREAD

**Issue by RMarinaro** [DigDes/SoapCore#452]
Hi! 

I'm wondering if using the soap service as scoped service instead of a singleton is supported.  All the examples I've found have 

`services.TryAddSingleton<IService>();`

as opposed to 

`services.TryAddScoped<IService>();`

Isn't using scoped more natural for something like this since this is the SOAP equivalent of an ASP.net controller? When I add the scoped service everything seems to work, I'm just worried I'll be running into some "gotcha" in production if it's not designed to be scoped. Thanks!

**Comment by chrgraefe** [comment]
Hi we are running also running our services using scoped without any issues. It is needed to get correct results, that initiated a new class for each request. Especially in case of calculations you would get wrong results.
I ran into the same issue after the first tests.
