### ISSUE TITLE
Error: Cannot obtain Metadata when trying to reference the service

### ISSUE THREAD

**Issue by KamranShahid** [DigDes/SoapCore#457]
I am getting following error when trying to reference the service

```
Error: Cannot obtain Metadata 
from http://127.0.0.1:1234/MyService.svc 
If this is a Windows (R) Communication Foundation service to which you have access, 
please check that you have enabled metadata publishing at the specified address. 
 For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.WS-Metadata Exchange Error    
 URI: http://127.0.0.1:1234/MyService.svc    Metadata contains a 
 reference that cannot be resolved: 'http://127.0.0.1:1234/MyService.svc'.   
 The server did not provide a meaningful reply; this might be caused by a contract mismatch, 
 a premature session shutdown or an internal server error.HTTP GET Error    
 URI: http://127.0.0.1:1234/MyService.svc    The document at the url http://127.0.0.1:1234/MyService.svc 
 was not recognized as a known document type.The error message from each known type may help you fix the problem:-
 Report from 'DISCO Document' is 'Discovery document at the URL http://127.0.0.1:1234/MyService.svc could not be found.'.  - The document format is not recognized.- Report from 'WSDL Document' is 'There is an error in XML document (54, 5).'.  - Value cannot be null.Parameter name: name- Report from 'XML Schema' is 'The root element of a W3C XML Schema should be <schema> and its namespace should be 'http://www.w3.org/2001/XMLSchema'.'.
```

**Comment by KamranShahid** [comment]
On debug windows i can see error

Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLV26Q1T1G4F", Request id "0HLV26Q1T1G4F:00000001": An unhandled exception was thrown by the application.
System.ServiceModel.CommunicationException: The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) 
does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). 
Make sure the binding is configured with the same version as the expected messages. (Parameter 'reader')
 ---> System.ArgumentException: The envelope version of the incoming message 
 (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder 
 (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages. (Parameter 'reader')

**Comment by sumantfordev** [comment]
any update on this, facing the same issue when adding teh web reference to a .net client app

**Comment by KamranShahid** [comment]
> any update on this, facing the same issue when adding teh web reference to a .net client app

I abandoned the idea that time of using soapcore
