### ISSUE TITLE
Anyway i can implement soap 1.2 service in .net core 3.1 using soapcore?

### ISSUE THREAD

**Issue by KamranShahid** [DigDes/SoapCore#458]
I have a third a party standard wsdl  which is on soap1.2 standard
As per my knowledge to support it we have to use wshttpbining
is there possibility of implemented it in .net core 3.1
when i am trying to run with 
```
app.UseEndpoints(endpoints =>
            {
                endpoints.UseSoapEndpoint<MyService>("/MyService.svc", new WSHttpBinding(), SoapSerializer.XmlSerializer);
            }); 
```
i am getting platform not supported exception

**Comment by habtu12** [comment]
Hi. Did u find a solution for this issue?
