### ISSUE TITLE
.Net Core 3.1 error when using SoapSerializer.XmlSerializer

### ISSUE THREAD

**Issue by rogerskk** [DigDes/SoapCore#459]
If I just use the following:
` app.UseRouting();
            app.UseEndpoints(endpoints => {
                endpoints.UseSoapEndpoint<IPaSTA_WCF>("/PaSTA_WCF.svc", new BasicHttpBinding());`

Then I get the wsdl in the browser, but it has extra namespaces that I didn't have before in .net Core 2.1:
<xs:import namespace="http://schemas.datacontract.org/2004/07/PRO_InterfaceforWebService"/>
<xs:import namespace="http://schemas.datacontract.org/2004/07/System.Xml.Linq"/>
<xs:import namespace="http://schemas.datacontract.org/2004/07/System.Xml"/>
and it gives the following error trying to use the wsdl in SoapUI:
Error loading [http://localhost:5060/pasta_wcf.asmx?wsdl]: org.apache.xmlbeans.XmlException: org.apache.xmlbeans.XmlException: error: Unexpected element: CDATA

If I use the XmlSerializer as follows:
`app.UseEndpoints(endpoints => {
                endpoints.UseSoapEndpoint<IPaSTA_WCF>("/PaSTA_WCF.svc", new BasicHttpBinding(), SoapSerializer.XmlSerializer, true, null);
            });`
which is what I used in .Net Core 2.1 that worked fine, I get the following error trying to pull up the wsdl in the browser:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.Collections.Generic.List<T>.get_Item(int index)
SoapCore.Meta.MetaBodyWriter.GetMessageContractBodyType(Type type)
SoapCore.Meta.MetaBodyWriter.WriteParameters(XmlDictionaryWriter writer, SoapMethodParameterInfo[] parameterInfos, bool isMessageContract)
SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)

**Comment by KamranShahid** [comment]
> If I just use the following:
> ` app.UseRouting(); app.UseEndpoints(endpoints => { endpoints.UseSoapEndpoint<IPaSTA_WCF>("/PaSTA_WCF.svc", new BasicHttpBinding());`
> 
> Then I get the wsdl in the browser, but it has extra namespaces that I didn't have before in .net Core 2.1:
> <xs:import namespace="[http://schemas.datacontract.org/2004/07/PRO_InterfaceforWebService"/>](http://schemas.datacontract.org/2004/07/PRO_InterfaceforWebService%22/%3E)
> <xs:import namespace="[http://schemas.datacontract.org/2004/07/System.Xml.Linq"/>](http://schemas.datacontract.org/2004/07/System.Xml.Linq%22/%3E)
> <xs:import namespace="[http://schemas.datacontract.org/2004/07/System.Xml"/>](http://schemas.datacontract.org/2004/07/System.Xml%22/%3E)
> and it gives the following error trying to use the wsdl in SoapUI:
> Error loading [http://localhost:5060/pasta_wcf.asmx?wsdl]: org.apache.xmlbeans.XmlException: org.apache.xmlbeans.XmlException: error: Unexpected element: CDATA
> 
> If I use the XmlSerializer as follows:
> `app.UseEndpoints(endpoints => { endpoints.UseSoapEndpoint<IPaSTA_WCF>("/PaSTA_WCF.svc", new BasicHttpBinding(), SoapSerializer.XmlSerializer, true, null); });`
> which is what I used in .Net Core 2.1 that worked fine, I get the following error trying to pull up the wsdl in the browser:
> ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
> System.Collections.Generic.List.get_Item(int index)
> SoapCore.Meta.MetaBodyWriter.GetMessageContractBodyType(Type type)
> SoapCore.Meta.MetaBodyWriter.WriteParameters(XmlDictionaryWriter writer, SoapMethodParameterInfo[] parameterInfos, bool isMessageContract)
> SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)

One thing i guess is you have to add SoapSerializer.XmlSerializer

Like 
app.UseRouting(); 
app.UseEndpoints(endpoints => { endpoints.UseSoapEndpoint<IPaSTA_WCF>("/PaSTA_WCF.svc", new BasicHttpBinding(), **SoapSerializer.XmlSerializer**);

I myself is struggling in some complex third party integration which have quite a complex wsdl with number of inner xsd's and complex type

**Comment by rogerskk** [comment]
So I can get it to generate the wsdl using 0.9.9.8-alpha version, but any newer one fails with this error.

**Comment by rogerskk** [comment]
I finally resolved this so I thought I would share.  With the 1.0.0 and newer versions of SoapCore (up to 1.1.04-beta as of this post) I had to add the [Serializable] attribute over my DataContract and MessageContract and set the Namespace in the contract attributes.  Then it was able to generate the proper wsdl. Hope that helps someone else.
