### ISSUE TITLE
Web method with XmlDocument as return type fails in SoapCore

### ISSUE THREAD

**Issue by PrinceManiGupta** [DigDes/SoapCore#463]
I am trying to host asmx type web service in asp.net core using SoapCore.

I have one web method as follows.

```
[OperationContract]
XmlDocument testProperties();
```
and concrete implementation for this as follows.

```
public XmlDocument testProperties()
{
    XmlDocument testProperties = new XmlDocument(); 
    testProperties.LoadXml("<test>abc</test>");
    return testProperties;
}
```
When I am trying to access this web method, it fails with following error.

```
System.InvalidOperationException: There was an error generating the XML document.
 ---> System.InvalidOperationException: This element was named 'test' from namespace '' but should have been named 'TestPropertiesResult' from namespace ''.
```
Note: This issue only comes when method has return type as XmlDocument. If it is string or other simple data type, everything works perfectly.

Any lead would be helpful.

**Comment by unruledboy** [comment]
I have exact same issue. Any one can help here, please?
