### ISSUE TITLE
Incorrect WSDL for List<string> when using SoapSerializer.XmlSerializer

### ISSUE THREAD

**Issue by mjnz** [DigDes/SoapCore#465]
I cannot import the WSDL due to the fact that there is a case mismatch 
````c#
public List<string> PictureHashes { get; set; }
````
Produces the following WSDL, Notice **arrayofstring** is lower case
````xml
<xsd:element xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" maxOccurs="1" name="PictureHashes" nillable="true" type="q1:arrayofstring"/>
````
further down the complextype is defined as **ArrayOfString**
````xml
<xsd:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
<xsd:complexType name="ArrayOfString">
<xsd:sequence>
<xsd:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="string" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
<xsd:element name="ArrayOfString" nillable="true" type="tns:ArrayOfString"/>
</xsd:schema>
</wsdl:types>
````
As a result attempting to import the WSDL gives me the following error  
    - Unable to import operation 'ExchangeInterfaceData'.
    - The datatype 'http://schemas.microsoft.com/2003/10/Serialization/Arrays:arrayofstring' is missing.

I wonder they might both be wrong as I see that the DataContract serializer has them both as **ArrayOfstring**.  But whatever it should be the case of the words must match (since XML is case sensitive).

Looks like problem is going to be in MetaBodyWriter.cs

**Comment by Cornishman** [comment]
Can confirm the same issue.
Looks like at somepoint in the past a .ToLower() was being used and then the MetaBodyWriter.cs class got refactored but a .ToLower() was left in causing this problem, specifically for Enumerable Strings.
See:
https://github.com/DigDes/SoapCore/blob/b656fa433cc74d57ad7fc8478c6137e59437ec9f/src/SoapCore/Meta/MetaBodyWriter.cs#L788
