### ISSUE TITLE
Element names are not changed when using XmlSerializerFormat

### ISSUE THREAD

**Issue by the-black-wolf** [DigDes/SoapCore#479]
Neither the `DataMember.Name` nor `XmlElement.ElementName` have any influence on the generated wsdl schema. 

```csharp
[XmlSerializerFormat, XmlType(TypeName = "PortingMessage", Namespace = "")] 
public sealed class PortingMessage
{
    [DataMember, XmlElement(ElementName = "messageheader")] public MessageHeader MessageHeader { get; set; }
    [DataMember(Name = "messagebody"), XmlElement] public MessageBody MessageBody { get; set; }
}
```

wsdl schema keeps using the cased property name:

```xml
<xsd:complexType name="PortingMessage">
  <xsd:sequence>
    <xsd:element minOccurs="0" maxOccurs="1" name="MessageHeader" type="tns:messageMessageheader" />
    <xsd:element minOccurs="0" maxOccurs="1" name="MessageBody" type="tns:messageMessagebody" />
  </xsd:sequence>
</xsd:complexType>
```

I am tied to the external WSDL that I need to emulate, but I would prefer to use my code casing standards for code. Is there any way I can get `name="messageheader"` in wsdl for `MessageHeader` property? If not, this seems like a bug (or a feature omission).

**Comment by sagos95** [comment]
Same problem. What is noticeable is that at the same time the names in usual xml are generated correctly, using parameters passed to xml attributes.

**Comment by the-black-wolf** [comment]
Whatever happened with this?
