### ISSUE TITLE
Start element namespace

### ISSUE THREAD

**Issue by icschutte** [DigDes/SoapCore#486]
Hi all,

I'm trying to process an xml message with a <string> element in the body, e.g.:

<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Test</string>

I'm getting this message though: 

Start element 'string' from namespace 'http://tempuri.org/' expected. Found element 'string' from namespace 'http://schemas.microsoft.com/2003/10/Serialization/'. Line 1, position 186.

How do I specify the namespace to use?

**Comment by tmcque9** [comment]
It took me a minute to figure this one out.  You set it in the ServiceContract attribute:

`[ServiceContract(Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
public interface IServiceName
{
}`

**Comment by d41z** [comment]
@icschutte  were you able to solve it?.
same problem.

**Comment by d41z** [comment]
I solved it using this in the interface

[ServiceContract(Namespace = "")]
