### ISSUE TITLE
How to add custom SoapMessageEncoder for different contentTypes

### ISSUE THREAD

**Issue by Gkschd** [DigDes/SoapCore#487]
Hello,

In the class 'SoapEndpointMiddleware' there is an array with several MessageEncoders, which are checked for supported content types before reading the message. I wasn't able to find a way to add a custom MessageEncoder to support other/different content types.

Can you tell me if there is a way to archieve this?

Any help is much appreciated.

Thank you.

**Comment by Peet-HD** [comment]
I currently have the same issue. This issue is unfortunately still not solved. @Gkschd could you reopen this issue so I don't have to open a new issue.

**Comment by andersjonsson** [comment]
There is not support for custom SoapMessageEncoders, but if you could share more information about what you're trying to achieve I might be able to suggest an alternative solution.

**Comment by Gkschd** [comment]
Hello, thank you for your response. 
We want to handle soap messages with binary attachements in multipart messages.
It has been a while ago since my question. I found a pull request (https://github.com/DigDes/SoapCore/pull/811) for multipart attachements, so i am not sure if this is already possbile an my post is obsolete.
