### ISSUE TITLE
MetaBodyWriter doesn't support XMLAttributes

### ISSUE THREAD

**Issue by ArtsiomKazlouski** [DigDes/SoapCore#488]
Hi, I've been trying to rewrite .asmx service [WebService]/[WebMethod]
Using SoapCore and mostly the things are doing well, but:

My models have a pretty complex structure e.g.:
```
        [SerializableAttribute]
	[XmlRoot("QueryReportResponse", Namespace = "http://bagov.net/", IsNullable = false)]
	public class TestResponseType
	{
		public TestResponseType()
		{
			DataList = new List<TestDataTypeData>();
		}
		[System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable = false)]
		public List<TestDataTypeData> DataList { get; set; }

		[System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable = false)]
		public List<TestDataTypeData> DataList2 { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Data")]
		[DataMember]
		public List<TestDataTypeData2> Data { get; set; }

		[XmlAttributeAttribute]
		public string PropRoot { get; set; }

		[XmlIgnore]
		public string PropIgnore { get; set; }
	}

	[Serializable]
	[XmlType(AnonymousType=true)]
	public class TestDataTypeData
	{
		[XmlAttributeAttribute]
		public string PropAnonymous { get; set; }
	}

	[Serializable]
	[XmlType(AnonymousType=true)]
	[DataContract]
	public class TestDataTypeData2
	{
		[XmlAttributeAttribute]
		[DataMember]
		public string PropAnonymous { get; set; }
	}
```

I use SoapSerializer.XmlSerializer and when I call created service from client, generated using old service wsdl it gets a request and returns a response as I expect.

But in the same time wsdl is generating with errors:
 - it has a complex type without a name
 - fields marked with [XMLAttribute] written as \<element/\>

**Comment by ArtsiomKazlouski** [comment]
Hi, could you tell me is it possible to create the prerelease nuget package with changes I made in the linked PR?

**Comment by kotovaleksandr** [comment]
@ArtsiomKazlouski Thank you very much for your effort! Please check:
https://www.nuget.org/packages/SoapCore/1.1.0.1-alpha

Merge was with some conflicts, i hope i'm haved merged code correctly.

**Comment by ArtsiomKazlouski** [comment]
@kotovaleksandr thanks, I've checked looks good.
