### ISSUE TITLE
Headers not being serialized correctly

### ISSUE THREAD

**Issue by mdailor** [DigDes/SoapCore#492]
Hello, thank you for bringing SOAP to .NET Core! I am having a problem with [XmlAttribute] and [XmlElement] not being honored when serializing headers. Let's say I have the following MyInterface class:

```
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.newtrade.com/expedia/R14/header")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.newtrade.com/expedia/R14/header", IsNullable = false)]
public class MyInterface
{
    private string nameField;
    private decimal versionField;

    [System.Xml.Serialization.XmlAttributeAttribute("Name")]
    public string Name
    {
        get { return this.nameField; }
        set { this.nameField = value;}
    }

    [System.Xml.Serialization.XmlElement("Version")]
    public decimal Version
    {
        get { return this.versionField; }
        set { this.versionField = value; }
    }
}
```
I am returning the same MyInterface object in a ResponseModel as both a header and a body:

```
[MessageContract(IsWrapped = false)]
public class ResponseModel
{
        [MessageHeader(Name = "MyInterface", Namespace = "http://www.newtrade.com/expedia/R14/header")]
        public MyInterface InterfaceAsHeader { get; set; }

        [MessageBodyMember(Name = "MyInterface", Namespace = "http://www.newtrade.com/expedia/R14/header")]
        public MyInterface InterfaceAsBody { get; set; }
}
```

This is the serialized result:

```
<s:Header>
    <MyInterface xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.newtrade.com/expedia/R14/header">
        <nameField xmlns = "http://schemas.datacontract.org/2004/07/MyContract" > ExpediaDirectConnect </ nameField >
        <versionField xmlns = "http://schemas.datacontract.org/2004/07/MyContract" > 0 </ versionField >
    </ MyInterface >
</ s:Header>
<s:Body>
    <MyInterface Name = "ExpediaDirectConnect" xmlns="http://www.newtrade.com/expedia/R14/header">
        < Version > 0 </ Version >
    </ MyInterface >
</ s:Body>

```
Note that in the header the element names are the private member names vs those specified in [XmlAttribute] and [XmlElement]. Also Name is being serialized as an element but it has been specified as an [XmlAttribute]. The body is perfect, though.

Can you shed some light on this for me, please? Thanks!

**Comment by mdailor** [comment]
@kotovaleksandr I wonder if you could take a look at this for me. In SoapEndpoinMiddleware.CreateResponseMessage, do you think passing an XmlObjectSerializer to MessageHeader.CreateHeader would fix this situation?

```
var messageHeaderMembers = responseObject.GetType().GetMembersWithAttribute<MessageHeaderAttribute>();
foreach (var messageHeaderMember in messageHeaderMembers)
{
	var messageHeaderAttribute = messageHeaderMember.GetCustomAttribute<MessageHeaderAttribute>();
	responseMessage.Headers.Add(MessageHeader.CreateHeader(messageHeaderAttribute.Name ?? messageHeaderMember.Name, operation.Contract.Namespace, messageHeaderMember.GetPropertyOrFieldValue(responseObject)));
}

```

**Comment by kotovaleksandr** [comment]
Hi @mdailor ! I can reproduce this problem. Headers serialization make .NET class:
https://github.com/dotnet/wcf/blob/209b0b584edcf7f629e4c34c8e923f43e76445c1/src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageHeader.cs#L476

We don't have any control how header write to final message.

In your case removing serialization attribute should solve problem. You can do it?
https://stackoverflow.com/questions/1953984/is-there-a-way-to-make-datacontractserializer-output-cleaner-xml

**Comment by mdailor** [comment]
Hi @kotovaleksandr, thanks for the reply! That got me further along, after removing [Serializable] I now have this:
```
<s:Header>
    <MyInterface xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.newtrade.com/expedia/R14/header">
        <Name xmlns = "http://schemas.datacontract.org/2004/07/MyContract" > ExpediaDirectConnect </ Name >
        <Version xmlns = "http://schemas.datacontract.org/2004/07/MyContract" > 0 </ Version >
    </ MyInterface >
</ s:Header>
<s:Body>
    <MyInterface Name = "ExpediaDirectConnect" xmlns="http://www.newtrade.com/expedia/R14/header">
        < Version > 0 </ Version >
    </ MyInterface >
</ s:Body>
```
Much better! But, the Version is still being serialized as an element:
```
<MyInterface>
  <Version>0</Version>
</MyVersion>
```
Instead of as an attribute:
```
<MyInterface Value="0"></MyInterface>
```

Any thoughts about that?

**Comment by kotovaleksandr** [comment]
@mdailor Try implement IXmlSerializable interface in your model, like this:
https://stackoverflow.com/a/1287433

**Comment by mdailor** [comment]
@kotovaleksandr That looks very promising, I will code it up and report back! Thank you!!

**Comment by mdailor** [comment]
BOOM! That was exactly what I needed, working perfectly now and thanks so much.

For anyone else who lands here, the class now looks like this:
```
public class MyInterface : IXmlSerializable
{
    public string Name { get; set; }

    public decimal Version { get; set; }

    public XmlSchema GetSchema() { return null; }
    public void ReadXml(XmlReader reader) { }
    public void WriteXml(XmlWriter writer)
    {
        writer.WriteAttributeString("Name", Name);
        writer.WriteAttributeString("Version", Version.ToString());
    }
}
```
and the output is:
```
<Interface Name = "ExpediaDirectConnect" Version="0">
</Interface>
```

**Comment by JpWebster** [comment]
Hi, we just ran into this issue with some of our services and the work-around to have our header class implement IXmlSerializable worked, however, can this be fixed in the SoapEndpointMiddleware to use create the MessageHeader in a similar manner as to the MessageBody where the bodyWriter is used? 

@kotovaleksandr - do you think there is any change that could be made in the middleware CreateResponseMessage method? 

https://github.com/DigDes/SoapCore/blob/a11b706010f94439ec00195386b30c7985fc7ef6/src/SoapCore/SoapEndpointMiddleware.cs#L616
