### ISSUE TITLE
OperationContract(IsOneWay = true) still generates the <wsdl:output 

### ISSUE THREAD

**Issue by gsaggu** [DigDes/SoapCore#493]
hi,
does anyone  have an idea why setting the operation service as void and IsOneWay = true generates the **<wsdl: output>** under operation. Is there a way to avoid the Output from WSDL
 
`   public interface IResponseService
    {
         [OperationContract(IsOneWay = true)]
        void SaveResponse(SaveResponseModel inputModel);
    }`

`<wsdl:operation name="SaveResponse">
<wsdl:input wsam:Action="https://rc-api-qual.agconnect.org/IResponseService/SaveResponse" message="tns:IResponseService_SaveResponse_InputMessage"/>
<wsdl:output wsam:Action="https://rc-api-qual.agconnect.org/IResponseService/SaveResponseResponse" message="tns:IResponseService_SaveResponse_OutputMessage"/>
</wsdl:operation>`

**Comment by gsaggu** [comment]
any help here would be appreciated guys! :( kind of stuck here with .net Core 3.1. I tried same service in WCF legacy style. it works as expected and the wsdl generation also doesn't include any OUTPUT

**Comment by gsaggu** [comment]
my modaland service contract as follows
` [Serializable]
    [DataContract ]
    public class SaveResponseModel
    {
        [DataMember(IsRequired = true)]
        public int request_id { get; set; } = 0;
      
        [DataMember (IsRequired = true ,EmitDefaultValue = false)]
        public string status { get; set; }
        
        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public string error_message { get; set; }
    }`

`[ServiceContract()  ]
    public interface IResponseService
    {
        [OperationContract(IsOneWay = true)]
        void SaveResponse(SaveResponseModel inputModel);
    }`

**Comment by gsaggu** [comment]
@kotovaleksandr  please, if you can help me out here would be highly appreciated

**Comment by kotovaleksandr** [comment]
Hi @gsaggu !
Check on latest commit:
https://github.com/DigDes/SoapCore/commit/c5753b09d2b5178ae30b3f90e77898c2e2512af6

**Comment by gsaggu** [comment]
@kotovaleksandr  thansk alot :)  it looks good

adding your fix  If(!operation.IsOneWay) on line 562 (MetaBodywriter.cs) and line 969 (MetaWCFBodyWriter.cs) under AddBinding method makes it perfect

WSDL is also now validated by https://www.wsdl-analyzer.com/

can you pull this fix to your latest release, again thanks a lot man :) you made my day

**Comment by kotovaleksandr** [comment]
Please check on latest nuget package https://www.nuget.org/packages/SoapCore/1.1.0.1-beta

**Comment by gsaggu** [comment]
this is awesome :) thanks really appreciate your help
