### ISSUE TITLE
The request reached the end of the pipeline without executing the endpoint

### ISSUE THREAD

**Issue by mpv06c** [DigDes/SoapCore#495]
I keep getting this issue when I attempt to visit the wsdl page for a service I created in .Net Core 3.0
The request reached the end of the pipeline without executing the endpoint: 'SoapCore'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.

SoapCore version: 1.1.0.1-beta
I have also tried version 1.0.0 with the same result

Code:
Configure Services Function

            services.AddControllers();
            services.AddSoapCore();
            services.TryAddSingleton<MyService>();
            services.AddMvc();

Configure Function

            if (env.IsDevelopment() || env.IsEnvironment("local"))
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
           
            app.UseRouting();
            app.UseAuthorization();            

            app.UseEndpoints(endpoints =>
            {
                endpoints.UseSoapEndpoint<MyService>("/Service.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);
                endpoints.MapControllers();
            });

**Comment by dmathijs** [comment]
For anyone stumbling on this in the future; By default the route is case-sensitive, you can pass a boolean to `UseSoapEndpoint` to change this.
