### ISSUE TITLE
Missing SoapSerializer in 0.9.5

### ISSUE THREAD

**Issue by DarthIwan** [DigDes/SoapCore#50]
I'm missing this new feature in the DLL. Some how is it not implemented in the 0.9.5 NuGet release. It is in the repo, but I can't find anything in the relase version. Is there a mistake, or do I miss something?

**Comment by AlexeyKalina** [comment]
You are right, thank you for the report. Version was updated to 0.9.6

**Comment by DarthIwan** [comment]
Great! Now everything is working as expected. :)

Thanks for the great work!
