### ISSUE TITLE
SoapCore serializes result type (child) instead of operation return type

### ISSUE THREAD

**Issue by truman303** [DigDes/SoapCore#509]
My service method returns a subtype (e.g. ChildResp) of the operation's return type (e.g. ParentResp). The parent is decorated with XmlIncludeAttribute(typeof(ChildResp)). Since the XmlSerilalizer is being used, I expected the output to use the element of the parent and specify the child type as an attribute (for example, xsi:type=a0:ChildResp), however SoapCore seems to serialize the child type directly and this is causing integration problems. I am porting an existing interface and require that the sample messages look the same.

expected output...
<i0:parentResp ... xsi:type="a0:ChildResp" ... >

actual output...
<a0:childResp ... >

some example code...

```c#
    public interface IBinding
    {
        [OperationContract(Action = "parentReq")]
        ParentResp ParentRequest(ParentReq parentReq);
     }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChildResp))] // this is not being used, as the child is serialized instead of the parent.
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mydomain.com/2.1/base/schema")]
    [System.Xml.Serialization.XmlRootAttribute("parentResp", Namespace="http://www.mydomain.com/2.1/base/schema", IsNullable=false)]
    public partial class ParentResp { }

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mydomain.com/2.1/my/schema")]
    [System.Xml.Serialization.XmlRootAttribute("childResp", Namespace="http://www.mydomain.com/2.1/my/schema", IsNullable=false)]
    public partial class ChildResp : ParentResp { }

```

I fiddled with the SoapCore library to rather serialize the return type as specified in operation's signature, i.e. the parent type, and this seems to sort out my issue..

```c#
// see https://referencesource.microsoft.com/System.Xml/System/Xml/Serialization/XmlSerializer.cs.html#c97688a6c07294d5
//var resultType = _result.GetType();   // this serializes child type root element a0:childResp instead of i0:parentResp
var resultType = _operation.ReturnType; // this serializes parent i0:parentResp with attribute xsi:type="a0:ChildResp"
```

..however, i would prefer not to make customisations to the code if not neccessary. Is there an existing way to do this without changing the lib? Do you think this is bug or feature that is missing from SoapCore or am i missing something?

**Comment by shadowkras** [comment]
I also have this problem. Is there any way for a base class to be serialized properly?
I have decored it with XmlInclude, but no luck.

**Comment by truman303** [comment]
I am still using my cusomised version. Looking at the latest source code it appears that part has not changed.

**Comment by oscar982** [comment]
Hi Truman,
can you please share the code of your customization of SoapCore library?
We have same issue and also today we have not found any solution.

Thanks

**Comment by andersjonsson** [comment]
If anyone of you feel like submitting a PR with a generic solution to this problem I'd be happy to get it merged. Seems like this is a missing feature in SoapCore

**Comment by truman303** [comment]
Hi All

The only line I changed was the one I mentioned in my original issue above, I.e. this:

```c#
// see https://referencesource.microsoft.com/System.Xml/System/Xml/Serialization/XmlSerializer.cs.html#c97688a6c07294d5
//var resultType = _result.GetType();   // this serializes child type root element a0:childResp instead of i0:parentResp
var resultType = _operation.ReturnType; // this serializes parent i0:parentResp with attribute xsi:type="a0:ChildResp"
```

The line to change can be found here in the original source:
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/ServiceBodyWriter.cs#L103

I'm not comfortable with a PR at this stage as I'm not sure what the full implications of the change are. Perhaps there are situations where using _result.GetType() is appropriate? Perhaps this should be configurable per service or per request type?

It would be nice to see how the original .Net framework handles this functionality.

**Comment by andersjonsson** [comment]
> I'm not comfortable with a PR at this stage as I'm not sure what the full implications of the change are. Perhaps there are situations where using _result.GetType() is appropriate? Perhaps this should be configurable per service or per request type?
> 
> It would be nice to see how the original .Net framework handles this functionality.

Same. I tried following the original source code starting with https://referencesource.microsoft.com/#System.Web.Services/System/Web/Services/Protocols/XmlReturnWriter.cs and I think your change would be correct. But the old source is not exactly straight forward 😉 

Maybe it would be safe to check for the attributes and alternating behavior depending on the result?

**Comment by oscar982** [comment]
Dear All,
i suppose that give the capabability to chose the beahavior is the best.
