### ISSUE TITLE
How to manage SoapParameterStyle.Bare for request ?

### ISSUE THREAD

**Issue by loic59** [DigDes/SoapCore#514]
As for the response in this post : https://github.com/DigDes/SoapCore/issues/98 , i want to do the same for the request.

Here is the request I get from another system :

```
<?xml version='1.0' encoding='UTF-8'?>
<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
	<soapenv:Header/>
	<soapenv:Body>
		<n:notificationRequest xmlns:n="http://toto.com/notifications">
				<ab>AAA</ab>
				<ac>BBB</ac>
				<ad>CCC</ad>

```
Code for my service :

```
[ServiceContract(Namespace = "http://toto.com/notifications")]
public interface IServiceToto
{
	[OperationContract(Action = "loadOrderNotificationRequest")]
	Task<TotoResponse> notificationRequest(NotificationRequest notificationRequest);
}

public class ServiceToto : IServiceToto
{
	public async Task<TotoResponse> notificationRequest(NotificationRequest notificationRequest)
    {
		//notificationRequest is null
	}
}

[Serializable]
[XmlRoot(Namespace = "http://toto.com/notifications")]")]
public class NotificationRequest
{
	[XmlElement(ElementName = "ab")]
	public string Ab { get; set; }
	[XmlElement(ElementName = "ac")]
	public string Ac { get; set; }
	[XmlElement(ElementName = "ad")]
	public string Ad { get; set; }
}

```

In old code , in .net framework we use this 
`[SoapDocumentMethod(
			Use = SoapBindingUse.Literal,
			ParameterStyle = SoapParameterStyle.Bare)
		]`

How to manage SoapParameterStyle.Bare with SoapCore ? My param notificationRequest is always null.

If i remove namespace and add a level in XML (for the object), it's working.

**Comment by loic59** [comment]
I resolved my problem by adding MessageContract and Namespace ""

[Serializable]
[MessageContract]
[XmlRoot(Namespace = "http://toto.com/notifications")]")]
public class NotificationRequest
{
	[XmlElement(ElementName = "ab",Namespace = "")]
	public string Ab { get; set; }
	[XmlElement(ElementName = "ac",Namespace = "")]
	public string Ac { get; set; }
	[XmlElement(ElementName = "ad",Namespace = "")]
	public string Ad { get; set; }
}

**Comment by neilsimp1** [comment]
Are you using XmlSerializer or DataContractSerializer? This didn't work for me with DataContractSerilizer.

**Comment by loic59** [comment]
I use XmlSerializer with this option  

` SoapEncoderOptions soapEncoderOptions = new SoapEncoderOptions()
            {
                MessageVersion = MessageVersion.Soap12WSAddressingAugust2004,
                WriteEncoding = System.Text.Encoding.UTF8,
                ReaderQuotas = XmlDictionaryReaderQuotas.Max
            };`

**Comment by neilsimp1** [comment]
Thanks, this did not work for me however. Maybe you have an older version of SoapCore since that same line was on 329 for me, not 320.

With these changes:
```
var soapEncoderOptions = new SoapEncoderOptions {
	MessageVersion = System.ServiceModel.Channels.MessageVersion.Soap12WSAddressingAugust2004,
	WriteEncoding = System.Text.Encoding.UTF8,
	ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max,
};

//endpoints.UseSoapEndpoint<INybeApplicationIntakeService>("/ServicePath.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);
endpoints.UseSoapEndpoint<INybeApplicationIntakeService>("/ServicePath.asmx", soapEncoderOptions, SoapSerializer.DataContractSerializer);
```

I now get the error that I described [here](https://github.com/DigDes/SoapCore/issues/550):
```
SoapCore.Meta.MetaBodyWriter.GetMessageContractBodyType(Type type) in MetaBodyWriter.cs
    				return messageBodyMembers[0].Member.GetPropertyOrFieldType();
```

So, I can fix that error by adding [System.ServiceModel.MessageBodyMember] to each property of my request/response objects, but then it returns first property inside of ExampleRequest as the input type rather than exampleRequest itself.
