### ISSUE TITLE
AmbiguousMatchException: Multiple custom attributes of the same type found.

### ISSUE THREAD

**Issue by timurabdurafeev** [DigDes/SoapCore#529]
I'm using XmlSerializer
`app.UseSoapEndpoint<IcTransactionService>("/services/IcTransactionService", new BasicHttpBinding(), SoapSerializer.XmlSerializer, true);`

and my request object contains multiple xmlelement's attributes like 

`  [System.Xml.Serialization.XmlElementAttribute("Element1", typeof(ClassType1), Order=4)]
  [System.Xml.Serialization.XmlElementAttribute("Element2", typeof(ClassType2), Order=4)]`

I got this exceptions once I pulled wsdl

An unhandled exception occurred while processing the request.
AmbiguousMatchException: Multiple custom attributes of the same type found.
System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, bool inherit)

Stack Query Cookies Headers Routing
AmbiguousMatchException: Multiple custom attributes of the same type found.
System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, bool inherit)
System.Reflection.CustomAttributeExtensions.GetCustomAttribute<T>(MemberInfo element)
SoapCore.Meta.MetaBodyWriter.AddSchemaTypeProperty(XmlDictionaryWriter writer, PropertyInfo property, TypeToBuild parentTypeToBuild)
SoapCore.Meta.MetaBodyWriter.AddSchemaComplexType(XmlDictionaryWriter writer, TypeToBuild toBuild)
SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
SoapCore.Meta.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.BodyWriter.WriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteBodyContents(XmlDictionaryWriter writer)
SoapCore.Meta.MetaMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteMessage(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteMessage(XmlWriter writer)
SoapCore.MessageEncoder.SoapMessageEncoder.WriteXmlCore(Message message, XmlWriter xmlWriter)
SoapCore.MessageEncoder.SoapMessageEncoder.WriteMessageAsync(Message message, PipeWriter pipeWriter)
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.ProcessMeta(HttpContext httpContext)
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by vholovko** [comment]
@timurabdurafeev 
Actually I've had the same AmbiguousMatchException being thrown during WSDL generation until I found out that multiple elements for a single property can be represented by [XmlChoiceIdentifierAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlchoiceidentifierattribute?view=netcore-3.1) 

So I came up with https://github.com/DigDes/SoapCore/pull/525 which was released in `1.1.0.3-beta` version.

Depending on the nature of the property, there can be two cases:

1. An object field that can have either `ClassType1` or `ClassType2` type.
```
[XmlType(IncludeInSchema = false)]
public enum ItemChoiceType
{
	Element1,
	Element2
}

[XmlChoiceIdentifier("ItemType")]
[XmlElementAttribute("Element1", typeof(ClassType1), Order=4)] 
[XmlElementAttribute("Element2", typeof(ClassType2), Order=4)]
public object Item {
    get { return _item; }
    set { _item = value; }
}

[XmlIgnore]
public ItemChoiceType ItemType {
    get { return ToItemChoiceType( _item  ); }
    set { }
}

private ItemChoiceType ToItemChoiceType(object instance)
{
    switch( instance )
    {
        case ClassType1 _:
            return ItemChoiceType.Element1;
        case ClassType2 _:
            return ItemChoiceType.Element2;
        default:
            throw new ArgumentException(
                message: "instance of not recognized class type",
                paramName: nameof(instance));
    }
}
```

2. An object array field where item can be of either `ClassType1` or `ClassType2` type.

```
[XmlChoiceIdentifier("ItemTypes")]
[XmlElementAttribute("Element1", typeof(ClassType1), Order=4)] 
[XmlElementAttribute("Element2", typeof(ClassType2), Order=4)]
public object[] Items{
    get { return _items.ToArray(); }
    set { _items = value; }
}

[XmlIgnore]
public ItemChoiceType ItemTypes {
    get { return _items.Select( ToItemChoiceType ).ToArray(); }
    set { }
}
```

The corresponding WSDL should look like 
```
<xsd:choice>
    <xsd:element minOccurs="0" maxOccurs="1" name="Element1" type="tns:Element1"/>
    <xsd:element minOccurs="0" maxOccurs="1" name="Element2" type="tns:Element2"/>
</xsd:choice>
```
in former case and 

```
<xsd:choice minOccurs="0" maxOccurs="unbounded">
    <xsd:element minOccurs="0" maxOccurs="1" name="Element1" type="tns:Element1"/>
    <xsd:element minOccurs="0" maxOccurs="1" name="Element2" type="tns:Element2"/>
</xsd:choice>
```
in latter case.

Hope it helps.

**Comment by timurabdurafeev** [comment]
here is my code
 ` [XmlChoiceIdentifier("ItemType")]
        [XmlElement("BusinessSubjects", typeof(InterConnectRequestTypeBusinessSubjects))]
        [XmlElement("ConsumerSubjects", typeof(InterConnectRequestTypeConsumerSubjects))]
        public object Item
        {
            get => _item;
            set => _item = value;
        }

        [XmlIgnore]
        public ItemChoiceType ItemType => ToItemChoiceType(_item);

        object _item;

        private ItemChoiceType ToItemChoiceType(object instance)
        {
            switch (instance)
            {
                case InterConnectRequestTypeBusinessSubjects _:
                    return ItemChoiceType.BusinessSubjects;
                case InterConnectRequestTypeConsumerSubjects _:
                    return ItemChoiceType.ConsumerSubjects;
                default:
                    throw new ArgumentException(@"instance of not recognized class type", nameof(instance));
            }
        }

        [XmlType(IncludeInSchema = false)]
        public enum ItemChoiceType
        {
            BusinessSubjects,
            ConsumerSubjects
        }
`

got this error 

AmbiguousMatchException: Multiple custom attributes of the same type found.
System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, bool inherit)
System.Reflection.CustomAttributeExtensions.GetCustomAttribute<T>(MemberInfo element)
SoapCore.Meta.MetaBodyWriter.AddSchemaTypeProperty(XmlDictionaryWriter writer, PropertyInfo property, TypeToBuild parentTypeToBuild) in MetaBodyWriter.cs
+
			var elementItem = property.GetCustomAttribute<XmlElementAttribute>();
SoapCore.Meta.MetaBodyWriter.AddSchemaComplexType(XmlDictionaryWriter writer, TypeToBuild toBuild) in MetaBodyWriter.cs
+
								AddSchemaTypeProperty(writer, element, toBuild);
SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer) in MetaBodyWriter.cs
+
				AddSchemaComplexType(writer, toBuild);
SoapCore.Meta.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer) in MetaBodyWriter.cs
+
			AddTypes(writer);
System.ServiceModel.Channels.BodyWriter.WriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteBodyContents(XmlDictionaryWriter writer)
SoapCore.Meta.MetaMessage.OnWriteBodyContents(XmlDictionaryWriter writer) in MetaMessage.cs
+
			_message.WriteBodyContents(writer);
System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteMessage(XmlDictionaryWriter writer)
System.ServiceModel.Channels.Message.WriteMessage(XmlWriter writer)
SoapCore.MessageEncoder.SoapMessageEncoder.WriteXmlCore(Message message, XmlWriter xmlWriter) in SoapMessageEncoder.cs
+
			message.WriteMessage(xmlWriter);
SoapCore.MessageEncoder.SoapMessageEncoder.WriteMessageAsync(Message message, PipeWriter pipeWriter) in SoapMessageEncoder.cs
+
			WriteXmlCore(message, xmlWriter);
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.ProcessMeta(HttpContext httpContext) in SoapEndpointMiddleware.cs
+
			await WriteMessageAsync(_messageEncoders[0], responseMessage, httpContext);
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider) in SoapEndpointMiddleware.cs
+
				await ProcessMeta(httpContext);
SoapCore.SoapEndpointMiddleware<T_MESSAGE>.Invoke(HttpContext httpContext, IServiceProvider serviceProvider) in SoapEndpointMiddleware.cs
+
						await ProcessOperation(httpContext, serviceProvider);
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by vholovko** [comment]
What version of SoapCore are you using ?

**Comment by timurabdurafeev** [comment]
1.1.0.3-beta

**Comment by vholovko** [comment]
Yes, in 1.0.0 it generates an array of objects in WSDL. 

This is strange, did you try to Restore the NuGet packages in the solution, then clean the project and build again ? 
If this does not help try to clone the SoapCore project aside from you main project and directly link the project source instead of using the package.

Then in  `MetaBodyWriter.cs` inside the `private void AddSchemaTypeProperty(XmlDictionaryWriter writer, PropertyInfo property, TypeToBuild parentTypeToBuild)` place the breakpoint againts`if (property.IsChoice())` condition. And see is this is true for your `public object Item` property.

**Comment by timurabdurafeev** [comment]
![image](https://user-images.githubusercontent.com/1639596/95769109-fcb30200-0c7c-11eb-8515-11e38f51d9d7.png)

**Comment by vholovko** [comment]
This is great, since we are adding the <xs:choice /> to the WSDL and returning right after.
And still you have this `AmbiguousMatchException: Multiple custom attributes of the same type found.` ?
On what property then ? Might be it's another property, not the `Item` ?

**Comment by timurabdurafeev** [comment]
You are right, I found another properties which contains multiple XmlElement attributes. 
And I can confirm the described case doesn't throw an exception anymore. 

Let me cover all properties with XmlChoice approach and I let you know. 
Thanks

**Comment by jmwheeler** [comment]
I am following the pattern outlined above using the XmlChoiceIdentifier attribute.  This allows the metadata to be constructed without error but now I am getting an error when trying to use the service.
 
Outer Exception:

System.InvalidOperationException: There was an error reflecting type 'PartnerAPI.SOAP.AccountTransfer.Models.AccountTransferRequestPayloadType'.

Inner Exception: 

Type PartnerAPI.SOAP.AccountTransfer.Models.VerificationMetadataType.VerificationCodeType is missing enumeration value 'http://hix.cms.gov/0.1/hix-core:AddressVerificationCode' for element 'AddressVerificationCode' from namespace 'http://hix.cms.gov/0.1/hix-core'.

Any direction you can provide on getting this to work?

**Comment by jmwheeler** [comment]
I was able to resolve my problem.  The enum values have to exactly match the elementName defined in the XmlElementAttribute.  I had some hyphens in some of the element names which aren't allowed by C#.  In that case I was able to solve by placing [XmlEnum("elementName")] on the enum values that contained hyphens.

**Comment by mwysocki87** [comment]
Hey! Bumping this thread because I've run into the same issue (AmbiguousMatchException). However, the weirdest thing in my case is I don't get the error when debugging locally in VS - there everything works fine. It's only when the application runs on remote host (Istio + K8S pod) where the error pops up. Would you have any idea what could be causing such behavior?

Much obliged!
