### ISSUE TITLE
How does one log raw messages on client and server side?

### ISSUE THREAD

**Issue by MihaMarkic** [DigDes/SoapCore#533]
How would I log raw messages on both client (responses) and server (requests) side?
Let's say with BasicHttpBinding

**Comment by MihaMarkic** [comment]
Looks like [this](https://github.com/dotnet/wcf/issues/3231#issuecomment-432834927) is the solution (at least for client side logging). Have to test it on server side.

**Comment by Simon-Campbell** [comment]
In my solution I layer the SOAP Core with middleware which grabs at the HttpContext and thus can get the request body.

**Comment by sgf** [comment]
> I have written solutions in the past using middleware to get the injected HttpContext (IHttpContextAccessor IIRC). Once you have the HttpContext you can get the request body, but you will have to enable "rewinding" of requests.
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-3.1

thats not good way.
