### ISSUE TITLE
I need to capture the raw XML request, is there a way to do this?

### ISSUE THREAD

**Issue by BonnieSoftware** [DigDes/SoapCore#542]
I need to capture the raw XML request for logging purposes, is this possible to do as the current interface makes it seem unlikely.

**Comment by mtpultz** [comment]
I'd like to do the same thing, but as far as I know you can't do it using a model with a single XElement navigation property, but you can use a tuner service:

```
namespace Services
{
    public class SoapServiceOperationTuner : IServiceOperationTuner
    {
        public void Tune(HttpContext httpContext, object serviceInstance,
            SoapCore.ServiceModel.OperationDescription operation)
        {
            if (serviceInstance is SoapAdapterAdapterService service)
            {
                service.Request = httpContext.Request;
            }
        }
    }

    [ServiceContract(Namespace = "EXAMPLE_1")]
    public interface ISoapAdapterService
    {
        [OperationContract(Name = "EXAMPLE_IN0000000")]
        void Method1();
    }

    public class SoapAdapterAdapterService : ISoapAdapterService
    {
        public HttpRequest Request { get; set; }

        public async void Method1() // Doesn't use a model
        {
            Console.WriteLine(Request.Body); // Envelope + XML
        }
    }
}
```

**Comment by Matthew-Bonner** [comment]
Thanks for your help, if this is the case I think I'm going to stick with WebAPI if I can't use models as it isn't really any different to using WebAPI without having to reference an additional library.

**Comment by mtpultz** [comment]
Yah, my exploration of SoapCore has been a bit frustrating in that sense.  I ended up using SoapCore since I can use the ServiceContract namespace and OperationContract name to route to specific methods where I can deserialize only specific parts of the request using XPath.

**Comment by nkdanfer** [comment]
Thanks this really helps. If I want an sync method to logging this, like the IAsyncResourceFilter in aspnetcore filters , if there's any way?

**Comment by dsthode** [comment]
I have logged the incoming request using the following middleware in the service stack:

```csharp
    public class LoggingMiddleware {
        private readonly RequestDelegate _next;
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();

        public LoggingMiddleware(RequestDelegate next) {
            _next = next;
        }

        public async Task Invoke(HttpContext context) {
            context.Request.EnableBuffering();
            using (var reader = new StreamReader(context.Request.Body, leaveOpen: true)) {
                logger.Debug("Request body:" + reader.ReadToEnd());
                context.Request.Body.Position = 0;
            }
            await _next(context);
        }
    }

```

Then I use it this way in my ```Configure``` method:

```csharp
app.UseMiddleware<LoggingMiddleware>();
```

**Comment by tkwin** [comment]
I would like to get raw soap xml from request body, but it always return as empty string. Do I miss some stuffs to configure ?
```
public class ServiceOperationTuner : IServiceOperationTuner
    {
        public void Tune(HttpContext httpContext, object serviceInstance, OperationDescription operation)
        {
            if (serviceInstance is PayByCellAcceptEndPoint service)
            {                
                httpContext.Request.EnableBuffering();
                var reader = new StreamReader(httpContext.Request.Body);
                reader.BaseStream.Seek(0, SeekOrigin.Begin);
                var xmlRequestBody = reader.ReadToEndAsync().GetAwaiter().GetResult();              
            }
        }
    }
```

**Comment by vadimpain** [comment]
@tkwin you found the reason why you get an empty body?

**Comment by andersjonsson** [comment]
@vadimpain
It is a consequence of removing memory buffering in a commit back in 2021.
Even though you enable buffering in your tuner it's too late. The body has already been read.

There are multiple ways to solve your issue, depending on what you're trying to accomplish.
Start by reading #861 

if that doesn't lead you to a solution I'd recommend opening a new issue, explaining what you are trying to do.

EDIT: Just realized that you were the one that opened #861, @tkwin. Sorry for pinging you about an already solved issue on your part 🤦‍♂️

**Comment by vadimpain** [comment]
@andersjonsson Thanks for the answer. Created https://github.com/DigDes/SoapCore/issues/926#issue-1476281511

**Comment by pboettcher** [comment]
Thank you very much for this code. It works.
But it logs only the incoming requests. Requests my application receives.
Is there any way to log requests sent by SoapCore from my application to the other side?
