### ISSUE TITLE
Support for parameterless operation contracts

### ISSUE THREAD

**Issue by rinkeb** [DigDes/SoapCore#567]
Hi, for some of our message contracts we need to to accept soap messages without a body. As far as i can see is currently not supported. 

For example, we need to accept echo response pings via this message:
```http
POST https://localhost:5001/service.svc HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "EchoResponse"
Content-Length: 139
Host: localhost:5001
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.5 (Java/12.0.1)

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Header/>
   <soapenv:Body/>
</soapenv:Envelope>
```
Unfortunately this results in the following exceptions:

Exception when generating the wsdl on service startup:
```csharp
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. 
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SoapCore.Meta.MetaBodyWriter.GetMessageContractBodyType(Type type)
   at SoapCore.Meta.MetaBodyWriter.WriteParameters(XmlDictionaryWriter writer, SoapMethodParameterInfo[] parameterInfos, Boolean isMessageContract)
   at SoapCore.Meta.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
   at SoapCore.Meta.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BodyWriter.WriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteBodyContents(XmlDictionaryWriter writer)
   at SoapCore.Meta.MetaMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessage(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessage(XmlWriter writer)
   at SoapCore.MessageEncoder.SoapMessageEncoder.WriteXmlCore(Message message, XmlWriter xmlWriter)
   at SoapCore.MessageEncoder.SoapMessageEncoder.<WriteMessageAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
    System.Collections.Generic.List<T>.this[int].get(int)
    SoapCore.Meta.MetaBodyWriter.GetMessageContractBodyType(System.Type)
    SoapCore.Meta.MetaBodyWriter.WriteParameters(System.Xml.XmlDictionaryWriter, SoapCore.ServiceModel.SoapMethodParameterInfo[], bool)
    SoapCore.Meta.MetaBodyWriter.AddTypes(System.Xml.XmlDictionaryWriter)
    SoapCore.Meta.MetaBodyWriter.OnWriteBodyContents(System.Xml.XmlDictionaryWriter)
    System.ServiceModel.Channels.BodyWriter.WriteBodyContents(System.Xml.XmlDictionaryWriter)
    System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(System.Xml.XmlDictionaryWriter)
    System.ServiceModel.Channels.Message.WriteBodyContents(System.Xml.XmlDictionaryWriter)
    SoapCore.Meta.MetaMessage.OnWriteBodyContents(System.Xml.XmlDictionaryWriter)
    ...
    [Call Stack Truncated]
```

Exception when the service operation is invoked:
```csharp
System.InvalidOperationException
  HResult=0x80131509
  Message=The body of the message cannot be read because it is empty.
  Source=System.Private.ServiceModel
  StackTrace:
   at System.ServiceModel.Channels.Message.GetReaderAtBodyContents()
   at SoapCore.SoapEndpointMiddleware`1.<ProcessOperation>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    System.ServiceModel.Channels.Message.GetReaderAtBodyContents()
    SoapCore.SoapEndpointMiddleware<T_MESSAGE>.ProcessOperation(Microsoft.AspNetCore.Http.HttpContext, System.IServiceProvider)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

It would be nice if the library could support this. 
If you like i can create a pull request with a resolution.

**Comment by kotovaleksandr** [comment]
Hi @rinkeb ! Of course it will be nice, please create PR with fix.

**Comment by jonas-jaderberg** [comment]
Hi,
I discovered a possible problem when calling parameterless operations from .Net Framework clients by using wsdl.exe or web reference. A fix for that is in pr #570

**Comment by rinkeb** [comment]
@jonas-jaderberg okay, i closed #569 due to some rebasing issues and planned to recreate the PR the coming days on the latest head with some additional fixes and soap11 tests. 

Looks like #570 touches code in the same area. Maybe its better if I wait with my PR until #570 is merged to avoid nasty merge conflicts?

**Comment by kotovaleksandr** [comment]
@rinkeb #570 PR already merged, please resend PR with green tests

**Comment by rinkeb** [comment]
@kotovaleksandr done, all tests are green now.

**Comment by jonas-jaderberg** [comment]
Sorry, #571 caused my scenario to fail.
This line 
var arguments = requestMessage.IsEmpty ? Array.Empty<object>() : GetRequestArguments(requestMessage, reader, operation, httpContext);
Is the problem. In my case requestMessage.IsEmpty is true, but it's handled nicely in the GetRequestArguments method. My case uses MessageContract and from the comment in code 
// MessageContracts are constrained to having one "InParameter". We can do special logic on
// for this
So in my case the problem line should just be
var arguments = GetRequestArguments(requestMessage, reader, operation, httpContext);

**Comment by rinkeb** [comment]
@jonas-jaderberg Sorry to hear that. Looks like your case is currently not covered by the unit tests. 

I think it would be best if you create a unit test that covers your specific message contract scenario and then fix the regression. This would guard your scenario from breaking in the future.

**Comment by jonas-jaderberg** [comment]
@rinkeb, yes I try to add that now.

**Comment by jonas-jaderberg** [comment]
@rinkeb this PR #572, I hope, should correct this. I now also figured out how to add tests that guard my scenario which is MessageContracts

**Comment by kotovaleksandr** [comment]
Merged, need new version of nuget package?

**Comment by rinkeb** [comment]
@kotovaleksandr Would be nice, but no hurries.

**Comment by kotovaleksandr** [comment]
@rinkeb https://www.nuget.org/packages/SoapCore/1.1.0.6

**Comment by rinkeb** [comment]
Thanks. The new nuget works perfectly in my project setup.
