### ISSUE TITLE
Don't wrap request in operation name

### ISSUE THREAD

**Issue by JulianBiermann** [DigDes/SoapCore#57]
Hi,

I'm trying to use this middleware in a project. We're currently calling an existing SOAP Endpoint from an external source which means we are using existing message formats.

The problem is that the format requires us that the request is not wrapped in the operation tags.

**Example:**

What we want to use:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header/>
   <soap:Body>
     <Message>A simple message</Message>
   </soap:Body>
</soap:Envelope>
```

But what we have to use to make the middleware work:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header/>
   <soap:Body>
     <TestOperation>
         <Message>A simple message</Message>
     <TestOperation>
   </soap:Body>
</soap:Envelope>
```

Is it possible to define our Service Contract that way?

Best Regards
Julian

**Comment by LuisLanfrediPoatek** [comment]
Could you solve this @JulianBiermann ?

**Comment by DmitryBryluk** [comment]
fixed it [here](https://github.com/DigDes/SoapCore/pull/111)

**Comment by DmitryBryluk** [comment]
look and experiment with extended samples under serialization tests, may be it covers your case. now it is updated to make posible XmlSerializer to deal with legacy wcf/ws

**Comment by JulianBiermann** [comment]
We already made our custom implementation because of growing requirments to the API.

Thanks anyways
