### ISSUE TITLE
AddSoapWsSecurityFilter not working (Authentication error: Authentication failed...)

### ISSUE THREAD

**Issue by Ivanca** [DigDes/SoapCore#579]
I'm trying to use AddSoapWsSecurityFilter without success, it throws "Authentication error: Authentication failed: the supplied credential is not right" despite using the correct username and password, any idea?

![image](https://user-images.githubusercontent.com/907138/104387004-3b6a8980-5504-11eb-89c0-76c3343dee9f.png)
![image](https://user-images.githubusercontent.com/907138/104387090-694fce00-5504-11eb-84d9-88f5a584cbe2.png)

cc @neilsimp1

**Comment by neilsimp1** [comment]
It looks like this may have been updated a bit since I worked on it. I can try and set up a local environment and test this out and let you know how it goes, but from glancing at https://github.com/DigDes/SoapCore/blob/c9f36ace6ac8ce819249915fe19e4dbd928463c6/src/SoapCore/WsMessageFilter.cs#L91, have you tried removing the `Type` attribute from `<wsse:Password>`?

**Comment by douglassimaodev** [comment]
@neilsimp1 would you be able to tell me how did you do to get this added:
<wsse:Security xmlns:wsse=""http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"">
			<wsse:UsernameToken>
				<wsse:Username>username</wsse:Username>
				<wsse:Password>password</wsse:Password>
			</wsse:UsernameToken>
		</wsse:Security>
		
		like I am trying to add header to mine but don't know how
		
		https://stackoverflow.com/questions/66432054/soapcore-asp-net-core-3-1-header

**Comment by neilsimp1** [comment]
I am unclear, are you attempting to use use SoapCore as a SOAP client or server?

If you are trying to set up a server and require WSSE username/password, then adding `services.AddSoapWsSecurityFilter("username", "password");` into `ConfigureServices()` like OP did here would be the way to do it.

**Comment by douglassimaodev** [comment]
Hi @neilsimp1  Thanks for your message

yes this does work (services.AddSoapWsSecurityFilter("username", "password");) and wont work if those values are not supplied

I have a webapi and I am using soapcore to expose my services interfaces to be consumed by SoapUi [ServiceContract]

when I map my app.UseSoapEndpoint<ISOAManagerService>("/SOAManager.svc", etc to soap UI it creates all the calls and parameters, all fine

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetService>
         <tem:ServiceType>?</tem:ServiceType>
         <tem:ServiceName>?</tem:ServiceName>
         <tem:ServiceVersion>?</tem:ServiceVersion>
      </tem:GetService>
   </soapenv:Body>
</soapenv:Envelope>

but my  <soapenv:Header/> is always like that, maybe that is how it should be but I was expecting it creates the params I was expecting when I map it will display like that no?

 <soapenv:Header>
         <username>?</username>
         <password>?</password>
  </soapenv:Header>

**Comment by neilsimp1** [comment]
Got you.

My answer is I am not sure if SOAP UI or other similar tools will or should generate that header for you or not.

At my day job, I interact with some SOAP services (not SoapCore) and whenever we generate a SOAP UI project for them we have to manually copy something like this in:

```
	<soapenv:Header>
		<wsse:Security xmlns:wsse=""http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"">
			<wsse:UsernameToken>
				<wsse:Username>username</wsse:Username>
				<wsse:Password>password</wsse:Password>
			</wsse:UsernameToken>
		</wsse:Security>
	</soapenv:Header>
```

**Comment by douglassimaodev** [comment]
Hi @neilsimp1 Thanks for you help!

if I can ask  I am returning this:
[OperationContract(Name = "SOAManagerGetServiceRequest")]
        public ServiceData GetService(
            ConnectionData ConnectionData,
            string ServiceType,
            string ServiceName,
            string ServiceVersion);
            
        But in Soap Ui this ServiceData is translated as "SOAManagerGetServiceRequestResult"
        <SOAManagerGetServiceRequestResponse
             <SOAManagerGetServiceRequestResult
             
             
             Even tho I set it 
             [DataContract(Name = "ServiceData")]
             public class ServiceData
             
             is there a way to configure the name it will be displayed?

**Comment by neilsimp1** [comment]
If you change `[OperationContract(Name = "SOAManagerGetServiceRequest")]` to something like `[OperationContract(Name = "ServiceData")]`, does that work? (I am guessing a bit here, I am not sure).
