### ISSUE TITLE
How to manipulate answer xml

### ISSUE THREAD

**Issue by MaSchue1** [DigDes/SoapCore#582]
I am getting following response:
`
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <s:Body>
        <putResponse xmlns="http://odg_und_partner/OCIT_C">
            <putResult>
                <errorCode>0</errorCode>
            </putResult>
        </putResponse>
    </s:Body>
</s:Envelope>"
`
I would like to eliminate the "putResult" level, as you can see in the following

`
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <s:Body>
        <putResponse xmlns="http://odg_und_partner/OCIT_C">
                <errorCode>0</errorCode>
        </putResponse>
    </s:Body>
</s:Envelope>"
`

**Comment by Mazafakaa** [comment]
Using MessageContractAttribute solved this problem for me
