### ISSUE TITLE
Version 1.1.0.4 and greater breaks GetRequestArguments

### ISSUE THREAD

**Issue by silvioboehme** [DigDes/SoapCore#583]
This request is from a java client is workling fine in 1.1.0.4 beta and lower and results in a endless loop in 1.1.0.4 (release) and higher.

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.preapproval.ws.carano.com">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:setDecision>
         
         <ser:setDecision>
            <capsAntragsID>6000</capsAntragsID>
            <dateTime>2018-03-09</dateTime>
            <capsAntragsNummer>TEST-6000</capsAntragsNummer>
            
            <infoText>OK</infoText>
            
            <infoTitle>OK</infoTitle>
            <status>REJECTED</status>
            <maxKreditbetrag>120000</maxKreditbetrag>
            <maxRatenbetrag>2000</maxRatenbetrag>
         </ser:setDecision>
      </ser:setDecision>
   </soapenv:Body>
</soapenv:Envelope>`

Endless loop is in GetRequestArguments:
while (!xmlReader.EOF) never terminates.

**Comment by silvioboehme** [comment]
`namespace Kiwi.AutoFinance.InquireScb.Domain.Interface
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.preapproval.ws.carano.com", ConfigurationName = "Kiwi.AutoFinance.InquireScb.Domain.Interface.IPreApprovalService")]
    public interface IPreApprovalService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://service.preapproval.ws.carano.com/setDecision")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(capsFeedbackObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AckResult")]
        Kiwi.AutoFinance.InquireScb.Domain.Interface.ackResult setDecision([System.ServiceModel.MessageParameterAttribute(Name = "setDecision")] Kiwi.AutoFinance.InquireScb.Domain.Interface.capsDecision setDecision1);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public partial class capsDecision : capsFeedbackObject
    {

        private capsStatus statusField;

        private decimal maxKreditbetragField;

        private decimal maxRatenbetragField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public capsStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal maxKreditbetrag
        {
            get
            {
                return this.maxKreditbetragField;
            }
            set
            {
                this.maxKreditbetragField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public decimal maxRatenbetrag
        {
            get
            {
                return this.maxRatenbetragField;
            }
            set
            {
                this.maxRatenbetragField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public enum capsStatus
    {

        /// <remarks/>
        REJECTED,

        /// <remarks/>
        DISBURSED,

        /// <remarks/>
        ACCOUNTED,

        /// <remarks/>
        RESIGNED,

        /// <remarks/>
        APPROVED,

        /// <remarks/>
        IN_DECISION,

        /// <remarks/>
        PENDING,

        /// <remarks/>
        CANCELLED,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(capsDecision))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public abstract partial class capsFeedbackObject
    {

        private long capsAntragsIDField;

        private System.DateTime dateTimeField;

        private string capsAntragsNummerField;

        private string infoTextField;

        private string infoTitleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long capsAntragsID
        {
            get
            {
                return this.capsAntragsIDField;
            }
            set
            {
                this.capsAntragsIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string capsAntragsNummer
        {
            get
            {
                return this.capsAntragsNummerField;
            }
            set
            {
                this.capsAntragsNummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string infoText
        {
            get
            {
                return this.infoTextField;
            }
            set
            {
                this.infoTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string infoTitle
        {
            get
            {
                return this.infoTitleField;
            }
            set
            {
                this.infoTitleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public partial class ackResult
    {

        private ackResultCode codeField;

        private string messageField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ackResultCode code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public enum ackResultCode
    {

        /// <remarks/>
        OK,

        /// <remarks/>
        KO,
    }
}
`

**Comment by silvioboehme** [comment]
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiwi.Demo
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.preapproval.ws.carano.com", ConfigurationName = "Kiwi.Demo.IPreApprovalService")]
    public interface IPreApprovalService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://service.preapproval.ws.carano.com/setDecision")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(capsFeedbackObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "AckResult")]
        Kiwi.Demo.ackResult setDecision([System.ServiceModel.MessageParameterAttribute(Name = "setDecision")] Kiwi.Demo.capsDecision setDecision1);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public partial class capsDecision : capsFeedbackObject
    {

        private capsStatus statusField;

        private decimal maxKreditbetragField;

        private decimal maxRatenbetragField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public capsStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public decimal maxKreditbetrag
        {
            get
            {
                return this.maxKreditbetragField;
            }
            set
            {
                this.maxKreditbetragField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public decimal maxRatenbetrag
        {
            get
            {
                return this.maxRatenbetragField;
            }
            set
            {
                this.maxRatenbetragField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public enum capsStatus
    {

        /// <remarks/>
        REJECTED,

        /// <remarks/>
        DISBURSED,

        /// <remarks/>
        ACCOUNTED,

        /// <remarks/>
        RESIGNED,

        /// <remarks/>
        APPROVED,

        /// <remarks/>
        IN_DECISION,

        /// <remarks/>
        PENDING,

        /// <remarks/>
        CANCELLED,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(capsDecision))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public abstract partial class capsFeedbackObject
    {

        private long capsAntragsIDField;

        private System.DateTime dateTimeField;

        private string capsAntragsNummerField;

        private string infoTextField;

        private string infoTitleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long capsAntragsID
        {
            get
            {
                return this.capsAntragsIDField;
            }
            set
            {
                this.capsAntragsIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string capsAntragsNummer
        {
            get
            {
                return this.capsAntragsNummerField;
            }
            set
            {
                this.capsAntragsNummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string infoText
        {
            get
            {
                return this.infoTextField;
            }
            set
            {
                this.infoTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string infoTitle
        {
            get
            {
                return this.infoTitleField;
            }
            set
            {
                this.infoTitleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public partial class ackResult
    {

        private ackResultCode codeField;

        private string messageField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ackResultCode code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.preapproval.ws.carano.com")]
    public enum ackResultCode
    {

        /// <remarks/>
        OK,

        /// <remarks/>
        KO,
    }
}

**Comment by silvioboehme** [comment]
public sealed class PreApprovalService : IPreApprovalService
    {
        [return: MessageParameter(Name = "AckResult")]
        public ackResult setDecision([MessageParameter(Name = "setDecision")] capsDecision setDecision1)
        {
            Console.WriteLine(setDecision1.capsAntragsNummer);
            return new ackResult { code = ackResultCode.OK, message = "asdad", state = "asdad" };
        }
    }

**Comment by BobBeix** [comment]
I'm seeing WSDL problems in versions 1.1.0.6 and later.  It seems the handling of input parameters quit working with this version.  My interface defines the following Ping method:

        [OperationContract]
        string Ping(string testString);

The WSDL created by the service defines the input and output parameters as the following.  This is consistent in all versions, so it doesn't seem there's a problem with this part of the WSDL.

      <xsd:element name="Ping">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" maxOccurs="1" name="testString" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="PingResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" maxOccurs="1" name="PingResult" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

However, when the WSDL defines the messages, I'm seeing the following with version 1.1.0.5, which seems correct.  The input and output parameters are included as part of the messages.

 <wsdl:message name="ISpecialActivity_Ping_InputMessage">
    <wsdl:part name="parameters" element="tns:Ping" />
  </wsdl:message>
  <wsdl:message name="ISpecialActivity_Ping_OutputMessage">
    <wsdl:part name="parameters" element="tns:PingResponse" />
  </wsdl:message>
 
When I upgrade to version 1.1.0.6 or 1.1.0.7, I get the following in my WSDL.  The input parameter is being skipped for some reason.  The same thing is happening for other methods in my interface that have more complex input parameters.

  <wsdl:message name="ISpecialActivity_Ping_InputMessage" />
  <wsdl:message name="ISpecialActivity_Ping_OutputMessage">
    <wsdl:part name="parameters" element="tns:PingResponse" />
  </wsdl:message>

This causes major problems for clients using these services as the interface isn't fully defined.  I'm going to stick with 1.1.0.5 until this is addressed.
