### ISSUE TITLE
Memory Leak Issue 

### ISSUE THREAD

**Issue by bluedog13** [DigDes/SoapCore#59]
I just have added the below line of code in StartUp.cs 
app.UseSoapEndpoint <MyService> ("/Service.svc", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);

And in the actual service implementation, it returns null at the moment.

So when I do a load test with around 100 requests/minute,  the memory increases to 1GB from 100MB (using Diagnostics tool).  Is there a memory leak issue?

**Comment by kotovaleksandr** [comment]
Maybe, i tried to reproduce leak on simple request in infinity loop - no result, process memory about 130 MB. Can you provide code sample?
PS. What .NET version you used: 4.5.1 or .NET Core?

**Comment by bluedog13** [comment]
I am using .NET core 2.x.  I realized that this might have to do with .net LOH (Large Object Heap) and not your NuGet package.  I tried the same function on .NET 4.6.1 full stack using WCF ad saw similar behaviour.  If you use a string >85,000KB as a function argument and run the app, you might see similar behaviour on .net framework. 

Thank you for looking into the issue and getting back.  I can say, the memory leak is not related to your NuGet package.

**Comment by bhenden** [comment]
I have also experienced memory leak issues, and have tracked it to [XmlSerializer](https://github.com/DigDes/SoapCore/blob/7522970ae761bca10f43ca73b04efc90db3479b7/src/SoapCore/SoapEndpointMiddleware.cs#L275) constructor. There is an explanation under the heading Dynamically Generated Assemblies [here](https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlserializer(v=vs.110).aspx).

I've created my own caching of these serializers, and doing some more tests to see if that helps.
