### ISSUE TITLE
complex type out parameters in OperationContract creates wrong wsdl

### ISSUE THREAD

**Issue by ruwentos** [DigDes/SoapCore#592]
I have an operation contract like this:

`[OperationContract]
 List<PropertyStub> GetDocumentDetails(Guid documentId, Guid processId, out DocumentFullInfoStub docData, out SystemStatus status, out JoinCandidate[] candidates);`

All out parameters are complex types.

In the generated xml one can find this part:
`<xs:element name="GetDocumentDetailsResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q27="http://schemas.datacontract.org/2004/07/Sequence_Bridge_MS.WCF.CommonContracts" minOccurs="1" name="GetDocumentDetailsResult" nillable="true" type="q27:ArrayOfPropertyStub"/>
<xs:element xmlns:q28="http://schemas.datacontract.org/2004/07/Sequence_Bridge_MS.WCF.CommonContracts" minOccurs="1" name="docData" nillable="true" type="q28:DocumentFullInfoStub&"/>
<xs:element xmlns:q29="http://schemas.datacontract.org/2004/07/Sequence_Bridge_MS.WCF.CommonContracts" minOccurs="1" name="status" type="q29:SystemStatus&"/>
<xs:element xmlns:q30="http://schemas.datacontract.org/2004/07/Sequence_Bridge_MS.WCF.CommonContracts" minOccurs="1" name="candidates" nillable="true" type="q30:JoinCandidate[]&"/>
</xs:sequence>
</xs:complexType>
</xs:element>`

After the three type names you get an '&' character. This breaks the xml parser while consuming this wsdl.
Primitive type out parameters work just fine.

Do I something wrong or is this a bug?

**Comment by arvicrivera** [comment]
no news? I am having this same problem.
