### ISSUE TITLE
UseSoapEndpoint is Case Sensitive

### ISSUE THREAD

**Issue by Montago** [DigDes/SoapCore#593]
The typical behavior of ASP.NET, IIS and Windows is to be case INsensitive. 

It's therefore odd to encounter a case sensitive behavior - such is the case of UseSoapEndpoint which obviously does a C# comparison of strings and therefore is case sensitive. 

eg: 
my site responds to "/Service.asmx" but not "/service.asmx"

**Comment by andersjonsson** [comment]
There should be a setting in UseSoapEndpoint (the one that accepts an option class) to make the path case-insensitive
