### ISSUE TITLE
XmlNamespaceManager corruption

### ISSUE THREAD

**Issue by mustfix** [DigDes/SoapCore#597]
I have hit an issue a few times I believe is due to these lines in CustomMessage.cs

var prefix = Version.Envelope.NamespacePrefix(namespaces);
var xsdPrefix = Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix(namespaces, "xsd", Namespaces.XMLNS_XSD);
var xsiPrefix = Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix(namespaces, "xsi", Namespaces.XMLNS_XSI);

Each of these is calling through to 

xmlNamespaceManager.AddNamespace(localPrefix, uri);

Which I believe is not thread safe, and if you are unlucky corrupts the namespace table leading to any number off odd behaviors, most commonly failing to serialize all SOAP responses.  Since the namespace table lifetime is owned by the SoapCoreMiddleware this will persist until the pipeline is rebuilt.

**Comment by spx-michael-c** [comment]
First to say, appreciate the work that's been done in bringing WCF compatibility to .NET Core.

In relation to this issue, I believe we've run into multiple problems related to this area too (CustomMessage.cs and non-thread safe use of XmlNamespaceManager).

We've observed multiple different exceptions but all seem related to corrupting the internal data. For example:

`ASPNETCore: An error occurred when trying to service a request on SOAP endpoint: /X.Y.Z 
System.IndexOutOfRangeException: Index was outside the bounds of the array. 
at System.Xml.XmlNamespaceManager.LookupPrefix(String uri) 
at SoapCore.Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix(XmlNamespaceManager xmlNamespaceManager, String preferredPrefix, String uri) 
at SoapCore.CustomMessage.OnWriteStartEnvelope(XmlDictionaryWriter writer) at System.ServiceModel.Channels.Message.WriteMessagePreamble(XmlDictionaryWriter writer) 
at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer) at SoapCore.MessageEncoder.SoapMessageEncoder.WriteXmlCore(Message message, XmlWriter xmlWriter) 
at SoapCore.MessageEncoder.SoapMessageEncoder.WriteMessageAsync(Message message, PipeWriter pipeWriter) 
at SoapCore.SoapEndpointMiddleware`1.WriteErrorResponseMessage(Exception exception, Int32 statusCode, IServiceProvider serviceProvider, Message requestMessage, SoapMessageEncoder messageEncoder, HttpContext httpContext) 
at SoapCore.SoapEndpointMiddleware`1.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider) 
at SoapCore.SoapEndpointMiddleware`1.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)`

Are there any updates on this issue, known workarounds or additional information we can provide in helping to resolve?

**Comment by mustfix** [comment]
I worked around this issue by using the SoapCoreOptions.XmlNamespacePrefixOverrides field.  First created a SoapCore.Namespaces.CreateDefaultXmlNamespaceManager() and then used SoapCore.Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix to add the extra namespaces my particular app needed before the pipeline was fully initialized.  Doesn't solve the underlying problem but if the namespace is already present then AddNamespaceIfNotAlreadyPresentAndGetPrefix during request processing will exit without altering the XmlNamespaceManager.

**Comment by spx-michael-c** [comment]
Thanks for the suggestion, we're looking into a few options for workarounds too until there are any updates for this one!

**Comment by bartschotten** [comment]
> I worked around this issue by using the SoapCoreOptions.XmlNamespacePrefixOverrides field. First created a SoapCore.Namespaces.CreateDefaultXmlNamespaceManager() and then used SoapCore.Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix to add the extra namespaces my particular app needed before the pipeline was fully initialized. Doesn't solve the underlying problem but if the namespace is already present then AddNamespaceIfNotAlreadyPresentAndGetPrefix during request processing will exit without altering the XmlNamespaceManager.

I'm experimenting with this a bit, and I don't see how this workaround is supposed to work. `CreateDefaultXmlNamespaceManager()` is called whenever a new CustomMessage is initialized regardless.
https://github.com/DigDes/SoapCore/blob/584ee9e4aa294867acf75d8715414b77e64b3709/src/SoapCore/CustomMessage.cs#L20
If I remove this property initialization it seems to work fine (all tests green), but then again that might actually make #650 worse.

**Comment by mustfix** [comment]
Been a while since I looked at this, but as I recall that field is overwritten at creation time in SoapEndpointMiddleware

T_MESSAGE customMessage = new T_MESSAGE
{
	Message = responseMessage,
	NamespaceManager = _xmlNamespaceManager
};

**Comment by bartschotten** [comment]
Ah, you're right that it is overwritten. That only makes auto property initialization unnecessary (with a slight performance penalty), but shouldn't cause the problem.
