### ISSUE TITLE
Using Sessions

### ISSUE THREAD

**Issue by gktech** [DigDes/SoapCore#60]
Has anyone tried/managed to access HttpContext within a Service as described in 

https://dotnetcoretutorials.com/2017/01/05/accessing-httpcontext-asp-net-core/    (see Inside Services)? 

This is my Startup class: 

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.TryAddSingleton<SampleService>();

            services.AddDistributedMemoryCache(); // Adds a default in-memory implementation of IDistributedCache
            services.AddSession();

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();
            loggerFactory.AddDebug();

            app.UseSoapEndpoint<SampleService>("/Service", new BasicHttpBinding(), SoapSerializer.DataContractSerializer);
            app.UseSoapEndpoint<SampleService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);

            // IMPORTANT: This session call MUST go before UseMvc()
            app.UseSession();

            app.UseMvc();
        }
    }
  
And the ServiceImpl: 

    public class SampleService : ISampleService
    {
        private IHttpContextAccessor _accessor;
        public SampleService(IHttpContextAccessor accessor)
        {
            _accessor = accessor;
        }

        public string Ping(string s)
        {
            string id = _accessor.HttpContext.Session.Id;
            Console.WriteLine("Exec ping method");
            return s;
        }
    }

I get a 
    **InvalidOperationException: Session has not been configured for this application or request** 

as described here: 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?tabs=aspnetcore2x 

Any ideas? 
Thank you.

**Comment by gktech** [comment]
Anyone interested may check my fork ...

**Comment by itn3000** [comment]
Mabe UseSessions() should be placed before UseSoapEndpoint<T>().
in Startup.Configure, call order is important.

**Comment by gktech** [comment]
Correct. 
And just don't forget to set **AllowCookies** to **true** on the binding in the client ... 
Thx.
