### ISSUE TITLE
System.Xml.Serialization.XmlArrayItemAttribute ElementName is ignored

### ISSUE THREAD

**Issue by anilcansutaner** [DigDes/SoapCore#601]
Hello, 

First of all, thank you for such a good project.  I have been trying to replatform my old NET Framework WCF service to  .Netcore . Firstly we design our wsdl , then generate webservice with WSCF Blue plugin. So, i try to move WCF service which is created by WSCF BLue plugin. 

The generated class is in the following: 

```
 [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class searchApplicationResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SearchApplicationResponse", Namespace = "http://isbank.com/CustSalesSvcg/Application/RetailApplicationManagement/Service/V" +
            "5", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Applications", IsNullable = false)]
        public ApplicationBriefInfo[] SearchApplicationResponse1;

        public searchApplicationResponse()
        {
        }

        public searchApplicationResponse(ApplicationBriefInfo[] SearchApplicationResponse1)
        {
            this.SearchApplicationResponse1 = SearchApplicationResponse1;
        }
    }
```

In SoapCore  XmlArrayItemAttribute.ElementName is ignored. 

Old service response is: 

```
<SearchApplicationResponse xmlns="http://isbank.com/CustSalesSvcg/Application/RetailApplicationManagement/Service/V5">
         <Applications>
            <ApplicationId>3000629800</ApplicationId>
            <CustomerNumber>162240216</CustomerNumber>
            <CitizenId>23243495822</CitizenId>
            <TaxId>0</TaxId>
            <ProductId>210010004</ProductId>
 <Applications>
</SearchApplicationResponse>
```

SoapCore service response is : 

```
<SearchApplicationResponse xmlns="http://isbank.com/CustSalesSvcg/Application/RetailApplicationManagement/Service/V5">
         <ApplicationBriefInfo>
            <ApplicationId>3000629800</ApplicationId>
            <CustomerNumber>162240216</CustomerNumber>
            <CitizenId>23243495822</CitizenId>
            <TaxId>0</TaxId>
            <ProductId>210010004</ProductId>
         </ApplicationBriefInfo>
      </SearchApplicationResponse>
```

As you can see that **"Applications"** element name is ignored by Serializer and replaced by type name which is "**ApplicationBriefInfo**"

Therefore , service response cannot be validated. How can we fix this issue ? 

Thank you

Regards

**Comment by martinp999** [comment]
Have you tried with [any of the attributes that are specifically for soap](https://docs.microsoft.com/en-us/dotnet/standard/serialization/attributes-that-control-encoded-soap-serialization)?

(not that I guarantee that they will work - I am facing an issue where neither `[System.Xml.Serialization.SoapType(TypeName = "OrderDetail")]` nor `[System.Xml.Serialization.XmlRoot(ElementName = "OrderDetail")]` seem to work, but something like these could work for your situation)
