### ISSUE TITLE
Expose Internals Sufficient to Use With HttpListener

### ISSUE THREAD

**Issue by awygle** [DigDes/SoapCore#611]
I need to handle a legacy WCF service endpoint in .NET Core. SoapCore works great for that when using Kestrel, but due to a port conflict with another application I need something that can handle URL namespacing correctly. I ended up implementing this manually on top of HttpListener. However, many of the things I had to implement were already implemented by SoapCore. It would be great if you could expose enough internals to support this use case.

**Comment by awygle** [comment]
This issue remains an issue.

**Comment by awygle** [comment]
Look, if you'd asked me to provide something and I hadn't responded in 30 days, this issue would be stale. No one from the project responding to me in 30 days does not make the issue stale. Not that you have any obligation to respond to this issue, but your GitHub robot is extremely irritating.

**Comment by kotovaleksandr** [comment]
Please describe your case. Whats "expose enough internals" you mean?
