### ISSUE TITLE
Is SoapCore supported on .NET 5?

### ISSUE THREAD

**Issue by dheerajjain11** [DigDes/SoapCore#618]
I am having simple query. I believe it should be supported but it is not mentioned in README.md. Following is section under Requirements:

The following frameworks are supported:

.NET Core 3.1 (using ASP.NET Core 3.0)
.NET Core 3.0 (using ASP.NET Core 3.0)
.NET Core 2.1 (using ASP.NET Core 2.1)
.NET Standard 2.0 (using ASP.NET Core 2.1)

**Comment by kotovaleksandr** [comment]
Hi, of course supported:) In readme.md listed package configurations, for .NET Core 5 enough .NET Standard 2.0

**Comment by elca-lan** [comment]
But the latest ASP.NET Core version that is still compatible with .NET Standard is ASP.NET Core 2.2, so you are suggesting to use ASP.NET Core 2.2 in .NET 5 essentially....

Aehm.... that's gonna be pretty darn problematic.

An additional .NET 5 target in the project configuration would make everything much more reasonable IMO.

**Comment by kotovaleksandr** [comment]
@elca-lan You can use SoapCore with .NET Core 5.0 and .NET Core 6.0 preview without any problems (in our projects we used both versions).
SoapCore depend on Microsoft.AspNetCore.Http version **greater** 2.1.0.
.NET Core have backward compatibility with older versions: assembly builded for netstandard or .NET CORE 1-2-3 can be used without restrictions in newer versions.

If you need explicit .NET Core 5-6 binding - please make PR, i merge them.

**Comment by elca-lan** [comment]
Huh... I didn't know that. But it's true, when I pull SoapCore 1.1.0.8 into a new .NET 5 project, then that ends up using the ".NETCoreApp 3.1" version of the assembly. Thanks a lot for pointing that out to me.

And if we run into problems, we'll create a PR - wouldn't be the first from "us" ❤
