### ISSUE TITLE
Support DateTimeOffset in wsdl generation

### ISSUE THREAD

**Issue by nalla** [DigDes/SoapCore#62]
Currently, when using `DateTimeOffset` as type an error is thrown indicating that the type is not supported.

```
.NET type DateTimeOffset cannot be resolved into XML schema type
```
Instead something similar to [here](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/data-contract-schema-reference#datetimeoffset-serialization) should be constructed.

```
<xs:schema targetNamespace="http://schemas.datacontract.org/2004/07/System">  
   <xs:complexType name="DateTimeOffset">  
      <xs:sequence minOccurs="1" maxOccurs="1">  
         <xs:element name="DateTime" type="xs:dateTime"  
         minOccurs="1" maxOccurs="1" />  
         <xs:elementname="OffsetMinutes" type="xs:short"  
         minOccurs="1" maxOccurs="1" />  
      </xs:sequence>  
   </xs:complexType>  
</xs:schema>
```

**Comment by drabb1956** [comment]
WSDL generation is failing for me when a parameter or property is Nullable of DateTimeOffset
