### ISSUE TITLE
soap core no parameters in generated client

### ISSUE THREAD

**Issue by rfidstammtisch** [DigDes/SoapCore#623]
I´ve followed this tutorial, where soapcore is used: https://dottutorials.net/creating-soap-web-services-dot-net-core-tutorial/
But when I generage a client, the methods does not have any parameters. The response-class was generated but no the request-class.

Here my code:

`[ServiceContract]
    public interface IService
    {
        [OperationContract]
        TestResponse TestMethod(TestRequest request);
    }
}

    [DataContract]
    public class TestResponse
    {
        [DataMember]
        public string Test { get; set; }
    }

    [DataContract]
    public class TestRequest
    {
        [DataMember]
        public string Test { get; set; }

    }`

Here my implementation of the interface:

`public class TestService : IService
    {
        public TestResponse TestMethod(TestRequest request)
        {
            return new TestResponse { Test = request.Test };
        }
    }`

Here the generated client code, which has no parameter to pass:

`[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService_V011")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/TestMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.TestMethodResponse> TestMethodAsync(ServiceReference1.TestMethodRequest request);
    }

[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.TestMethodResponse> ServiceReference1.IService.TestMethodAsync(ServiceReference1.TestMethodRequest request)
        {
            return base.Channel.TestMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TestMethodResponse> TestMethodAsync()
        {
            ServiceReference1.TestMethodRequest inValue = new ServiceReference1.TestMethodRequest();
            return ((ServiceReference1.IService)(this)).TestMethodAsync(inValue);
        }`

And finaly the code within the startup.cs:

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IService, TestService>();
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseSoapEndpoint<IService>("/Service.asmx", new BasicHttpBinding(), SoapSerializer.XmlSerializer);
        }`

**Comment by ducka** [comment]
This issue seems to be occurring in builds from v1.1.0.6 onwards. Downgrading to 1.1.0.5 has resolved the issue for me. It seems the input  `<wsdl:message />` elements in the WSDL markup aren't generating correctly for the input message. The message element's contents is empty.

```
  <wsdl:message name="ParkingSessionWebService_GetActiveSessionsByLocation_InputMessage" />
  <wsdl:message name="ParkingSessionWebService_GetActiveSessionsByLocation_OutputMessage">
    <wsdl:part name="parameters" element="tns:GetActiveSessionsByLocationResponse" />
  </wsdl:message>
```
