### ISSUE TITLE
How  .net  5  call   a  webservice?

### ISSUE THREAD

**Issue by efreer1988** [DigDes/SoapCore#629]
How did   call a webservice  on    .net 5???

example:http://www.abc.com/TPlantProService?wsdl

**Comment by TomBruns** [comment]
Here are three (3) alternatives I have used

1. Add a "connected service" in Visual Studio
[https://devblogs.microsoft.com/aspnet/generating-http-api-clients-using-visual-studio-connected-services/
](https://devblogs.microsoft.com/aspnet/generating-http-api-clients-using-visual-studio-connected-services/
)
Then you get a strongly typed client

            using var httpClient = new HttpClient();
            var yourClient = new ssoServiceClient(@"http://localhost:44314/SsoService.asmx", httpClient);

2. Call if you do not have a shared interface available

           // serialize the request data
           var bodyContent = new StringContent(requestBodyString, Encoding.UTF8, @"text/xml");
           var client = new HttpClient();
           using var httpResponse = client.PostAsync($"http://localhost:44314/SsoService.asmx", bodyContent).Result;

            if (httpResponse.StatusCode != HttpStatusCode.OK)
            {
                throw new ApplicationException($"Unexpected Result: [{httpResponse.StatusCode}]");
            }

            // grab the body of the SOAP response
            var responseBodyString = httpResponse.Content.ReadAsStringAsync().Result;

3. Call if you do have a shared interface available

            protected readonly ISsoService _serviceClient = null;
            // enable TLS/SSL  (not reqd for your use case)
            var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);

            var endpoint = new EndpointAddress(new Uri("https://localhost:44314/SsoService.asmx"));

            var channelFactory = new ChannelFactory<ISsoService>(binding, endpoint);

            _serviceClient = channelFactory.CreateChannel();

            // call service
           var response = _serviceClient.SomeMethod(paramData);
