### ISSUE TITLE
Slashes are removed from soap:address location when using WsdlFileOptions

### ISSUE THREAD

**Issue by dikklop** [DigDes/SoapCore#630]
I have a predefined wsdl file that I want to serve to the clients.
Therefor I added the following properties to the appsettings:
`
"FileWSDL": {
    "UrlOverride": "",
    "WebServiceWSDLMapping": {
      "v2_4MyService": {
        "SchemaFolder": "wwwroot/xxxxxxxxx/v2_4/MyService",
        "WsdlFolder": "wwwroot/xxxxxxxxx/v2_4/MyService",
        "WsdlFile": "MyService-v2.4.wsdl"
      }
    },
    "VirtualPath": ""
  }
`

In the application setup I added the following line:
`
app.UseSoapEndpoint<CatalogServiceController24>("/v2_4/MyService",
                                                            new Soap11WsaBinding(),
                                                            SoapSerializer.XmlSerializer,
                                                            false,
                                                            null,
                                                            settings);
`

The predefined wsdl file contains this block:
`
<wsdl:service name="MyService">
       <wsdl:port name="MyService" binding="tns:Basic_Http_IMyService">
           <soap:address location="https://xxxxxxxxxxxxxx/v2_4/MyService" />
       </wsdl:port>
   </wsdl:service>
`

However when the clients retrieve the wsdl, the slash between v2_4 and MyService is missing. The SoapEndPointMiddleware rewrites the wsdl to:
`
<wsdl:service name="MyService">
<wsdl:port name="MyService" binding="tns:Basic_Http_IMyService">
<soap:address location="https://xxxxxxxxxxxxxx/v2_4MyService"/>
</wsdl:port>
</wsdl:service>
`

It looks like the rewrite uses the path from **WebServiceWSDLMapping**. I had to remove the slashes from  the path in the appsettings to prevent a **KeyNotFoundException**.

It was working in version 1.1.0.7 and not in 1.1.0.8. I guess because of PR #607 which solves an issue with the WsdlFileOptions.

Is this a bug or am i missing something?

**Comment by dikklop** [comment]
A simple quickfix for me was modifying this line in SoapEndpointMiddleware 
from: `meta.CurrentWebService = httpContext.Request.Path.Value.Replace("/", string.Empty);`
to: `meta.CurrentWebService = httpContext.Request.Path.Value;`

It works for me, but of of course this change will have nasty side effects for others because the existing keys will no longer match.

So a permanent fix/change would be appreciated.

**Comment by mgrueger** [comment]
I had a similar problem then I try to register an Endpoint at “http://servername/api/ServiceName.
I use the following json in appsettings:
`"FileWSDL": {
    "UrlOverride": "",
    "WebServiceWSDLMapping": {
      "ServiceName": {
        "WsdlFile": "ServiceName.wsdl",
        "SchemaFolder": "Schemas",
        "WsdlFolder": "Schemas"
      }
    },
    "VirtualPath": "api"
  }`

I use the following code to fix the problem in 
SoapEndPointMiddleware.ProcessXSD and SoapEndPointMiddleware.ProcessMetaFromFile

`var requestPath = httpContext.Request.Path.Value;`
`if(!string.IsNullOrEmpty(_options.WsdlFileOptions.VirtualPath))`
`			{`
`				meta.CurrentWebServer = _options.WsdlFileOptions.VirtualPath + "/";`
`               requestPath = requestPath.Replace(meta.CurrentWebServer, string.Empty);`
`			}`
`			meta.CurrentWebService = requestPath.Replace("/", string.Empty);`
`WebServiceWSDLMapping mapping = _options.WsdlFileOptions.WebServiceWSDLMapping[meta.CurrentWebService];`

As @dikklop wrote, a permanent fix/change would be much nicer.

**Comment by bferdinandus** [comment]
Is there any progress on this issue?

**Comment by bferdinandus** [comment]
Is there any progress on this issue?
