### ISSUE TITLE
Support for MTOM message format

### ISSUE THREAD

**Issue by mcavigelli** [DigDes/SoapCore#636]
Hi there

We must produce SOAP-messages in the MTOM [1] format. This allows shorter messages.

It seems that one must create a different _XmlDictionaryWriter_ with the static method _XmlDictionary.CreateMtomWriter()_. I'm not sure if that is already the whole thing.

This dictionary is currently created with _XmlDictionaryWriter.CreateDictionaryWriter()_ in _SoapMessageEncoder.WriteMessageAsync()_. The method is virtual and could be overriden. But I don't see any possibility to configure or inject the creation of SoapMessageEncoder.

Is there a way to configure the XmlDictionaryWriter?

Matthias

[1] https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldictionarywriter.createmtomwriter?view=net-5.0

**Comment by oakdemirci** [comment]
Hi, thanks for **SoapCore**. @mcavigelli did you implement mtom ? I also need it. Thanks

**Comment by mcavigelli** [comment]
No, I did not implement it.

Our need was to simulate a SOAP service with MTOM message format.
We used SoapUI to simulate some responses in the MTOM format.

**Comment by tufanunlu** [comment]
> Hi, thanks for **SoapCore**. @mcavigelli did you implement mtom ? I also need it. Thanks

Hi, did you find any solution for mtom support?

**Comment by oakdemirci** [comment]
> > Hi, thanks for **SoapCore**. @mcavigelli did you implement mtom ? I also need it. Thanks
> 
> Hi, did you find any solution for mtom support?

Since it doesn't support at that time, I've implemented a .net framework api gateway (you dont neen soapcore bla bla) and call .net core api from this gateway, not using soap, using rest api json call.

**Comment by tufanunlu** [comment]
> > > Hi, thanks for **SoapCore**. @mcavigelli did you implement mtom ? I also need it. Thanks
> > 
> > 
> > Hi, did you find any solution for mtom support?
> 
> Since it doesn't support at that time, I've implemented a .net framework api gateway (you dont neen soapcore bla bla) and call .net core api from this gateway, not using soap, using rest api json call.

Thank you for your response.
