### ISSUE TITLE
XmlNamespaceManager is not thread safe

### ISSUE THREAD

**Issue by Janneman96** [DigDes/SoapCore#650]
The same `XmlNamespaceManager` instance is used multiple times at once in the SoapCore library. 

- In the `XmlNamespaceManager.AddNamespace()` method, `_nsdecls[++_lastDecl]` is used. When two threads are running on the same `XmlNamespaceManager` instance, this can cause the `_lastDecl` to increment twice before the array size is increased. This could cause an `IndexOutOfRangeException`.
- For us, an `IndexOutOfRangeException` was thrown in the `XmlNamespaceManager.LookupPrefix()` method 3 times on production. We've included a brute force test example below. While we were setting up this test, we came across different threading related issues.

The source code of the `XmlNamespaceManager` can be found [here](https://github.com/dotnet/runtime/blob/119785100b1ce36cffcf0caf2cc3e23cce32b222/src/libraries/System.Private.Xml/src/System/Xml/XmlNamespacemanager.cs#L168).

The brute force test:

	using System;
	using System.Threading;
	using Microsoft.VisualStudio.TestTools.UnitTesting;
	namespace SoapCore.Tests
	{
		[TestClass]
		public class ThreadTests
		{
			[TestMethod]
			public void RaceConditionNamespacesTest()
			{
				int currentTestRunNumber = 0;
				const int maximumNumberOfTests = 100;
				IndexOutOfRangeException expectedIndexOutOfRangeException = null;
				do
				{
					ManualResetEvent allGo = new ManualResetEvent(false);
					var namespaceManager = Namespaces.CreateDefaultXmlNamespaceManager();
					int waiting = 20;
					int failures = 0;
					Exception firstException = null;
					Thread[] threads = new Thread[20];
					for (int j = 0; j < 10; j++)
					{
						threads[2 * j] = new Thread(() =>
						{
							try
							{
								if (Interlocked.Decrement(ref waiting) == 0)
								{
									allGo.Set();
								}

								allGo.WaitOne();
								string numberString = $"number {currentTestRunNumber}.{j}";
								Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix(namespaceManager, numberString, numberString);
							}
							catch (Exception ex)
							{
								Interlocked.CompareExchange(ref firstException, ex, null);
								Interlocked.Increment(ref failures);
							}
						});
						threads[(2 * j) + 1] = new Thread(() =>
						{
							try
							{
								if (Interlocked.Decrement(ref waiting) == 0)
								{
									allGo.Set();
								}

								allGo.WaitOne();
								string numberString = $"number {currentTestRunNumber}.{j}";
								Namespaces.AddNamespaceIfNotAlreadyPresentAndGetPrefix(namespaceManager, numberString, numberString);
							}
							catch (Exception ex)
							{
								Interlocked.CompareExchange(ref firstException, ex, null);
								Interlocked.Increment(ref failures);
							}
						});
					}

					for (int j = 0; j < threads.Length; j++)
					{
						threads[j].Start();
					}

					for (int j = 0; j < threads.Length; j++)
					{
						threads[j].Join();
					}

					expectedIndexOutOfRangeException = firstException is IndexOutOfRangeException actualIndexOutOfRangeException ? actualIndexOutOfRangeException : null;
					currentTestRunNumber++;
				}
				while (expectedIndexOutOfRangeException == null || !expectedIndexOutOfRangeException.StackTrace.Contains("LookupPrefix") || currentTestRunNumber < maximumNumberOfTests);
				Assert.IsNull(expectedIndexOutOfRangeException, $"Got {expectedIndexOutOfRangeException} as exception");
			}
		}
	}

Can we contribute in resolving this issue?

**Comment by spx-michael-c** [comment]
We have also been running into problems in this area, and it appears there is another related [issue](https://github.com/DigDes/SoapCore/issues/597) raised.
