### ISSUE TITLE
Whitespace in XML breaking SerializerHelper

### ISSUE THREAD

**Issue by aeslinger0** [DigDes/SoapCore#654]
When I post XML like this, the SerializerHelper returns null for my `SomeCompany` property:

```
<?xml version="1.0" encoding="UTF-8"?>
<D:Envelope xmlns:A="http://www.someCompany.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:D="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:C="http://www.openapplications.org/oagis"
    xmlns:B="http://www.starstandards.org/STAR">
    <SOAP:Header xmlns:SOAP-SEC="http://schemas.xmlsoap.org/soap/security/2000-12" xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/">
        ...
    </SOAP:Header>
    <D:Body id="Body">
        <B:ProcessCreditApplication>
            ...
        </B:ProcessCreditApplication>
        <A:SomeCompany>
            ...
        </A:SomeCompany>
    </D:Body>
</D:Envelope>
```

If you take out the whitespace between `</B:ProcessCreditApplication>` and `<A:SomeCompany>` it succeeds, but I cannot enforce the client to submit the XML this way.

I was able to resolve this by adding this code to the beginning of `SerializerHelper.DeserializeInputParameter()`:

```
// Advance past any whitespace.
while (xmlReader.NodeType == System.Xml.XmlNodeType.Whitespace && xmlReader.Read())
{
}
```

I'm not sure if other places in the code base could benefit from better handling of whitespace, but could this be added to the NuGet package?

**Comment by kotovaleksandr** [comment]
fixed in #655
