### ISSUE TITLE
SoapExceptionTransformer not usable since v0.9.5 (related to #23)

### ISSUE THREAD

**Issue by draphyz** [DigDes/SoapCore#66]
When I use an exception transformer like this : 

`services.AddSoapExceptionTransformer(ex => ex.Message);`

I receive an exception of type NullReferenceException for exceptions without InnerException

`SoapEndpointMiddleware.WriteErrorResponseMessage() lines 260 to 264`

```
var errorText = exception.InnerException != null ? exception.InnerException.Message : exception.Message;

var transformer = serviceProvider.GetService<ExceptionTransformer>();
if (transformer != null)
	errorText = transformer.Transform(exception.InnerException);
```

**Comment by kotovaleksandr** [comment]
Please check on latest master.
