### ISSUE TITLE
How to add namespaces in envelop tag?

### ISSUE THREAD

**Issue by ramondeallima** [DigDes/SoapCore#662]
How is it done by the soap core

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">`

How i want to do

`<env:Envelope env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns0="http://www.atg.com/atg.security" xmlns:ns1="http://www.atg.com/webservices" xmlns:ns2="http://www.atg.com/com.seguros.portal.service.token" xmlns:ns3="http://www.atg.com/com.seguros.portal.service">`

**Comment by freddycoder** [comment]
You can create a derived message based on CustomMessage, override the OnWriteStartEnvelope method, and implemented it to fit your needs. 

Then you'll need to use the UseSoapEndpoint<T, T_MESSAGE> method to add the middleware.

CustomMessage : https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/CustomMessage.cs

SoapEnpointExtension : https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/SoapEndpointExtensions.cs

**Comment by ramondeallima** [comment]
Thanks @freddycoder , this worked for me.

Now i want remove this extra tag in XML request. 

![image](https://user-images.githubusercontent.com/37948637/120951370-0bc05600-c71f-11eb-8de0-440083cdb4ff.png)

Do you have an idea how i can do it?

**Comment by debidwitamayusup** [comment]
hello, can we remove those xsi and xsd prefix?

**Comment by andersjonsson** [comment]
You can probably do it in the same way as described above.
Or you can use a regular asp.net core middleware to customize incoming/outgoing messages.
