### ISSUE TITLE
Wrong WSDL metadata routing for two services with equal names

### ISSUE THREAD

**Issue by chrplankl-test** [DigDes/SoapCore#670]
Hey there,

I have the scenario where I want to provide two endpoints to the user and hence I have two registrations. Since one instance of the services is an old implementation and versioning is done with URL versioning my endpoint registrations look like this:
```
app.UseEndpoints(_ =>
{
	app.UseSoapEndpoint<LegacyV1.IMyService>("/LegacyV1/MyService.svc", soap12EncoderOptions, wsdlFileOptions: wsdlFileOptions);
	app.UseSoapEndpoint<V1.IMyService>("/MyService.svc", soap11EncoderOptions, wsdlFileOptions: wsdlFileOptions);
});
```

The wsdlFileOptions include 2 paths to the WSDL files I want to publish for the two endpoints. The problem here is that both services are named the same "MyService.svc". This means that always the file from the second registration is served even if the user requests the first one.

The cause of the problem in this case is in the middleware here in line 115:
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/SoapEndpointMiddleware.cs

The paths are cut to look exactly the same with:
```
var trailPathTuner = serviceProvider.GetServices<TrailingServicePathTuner>().FirstOrDefault();

trailPathTuner?.ConvertPath(httpContext);
```

Is there any special reason why the paths are shortened?

**Comment by tibel** [comment]
Why are you using `TrailingServicePathTuner`? Seems like without it everything should be fine.

**Comment by chrplankl-test** [comment]
@tibel I do not use it explicitly. It's used by the SoapCore middleware and as far as I have seen I cannot disable it.

**Comment by tibel** [comment]
Have you tried the Sample in this repo? There `TrailingServicePathTuner` is not used.
