### ISSUE TITLE
WSDL generation appears to ignore custom element names

### ISSUE THREAD

**Issue by iamdevman** [DigDes/SoapCore#68]
Is there a problem with WSDL generation ignoring XmlElement("customName") or DataMember(Name = "customName")?  It seems to always take the actual property name instead of the name defined by the attribute.

**Comment by itn3000** [comment]
It surely was so. Additionaly, DataContrctAttribute.Name did not worked correctly too.

**Comment by webmannetwork** [comment]
Are there any workarounds or fixes planned?  I'm currently having to name my properties exactly how they should show up in the WSDL, which isn't ideal.

**Comment by itn3000** [comment]
wsdl content is implemented in SoapCore.MetaBodyWriter.
https://github.com/DigDes/SoapCore/blob/028fb4588ddf22f045f7251767a7737514a5faa0/src/SoapCore/MetaBodyWriter.cs
Currently, MetaBodyWriter does not consider custom attributes of element.
I think fixing code is needed.

**Comment by farlop** [comment]
I'm having the same problem. I would like to use custom naming through DataMember

**Comment by kotovaleksandr** [comment]
@farlop @itn3000 @webmannetwork DataMember attribute Name currently support, can close issue?
