### ISSUE TITLE
Close inactive issues automatically

### ISSUE THREAD

**Issue by tibel** [DigDes/SoapCore#684]
It makes no sense to keep inactive issues open when there is no reaction from the creator of the issue.

I suggest to add a GitHub Action to close those old/inactive issues automatically:
- https://docs.github.com/en/actions/guides/closing-inactive-issues
- https://github.com/marketplace/actions/close-stale-issues

**Comment by kotovaleksandr** [comment]
Thanks! Done: https://github.com/DigDes/SoapCore/blob/develop/.github/workflows/close_inactive_issues.yml
