### ISSUE TITLE
System.Xml.XmlException: 'nillable' is a duplicate attribute for ArrayOfArrayOfString 

### ISSUE THREAD

**Issue by edukubota** [DigDes/SoapCore#704]
the soap core not serialize string[][] 

Ex.:
``` 
public string[][] getData(string name)
{
   return new string[][]
   {
       new string[] {"1.1","1.2", "1.3"},
       new string[] {"2.1","2.2", "2.3"},
       new string[] {"3.1", "3.2", "3.3"}
   };
}    
```

explode this error
crit: SoapCore.SoapEndpointMiddleware[0]
      An error occurred when trying to service a request on SOAP endpoint: /Service.asmx
System.Xml.XmlException: 'nillable' is a duplicate attribute name.
   at System.Xml.XmlWellFormedWriter.AddAttribute(String prefix, String localName, String namespaceName)
   at System.Xml.XmlWellFormedWriter.WriteStartAttribute(String prefix, String localName, String namespaceName)
   at System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteStartAttribute(String prefix, String localName, String namespaceUri)
   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   at SoapCore.Meta.MetaBodyWriter.AddSchemaType(XmlDictionaryWriter writer, TypeToBuild toBuild, String name, Boolean isArray, String namespace, Boolean isAttribute, Boolean isListWithoutWrapper, Boolean isUnqualified)

**Comment by Kyte** [comment]
I was hit with this same bug while generating WSDL.
The issue occurs [here](https://github.com/DigDes/SoapCore/blob/84e35ff8817b30f7f6e84070bc9186f6f0182d6e/src/SoapCore/Meta/MetaBodyWriter.cs#L968), where it writes the nillable attribute, and then tries to write it again [here](https://github.com/DigDes/SoapCore/blob/84e35ff8817b30f7f6e84070bc9186f6f0182d6e/src/SoapCore/Meta/MetaBodyWriter.cs#L992).

I had to download the source and apply a custom fix to get it working.
```
...
    writer.WriteAttributeString("minOccurs", "0");
    var alreadyWroteNillable = false;
    if (isArray)
    {
	    writer.WriteAttributeString("maxOccurs", "unbounded");
	    writer.WriteAttributeString("nillable", "true");
 	    alreadyWroteNillable = true;
    }
    else
    {
	    writer.WriteAttributeString("maxOccurs", "1");
    }
...
    else if (type.IsArray)
    {
...
	    writer.WriteAttributeString("name", name);
	    WriteQualification(writer, isUnqualified);
 	    if (!alreadyWroteNillable) { writer.WriteAttributeString("nillable", "true"); }
	    writer.WriteAttributeString("type", "tns:" + newTypeToBuild.TypeName);
    
	    _complexTypeToBuild.Enqueue(newTypeToBuild);
    }
...
```
I don't know enough about the WSDL generation or the reasoning behind the original code to submit a PR, but it works for my test case at least.
