### ISSUE TITLE
all namespaces in envelope tag

### ISSUE THREAD

**Issue by LadyR123** [DigDes/SoapCore#715]
Hello, how can I make from this 
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:Action xmlns:h="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns="http://schemas.xmlsoap.org/ws/2004/08/addressing">http://test.com</h:Action>
    </s:Header>
</s:Envelope>
```
this

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:h="http://schemas.xmlsoap.org/ws/2004/08/addressing"  >
    <s:Header>
        <h:Action>http://test.com</h:Action>
    </s:Header>
</s:Envelope>

```

**Comment by andersjonsson** [comment]
We solved a similar issue with an IMessageInspector2, but in our case the namespace was on the right place. It just had the wrong prefix.

Check out https://justsimplycode.com/2020/03/29/adding-custom-suffix-in-namespaces-in-soap-web-service-xml-response-with-soapcore/
I think you can fix your issue using that approach
