### ISSUE TITLE
New Invocation Pattern

### ISSUE THREAD

**Issue by MCFHTAGENTS** [DigDes/SoapCore#738]
Please can you help me translate my service invocation (which worked fine until recently when it stopped compiling):
```
                 endpoints.UseSoapEndpoint<Controllers.IMyService>(
                    "/Endpoint.asmx",
                    new BasicHttpBinding(BasicHttpSecurityMode.Transport)
                    {
                        MaxReceivedMessageSize = int.MaxValue,
                        ReaderQuotas = new XmlDictionaryReaderQuotas()
                        {
                            MaxStringContentLength = int.MaxValue,
                            MaxArrayLength = int.MaxValue,
                            MaxDepth = int.MaxValue,
                        },
                    },
                    SoapSerializer.XmlSerializer);
```
I have so far replaced it with

```
                endpoints.UseSoapEndpoint<Controllers.IMyService>(
                    "/Endpoint.asmx",
                    new SoapEncoderOptions()
                    {
                        MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap11),
                        WriteEncoding = Encoding.UTF8,
                        ReaderQuotas = new XmlDictionaryReaderQuotas()
                        {
                            MaxStringContentLength = int.MaxValue,
                            MaxArrayLength = int.MaxValue,
                            MaxDepth = int.MaxValue,
                        },
                    },
                    SoapSerializer.XmlSerializer);
```

but the service invoking is generating an error:
SOAP Header Action is not understood

THank you

**Comment by petarpetrovt** [comment]
I have the same problem. :)
Check [this](https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/Meta/BindingExtensions.cs#L24) extension method

**Comment by Vertygo** [comment]
@MCFHTAGENTS I had the same issue, what helped me is setting encoder options. In your case, it might be that you have SOAP 1.2 client and your server is returning SOAP 1.1 response.
I think that SoapCore doesn't do a check for version compatibility and that all it does is try to [find the best matching encoder based on content type](https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/SoapEndpointMiddleware.cs#L194) meaning that if you have multiple encoders then the order of encoders in `EncoderOptions` collection matters.

```
	opt.EncoderOptions = new[]
	{
		new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap12WSAddressingAugust2004, WriteEncoding = System.Text.Encoding.UTF8 },
		new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap11, WriteEncoding = System.Text.Encoding.UTF8 },
	};
```

**Comment by MCFHTAGENTS** [comment]
Thank you - finally got to test it and the extension method did the trick.
