### ISSUE TITLE
The program '[XX] XXX.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

### ISSUE THREAD

**Issue by Antwane** [DigDes/SoapCore#745]
Hi There,

I recently came across this error when using the SoapCore nuget 1.1.0.17,

Error Message
The program '[XX] XXX.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

I've tested it with 1.1.0.16 and 1.1.0.12 and they both give me the same error. I'm currently using version 1.1.0.10 and works fine without an issue.

The problem occurs when this line of code is hit

![image](https://user-images.githubusercontent.com/3491588/139233181-6afb3c67-8293-42d5-8d7a-b0809f30f889.png)

endpoints.UseSoapEndpoint<ValidService>(path: "MyService.asmx", serializer: SoapSerializer.XmlSerializer, encoders: encodingOptions);

After the line is hit the application goes down and restarts with the error I stated above. I'm currently using a .net Core web api on ServiceFabric with netcoreapp3.1.

Any help would be appreciated, 
Thanks

**Comment by andersjonsson** [comment]
This could be related to a recursion bug that will be fixed in the next version.
Try to use the overload with Action<SoapCoreOptions>, so something like:

```
endpoints.UseSoapEndpoint<ValidService>((opt) =>
{
	opt.Path = "MyService.asmx";
	opt.SoapSerializer = SoapSerializer.XmlSerializer;
	opt.EncoderOptions = encodingOptions
});
```
