### ISSUE TITLE
[Question] Support for dependency injection and authorization

### ISSUE THREAD

**Issue by yohny** [DigDes/SoapCore#753]
Currently the SOAP service is registered as `services.TryAddSingleton<ServiceContractImpl>();`. Is there a way to injects scoped or transient dependencies into it? Adding them to constructor will not adhere to their scopes as the `ServiceContractImpl` is created only once.

Is there any plan to support `[Authorize]` attribute for Soap service?

**Comment by andersjonsson** [comment]
Just register the services as Scoped instead of Singletons. That's the way I do it.

**Comment by yohny** [comment]
is there any particular reason why documentation uses `services.TryAddSingleton<ServiceContractImpl>();`? Are there any side-effect when added as scoped?

**Comment by andersjonsson** [comment]
No idea TBH. I'm just a user/recent contributor 😉

Maybe submit a PR to clarify the documentation?

**Comment by andersjonsson** [comment]
https://github.com/DigDes/SoapCore/blob/a9ba769d9b2d15e1f4c2fc5fa9383fa2c7e71256/src/SoapCore/SoapEndpointMiddleware.cs#L281
This is, as far as I can tell, the only place where the service is instantiated.
I can't see any side-effects (other than allocations, of course)

**Comment by yohny** [comment]
thanks, registering as scoped seems to work without issues

is there any way to make the soap service endpoint accessible only to authorized users?

**Comment by andersjonsson** [comment]
I would try to add a separate middleware for that.

I used this one to inspect the soap payload (useful when I tried to debug weird behavior)
```
app.Use(async (context, next) =>
{
	var body = context.Request.Body;
	context.Request.EnableBuffering();

	var buffer = new byte[Convert.ToInt32(context.Request.ContentLength)];
	await context.Request.Body.ReadAsync(buffer, 0, buffer.Length);

	var bodyAsText = Encoding.UTF8.GetString(buffer);

	context.Request.Body.Position = 0;

	await next();
});
```

You should be able to check authorization, in whatever way you want, there.
This blogpost might be of use 
https://blog.joaograssi.com/posts/2021/asp-net-core-permission-based-authorization-middleware/

Remember to add the middleware before you add the soap endpoints 😉

**Comment by andersjonsson** [comment]
Now that I think about it `.UseAuthorization` should work, but I would assume that you have to place that call between `.UseRouting()` and `.UseSoapEndpoint()`

**Comment by yohny** [comment]
yes, that what I would expect to work (I have it placed between `UseRouting()` and `UseSoapEndpoint()`) and it works as expected for controllers, but not for sap endpoint

**Comment by andersjonsson** [comment]
> yes, that what I would expect to work (I have it placed between `UseRouting()` and `UseSoapEndpoint()`) and it works as expected for controllers, but not for sap endpoint

I see! Then a custom middleware might be the way to go

**Comment by andersjonsson** [comment]
I found this old issue that has a lot of info
https://github.com/DigDes/SoapCore/issues/85

**Comment by yohny** [comment]
The issue is that I dont want basic auth (username+password) as the rest of the endpoints (controllers) use `Bearer` authentication and I want to stick with it.
If I provide correct `Bearer` authorization header than the user's identity is correctly populated in soap service, same as in regular controllers. So the auth middleware obviously works for both regular controller and the soap service as in both cases the auth middleware validates JWT token and extracts claims.
Controller endpoints and soap endpoint have `.RequireAuthorization()` set up as shown in my previous comment.
The only problem is that if I dont provide `Bearer` auth header the regular controllers return 401, but soap service returns 415 (Unsupported media type)

**Comment by yohny** [comment]
ok, it seems that all works as expected, the 415 was not coming from the SOAP service, but from identity provider that that the unauthenticated SOAP call was forwarder to
