### ISSUE TITLE
WSDL reply

### ISSUE THREAD

**Issue by antonad** [DigDes/SoapCore#76]
Hello. I have just moved my code from ASP .NET Forms to ASP .NET Core 2. To create XML web service I have used your component.

Now I am comparing reply from my old service.asmx?WSDL and new service.asmx and see several differences. The main difference is XML header. In old project all data was included in <?xml version="1.0" encoding="utf-8"?> tag while in new reply this tag is missed.

As result I can not add link to this service from visual studio 2017 while I was able to to so in old asp .net forms project. 

I dont shure the problem is in <?xml> tag. May be you can give me advice how to make new soap service (based on your component) to be linked to other .NET projects

**Comment by kotovaleksandr** [comment]
Hello! With IMessageInspector you can modify body of response message as you wish. Compare ideal response with response from SoapCore (i'm use Fiddler) and write implementation of IMessageInspector for fix difference between responses.
