### ISSUE TITLE
WSDL Generate schema missing custom attribute in parameter

### ISSUE THREAD

**Issue by tldkhoa** [DigDes/SoapCore#763]
When I add custom attribute to Array in parameter like this
`void setCurrentChannels([XmlArray("channels"), XmlArrayItem(ElementName = "item")] string[] channels)`
SoapCore Generate only generic WSDL without "item" attribute .
```
<xsd:sequence>
<xsd:element minOccurs="0" maxOccurs="1" name="userId" type="xsd:string"/>
<xsd:element minOccurs="0" maxOccurs="1" name="channels" nillable="true" type="tns:ArrayOfString"/>
</xsd:sequence>
```
The message generate from WSDL cannot invoke a service:
```
   <soapenv:Body>
    <urn:setCurrentChannels>
         <urn:channels>
            <urn:string>1</urn:string>
         </urn:channels>
      </urn:setCurrentChannels>
   </soapenv:Body>
```
My client from another service provider cannot change their request message.
Original request:
```
 	<SOAP-ENV:Body>
		<ns0:setCurrentChannels xmlns:ns0="urn:IciUserInterface">
			<channels xmlns="urn:IciUserInterface">
				<item>1</item>
			</channels>
		</ns0:setCurrentChannels>
	</SOAP-ENV:Body>
```

Any solution to generate correct wsdl ?

**Comment by andersjonsson** [comment]
There are a lot of weird quirks in WSDL. I had to fix quite a few to get it to work with my legacy service.

I recommend starting here:
https://github.com/DigDes/SoapCore/blob/fd762f8d1903f6ff419e664b45b548988735c6b6/src/SoapCore/Meta/MetaBodyWriter.cs#L476-L507
and see if you can submit a PR that fixes your issue. PR's are usually accepted quickly
