### ISSUE TITLE
Is possible to add a SOAP header?

### ISSUE THREAD

**Issue by Raffa50** [DigDes/SoapCore#77]
I would like to expose a call like these from my ASP.net core api

`<binding name="SMSDeliveryNotificationPortBinding" type="tns:SMSDeliveryNotification">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="notifySMSDelivery">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="tns:notifySMSDelivery" part="gdspHeader" use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>`

is possible to add the header? I used a custom messageInspector but the svc doesn't expose the header to me (only body)

**Comment by kotovaleksandr** [comment]
You can add header to response with custom ASP.NET Core middleware. Another way - add to IMessageInspector new methods (don't change old methods for backward compatibility) with argument HttpContext.

**Comment by sandhyachinta** [comment]
I am looking for similar requirement. I wrote a custom MessageInspector which deserialize the soap header and return the Auth object I am looking for. But the Authentication happens at Service Operation level and I couldn't find a way to pass the Auth object received from MessageInspector to the operation. Is there a way we could add Header to each Operation like [SoapHeader("Authentication", Required = true)]  [OperationContract] which would also reflect in wsdl generation?

**Comment by Raffa50** [comment]
I have solved by editing myself a Better soap Middleware that works with standard asp.net controllers: https://github.com/Raffa50/SmartSoap

**Comment by douglassimaodev** [comment]
Hi @Raffa50 Thanks for you post!

that is my need, will it help me to create this? 
https://stackoverflow.com/questions/66432054/soapcore-asp-net-core-3-1-header
