### ISSUE TITLE
Does SoapCore currently support Dictionary or List<List<string>>?

### ISSUE THREAD

**Issue by oracinho** [DigDes/SoapCore#776]
I'm trying to implement a Soap service where I must provide a very generic parameter list like this:

<cardData>
    //zero or more repetitions
    <item>
          <key>key<key/>
          <value>value<value/>
    <item/>
</cardData>

So far, I used Dictionary<string, string> and List<List<string>> as parameters but none of this types worked. Either got an WSDL malformed or the service is successfully invoked but with empty parameters.

Here's my code.

Startup.cs
`
app.UseSoapEndpoint<IWorkflowEngineSoapService>("/webdesk/ECMWorkflowEngineService.wsdl", new SoapEncoderOptions());
`

CustomList.cs
```
    [CollectionDataContract(Name = "cardData", ItemName = "item", KeyName = "key", ValueName = "value")]
    public class CustomList : Dictionary<string, string>
    {
        public CustomList() : base() { }

    }
```

IWorkflowEngineSoapService.cs
```
    [ServiceContract]
    public interface IWorkflowEngineSoapService
    {
        [OperationContract(Name = "simpleStartProcess")]
        public string StartAuditoryProcess(
            CustomList cardData);
    }
```

WorkflowEngineSoapService.cs
```
public class WorkflowEngineSoapService : IWorkflowEngineSoapService
    {
        public WorkflowEngineSoapService() { }

        public string StartAuditoryProcess(
            CustomList cardData)
        {
            foreach (var item in cardData)
            {
                return item.Value;
            }
            return "nok";
        }
    }
```

With this code I get this error when I try to add the wsdl on SoapUi.
> Source: http://localhost:5000/webdesk/ECMWorkflowEngineService.wsdl Error: type 
> 'KeyValuePairOfStringString@http://schemas.datacontract.org/2004/07/System.Collections.Generic' not found.

After read the WSDL generated I found that KeyValuePairOfStringString is the type of CustomList, and it's not defined anywhere. 

So, I tried to use the Dictionary directly in the service parameters

IWorkflowEngineSoapService.cs
```
[ServiceContract]
    public interface IWorkflowEngineSoapService
    {
        [OperationContract(Name = "simpleStartProcess")]
        public string StartAuditoryProcess(
            Dictionary<string, string> cardData);
    }
```
WorkflowEngineSoapService.cs
```
public class WorkflowEngineSoapService : IWorkflowEngineSoapService
    {
        public WorkflowEngineSoapService() { }

        public string StartAuditoryProcess(
            Dictionary<string, string> cardData)
        {
            foreach (var item in cardData)
            {
                return item.Value;
            }
            return "nok";
        }
    }
```

With this code the service is succesfully invoked. So the definitions in WSDL are correct with the default names. But cardData is empty, returning "nok".
Even if it worked, I wouldn't be able to change the elements names.

So, I have 3 hypothesis.

1. My code is wrong somewhere;
2. The first error indicates me to a missing feature in SoapCore, where it doesn't writes the WSDL correctly.
3. The second one indicates me to a problem in the System.Serialization, for it doesn't return any value to my collection. Which may be the cause for it be a missing feature in SoapCore.

**Comment by andersjonsson** [comment]
In this PR https://github.com/DigDes/SoapCore/pull/756 I added a fix for List<List<>> in the wsdl. In my case I only needed it for a return value so I didn't check if it worked for parameters.

Check out https://github.com/DigDes/SoapCore/blob/706823b8da2161366600b0c362e0bd3718932968/src/SoapCore/XmlSerializerExtensions.cs#L24-L39
My guess is that you would have to check if T is an enumerable and then call DeserializeArray recursively.
For what parameters to use, see https://github.com/DigDes/SoapCore/blob/706823b8da2161366600b0c362e0bd3718932968/src/SoapCore/SerializerHelper.cs#L154

Probably a good refactoring opportunity too.

As for Dictionary I haven't done any digging into that. I have no such methods in the soap service I'm trying to convert
