### ISSUE TITLE
System.Xml.XmlException: 'nillable' is a duplicate attribute name. for List<List<string>>

### ISSUE THREAD

**Issue by harundiri** [DigDes/SoapCore#789]
SoapCore does not serialize `List<List<string>>`
for example:
`public List<List<string>> getData(string name)`
`        {`
`            return new List<List<string>>`
`            {`
`                new List<string> {"a","b", "c"},`
`                new List<string> {"1","2", "3"}`
`            };`
`        }`
Exception:
Message: 
Test method NextGen.Framework.Services.Extensions.Use3EExtensionsTests.Use3ESoapEndpoints_SoapServiceEndpointAddedToRouting_WhenConfiguringAppBuilder threw exception: 
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException:  ---> System.Xml.XmlException: 'nillable' is a duplicate attribute name.

      Stack Trace: 
XmlWellFormedWriter.AddAttribute(String prefix, String localName, String namespaceName)
XmlWellFormedWriter.WriteStartAttribute(String prefix, String localName, String namespaceName)
XmlWrappedWriter.WriteStartAttribute(String prefix, String localName, String namespaceUri)
XmlWriter.WriteAttributeString(String localName, String value)
MetaBodyWriter.AddSchemaType(XmlDictionaryWriter writer, TypeToBuild toBuild, String name, Boolean isArray, String namespace, Boolean isAttribute, Boolean isListWithoutWrapper, Boolean isUnqualified)
MetaBodyWriter.AddSchemaComplexType(XmlDictionaryWriter writer, TypeToBuild toBuild)
MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
BodyWriter.WriteBodyContents(XmlDictionaryWriter writer)
BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
<15 more frames...>
DefaultPipeReader.GetResult(Int16 token)
ResponseBodyReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
StreamToStreamCopy.<CopyAsync>g__DisposeSourceAsync|0_0(Task copyTask, Stream source)
HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
--- End of inner exception stack trace ---
HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Use3EExtensionsTests.Use3ESoapEndpoints_SoapServiceEndpointAddedToRouting_WhenConfiguringAppBuilder(String endpoint) line 50
ThreadOperations.ExecuteWithAbortSafety(Action action)

**Comment by andersjonsson** [comment]
It works for string[][] though.

If you feel like fixing it and submitting a PR it should be sufficient to wrap this call with an if-statement, just like in the array-case earlier in the method.
https://github.com/DigDes/SoapCore/blob/cbf7428774a81a6bf1c82c061fdecdcf70e70a4f/src/SoapCore/Meta/MetaBodyWriter.cs#L1069

Like so
```
if (!isArray)
{
	writer.WriteAttributeString("nillable", "true");
}
```

Full disclosure: I'm not a project maintainer. Just a user/contributor trying to help other users to contribute. That way we can all help to move this project forward.
