### ISSUE TITLE
I want to use vin65 Contact service but unable to bind or create it's class and interface class for binding

### ISSUE THREAD

**Issue by Itsathere** [DigDes/SoapCore#8]
I am trying to use Vin65 Contact-service`https://documentation.vin65.com/Webservices/Webservices-v3/Contact-Service`

I have followed the sample but unable to create my own.If anyone have any idea please share
thanks

**Comment by kotovaleksandr** [comment]
If you need client library to consume soap service (like vin65) you should use [WCF client](https://github.com/dotnet/wcf). SoapCore its server side library to create web-services over SOAP with ASP.NET Core.

**Comment by Itsathere** [comment]
After using [ WCF client](https://github.com/dotnet/wcf) getting error. That's why I am trying to call services using  SOAP with ASP.NET Core.
