### ISSUE TITLE
README has outdated example for .NET Core 3.1+ UseSoapEndpoint

### ISSUE THREAD

**Issue by Burwin** [DigDes/SoapCore#816]
## Example in README
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseRouting();

    app.UseEndpoints(endpoints => {
        endpoints.UseSoapEndpoint<ServiceContractImpl>("/ServicePath.asmx", new SoapEncoderOptions());
    });
    
}
```

## Expected
No compiler errors.

## Actual
Compiler error message: `'IEndpointRouteBuilder' does not contain a definition for 'UseSoapEndpoint'...`

## Suggested Fix
Either the README needs updated to include an explicit `SoapSerializer` parameter passed to `UseSoapEndpoint` in this example, or the extension method in question should be made to mirror that for `IApplicationBuilder`, which defines a default `SoapSerializer` of `SoapSerializer.DataContractSerializer`.

## Context
- .NET 5
- SoapCore 1.1.0.25
- VS 2019

**Comment by javiertuya** [comment]
Same issue, netcore 3.1, SoapCore >=1.1.0.12

**Comment by andersjonsson** [comment]
Added SoapSerializer.DataContractSerializer to the sample. Hopefully it's correct now 😉
