### ISSUE TITLE
Invalid WSDL generation for data members with generics

### ISSUE THREAD

**Issue by atasmrk007** [DigDes/SoapCore#823]
When a data member is a generic type, wsdl will have "`1" added to the data member name.

Attached is a solution that demonstrates this problem.
[DotNetSoapTest.zip](https://github.com/DigDes/SoapCore/files/8066699/DotNetSoapTest.zip)

**Comment by andersjonsson** [comment]
You can probably use attributes to work around this
https://docs.microsoft.com/en-us/dotnet/standard/serialization/controlling-xml-serialization-using-attributes

Not all attributes are respected in the wsdl generation though, so you will have to test it.
