### ISSUE TITLE
SOAP 1.2 Support with DataContractSerializer not working

### ISSUE THREAD

**Issue by GreekOctopus** [DigDes/SoapCore#825]
Hi

I am try to setup support for SOAP 1.2 using SoapCore with the DataContractSerializer. I am not sure if I am doing something wrong, however based on previous SoapCore versions when setting up the MessageVersion in the SoapEncoderOption the appropriate version of SOAP would be supported. When I am selecting any of the SOAP 1.2 flavours (Soap12WSAddressing10 or Soap12WSAddressingAugust2004) I still get SOAP 1.1 in the WSDL. This is not the issue if I use the XmlSerializer. 

Am I missing some configuration or is this an issue? I have attached a demo project.

[SOAPTester.zip](https://github.com/DigDes/SoapCore/files/8117163/SOAPTester.zip)

**Comment by andersjonsson** [comment]
Seems to be an issue.
As far as I can tell, soap 1.1 is hard-coded into https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/Meta/MetaWCFBodyWriter.cs (the metabodywriter for DataContractSerializer)

I'm sure a PR would be welcome if you feel like fixing it. It would probably be a good idea to look at how it works in https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/Meta/MetaBodyWriter.cs (the metabodywriter for XmlSerializer)

**Comment by andersjonsson** [comment]
That's where I would put it, but maybe @kotovaleksandr can confirm?

I'd say: Make a PR and move the test later if you get that feedback

**Comment by kotovaleksandr** [comment]
Hi @GreekOctopus, thanks! Yes, put tests to WsdlTests.cs. I agree with the @andersjonsson , send PR, we will consider it and give feedback.

**Comment by GreekOctopus** [comment]
I have been a bit slow with the PR. Do I need to open a new ticket or re-open this going forward?

**Comment by andersjonsson** [comment]
> I have been a bit slow with the PR. Do I need to open a new ticket or re-open this going forward?

No worries 😄

**Comment by isaacholden** [comment]
Following. This issue is causing issues for a project I'm working on.

**Comment by GreekOctopus** [comment]
I have been a bit slow with the PR. Do I need to open a new ticket or re-open this going forward?

**Comment by andersjonsson** [comment]
> I have been a bit slow with the PR. Do I need to open a new ticket or re-open this going forward?

👍 
No need to open a new ticket. Just reference this one

**Comment by GreekOctopus** [comment]
As I was modifying the tests WsdlTests to test for both serializers, I noticed that the GetSoapMetaParameters method appends the soapPrefix on both the Binding and Port names. Is that a SOAP/RFC requirement or something else I am missing out on?

**Comment by andersjonsson** [comment]
> Is that a SOAP/RFC requirement

Nope, it's just to stay consistent with an old behavior. With the support to override both BindingName and PortName you can pick whatever you like

**Comment by GreekOctopus** [comment]
So as the current implementation of the MetaWCFBodyWritter does not include it, is it ok to not bring that forward to it? I do not know if there should be parity with the MetabodyWriter as it is a legacy issue.

**Comment by andersjonsson** [comment]
> So as the current implementation of the MetaWCFBodyWritter does not include it, is it ok to not bring that forward to it? I do not know if there should be parity with the MetabodyWriter as it is a legacy issue.

Yes, skip it. Feature parity is nice but I personally think it’s more important to keep the default behavior.

**Comment by GreekOctopus** [comment]
Hi Anders I have commited a merge request 6 days, with comments and new tests, but I am not sure if I need to raise a PR by following any additional steps. Can you please confirm if this is the correct way? Thanks
