### ISSUE TITLE
CRLF in string DataMember coverted to LF

### ISSUE THREAD

**Issue by eloveeri** [DigDes/SoapCore#827]
I have a definition as follows in my contract:

```
[DataMember]
public string data { get; set; }
```

When trying to return a value that contains `\r\n` it automatically seems to get converted to `\n`. I have not been able to find any way around this problem. I am running the application in an `aspnet:6.0` container and I am using the DataContractSerializer (XmlSerializer does not work for my purposes).

Does a solution exist?

EDIT: I am dealing with a WCF implementation that allowed this. I have not looked at what's going over the wire, but on the client side they show up as `\r\n` with a WCF service implementation.

**Comment by andersjonsson** [comment]
Are you using a linux container? Newline is encoded as just `\n` there.
How do you produce the string? If you serialize an object it would probably produce different results on windows and on linux.

See https://stackoverflow.com/questions/58105071/is-it-possible-to-force-net-core-on-linux-to-use-crlf for reference.

**Comment by eloveeri** [comment]
Yes, using a Linux container and also expect results would be different on Windows. But I need the Linux container to behave the same.

[XmlWriterSettings.NewLineChars](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwritersettings.newlinechars?view=net-6.0) looks interesting and it's set to [Environnment.NewLine](nvironment.NewLine) by default and in SoapCore can't be alterered.

**Comment by andersjonsson** [comment]
Yup, that seems like a likely fix.
Check out my previous PR https://github.com/DigDes/SoapCore/pull/766 for allowing invalid xml characters to be serialized, if you want to get a sense for how to add such an option to SoapCore
