### ISSUE TITLE
"/ServicePath.asmx "Paths cannot be case insensitive

### ISSUE THREAD

**Issue by lxhcnblogscom** [DigDes/SoapCore#828]
`public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseRouting();

    app.UseEndpoints(endpoints => {
        endpoints.UseSoapEndpoint<ServiceContractImpl>("/ServicePath.asmx", new SoapEncoderOptions());
    });
    
}`

question: "/ServicePath.asmx "Paths cannot be case insensitive

**Comment by andersjonsson** [comment]
You can use CaseInsensitivePath in SoepCoreOptions

```
app.UseEndpoints(endpoints => {
    endpoints.UseSoapEndpoint<ServiceContractImpl>(opt =>
    {
        opt.Path = "/ServicePath.asmx",
        opt.CaseInsensitivePath = true,
        EncoderOptions = new SoapEncoderOptions()
        //...
    }
});
```
