### ISSUE TITLE
Can add only 1 with AddSoapMessageProcessor(ISoapMessageProcessor)

### ISSUE THREAD

**Issue by myobis** [DigDes/SoapCore#837]
The implementation of [AddSoapMessageProcessor(ISoapMessageProcessor)](https://github.com/DigDes/SoapCore/blob/1160177e9d69021a27e606b2f1dbbee87dbcfd3b/src/SoapCore/SoapEndpointExtensions.cs#L435) is using `.TryAddSingleton(messageProcessor)` .

The problem is that only the first call to `AddSoapMessageProcessor()` is considered.
I guess this is because `TryAddSingleton` will only adds a `ISoapMessageProcessor` if none is there yet. `AddSingleton` would not add _only the first one_.

The test that I did :
- Assume you have 2 classes `CustomProcessor1` and `CustomProcessor2` both implementing `ISoapMessageProcessor`.
- The following code will only register the `CustomProcessor1` instance.
`CustomProcessor2.ProcessMessage()` is never called.
```
services.AddSoapMessageProcessor(new CustomProcessor1());
services.AddSoapMessageProcessor(new CustomProcessor2());
```
- The following workaround code works to registers both and I confirm that both are called.
```
services.AddSingleton<ISoapMessageProcessor>(new CustomProcessor1());
services.AddSingleton<ISoapMessageProcessor>(new CustomProcessor2());
```

Hence using `.AddSingleton<ISoapMessageProcessor>()` instead, might be a fix.

NB: I didn't test the other overload of `AddSoapMessageProcessor()` .. It might suffer the same defect.

**Comment by andersjonsson** [comment]
Nice catch! 
AddSoapServiceOperationTuner had the same bug, so I fixed that one too
