### ISSUE TITLE
List<T> and IEnumerable<T> handling

### ISSUE THREAD

**Issue by neilsimp1** [DigDes/SoapCore#84]
I have an operation that returns `List<JobSummary>`.
I also have several properties that are a `List` of objects, such as `List<Destination>` on type `JobSummary`
When generating the WSDL, two issues arise from using `List`.

1. The element in the WSDL for anything with a List type shows as ``List`1``. When I try to create a project in SoapUI using that WSDL, it gives me an error on that type.
I've tried programmatically removing the `` `1`` in `MetaBodyWriter.AddSchemaType()`, so it was just ` type="tns:List"` but then ran into other issues with List...

2. The ComplexType for List in the WSDL gets generated as
```
<xs:complexType name="List">
  <xs:sequence>
    <xs:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="JobSummary" type="tns:JobSummary"/>
  </xs:sequence>
</xs:complexType>
```
which is not right. If I try to Create a project in SoapUI any property that is a List will have a JobSummary object in place of wherever the list should be.

Changing all of my Lists to arrays isn't going to be easy, and I'm not even sure if that is what is needed. There's a much larger codebase that's using `IEnumerable` and `List` a lot in the models.

Am I doing something incorrectly?

**Comment by neilsimp1** [comment]
I took a look at a proper WCF project that uses `List<T>` for several properties and looked at the WSDL (disclaimer: I've never used WCF before) and all of the `List` properties turned into `ArrayOf***` in the WSDL.

https://gist.github.com/neilsimp1/f809b33e580e7bb8cac6fb23a13fc59a

See the gist. I've updated `MetaBodyWriter.cs` to change anything that is an `IEnumerable` to `ArrayOf***` in the WSDL. Would something like this be useful as a PR? The project imports into SoapUI properly now.

Note: There are a few other small changes in this file not having to do with this issue.

**Comment by kotovaleksandr** [comment]
Hi, yes. Send changes as PR and we will publish new release on nuget.

**Comment by neilsimp1** [comment]
Do you have any requirements for this, such as writing tests? I have not written any tests for this yet.

**Comment by kotovaleksandr** [comment]
Yes, tests are needed

**Comment by neilsimp1** [comment]
Ok, thanks! I've submitted https://github.com/DigDes/SoapCore/pull/86 with tests and an updated Sample project for this.

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/0.9.8

**Comment by neilsimp1** [comment]
If there's a better place to discuss this, please direct me there. I don't want to create another Issue just to ask you some questions, though...

I've been working to add in some other new features that I've needed out of this library.

- `services.AddSoapMessageFilter()`
  - This lets you add a service that gets called `OnRequestExecuting` and `OnResponseExecuting` and takes in a `Message` object. These function get called from `SoapEndpointMiddleware.ProcessOperation()` before `messageInspector?.AfterReceiveRequest(requestMessage);` and just before `return responseMessage;`, respectively.
- `services.AddSoapWsSecurityFilter()`
  - This lets you define a username and password and creates a service with `AddSoapMessageFilter()` that looks for a `<wsse:UsernameToken>` in your SOAP header with a proper username and password. Your SOAP header must look like:
  ```
  <soapenv:Header>
      <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <wsse:UsernameToken>
            <wsse:Username>yourusername</wsse:Username>
            <wsse:Password Type="wsse:PasswordText">yourpassword</wsse:Password>
         </wsse:UsernameToken>
      </wsse:Security>
   </soapenv:Header>
  ```
  Note I have not provided full WS Security support, only `<UsernameToken>` with Username and Password. There is a lot more to WS Security that isn't implemented and I don't know much about.
- `services.AddSoapModelBindingFilter()`
  - This is similar to the `AddSoapMessageFilter()`, except that it is called after your model(s) is deserialized, and before invoking the Operation. This lets you perform work on the model object before it enters into the `[OperationContract]` in your Service class.
- MVC ActionFilter support
  - This allows you to decorate your `[OperationContract]` methods in your Service class with `Microsoft.AspNetCore.Mvc.Filters`. ex. [ServiceFilter(typeof(MyCustomFilter))]`.
  These filters will get called after the model binding filters, but before the SOAP operation is invoked, the same as in ASP.Net MVC.

My use cases were
- Needed some sort of authentication on SOAP requests
- Needed to share validation code and filters between REST API and SOAP services

Please let me know if any of this will be useful to the project, and I will happily break them up into whatever PRs you think would work. And again, let me know if there's a better place for this question, and I'll move the discussion there.

**Comment by kotovaleksandr** [comment]
Hi @neilsimp1, sorry for late response. Of course it good improvements and it will be useful not only for you. Exists one requirement - saving backward compatibility, if you changes not break them - send PR, we will be very thankful!
