### ISSUE TITLE
Read attributes from root

### ISSUE THREAD

**Issue by joshingham** [DigDes/SoapCore#844]
I'm trying to accommodate users retaining existing payloads from legacy systems and struggling to see if there's a way for the following to be parsed correctly as a complex input:
```
<OTA_PingRQ TimeStamp="2008-05-15T15:45:05" Target="Production" Version="1.005" PrimaryLangID="EN" xmlns="http://www.opentravel.org/OTA/2003/05">
    <EchoData>Sample Ping Echo Data</EchoData>
</OTA_PingRQ>
```

When I use the sample code provided and tweak the properties and parameters to look how I want, I have to use something like the following to have any data parsed at all:
```
<OTA_PingRQ xmlns="http://www.opentravel.org/OTA/2003/05">
    <input TimeStamp="2008-05-15T15:45:05" Target="Production" Version="1.005" PrimaryLangID="EN">
        <EchoData>Sample Ping Echo Data</EchoData>
    </input>
</OTA_PingRQ>
```

However, I need to be able to read the attributes from the root of the body as in the first example. I need the data structure to be shifted one level, and do away with the "input" tag, which is just the name of the parameter on the "OTA_PingRQ" method.

Is this possible at present? Or can anyone suggest a way of achieving this? I'd rather not resort to creating a web service in .NET Framework to support these users.

**Comment by andersjonsson** [comment]
It's not supported out of the box.
A possible workaround is to use a SoapMessageProcessor that rearranges the message in a way that SoapCore can handle

```
var bufferedMessage = message.CreateBufferedCopy(int.MaxValue);
var msg = bufferedMessage.CreateMessage();
var reader = msg.GetReaderAtBodyContents();
var content = reader.ReadInnerXml();

var message = x
//If the message is correct, use bufferedMessage.CreateMessage(); otherwise use one of the overloads of Message.CreateMessage() to create a new message

return await next(message);
```


If you want to add support for parameters as attributes, this method would be a good place to start.
https://github.com/DigDes/SoapCore/blob/b0083a685cdf282b23d1a26df3884059c897321e/src/SoapCore/SoapEndpointMiddleware.cs#L609

The method loops through all child tags and parses them. My best bet would be to add a similar loop that tries to parse any attributes that matches a parameter name.

A potential conflict would be how to handle if a message has both an attribute and a child tag with the same name... but that seems like an unlikely scenario

**Comment by joshingham** [comment]
That's great, thanks for taking the time. I'll explore the options you've presented and let you know how it goes!

**Comment by joshingham** [comment]
This worked a treat, thank you!

The readme says "this allows you to inspect the message on the way in and out" - so is there a way to intercept the outgoing response with a similar treatment?

**Comment by andersjonsson** [comment]
> This worked a treat, thank you!
> 
> The readme says "this allows you to inspect the message on the way in and out" - so is there a way to intercept the outgoing response with a similar treatment?

Yup!

```
var responseMessage = await next(message);

//Then return whatever you like.
return myNewResponseMessage;
```

**Comment by joshingham** [comment]
That's great, thanks for clarifying that. I appreciate the help you've given so far.

My (hopefully) final problem occurs when I intercept the outgoing message to rename the elements that are automatically created, e.g. "OTA_PingRQResponse".

With my outbound message manipulation I'm trying to do the reverse of the inbound manipulation that I outlined previously, but also with some renaming. For example, I get the following response with no outbound manipulation:
```
<OTA_PingRQResponse xmlns="http://www.opentravel.org/OTA/2003/05">
    <OTA_PingRQResult Version="0.02">
        <EchoData>Sample Ping Echo Data</EchoData>
    </OTA_PingRQResult>
</OTA_PingRQResponse>
```

My goal is to make the received response be:
```
<OTA_PingRS xmlns="http://www.opentravel.org/OTA/2003/05" Version="0.02">
    <EchoData>Sample Ping Echo Data</EchoData>
</OTA_PingRS>
```

When I do this, an error is thrown stating "No operation found for specified action: OTA_PingRS". If I make a new endpoint called OTA_PingRS and give it an operation contract, then the response I receive when testing has nothing to with my manipulation, and is instead a single empty element with the name "OTA_PingRSResponse".

Am I intercepting the outbound message too early somehow? Am I missing something? Or am I trying to do something the library doesn't support? If the latter, what could my options be to achieve this goal?

**Comment by andersjonsson** [comment]
> When I do this, an error is thrown stating "No operation found for specified action: OTA_PingRS"

That sounds weird. Are you calling next() with your new response message instead of just returning it? That error is thown in "ProcessMessage" that gets called as the last step in the pipe.

If not, please include the code (redaced or abbreviated if you feel the need) of your SoapMessageProcessor so I can see what's going on

**Comment by joshingham** [comment]
Sure, thank you.

When I do "return finalResponseMessage" I get a response of just:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body />
</s:Envelope>
```

When I do "return await next(finalResponseMessage)" I get the error I described. I was sticking with that because it seemed like progress to have an XML-related error rather than an empty response.

It sounds like I was wrong though. Please find my rough code below, unaltered. This is the entire contents of my SoapMessageProcessor.

```
    public async Task<Message> ProcessMessage(Message message, HttpContext context, Func<Message, Task<Message>> next)
    {
      var bufferedMessage = message.CreateBufferedCopy(int.MaxValue);
      var msg = bufferedMessage.CreateMessage();
      var modifiedBodyContent = ReformatRequestBody(msg);

      Message intialResponseMessage = null;

      using (var ms = new MemoryStream())
      {
        await ms.WriteAsync(Encoding.UTF8.GetBytes(modifiedBodyContent), 0, modifiedBodyContent.Length);
        ms.Position = 0;
        using (var xmlReader = XmlReader.Create(ms))
        {
          var newMessage = Message.CreateMessage(msg.Version, null, xmlReader);
          newMessage.Headers.CopyHeadersFrom(msg);

          intialResponseMessage = await next(newMessage);

          //return await next(newMessage);
        }
      }

      var bufferedMessage1 = intialResponseMessage.CreateBufferedCopy(int.MaxValue);
      var msg1 = bufferedMessage1.CreateMessage();
      var modifiedBodyContent1 = ReformatResponseBody(msg1);

      Message finalResponseMessage = null;

      using (var ms = new MemoryStream())
      {
        await ms.WriteAsync(Encoding.UTF8.GetBytes(modifiedBodyContent1), 0, modifiedBodyContent1.Length);
        ms.Position = 0;
        using (var xmlReader = XmlReader.Create(ms))
        {
          finalResponseMessage = Message.CreateMessage(msg1.Version, null, xmlReader);
          finalResponseMessage.Headers.CopyHeadersFrom(msg1);

          string test = finalResponseMessage.ToString();

          return finalResponseMessage;
        }
      }
    }

    public string ReformatRequestBody(Message message)
    {
      var reader = message.GetReaderAtBodyContents();
      var content = reader.ReadOuterXml();

      XDocument xDocument = XDocument.Parse(content);
      var root = xDocument.Descendants().FirstOrDefault();
      XNamespace xn = root.HasAttributes ? root.Attribute("xmlns").Value : "http://tempuri.org/";
      var nodes = root.Nodes().ToList();
      XElement input = new XElement(xn + root.Name.LocalName);
      if (root.HasAttributes)
      {
        foreach (var attribute in root.Attributes())
        {
          if (attribute.Name != "xmlns")
            input.SetAttributeValue(attribute.Name, attribute.Value);
        }
      }
      root.ReplaceNodes(input);
      input.ReplaceNodes(nodes);

      return xDocument.ToString();
    }

    public string ReformatResponseBody(Message message)
    {
      var reader = message.GetReaderAtBodyContents();
      var content = reader.ReadOuterXml();

      XDocument xDocument = XDocument.Parse(content);

      //return xDocument.ToString();

      var root = xDocument.Descendants().FirstOrDefault();
      var elementToRemove = root.Descendants().FirstOrDefault();

      XNamespace xn = root.HasAttributes ? root.Attribute("xmlns").Value : "http://tempuri.org/";
      XElement newRoot = new XElement(xn + root.Name.LocalName.Replace("RQResponse", "RS"));

      if (elementToRemove.HasAttributes)
      {
        foreach (var attribute in elementToRemove.Attributes())
        {
          if (attribute.Name != "xmlns")
            newRoot.SetAttributeValue(attribute.Name, attribute.Value);
        }
      }

      var nodesToMove = elementToRemove.Nodes().ToList();
      newRoot.ReplaceNodes(nodesToMove);

      root.ReplaceWith(newRoot);

      return xDocument.ToString();
    }
```

**Comment by andersjonsson** [comment]
I think the xmlReader is read first when the message is written somewhere, so that your using clauses on the memorystream and the reader are the culprit.

This worked for me

```
var msg = await next(message);
var reader = msg.GetReaderAtBodyContents(); //no need to create a buffered copy since I know that I will return a new message

var content = await reader.ReadOuterXmlAsync();

var ms = new MemoryStream(Encoding.UTF8.GetBytes(content.Replace("Ping", "Pong")));
ms.Position = 0;
var xmlReader = XmlReader.Create(ms);

return Message.CreateMessage(msg.Version, null, xmlReader);
```

When I had a usings on the reader and the memorystream it failed.

**Comment by joshingham** [comment]
Aha, that did it! Thanks for very much for you assistance here!
