### ISSUE TITLE
CustomBinding vs WsBinding

### ISSUE THREAD

**Issue by GreekOctopus** [DigDes/SoapCore#850]
Hi

When consuming a service implementing Soap Core, my test client that is a .Net framework client creates a Custom binding instead of a WS one. In the WSDL I cannot see anything determining what type of binding to create, so how can Visual Studio know what to create? I cannot seem to be able to specify that in the service either via Soap Core. At this point I am not sure if this is missing from Soap Core or if this is my misunderstanding when it comes to my implementation.

I am happy to attach a demo project, I just do not feel there is much value with my question.

**Comment by andersjonsson** [comment]
wsHttpBinding is currently not supported in SoapCore. To fully support wsHttpBinding we would need to add sessions, authentication and encryption.

If this is something you need, and if you feel like looking into it, a PR would be welcome
