### ISSUE TITLE
How can i change <soap:address location > https from http ?

### ISSUE THREAD

**Issue by kadirafsin** [DigDes/SoapCore#852]
Hi
I have a service with below configuration

`public void Configure(IApplicationBuilder app, IWebHostEnvironment env)`
        `{`
         `   app.UseSoapEndpoint<IBKMVendorFieldService>("/bkm/BKMTechPosService.asmx", new SoapEncoderOptions() , SoapSerializer.DataContractSerializer);`
        `    app.ConfigureAll();`
    `    }`

When its run on IISExpress on my local machine with visualStudio, in wsdl definition, soap:address seems like 

`<soap:address location="https://localhost:44305/bkm/BKMTechPosService.asmx"/>
`
But when i publish this api with ssl (https url) on test environment with docker, its look like ;
`
<soap:address location="http://blabla-test.blabla.com/bkm/BKMTechPosService.asmx"/>`

How can i change this attribute ?

**Comment by andersjonsson** [comment]
The WSDL just display the url used to access the endpoint. See:
https://github.com/DigDes/SoapCore/blob/21b1ca1f63c648818be629dd926c18ea0dc39194/src/SoapCore/SoapEndpointMiddleware.cs#L234

Do you want to use http:// locally?
The automatic https:// locally is default aspnet core behavior. To disable it, see:
https://munda.net/2021/01/disable-https-for-asp-net-core-5-0-api-project/

**Comment by kadirafsin** [comment]
No, i just want change  soap:address location start with https instead http ? Is it possible, cuz our access end point starts with https

**Comment by andersjonsson** [comment]
There is no way to set an explicit url for the location-attribute. If that is the best solution for you, please feel free to submit a PR with an optional override.

Do you have have SSL termination in a load balancer or something? If you check out the code in SoapEndpointMiddleware that I referred to, you can see that httpContext.Request.Scheme is printed, as is.

The legacy service I work on has SSL Termination, but the load balancer (HA-Proxy) adds an "X-Forwarded-Proto"-header. So I use that to change Protocol and Scheme like this

```
httpContext.Request.Protocol = httpContext.Request.Headers["X-Forwarded-Proto"];
httpContext.Request.Scheme = httpContext.Request.Headers["X-Forwarded-Proto"];
```

If you know that you will always use https:// i suppose you can add a hardcoded middleware before your UseSoapEndpoint that does something like this:

```
app.Use(async (context, next) =>
{
    context.Request.Protocol = "HTTPS";
    context.Request.Scheme = "HTTPS";
    
    await next();
}
);
```

That will _probably_ work

**Comment by kadirafsin** [comment]
Thanks for your help Anders. I think reason is LB as you said. Your suggestion is worked for me
