### ISSUE TITLE
I set the XmlSerializerFormat Style to  the Rpc .But it doesn't work.

### ISSUE THREAD

**Issue by qile3897** [DigDes/SoapCore#853]
I change the .net framework to .net core
I want to switch the xmlserializeformat document to  rpc and use encoded and Insert Body Namespace.
What should I do ?
This is My Code.
Service Code
```
 public interface IMonWeb
    {
        [OperationContract(Action ="")]
        [return: MessageParameter( Name = "queryObjectOutReturn")]
        [XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Encoded)]
        string queryObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc);
    }
```
Startup.cs
```
            app.UseEndpoints(endpoints =>
            {
                endpoints.UseSoapEndpoint<IMonWeb>("/HelloSoap", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
            });
```
And The soapcore WSDL Code
```
<wsdl:binding name="BasicHttpBinding_WebServiceSoap_soap" type="tns:WebServiceSoap">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="queryObjectOut">
    <soap:operation soapAction="" style="document"/>
    <wsdl:input>
      <soap:body use="literal"/>
    </wsdl:input>
    <wsdl:output>
      <soap:body use="literal"/>
    </wsdl:output>
  </wsdl:operation>
</wsdl:binding>
```

This is the .net framework wsdl code
```
<wsdl:binding name="WebServiceSoap" type="tns:WebServiceSoap">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="queryObjectOut">
  <soap:operation soapAction="" style="rpc"/>
    <wsdl:input>
      <soap:body use="encoded" namespace="http://endpoint.axis.framework.tmri.com" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </wsdl:input>
    <wsdl:output>
      <soap:body use="encoded" namespace="http://localhost:8080/monweb/services/TmriOutAccess" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
    </wsdl:output>
  </wsdl:operation>
</wsdl:binding>
```

**Comment by andersjonsson** [comment]
Unfortunately there is no support for that in SoapCore at the moment.

As you can see here
https://github.com/DigDes/SoapCore/blob/21b1ca1f63c648818be629dd926c18ea0dc39194/src/SoapCore/Meta/MetaBodyWriter.cs#L657-L662
`style=" document"` and `use="literal"` are hard coded.

To check for attributes and use those values in the wsdl should be easy enough, but one would need to add support for different encodings messages are read/written.

Please feel free to submit a PR if you feel like giving this a go.

**Comment by qile3897** [comment]
> 

I think the problem is not just about MetaBodyWriter.cs。
Because when I code the xmlserializerformat,the client call the action result will be null .
Service Code
‘’‘
        [XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Encoded)]
        string queryObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc);
’‘’
Client Code
'''
 var clientResult = new WebServiceSoapClient(binding, endpoint).queryObjectOut("1","2","3","4");
'''
