### ISSUE TITLE
ServiceKnownTypeAttribute with the specified methodName is not supported

### ISSUE THREAD

**Issue by psvetlov** [DigDes/SoapCore#858]
Seems where it is not possible to use ServiceKnownTypeAttribute(String, Type) due to EnsureServiceKnownTypes method is checking for null Type.

**Comment by andersjonsson** [comment]
Interesting. I see, in the source, that you are correct. What would a reasonable behavior be?
How should it work when Type is null?

**Comment by andersjonsson** [comment]
Ah, I see! 
Shouldn't be that big of an effort to get that working

**Comment by andersjonsson** [comment]
Do you have a good test case, so you can verify my fix? Unfortunately there are no unit tests for this method.
If you feel up for it I'd appreciate suggestions for good test cases
