### ISSUE TITLE
Is there any way to set the wsdl/binding/operation/input or output namespace?

### ISSUE THREAD

**Issue by qile3897** [DigDes/SoapCore#859]
My old wsdl file:
```
<wsdl:binding name="BasicHttpBinding_WebServiceSoap_soap" type="tns:WebServiceSoap">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="queryObjectOut">
<soap:operation soapAction="" style="rpc"/>
<wsdl:input>
<soap:body use="encoded" namespace="http://endpoint.axis.framework.tmri.com" encodingStyle="http://www.w3.org/2003/05/soap-encoding"/>
</wsdl:input>
<wsdl:output>
<soap:body use="encoded" namespace="http://localhost:8080/monweb/services/TmriOutAccess" encodingStyle="http://www.w3.org/2003/05/soap-encoding"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
````
The WebService set the property
```
 [SoapRpcMethod(Action= "", RequestNamespace = "http://endpoint.axis.framework.tmri.com")]
public string queryObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc)
```

I found the XmlSerializerFormatAttribute ,but it doesn't have the Request or Response NameSpace
```
[XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Encoded)]
```

**Comment by andersjonsson** [comment]
Unfortunately not. It's the same deal as with your latest issue.
Check out https://github.com/DigDes/SoapCore/blob/21b1ca1f63c648818be629dd926c18ea0dc39194/src/SoapCore/Meta/MetaBodyWriter.cs

There you can see what is supported, and it's not much when it comes to those things. Body is hardcoded to `use="document"`, for instance.

If you feel like submitting a PR, adding functionality in this vein, I'll try to assist you with any questions you might have.

**Comment by qile3897** [comment]
@andersjonsson 
Okay,I just fork the project and hardcoded https://github.com/DigDes/SoapCore/blob/21b1ca1f63c648818be629dd926c18ea0dc39194/src/SoapCore/Meta/MetaBodyWriter.cs to make wsdl file  which I expected.
However,the service still not worked. The  error message :Start element 'xxxx' from namespace 'yyyy' expected. Found element 'xxxx' from namespace 'zzzz'.
And It seems like the wsdl file and the wcf service not matched.

**Comment by andersjonsson** [comment]
Firstly: If you're using SoapSerializer.DataContractSerializer it's https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/Meta/MetaWCFBodyWriter.cs that you have to modify. Sorry for not making this clear.

Secondly, the wsdl is just documentation. Body="encoded" means that the client will send data encoded in a certain format and will expect the same type of encoding in the return messages.
There is no such support built in to SoapCore.

So fixing the wsdl is just a first step.

One way to go about this would be to add an ISoapMessageProcessor and decode the message on the way in. You could then do the same thing on the way out, to encode the response message.
See issue #844 where this technique was used to solve an issue with the format of the request/response-messages.


If you want to look at adding this support as feature in SoapCore I recommend that you start by adding a `BodyFormat`-property (The name is just the first thing that came to mind. Feel free to use whatever you think is clear) to SoapEncoderOptions. This can, in turn, guide how the wsdl is generated and how the messages are read/written

**Comment by andersjonsson** [comment]
Information about the encoding can be found here.
https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383512
As far as I can tell the encoding is only a feature of Soap1.1, so that would also have to be taken into consideration

**Comment by qile3897** [comment]
Thank you for your tips.@andersjonsson
My goal is to seamlessly replace java webservice with .net core webservice. Now I have achieved，in a hardcoded way.
I modify the MetaBodyWriter.cs to change the wsdl doc.
I modify the ServiceBodyWriter to change the response message.
