### ISSUE TITLE
SoapCore Not Serializing Properties When Structure of Soap XML Call Changes

### ISSUE THREAD

**Issue by isaacholden** [DigDes/SoapCore#862]
I've managed to re-create some odd behavior I found when messing with SoapCore serialization.

Here is the GitHub project to the .NET Core 3.1 solution with the included SoapUI project: https://github.com/isaacholden/SoapCoreXMLStructure

If you stick a breakpoint on line 13 of ProcessPerson.cs, and run the Soap call and inspect the calc local variable, the Gender and DateOfBirth properties are populated. If either of those two properties are moved in the Soap call to a different location still within <tem:calculatorRequest>, then Gender and DateOfBirth are not serialized, and the calc local variable will show null for both properties.

Here is an example of the Soap call being altered where Gender and DateOfBirth will not be serialized:

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:soap="http://schemas.datacontract.org/2004/07/SoapCore_Test.Model">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Process>
         <tem:calculatorRequest>
            
            <soap:Adjustment>
               
               <soap:FirstID>1</soap:FirstID>
               
               <soap:SecondID>2</soap:SecondID>
               
               <soap:ThirdID>3</soap:ThirdID>
            </soap:Adjustment>
            
            
            <soap:Keys>
               
               <soap:Lot>10</soap:Lot>
               
               <soap:MoneyOne>20</soap:MoneyOne>
               
               <soap:TestMoney>20</soap:TestMoney>
            </soap:Keys>
            
            <soap:ProfileType>Test</soap:ProfileType>
            <soap:DateOfBirth>2020-01-01</soap:DateOfBirth>
            <soap:Gender>Male</soap:Gender>
         </tem:calculatorRequest>
      </tem:Process>
   </soapenv:Body>
</soapenv:Envelope>`

Any idea why this might be the case? Is this expected behaviour?

Thanks

**Comment by andersjonsson** [comment]
Yes. With datacontractserializer, order matters.
https://stackoverflow.com/questions/2250111/does-order-matter-in-the-xml-read-by-the-datacontractserializer

If you need to support different ordering I recommend that you give XmlSerializer a try.

Otherwise you would need to intercept the message (possibly with an ISoapMessageProcessor) and rearrange the incoming message in the correct order.

**Comment by isaacholden** [comment]
You're absolutely right andersjonsson, thanks for the info!
