### ISSUE TITLE
Namespace Prefix

### ISSUE THREAD

**Issue by brentos99** [DigDes/SoapCore#87]
I'd need to generate a namespace prefix for the response object. The sample response object has the namespace as an attribute in the response object, however i need to use a prefix instead. 

This is a sample of my object using a [ServiceContract(Namespace=@"http://freshfighter.net/text.xsd")] attribute. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <testResponse xmlns="http://freshfighter.net/test.xsd">
            <message>Hello</message>
        </testResponse>
    </s:Body>
</s:Envelope>
```

The following is what I would like the response object to look like. 
```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://freshfighter.net/test.xsd">
    <s:Body>
        <ns1:testResponse>
            <ns1:message>Hello</ns1:message>
        </ns1:testResponse>
    </s:Body>
</s:Envelope>
```

I was able to make the SoapCore generate the about response object by adding the following code to the **CustomMessage** class.
```c#
protected override void OnWriteStartEnvelope(XmlDictionaryWriter writer) {
  ...
  writer.WriteXmlnsAttribute("ns1", "http://freshfighter.net/test.xsd");
  ..
}
```

Obviously this is just a quick hack! I would like to be able to generate the above Response using an attribute on the service contract, but it doesn't appear to be away to specify a prefix or the ability to tell the serialiser to put the namespace at the Envelope level.

I was thinking that I could create a PR and provide a new Attribute that can be used along with ServiceContractAttribute and the code to use the attributes when serialising the message. Is this the best way to go about this? Would such a PR get accepted or be useful for anybody else?

Thanks

Brent

**Comment by brentos99** [comment]
Looking into it a little further. It might be good to use the **[XmlNamespaceDeclarationsAttribute](https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlnamespacedeclarationsattribute%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)** 

It would then be a matter of having an option at some level in SOAPCore whether or not to use the namespaces at the Envelope level and some code in **CustomMessage::OnWriteStartEnvelope** to use add the namespaces to the XmlWriter.

There doesn't look like there is a way to get access to the Operation object from inside the CustomMessage to extract the XmlSerializerNamespaces. Would it be best to do the _Create response message_ section of the **ProcessOperation** function?

**Comment by phikll12** [comment]
have you solved the problem yet?
