### ISSUE TITLE
SoapCore can use XSD anyType

### ISSUE THREAD

**Issue by crisoe7** [DigDes/SoapCore#870]
web api function can use object type?
Depending on the request object may be bool may be string may be datatable and so on

web api function:
`public object TestAnyType(string method, object[] parameters)
        {
            string str = "123";
            return str;
        }`

wsdl:
`<xsd:element name="TestAnyType">
<xsd:complexType>
<xsd:sequence>
<xsd:element minOccurs="0" maxOccurs="1" name="method" type="xsd:string"/>
<xsd:element minOccurs="0" maxOccurs="1" name="parameters" nillable="true" type="tns:ArrayOfObject"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="TestAnyTypeResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element minOccurs="0" maxOccurs="1" name="TestAnyTypeResult" type="tns:Object"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>`

SoapCore is tns:ArrayOfObject , but Framework web service is ArrayOfAnyType

**Comment by andersjonsson** [comment]
Yeah, unfortunately there is no built in support for the "any"-type as far as I can tell.
See #829 

Should be possible to add this support if you feel up for it
