### ISSUE TITLE
Operation cannot be found issue

### ISSUE THREAD

**Issue by kristijanmihaljinac** [DigDes/SoapCore#873]
Hi to all,
We have a problem if the header soapaction is not specified. When soapaction is not specified then middlware cannot find which service method to call. 

Method name: 
![image](https://user-images.githubusercontent.com/59372416/167352050-40ffabc0-33eb-4f2a-bd03-2915ab40c652.png)

I found a solution so I ask if you could add that to the code.
Problem is in TryGetOperation method. The picture shows the as is state and that is the state with the change. After the change, there is no problem anymore. My question is if you could add that in the next version.

![image](https://user-images.githubusercontent.com/59372416/167352594-bfa66283-8b09-40a7-858a-a8e76b480ba2.png)

**Comment by andersjonsson** [comment]
Looks good. A pull request would be most appreciated. Feel like submitting one?

**Comment by kristijanmihaljinac** [comment]
Ok. I will submit PR as soon as possible.
