### ISSUE TITLE
Fault XML is incorrect

### ISSUE THREAD

**Issue by kristijanmihaljinac** [DigDes/SoapCore#875]
Hi all, 
we have problem that Fault XML does not seem as expected. 

This is how looks: 
![image](https://user-images.githubusercontent.com/59372416/167865806-34b82c99-d9b0-4f95-a920-1f208b5972ab.png)

This. is expected:
![image](https://user-images.githubusercontent.com/59372416/167865832-3781b7e2-5087-4542-b160-08ae75674c17.png)

In service we have this attribute on method but it's ignored:
![image](https://user-images.githubusercontent.com/59372416/167866230-7ccc168b-5b91-48b9-9488-02d537e3abb6.png)

Can you help me or tell me how to correct the mistake?

**Comment by kristijanmihaljinac** [comment]
@andersjonsson This is urgent for us so if you can take a look. 
How to format fault xml and how to add prefix?
Thanks for help.

**Comment by andersjonsson** [comment]
As far as I can tell the only support for customizing faults is by using FaultException<T>.
Check out https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/FaultBodyWriter.cs

If you need more than what's currently available you are more than welcome to submit a PR if you feel up for it.

My own contributions to SoapCore came from a similar situation where I needed support for certain operations to be able to port a legacy web service over to dotnet core.

**Comment by kristijanmihaljinac** [comment]
@andersjonsson  Can you please provide me how to setup LookupPrefix?
![image](https://user-images.githubusercontent.com/59372416/168746039-cc456d46-7d36-4eeb-8819-013ec9347b39.png)

**Comment by andersjonsson** [comment]
> @andersjonsson Can you please provide me how to setup LookupPrefix?

I believe LookupPrefix uses the XmlNamespaceManager passed in here:
https://github.com/DigDes/SoapCore/blob/be7565080cc37be8017dadc439c477997ca35c5a/src/SoapCore/DefaultFaultExceptionTransformer.cs#L28

That means you can use XmlNamespaceOverrides in the encoderoptions to configure the namespaces to suit your needs.

**Comment by andersjonsson** [comment]
> @andersjonsson is there any example how to use XmlNamespaceOverrides?

You can use it like this:
```
var nsm = new XmlNamespaceManager(new NameTable());
nsm.AddNamespace("xsi", "http://www.w3.org/2001/XMLSchema-instance");
nsm.AddNamespace("s", "http://www.w3.org/2001/XMLSchema");
nsm.AddNamespace("soap12", "http://schemas.xmlsoap.org/wsdl/soap12/");
nsm.AddNamespace("http", "http://schemas.xmlsoap.org/wsdl/http/");
nsm.AddNamespace("http", "http://schemas.microsoft.com/ws/06/2004/policy/http");
nsm.AddNamespace("mime", "http://schemas.xmlsoap.org/wsdl/mime/");
nsm.AddNamespace("soap", "http://schemas.xmlsoap.org/soap/envelope/");
nsm.AddNamespace("tm", "http://microsoft.com/wsdl/mime/textMatching/");
nsm.AddNamespace("soapenc", "http://schemas.xmlsoap.org/soap/encoding/");
nsm.AddNamespace("wsdl", "http://schemas.xmlsoap.org/wsdl/");

e.UseSoapEndpoint<IMyService>(opt => 
{
    opt.Path = "/MyService.asmx",
    opt.XmlNamespacePrefixOverrides = nsm;
});
```

**Comment by kristijanmihaljinac** [comment]
@andersjonsson Thanks for help.
