### ISSUE TITLE
Model is null

### ISSUE THREAD

**Issue by lvargas99** [DigDes/SoapCore#878]
I'm writing a Soap Service to digest an XML payload that looks like this. In the header, I set SOAPAction to be http://tempuri.org/ActionOne   which is also the name of the initial XML element in the payload.
I'm using .NET Core 5 and the latest SoapCore NuGet package 1.1.0.29

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <soap:Body>
        <ActionOne xmlns="http://tempuri.org/">
            <oneString>sometext</oneString>
             <twoString>sometext</twoString>
        </ActionOne>
    </soap:Body>
</soap:Envelope>
```

As much as I tried looking at the sample code, the repo, and other contributors when my Service method starts the model is null. My payload is not serialized and does not bind properly it seems. Any suggestions would be appreciated. 

Program.cs
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
namespace SoapCoreLab
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```
Startup.cs
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using SoapCore;
using SoapCoreLab.Services;
namespace SoapCoreLab
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSoapCore();
            services.AddScoped<ISoapService,SoapService>();
            services.AddMvc();
        }
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseWhen(ctx => ctx.Request.Path.Value.Contains("asmx"), app2 =>
            {
                app2.UseRouting();

                app2.UseSoapEndpoint<ISoapService>("/Service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
            });
        }
    }
}
```
ActionOne.cs
```
using System.ServiceModel;

namespace SoapCoreLab.Models
{
    [MessageContract]
    public class ActionOne
    {
        private string _oneString;
        private string _twoString;
        public ActionOne()
        {
        }
        
        [MessageBodyMember]
        public string oneString
        {
	      get
	      {
		      return _oneString;
	      }
	      set
	      {
		      _oneString = value;
	      }
        }

        [MessageBodyMember]
        public string twoString
	{
            get
            {
                return _twoString;
            }
            set
            {
		_twoString = value;
            }
        }
    }
}
```
ISoapService.cs
```
using System.ServiceModel;
using System.Threading.Tasks;

namespace SoapCoreLab.Services
{
    [ServiceContract(Namespace = "http://tempuri.org")]
    public interface ISoapService
    {
        [OperationContract]
        [XmlSerializerFormat(SupportFaults = true)]
        Task ActionOne(Models.ActionOne requestObject);
    }
}
```
SoapService.cs
```
using System.Threading.Tasks;
namespace SoapCoreLab.Services
{
    public class SoapService : ISoapService
    {
        public Task ActionOne(Models.ActionOne requestObject)
        {
           //requestObject is always null  :(
            var string1 = requestObject.oneString;
            var string2 = requestObject.twoString;
            return null;
        }
    }
}
```

**Comment by lvargas99** [comment]
In an effort to try things I looked at another example in the code and tried that. But the result is the same. My request model is null :(
Here is the new code.

Payload I sent using Postman.

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <soap:Body>
        <ActionOne xmlns="http://tempuri.org/">
            <oneString>sometext</oneString>
             <twoString>sometext</twoString>
        </ActionOne>
    </soap:Body>
</soap:Envelope>`

Program.cs
`using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace SoapCoreLab
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}`

Startup.cs
`
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using SoapCore;
using SoapCoreLab.Services;

namespace SoapCoreLab
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSoapCore();
            services.AddScoped<ISoapService,SoapService>();
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseWhen(ctx => ctx.Request.Path.Value.Contains("asmx"), app2 =>
            {
                app2.UseRouting();

                app2.UseSoapEndpoint<ISoapService>("/Service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
            });
        }
    }
}
`
ActionOne.cs

`using System.Runtime.Serialization;

namespace SoapCoreLab.Models
{
    [DataContract]
    public class ActionOne
    {
		[DataMember]
		public string oneString { get; set; }

		[DataMember]
		public string twoString { get; set; }
    }
}`

ISoapService.cs

`using System.ServiceModel;
using System.Threading.Tasks;

namespace SoapCoreLab.Services
{
    [ServiceContract]
    public interface ISoapService
    {
        [OperationContract]
        Task ActionOne(Models.ActionOne requestObject);
    }
}`

SoapService.cs

```
using System.Threading.Tasks;
namespace SoapCoreLab.Services
{
    public class SoapService : ISoapService
    {
        public Task ActionOne(Models.ActionOne requestObject)
        {
            var string1 = requestObject.oneString;
            var string2 = requestObject.twoString;
            return null;
        }
    }
}
```

**Comment by andersjonsson** [comment]
Not sure but I'm guessing that the namespace is to blame.
```
<ActionOne xmlns="http://tempuri.org/">
    <oneString>sometext</oneString>
    <twoString>sometext</twoString>
</ActionOne>
```

Try to remove `xmlns="http://tempuri.org/"` or to specify the namespace in your ServiceContract-attribute:
`[ServiceContract(Namespace = "http://tempuri.org/")]`

If that doesn't work I'd try changing the name of the request object, just to see if there is a bug when the operation and the parameter have the same name.


Also, when using XmlSerializer you don't need to use `[DataContract]` or `[DataMember]` on your classes, but I don't think they do any harm either.

**Comment by lvargas99** [comment]
Thanks @andersjonsson  I tried everything it seems.   Interestingly removing xmlns="http://tempuri.org/" from the payload results in a fault saying that it expects namespace xmlns="http://tempuri.org/". Does that mean this is the default namespace? I added it back to the payload without specyining it in the ServiceContract. That at least results in my Action method executing. However, no luck in the request object populating.  I also noticed the Action in the header is not used by default as having it or not having it did nothing different. The Action method is strictly tied to the first XML element inside the body.  I can't figure out how is the name of the first element also tied to the response Object.  As you suggested I changed the class name for the request object to be different than the Action name  but it made no difference in populating the request Object. It is still null.  This shouldn't  be this tricky right? I'll try more things. Maybe I need a middleware to extract the object from the payload. But I'm thinking this should be regular behaviour of a soap server.  Thanks for your time.

**Comment by lvargas99** [comment]
Made a little progress and I now get a valid request object and it's not null. However its two properties are null :(  I tried both XMlSerializer and DataContractSerializer on UseEndPoints.  By trying MessageContract  I can now have the server respond to the header Action and call that method    SOAPAction = http://tempuri.org/ActionOne and there is no problem having the action be the same name as the initial element in the XML

Here is the code

Payload I send via Postman with header    SOAPAction = http://tempuri.org/ActionOne
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <soap:Body>
        <ActionOne xmlns="http://tempuri.org/">
            <oneString>sometext</oneString>
             <twoString>sometext</twoString>
        </ActionOne>
    </soap:Body>
</soap:Envelope>
```



ActionOne.cs
```
using System.ServiceModel;

namespace SoapCoreLab.Models
{
    [MessageContract(IsWrapped = false)]
    public class ActionOne
    {
        [MessageBodyMember]
        public string oneString { get; set; }

        [MessageBodyMember]
        public string twoString { get; set; }	
    }
}

```
ISoapService.cs
```
using SoapCoreLab.Models;
using System.ServiceModel;

namespace SoapCoreLab.Services
{
    [ServiceContract(Namespace = "http://tempuri.org")]
    public interface ISoapService
    {
        [OperationContract]
        [XmlSerializerFormat(SupportFaults = true)]
        ActionOne ActionOne( ActionOne requestObject);
    }
}
```

SoapService.cs
```
using SoapCoreLab.Models;
using System;
namespace SoapCoreLab.Services
{
    public class SoapService : ISoapService
    {
        public ActionOne ActionOne(ActionOne requestObject)
        {
            Console.WriteLine("ActionOne String: {0}, String: {1}", requestObject.oneString, requestObject.twoString);
            return requestObject;
        }
    }
}
```

**Comment by andersjonsson** [comment]
I would guess that SoapCore interprets your <ActionOne>-tag as the action.
Try not sending the header and see if you get the same result.

If I were you I'd fetch the source and set up a test case that's identical to yours. Then debug through SoapEndpointMiddleware and see if you can grasp what's going on

**Comment by lvargas99** [comment]
Hi @andersjonsson, took your advice and cloned the code, and created a test with a payload similar to what I need. Turns out that to be able to deserialize a payload where there is one element with a number of child elements one needs to create one class for the parent element and another class for the children elements. Then the request object is basically an object that contains another object and that object's properties contain the values of your payload.  Here is the code so it can help someone else in the future. Thanks for the tips.

Payload: I sent it using Postman and added a header in postman :  SOAPAction = http://tempuri.org/ActionOne

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"  >
    <soap:Body>
        <ActionOne xmlns="http://tempuri.org">
            <OneString>sometext</OneString>
            <TwoString>sometext</TwoString>
        </ActionOne>
    </soap:Body>
</soap:Envelope>
```
Program.cs
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace SoapCoreLab
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```
Startup.cs
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using SoapCore;
using SoapCoreLab.Services;

namespace SoapCoreLab
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSoapCore();
            services.TryAddScoped<ISoapService,SoapService>();
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseSoapEndpoint<ISoapService>("/Service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
        }
    }
}
```
ActionOneWrapper.cs  This is the class needed for the main payload element.
```
using System.ServiceModel;

namespace SoapCoreLab.Models
{
    [MessageContract(IsWrapped = false)]
    public class ActionOneWrapper
    {
        [MessageBodyMember]
        public ActionOneDetails ActionOne { get; set; }	
    }
}

```
ActionOneDetails.cs  This is the class for the interior elements in the XML

```
using System.Runtime.Serialization;

namespace SoapCoreLab.Models
{
    [DataContract]
    public class ActionOneDetails
    {
        [DataMember]
        public string OneString { get; set; }

        [DataMember]
        public string TwoString { get; set; }
    }
}

```
ActionOneResponse.cs   Class for response values and validation

```
using System.ServiceModel;

namespace SoapCoreLab.Models
{
    public class ActionOneResponse
    {
        [MessageBodyMember]
        public string OneString { get; set; }

        [MessageBodyMember]
        public string TwoString { get; set; }
    }
}

```
ISoapService.cs   Service interface 
```
using SoapCoreLab.Models;
using System.ServiceModel;

namespace SoapCoreLab.Services
{
    [ServiceContract(Namespace = "http://tempuri.org")]
    public interface ISoapService
    {
        [OperationContract]
        [XmlSerializerFormat(SupportFaults = true)]
        ActionOneResponse ActionOne( ActionOneWrapper requestObject);
    }
}

```

SoapService.cs  Service class

```
using SoapCoreLab.Models;
using System.ServiceModel;

namespace SoapCoreLab.Services
{
    [ServiceContract(Namespace = "http://tempuri.org")]
    public interface ISoapService
    {
        [OperationContract]
        [XmlSerializerFormat(SupportFaults = true)]
        ActionOneResponse ActionOne( ActionOneWrapper requestObject);
    }
}

```
