### ISSUE TITLE
How to change the namespace prefix with the option XmlNamespacePrefixOverrides

### ISSUE THREAD

**Issue by BernhardJ** [DigDes/SoapCore#880]
My question is: How can I change the prefix in a soap response?

My shortend response body looks like:

```xml
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="http://www.w3.org/2005/08/addressing">
    <s:Body>
        <GetAllResponse xmlns="https://localhost:8083/ws/">
            <GetAllResult xmlns:d4p1="http://schemas.datacontract.org/2004/07/WSSnipp" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                <d4p1:Items>
                    <d4p1:Item>
                        <d4p1:Id>1102</d4p1:Id>
                    </d4p1:Item>
                </d4p1:Items>
            </GetAllResult>
        </GetAllResponse>
    </s:Body>
</s:Envelope>
```

I wanted to replace the d4p1 with b

```xml
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:a="http://www.w3.org/2005/08/addressing">
    <s:Body>
        <GetAllResponse xmlns="https://localhost:8083/ws/">
            <GetAllResult xmlns:b="http://schemas.datacontract.org/2004/07/WSSnipp" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                <b:Items>
                    <b:Item>
                        <b:Id>1102</b:Id>
                    </b:Item>
                </b:Items>
            </GetAllResult>
        </GetAllResponse>
    </s:Body>
</s:Envelope>
```

I tried to add an XmlNamespaceManager and set the XmlNamespacePrefixOverrides property:

```c#
	var nsmSnipp = new XmlNamespaceManager(new NameTable());
	nsmSnipp.AddNamespace("b", "http://schemas.datacontract.org/2004/07/WSSnipp");
	...
	app.UseEndpoints(endpoints =>
	{
		endpoints.UseSoapEndpoint<ISnipp>(options =>
		{
			options.Path = "/Snipp.svc";
			options.EncoderOptions = new SoapEncoderOptions[] { new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap12WSAddressingAugust2004 } };
			options.UseBasicAuthentication = true;
			options.CaseInsensitivePath = true;
			options.XmlNamespacePrefixOverrides = nsmSnipp;
		})
	...
```

But this does not change the output as expected. Or is this property for something else?

I hope this channel is the right place to ask such questions.

I use .NET 6 with SoapCore version 1.1.0.29

**Comment by andersjonsson** [comment]
That should work. I use XmlNamespacePrefixOverrides like that, and it works.

I recommend cloning the repo and making a unit test that you can debug. 
Start here: https://github.com/DigDes/SoapCore/blob/39342caab85260526ff858ff1241c2a356742a55/src/SoapCore/SoapEndpointMiddleware.cs#L514

**Comment by andersjonsson** [comment]
Aah, I see now. Seems like XmlNamespacePrefixOverrides won't work for modifying namespaceprefixes on your response objects. It only works for the envelope and the meta document.

It should be possible to fix though, if you feel up for it.
ServiceBodyWriter (https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore/ServiceBodyWriter.cs) is the place to start.
You would need to pass the namespacemanager to that class, and into the different serialization-helpers later on.

Another alternative is to check out the options around xmlserialization, to see if you can specify a preferred prefix there, somehow.
