### ISSUE TITLE
SoapCore WCF program doesn't work with async with CancellationToken

### ISSUE THREAD

**Issue by alexandruchirita4192** [DigDes/SoapCore#884]
Hi,

The problem is that `CancellationToken` is not ignored for any serializer and there's no way to ignore the cancellation token in WSDL:
* for `SoapSerializer.XmlSerializer` serializer we get exception trying to serialize `CancellationToken`:
![image](https://user-images.githubusercontent.com/34884567/177485394-73f5896a-ad09-44ae-b27d-2123964edd23.png)
* for `SoapSerializer.DataContractSerializer` serializer we get `CancellationToken` serialized in WSDL but that shouldn't be shown:
![image](https://user-images.githubusercontent.com/34884567/177485781-43805997-f508-47c6-bfd1-468744bd006d.png)

I have the following problem exposed as best as possible at the link below and solved by myself with a workaround by removing the `CancellationToken` entirely:
https://stackoverflow.com/questions/72783426/soapcore-wcf-c-sharp-program-using-xmlserializer-doesnt-create-the-wsdl-with-as

Using `CancellationToken` in async methods is a best practice to be able to stop requests in process, stop consuming resources in servers, and so on.

Thank you!

**Comment by andersjonsson** [comment]
There is no support for this scenario right now.
You are welcome to submit a PR if you feel like giving it a shot yourself
