### ISSUE TITLE
error end of "wsp:Policy" element in WSDL

### ISSUE THREAD

**Issue by LadislavSmid** [DigDes/SoapCore#886]
in the current version 1.1.0.30
"wsp:Policy" element  is not ending before "wsdl:types" element  - the element is closing at the end of the wsdl

` <wsp:Policy p10:Id="BasicHttpBinding_IConditionalPrintingService_IConditionalPrintingService_policy" xmlns:p10="wsu">`
`    <wsp:ExactlyOne>`
`      <wsp:All>`
`        <http:BasicAuthentication>`
`          <wsaw:UsingAddressing xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" />`
`        </http:BasicAuthentication>`
`      </wsp:All>`
`    </wsp:ExactlyOne>`
`    <wsdl:types>`
...
`    </wsdl:service>`
`  </wsp:Policy>`
`</wsdl:definitions>`

**the error is probably in the class "MetaMessage" rows 72 - 84. 
5 elements open but only 4 close**

if (_hasBasicAuthentication)
			{
				writer.WriteStartElement("Policy", Namespaces.WSP_NS);
				writer.WriteAttributeString("Id", _xmlNamespaceManager.LookupPrefix(Namespaces.WSU_NS), $"{_bindingName}_{_service.GeneralContract.Name}_policy");
				writer.WriteStartElement("ExactlyOne", Namespaces.WSP_NS);
				writer.WriteStartElement("All", Namespaces.WSP_NS);
				writer.WriteStartElement("BasicAuthentication", Namespaces.HTTP_NS);
				writer.WriteStartElement("wsaw", "UsingAddressing", Namespaces.WSAW_NS);
				writer.WriteEndElement();
				writer.WriteEndElement();
				writer.WriteEndElement();
				writer.WriteEndElement();
			}

**Comment by andersjonsson** [comment]
If you feel up for it, please submit a PR with a fix and a unit test that verifies the fix. We'll get it merged as soon as possible

**Comment by WillTartak** [comment]
This is still happening in 1.1.0.32. Unfortunately, I don't have time to submit a PR. For now I'm rolling back to 1.1.0.29.

**Comment by andersjonsson** [comment]
Fixed in 1.1.0.33

**Comment by WillTartak** [comment]
I am happy to report I upgraded to 1.1.0.33 and it is working as expected.

**Comment by andersjonsson** [comment]
Thank you for confirming
