### ISSUE TITLE
Soap Response with xml declaration

### ISSUE THREAD

**Issue by sebastian-arz** [DigDes/SoapCore#887]
We are using SoapCore, and it works just fine, except for one problem.

In our Soap Response there is no XML Header like
`<?xml version="1.0" encoding="utf-8"?>`
in the first line.

This leads to Errors with some of our Customers.

How can i add the xml declaration line?

**Comment by andersjonsson** [comment]
This can be specified on the endpoint:

```
app.UseSoapEndpoint<ServiceType>((opt) =>
{
	opt.Path = $"/MyService.asmx";
	opt.OmitXmlDeclaration = false;
})
```
