### ISSUE TITLE
How to add an endpoint for the netHttpBinding

### ISSUE THREAD

**Issue by jhughesjha** [DigDes/SoapCore#890]
Can you provide steps necessary to add support for the netHttpbinding with binary encoding? It looks like we would need to create a custom MessageEncodingBindingElement and something similar to WCF's BinaryMessageEncoderFactory but not sure how to get these configured into soapcore.

**Comment by andersjonsson** [comment]
I think that would require quite a bit of work. You are, of course, very welcome to give it a shot and submit a PR.

I suggest forking the repository and getting familiar with the source code. I find that debugging through a unit test helps to get a general sense of the request/response flow.
