### ISSUE TITLE
Need to match request from older wcf  any thoughts help

### ISSUE THREAD

**Issue by uchinago** [DigDes/SoapCore#892]
I am trying to replace existing wcf with soapcore but all requests are null.  

I have successfully used this for other services,  however this one seems to be stumping me.
c# .net 5 is my target right now

What should the interface look like...  as long as i don't break the existing users,  I can modify it however I need to...
the current interface for this operation is
_[OperationContract( IsTerminating = false, IsInitiating = true, IsOneWay = false,	AsyncPattern = false,
			Action = "FindMember",	ProtectionLevel = ProtectionLevel.None
		)]
FindMemberResponse FindMember(FindMemberRequest request);_

When using SoapUI  here is what a current request looks like

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:bci="http://bci.member.model/bci" 
xmlns:bci1="http://BCI.Member.Model/BCI">
   <soapenv:Header/>
   <soapenv:Body>
      <bci:FindMemberRequest>
         <bci:BirthDate>1953-04-23T19:49:45</bci:BirthDate>
        <bci:EnrolleeID>99999999</bci:EnrolleeID>
         <bci:EnvironmentName>TEST04_SYBASE</bci:EnvironmentName>
         <bci:Gender>Male</bci:Gender>
         <bci:GroupID>84848484</bci:GroupID>
         <bci:Name>
            <bci1:First>First</bci1:First>
            <bci1:Last>Last</bci1:Last>
            <bci1:Middle>Middle</bci1:Middle>
         </bci:Name>
      </bci:FindMemberRequest>
   </soapenv:Body>
</soapenv:Envelope>

partial file to demonstrate what the class looks like...  

namespace bci.member.model.bci
{
    [MessageContract(IsWrapped = true, WrapperName = "FindMemeberRequest", WrapperNamespace = "http://bci.member.model/bci")]
    [DataContract(Namespace = "http://bci.member.model/bci")]
    [SerializableAttribute()]
    [XmlType(AnonymousType = true, Namespace = "http://bci.member.model/bci")]
    [XmlRoot(Namespace = "http://bci.member.model/bci", IsNullable = false)]
    public class FindMemberRequest
    {

        [DataMember( Name = "GroupID")]
        [MessageBodyMember()]
        public string GroupID { get; set; }

**Comment by andersjonsson** [comment]
Not sure I understand correctly. Are you having trouble getting requests from existing clients to work? 
If you need to keep supporting existing payloads, that doesn't work out of the box, one option could be to rewrite the payload before it hits the service endpoint. 
See this issue https://github.com/DigDes/SoapCore/issues/844 for some pointers
