### ISSUE TITLE
Implement multiple interfaces same endpoint

### ISSUE THREAD

**Issue by etboy-b** [DigDes/SoapCore#893]
Is it possible to register multiple interfaces on the same endpoint?
The code sample below doesn't work
app.UseSoapEndpoint<ServiceContractA,ServiceContractB>("/ServicePath.asmx", new SoapEncoderOptions());

**Comment by andersjonsson** [comment]
That scenario is not supported and I don't think it can be support. It could result in conflicting namespaces, duplicate actions etc.

You'll have to combine both of them, if it's important to use the same endpoint

**Comment by Refactoring** [comment]
@etboy-b 
Whether this treatment can achieve your needs?
```
[ServiceContract]
public interface IServiceContract : IServiceContractA, IServiceContractB
{
}


[ServiceContract]
public interface IServiceContractA: 
{
}


[ServiceContract]
public interface IServiceContractB: 
{
}

app.UseSoapEndpoint<IServiceContract>("/ServicePath.asmx", new SoapEncoderOptions());
```
