### ISSUE TITLE
SoapEncoderOptions[] is not working

### ISSUE THREAD

**Issue by whocarescode** [DigDes/SoapCore#899]
I tried to use this property to set two soap encoder options to accept both soap11 and soap12 requests like following :
`endpoints.UseSoapEndpoint<helloworld>(opt =>
        {
            opt.OmitXmlDeclaration = false;
            opt.Path = "/helloworld.asmx";
            opt.CaseInsensitivePath = true;
            opt.EncoderOptions = new[] {
                    new SoapEncoderOptions() { MessageVersion = System.ServiceModel.Channels.MessageVersion.Soap11, WriteEncoding = System.Text.Encoding.UTF8 },
                    new SoapEncoderOptions() { MessageVersion = System.ServiceModel.Channels.MessageVersion.Soap12WSAddressing10, WriteEncoding = System.Text.Encoding.UTF8 }
            };
            opt.SoapSerializer = SoapSerializer.XmlSerializer;
        });`

But it always assigns the first one to the service.  It works fine with Soap11 requests and error out with soap12. When i change the order, The soap12 requests works fine and soap11 request error out.

I get below error:
The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages.

**Comment by andersjonsson** [comment]
I had a similar problem. When a client calls a soap1.2 service they are supposed to use the content-type "application/soap+xml". That is not always the case though...

I fixed that by adding a middleware that checks if there is a soap1.2 envelope in the payload and if so, corrects the content-type.

The order of encoders are Soap11 first and Soap12 second

```
                        const string Soap12NS = "http://www.w3.org/2003/05/soap-envelope";

			app.Use(async (context, next) =>
			{
				if (context.Request.Method == "POST")
				{
					//This line allows us to set the reader for the request back at the beginning of its stream.
					context.Request.EnableBuffering();

					//We convert the byte[] into a string using UTF8 encoding...
					var bodyAsText = Encoding.UTF8.GetString(await context.Request.Body.ReadFullyAsync());

					try
					{
						var xdoc = XDocument.Parse(bodyAsText);

						bodyAsText = xdoc.ToString();
						context.Request.Body = new MemoryStream(Encoding.UTF8.GetBytes(bodyAsText));

						//Upgrade Content-Type if Envelope is Soap1.2
						if (context.Request.Headers["Content-Type"] != "application/soap+xml")
						{
							var envelope = xdoc.Descendants().FirstOrDefault(x => x.Name.LocalName == "Envelope");
							if (envelope != null && envelope.Name.ToString().Contains(Soap12NS))
							{
								context.Request.Headers["Content-Type"] = "application/soap+xml";
							}
						}

					}
					catch
					{ }

					context.Request.Body.Position = 0;
				}

				await next();
			}
```

**Comment by whocarescode** [comment]
@andersjonsson thanks, this fixed the issue.
