### ISSUE TITLE
SchemaFolder nested structure

### ISSUE THREAD

**Issue by GabrieleGuelfi** [DigDes/SoapCore#902]
I have a SchemaFolder that contains nested folder with more .xsd files inside, it can be summarized as follows:

![SoapSchemaFolder](https://user-images.githubusercontent.com/37705386/190983299-6feeaa32-1af5-4b8b-b7a6-8a25006d6d02.png)

Trying to access one of TypesA-D.xsd files at the “http://localhost:3000/Service.ws?xsd&name=FolderA/FolderB/TypesB.xsd”, returns the following error everytime:

![SoapSchemaException](https://user-images.githubusercontent.com/37705386/190983387-a6c8a542-3c2f-4c30-ad06-b07306fb208b.png)

I think it is raised by the following code: 
```
string xsdfile = httpContext.Request.Query["name"];
if (string.IsNullOrEmpty(xsdfile) || Path.GetFileName(xsdfile) != xsdfile)		{
	throw new ArgumentNullException("xsd parameter contains illegal values");
}
```
I tried to put every xsd file directly inside the schemaFolder and it works, unfortunately the folder structure is made mandatory by the customer and I cannot change it.

I would like to ask if there is any reason for this restriction and eventually add the possibility to have more folders inside the schema one.

Thanks!

**Comment by andersjonsson** [comment]
the if-statement is commented with "Check to prevent path traversal", so I assume that the restriction exists to prevent "../" and such, that could allow an attacker to access files outside of the xsd-path.

If you feel up for it you are more than welcome to fork the repo and add support for sub-directories. Should be possible to still have safeguards against path traversal by checking that the file exists within the xsd-directory (or its sub-directories)
