### ISSUE TITLE
XmlNode argument always null

### ISSUE THREAD

**Issue by shustrenko** [DigDes/SoapCore#908]
Hi, I am trying to create the following service which expects to receive an envelope body as an argument. The problem that infoReq argument always comes null in the service method. What can the problem here?

```
[ServiceContract]
public interface ITestService
{
    [OperationContract]
    public XmlNode GetInfo(XmlNode infoReq);
}

public class GenericService : IGenericService
{
    public XmlNode GetInfo(XmlNode infoReq)
    {
        return infoReq;
    }
}
```

using XmlSerializer
```
endpoints.UseSoapEndpoint<ITestService>("/TestService.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
```

sample of xml which i pass from SoapUI

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetInfo>
         <!--Optional:-->
         <tem:infoReq>
            <test>string</test>
            <tem:Object/>
         </tem:infoReq>
      </tem:GetInfo>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by andersjonsson** [comment]
My guess is that the deserialization in SoapCore simply can't handle deserialization to XmlNode.

If I were you I'd fork the repo and set up a test case for that. That way you can debug into the deserialization and see what happens.
You are very welcome to ask specific questions if you run into issues, and a PR with a fix would be appreciated!

This is the way I got started contributing to SoapCore. I had a need for specific serialization and wsdl-fixes, so I added them myself and sent PR's

**Comment by shustrenko** [comment]
I was able to reproduce the issue with a next sample code. It uses almost same approach what method SoapCore.SoapEndpointMiddleware.GetRequestArguments does. 
With empty namespace parameterNs ="" deserializer returns not null value. But if i set not empty namespace that Deserializer returns awlays null. Any idea?


```
        private static void TestDeserialization()
        {
            var parameterNs = "http://mynamespace/";
            string inputXml;
            if (string.IsNullOrEmpty(parameterNs))
            {
                inputXml = "<GetInfo>";
            }
            else
            {
                inputXml = $@"<GetInfo xmlns=""{parameterNs}"">";
            }

            inputXml += @"
<infoReq>
<MyClass>
<child1>foo</child1>
<child2>bar</child2>
</MyClass>
</infoReq>
</GetInfo>";

            var operationName = "GetInfo";
            var parameterName = "infoReq";

            var reader = XmlReader.Create(new StringReader(inputXml));
            var msg = Message.CreateMessage(MessageVersion.Soap11, $"{parameterNs}{parameterName}", reader);

            XmlDictionaryReader xmlReader = msg.GetReaderAtBodyContents();
            xmlReader.ReadStartElement(operationName, parameterNs);
            xmlReader.MoveToStartElement(parameterName, parameterNs);

            XmlSerializer serializer
                = new XmlSerializer(typeof(XmlNode), null, Array.Empty<Type>(), new XmlRootAttribute(parameterName), parameterNs);

            var newInstance = (XmlNode)serializer.Deserialize(xmlReader);

            Assert.True(string.IsNullOrEmpty(parameterNs) ? newInstance != null : newInstance == null);
        }
```

**Comment by andersjonsson** [comment]
I'm guessing that your issue is tied to the fact that the parameter-xml can look whatever way.
XmlDeserialization is sensitive when it comes to namespaces.

I'd try skipping deserialization and just use something like
```
var xmlDoc = new XmlDocument();
xmlDoc.LoadXml(inputXml);
var xmlNode = xmlDoc.FirstChild;
```

If that works you can try adding a special case for XmlNode to DeserializeObject 
https://github.com/DigDes/SoapCore/blob/10d4464aef2bc663250d89691ab80ec083ae42b5/src/SoapCore/SerializerHelper.cs#L75-L94
It should work like the case for Stream, but then read a string from the xmlreader and load it into an XmlNode.

I haven't tried this myself. Just making educated guesses.


Just to be clear. Will the xml passed to GetInfo vary in "shape"? Otherwise you should just make a regular object for the parameter and skip the XmlNode.

**Comment by shustrenko** [comment]
> Just to be clear. Will the xml passed to GetInfo vary in "shape"? Otherwise you should just make a regular object for the parameter and skip the XmlNode.

yes, the  xml passed to GetInfo will vary in the shape. I tried same approach using this sample https://learn.microsoft.com/en-us/previous-versions/dotnet/articles/aa480498(v=msdn.10)?redirectedfrom=MSDN#the-power-of-xmlelement in the .net 4.5 web application with .asmx webservice. And it works fine, i mean that argument comes not null.

>It should work like the case for Stream, but then read a string from the xmlreader and load it into an XmlNode.

thanks for the tips. i will try it
