### ISSUE TITLE
app.UseSoapEndpoint<T> is ambiguous when SoapSerializer is provided

### ISSUE THREAD

**Issue by moffitj** [DigDes/SoapCore#909]
I'd like to pass SoapSerializer.XmlSerializer to WebApplication.UseSoapEndpoint<T>, but when I add the argument to the call I get the following error:

This works:
`app.UseSoapEndpoint<Ping>("/ping.asmx", new SoapEncoderOptions());`

Specifying the serializer causes the following error:
`app.UseSoapEndpoint<ServiceReference.OD_ServerSoap>("/ping.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);`
`app.UseSoapEndpoint<ServiceReference.OD_ServerSoap>("/ping.asmx", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);`

```
The call is ambiguous between the following methods or properties: 
'SoapEndpointExtensions.UseSoapEndpoint<T>(IApplicationBuilder, string, SoapEncoderOptions, SoapSerializer, bool, ISoapModelBounder, WsdlFileOptions, bool, bool)' and 
'SoapEndpointExtensions.UseSoapEndpoint<T>(IEndpointRouteBuilder, string, SoapEncoderOptions, SoapSerializer, bool, ISoapModelBounder, WsdlFileOptions, bool, bool)'
```

It looks like SoapEndpointExtensions defines extension methods for both IApplicationBuilder and IEndpointRouteBuilder, and Microsoft.AspNetCore.Builder.WebApplication implements them both:

`public sealed class WebApplication : IHost, IDisposable, IApplicationBuilder, IEndpointRouteBuilder, IAsyncDisposable`

What is the expected way around this? The extension methods are in the same namespace which takes away the ways I know to solve this.

thanks

**Comment by andersjonsson** [comment]
Three are (at least) two options for you here.

1. Change the input parameter for the Configure-method from WebApplication app to IApplicationBuilder app (that's the way it's set up in my web services)
2. Cast app to one of the interfaces, something like `((IApplicationBuilder)app).UseSoapEndpoint...`
