### ISSUE TITLE
Nuget publish doesn't work

### ISSUE THREAD

**Issue by andersjonsson** [DigDes/SoapCore#913]
Publish of 1.1.0.33 to nuget failed, seemingly because of the api key.

@kotovaleksandr Could you have a look?

**Comment by kotovaleksandr** [comment]
Hi! Fixed:)

**Comment by kotovaleksandr** [comment]
https://www.nuget.org/packages/SoapCore/1.1.0.33

**Comment by andersjonsson** [comment]
Great, thanks! 😄

**Comment by andersjonsson** [comment]
@kotovaleksandr it's that time again. Could you update the api-key?

**Comment by kotovaleksandr** [comment]
Easy!
[9](https://github.com/DigDes/SoapCore/actions/runs/24344052445/job/71127545558#step:4:159)
  Successfully created package '/__w/SoapCore/SoapCore/nupkg/SoapCore.1.2.1.13.nupkg'.
Pushing SoapCore.1.2.1.13.nupkg to 'https://www.nuget.org/api/v2/package'...

**Comment by andersjonsson** [comment]
Thank you!
