### ISSUE TITLE
Parameter binding in SoapCore

### ISSUE THREAD

**Issue by hungvo2010** [DigDes/SoapCore#914]
How can I parse an XML param from client (postman) and return SOAP message?

**Comment by andersjonsson** [comment]
I'm confused. Parsing XML-parameters from SOAP requests and returning SOAP messages as response is the core function of SoapCore.
Take a look at
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/ITestService.cs
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/TestService.cs
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/Startup.cs
https://github.com/DigDes/SoapCore/blob/develop/src/SoapCore.Tests/IntegrationTests.cs

for some simple examples of how it's done

**Comment by hungvo2010** [comment]
But how can I post a SOAP message (from POSTMAN for example) to work with ComplexParam like ComplexModelInput?

**Comment by andersjonsson** [comment]
There is an example at https://learning.postman.com/docs/sending-requests/soap/making-soap-requests/
That example is for SOAP 1.1

If you need SOAP 1.2 the request should look more like
```
<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Body>
    <MethodName xmlns="http://www.mynamespace.com/">
      <param1>1</param1>
      <param2>hello</param2>
    </MethodName>
  </soap12:Body>
</soap12:Envelope>
```
Note that for SOAP 1.2 you have to set the Content-Type header to `application/xml`

**Comment by hungvo2010** [comment]
I have tried but got an error: 
`System.InvalidOperationException: Incorrect Content-Type: application/xml                                                  at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()                                                            at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()  `
Could you help me figure out how to fix it?

**Comment by andersjonsson** [comment]
That error means that you're not hitting your ServiceEndpoint at all.
I can't help you without knowing more. Could you please verify that you've registered the soapendpoint with a call to `UseSoapEndpoint` in startup, and that you have the correct url in postman.
If you hit the same endpoint in a browser, do you see the wsdl document? It shows up as a big blob of xml

**Comment by hungvo2010** [comment]
Thank you for helping me. My request has reach ServiceEndpoint, however the request body:
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ComplexParam xmlns="http://com.vng.zing.media/">
            <test>
                <ComplexModel xmlns="http://com.vng.zing.media/">
                    <StringProperty>test</StringProperty>
                    <IntProperty>124</IntProperty>
                </ComplexModel>
            </test>
        </ComplexParam>
    </soap:Body>
</soap:Envelope>
```
can not be deserialized to object of complex type (described below):
```public class ComplexModel
	{
		public ComplexModel(string v1, int v2)
		{
			StringProperty = v1;
			IntProperty = v2;
		}

		public ComplexModel()
		{
			StringProperty = "ComplexModel";
			IntProperty = 123;
		}

		[DataMember]
		public string StringProperty { get; set; }

		[DataMember]
		public int IntProperty { get; set; }
	}
```
In an endpoint in service:
```
public ComplexModel ComplexParam(ComplexModel test)
```
I find that test.IntProperty = 123 (the default value in default constructor of ComplexModel).
All the server code, configuration I use is the same as SoapCore.Test of this repo.
Could you help me to deserialize xml to object of complex type? Thank you so much.

**Comment by andersjonsson** [comment]
Not quite sure, but I don't think you need the type in your request

Try

```
<ComplexParam xmlns="http://com.vng.zing.media/">
            <test>
                    <StringProperty>test</StringProperty>
                    <IntProperty>124</IntProperty>
            </test>
</ComplexParam>
```

Otherwise, try to debug a test method of your choice, and set at breakpoint in `SoapEndpointMiddleware.ProcessOperation` (after the call to `ReadMessageAsync`).
You can get the requestbody by calling `requestMessage.CreateBufferedCopy(int.MaxValue).CreateMessage().GetReaderAtBodyContents().ReadInnerXml()`

That way you can see how the payload should look

**Comment by hungvo2010** [comment]
Some of my class (inside dll which provided by third-party) cannot be annotated with DataContract or DataMember. How can I deserialize from SOAP message into object of these class?
I have an idea about using XMLNode or XMLDocument for received such message from incoming request. But the arguments I received was always null. Does SoapCore support any feature to solve this issue?

**Comment by andersjonsson** [comment]
First: You only need DataContract and DataMember if you use DataContractSerializer or if you need to specify stuff, like adding namespaces or changing the name of a member for serialization purposes.
If you use XmlSerializer and don't need to customize stuff in the serialization you should be fine.

There is currently no way to add attributes to a 3rd party class so if you need customized serialization (or are using DataContractSerializer) i would make a class that mirrors the 3rd party class, and make methods to "translate" from one object to the other and back. If it's simple properties you can use something like AutoMapper if you don't want to write the mapping code yourself.
