### ISSUE TITLE
Disable log.LogInformation Receive/Request

### ISSUE THREAD

**Issue by Mahodevs** [DigDes/SoapCore#916]
Cannot disable log.LogInformation each receive/request.
Could this information be changed to log.LogDebug please?
Thanks for all.
Maho

**Comment by andersjonsson** [comment]
It would probably be ok to change that. Maybe we should add a LogLevel-setting to SoapCoreOptions and SoapOptions, just to avoid changing behavior. I would be ok with setting the default to Debug.

A PR would be welcome if you feel up for it.

**Comment by Mahodevs** [comment]
That would be the best approach.
I just wanted to keep the effort as simple as possible, as I think changing this logging level in these places will not pose any problems, only advantages.
Thx and a nice day all.
