### ISSUE TITLE
ASP0014: Suggest using top level route registrations instead of UseEndpoints

### ISSUE THREAD

**Issue by the-enjoyer** [DigDes/SoapCore#929]
Hello, I use .net7 and Rider IDE.
I have this Problem (no stopper) how to fix this problem?

<img width="969" alt="1" src="https://user-images.githubusercontent.com/6857962/208415844-96a2b717-a68a-4f5e-aa7b-34489badf0dd.png">

**Comment by the-enjoyer** [comment]
I trying to write top-level `app.UseSoapEndpoint` but getting error:

> Ambiguous invocation: Microsoft.AspNetCore.Builder.IApplicationBuilder UseSoapEndpoint<IKsunciSoapService>(this Microsoft.AspNetCore.Builder.IApplicationBuilder, string, SoapCore.SoapEncoderOptions, SoapCore.SoapSerializer, bool, SoapCore.Extensibility.ISoapModelBounder, SoapCore.WsdlFileOptions, bool, bool) (in class SoapEndpointExtensions) 
> 
> Microsoft.AspNetCore.Builder.IEndpointConventionBuilder UseSoapEndpoint<IKsunciSoapService>(this Microsoft.AspNetCore.Routing.IEndpointRouteBuilder, string, SoapCore.SoapEncoderOptions, SoapCore.SoapSerializer, bool, SoapCore.Extensibility.ISoapModelBounder, SoapCore.WsdlFileOptions, bool, bool) (in class SoapEndpointExtensions) match

Many overloaded variants of the method. I can't find the right one

**Comment by andersjonsson** [comment]
Try using named parameters to make it unambiguous.
Or use the overload that accepts an `Action<SoapCoreOptions>`.

That's what I do
```
app.UseSoapEndpoint<IMyApiService>(o =>
			{
				o.SoapSerializer = SoapSerializer.XmlSerializer;
				o.Path = "/myapi.asmx";
				//etc
			});
```

**Comment by the-enjoyer** [comment]
Thank You! 
I tried you example, but problem don't go out )).
I want use only the three params, may be has other params witch that no effect?!

<img width="1527" alt="Снимок экрана 2022-12-21 в 10 06 15" src="https://user-images.githubusercontent.com/6857962/208842630-8cbb9d84-96ff-48f7-b162-fcde17d130b1.png">

**Comment by andersjonsson** [comment]
Ah, so the ambiguity is with `app`, not with the method call.
Does it work if you change the line to `((IApplicationBuilder)app).UseSoapEndp...` or `((IEndpointRouteBuilder)app).UseSoapEndp...`?

**Comment by the-enjoyer** [comment]
Yes! Thank You!
