### ISSUE TITLE
As of commit f8a6c21 the build fails for MessageInspectorTests.cs with error CS0117

### ISSUE THREAD

**Issue by awenius** [DigDes/SoapCore#93]
Hello,

when compiling the source code from commit f8a6c21 I get the following build error:

`MessageInspector\MessageInspectorTests.cs(91,7,91,29): error CS0117: "ComplexModelInput" does not contain a definition for "DateTimeOffsetProperty".`

(Translated error message, may not be exactly the original english error message).

Best regards
Andreas

**Comment by kotovaleksandr** [comment]
Fixed in https://github.com/DigDes/SoapCore/commit/362780159ccd141f59fae2226c1c4df5fd41fb36

**Comment by awenius** [comment]
Thanks a lot for the quick fix!

Best regards
Andreas
