### ISSUE TITLE
cant remove function name on xml

### ISSUE THREAD

**Issue by gunduzcagri** [DigDes/SoapCore#933]
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://xxxx.xxx.com/v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <v2:method>
         <!--Optional:-->
         <v2:SorgulamaG>
            <userType>?</userType>
            <!--Optional:-->

```

İ expected  this : 
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://xxxx.xxx.com/v2/">
   <soapenv:Header/>
   <soapenv:Body>
         <v2:SorgulamaG>
            <userType>?</userType>
            <!--Optional:-->
```

**Comment by andersjonsson** [comment]
As far as I know there is no setting in SoapCore to get this result.
However, you could use a SoapMessageProcessor to rewrite the message on the way in and out.

That would make it possible to accept your XML and rewrite it to something that SoapCore likes. And on the way out you can strip the parts that you don't want in your client

See https://github.com/DigDes/SoapCore/issues/844 for example of usage
