### ISSUE TITLE
Manage Http Status Code

### ISSUE THREAD

**Issue by xNout** [DigDes/SoapCore#934]
Hi, would i like customize http status code responses.

When the IFaultExceptionTransformer is executed, i'm trying to set a 400 status code in the message properties.

`public Message ProvideFault(Exception exception, MessageVersion messageVersion, Message requestMessage, XmlNamespaceManager xmlNamespaceManager)
        {
            using IServiceScope provider = scopeFactory.CreateScope();
            
            //calling dependencies...

            DateTime Fecha = DateTime.Now;
            List<ErrorMessage> Errores = new();

            string DescripcionError = "Ocurrio un error interno";
            if (exception?.Source?.Contains("DataContractSerialization") ?? false)
            {
                ReadAndAddInnerExceptions(exception, ref Errores);
                DescripcionError = "XML mal formado";
            }
            else
            {
                // another actions
            }

            object response = requestHandler.Generate(EdocConstants.ERROR_VALIDACIONES_EDOC, Errores);
            

            // status code customization.
            Message message = Message.CreateMessage(messageVersion, null, response);
            message.Properties.Add(HttpResponseMessageProperty.Name, new HttpResponseMessageProperty { StatusCode = HttpStatusCode.BadRequest, StatusDescription = DescripcionError });
            return message;
        }`

But the service always  returns 200 status code. Can Anyone tell me what i'm doing wrong?

**Comment by andersjonsson** [comment]
Even if the message contains a HttpResponseMssageProperty with a statuscode, the StatusCode property in HttpContext never gets set.
You need to set it manually.
`httpContext.Response.StatusCode = statusCode;`

**Comment by xNout** [comment]
> Even if the message contains a HttpResponseMssageProperty with a statuscode, the StatusCode property in HttpContext never gets set. You need to set it manually. `httpContext.Response.StatusCode = statusCode;`
Where can i find HttpContext into IFaultExceptionTransformer?

**Comment by xNout** [comment]
> Even if the message contains a HttpResponseMssageProperty with a statuscode, the StatusCode property in HttpContext never gets set. You need to set it manually. `httpContext.Response.StatusCode = statusCode;`

Where can i find HttpContext into IFaultExceptionTransformer?

**Comment by andersjonsson** [comment]
You could probably accept an IHttpContextAccessor in your IFaultExceptionTransformer, but I haven't tested it.
See https://stackoverflow.com/questions/56902394/accessing-httpcontext-outside-controller-in-net-core for more information
