### ISSUE TITLE
How can I change the wsdl:message, name Input Message default

### ISSUE THREAD

**Issue by xcarlosperu** [DigDes/SoapCore#935]
![image](https://user-images.githubusercontent.com/3187492/227830324-03d936c0-5fba-482b-94fc-5d204daa88a0.png)

**Comment by andersjonsson** [comment]
If you search through closed issues I think you’ll find the solution to your question

**Comment by xcarlosperu** [comment]
I can't find anything, help please, I'll appreciate it
