### ISSUE TITLE
Help me please: whitespaces in result, removes them at the end

### ISSUE THREAD

**Issue by xcarlosperu** [DigDes/SoapCore#936]
I have spaces at the end but when displaying the result it removes them, how can I keep blank spaces at the end

**Comment by andersjonsson** [comment]
Not sure what you mean by "displaying the result". If you check the result in Postman or some similar solution, is the whitespace still there?
As far as I know there is nothing in SoapCore that trims whitespace from your results.

If the whitespace is removed by SoapCore I think you should fork the repo and do some experiments. Set up a unit test that returns the same result as your code and try to figure out where the whitespace is removed.
