### ISSUE TITLE
No way to get rid of new line characters in response

### ISSUE THREAD

**Issue by alsommer1** [DigDes/SoapCore#938]
Inside SoapEndpointMiddleware.cs class there is XmlWriterSettings. 
Probably changing NewLineHandling might remove \r\n symbols in response.
Would be good to have it configurable.

Was not able to find anything similar in SoapEncoderOptions or way to replace Serializer with custom.

**Comment by andersjonsson** [comment]
That sounds reasonable. Feel like submitting a PR?
You can look at #927 or #766 for examples

**Comment by alsommer1** [comment]
Closing this issue. Hopefully PR would be proposed later
