### ISSUE TITLE
WSDL generation fails for Nullable<DateTimeOffset> properties

### ISSUE THREAD

**Issue by gcsizmadia** [DigDes/SoapCore#941]
`DateTimeOffset` properties work well but unfortunately, `Nullable<DateTimeOffset>` / `DateTimeOffset?` properties cause WSDL generation to fail.

I found a comment in a closed issue that says the same:

_Originally posted by @drabb1956 in https://github.com/DigDes/SoapCore/issues/62#issuecomment-495396922_

**Comment by andersjonsson** [comment]
Yup. I can see in both MetaBodyWriter.cs and MetaWCFBodyWriter.cs that the special case for DateTimeOffset occurs before a check for nullable.

Feel like submitting a PR? If you fork the repo and search for `typeof(DateTimeOffset).IsAssignableFrom(type)` you should find the right places quite easily.
