### ISSUE TITLE
ServiceContract Namespace issue

### ISSUE THREAD

**Issue by zemraza** [DigDes/SoapCore#946]
I am useing SoapCore in asp.net core 6 My code sample given below

Issue is if i am remove  domain name from **_[ServiceContract(Namespace = "My Domain name Here")]_** so soap not respond i need add namespace dynamically set from **appsettings.json** 

[ServiceContract(Namespace = "My Domain name Here")]
	public **interface ImobileService**
	{
	        [OperationContract]
		string appLogin(string UserName, string UserPassword);
	}
_______________________________________________________________________________________________________________

public class **mobileserves : ImobileService**
    {
        Data.ApplicationDbContext _context;
        public mobileserves(IServiceProvider serviceProvider)
        {
            _context = serviceProvider.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>();
        }
        
        public string appLogin(string UserName, string UserPassword)
        {
            return "Login successfully";
        }
   }
_______________________________________________________________________________________________________________
**### Program.cs File**

builder.Services.AddSoapCore();
builder.Services.TryAddSingleton<ImobileService, mobileserves>();
var app = builder.Build();

app.UseRouting();
app.UseEndpoints(endpoints =>
{
	endpoints.UseSoapEndpoint<ImobileService>("/Service/mobileapp_service.svc", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);
	endpoints.UseSoapEndpoint<ImobileService>("/Service/mobileapp_service.asmx", new SoapEncoderOptions(), SoapSerializer.XmlSerializer);
});

**Comment by andersjonsson** [comment]
Do I understand you correctly that you want to set the namespace for your service from appsettings.json?
That's not really a question for this forum since it's more a matter of what's possible in C# and dotnet.

I googled for a bit and found this: https://stackoverflow.com/questions/10585886/is-it-possible-to-dynamically-change-namespace-to-servicecontract-during-runtime
Hope it helps.
