### ISSUE TITLE
How to enable Self Closing tags?

### ISSUE THREAD

**Issue by wwdenis** [DigDes/SoapCore#947]
Hello everyone,
In my ASP .NET Web Services application the default behavior is to serialize tags as self closing. (e.g. ```<MyTag MyAttr="123" />```)
When implementing SoapCore, instead I noticed self closing tags are disabled. (e.g. ```<MyTag MyAttr="123"></MyTag>```)

_**Question**: How to enable Self Closing tags?_

- OS: Windows 11 Pro
- Target: .NET 6.0
- SoapCore Version: 1.1.0.38

**Comment by andersjonsson** [comment]
That seems weird. You are more than welcome to submit a PR for this, if you feel like it.
I think it would be ok to change the default behavior in this case

**Comment by wwdenis** [comment]
I will take a look @andersjonsson 
I can open a new issue if needed.
