### ISSUE TITLE
[Question] System.Web.Services.Protocols.SoapDocumentMethodAttribute alternative 

### ISSUE THREAD

**Issue by PaloMraz** [DigDes/SoapCore#950]
[Question] Hello, I am using your nice SoapCore library to help me port some legacy `.asmx` SOAP services that are using the [SoapDocumentMethodAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.web.services.protocols.soapdocumentmethodattribute?view=netframework-4.8.1) quite extensively in order to shape the genereated SOAP responses.

Is there support for some of the SoapDocumentMethodAttribute "aspects" in SoapCore? Could you please give me some hints as to how to proceed in order to customize the SOAP responses generated by your library?

**Comment by andersjonsson** [comment]
As far as I know there is no easy way to accomplish this. If the shaping is somewhat limited you might be able to do what you want with attributes to give hints to the XmlSerializer (like serializing properties as attributes etc.).

If you need more advanced shaping you can use an IMessageInspector2 or an ISoapMessageProcessor. This will, however, require you to parse the outgoing message and build a new one, shaped according to your needs.

I can definitely see advantages to supporting the SoapDocumentMethodAttribute. If you feel up to implementing that support and submitting a PR that would be most welcome

**Comment by PaloMraz** [comment]
@andersjonsson, thank you for your feedback! I have forked the `SoapCore` repo and experimented with a sample solution involving legacy `.asmx` SOAP implementation as well as your modern `SoapCoreMiddleware`-based implementation. The results are summarized [here](https://github.com/PaloMraz/SoapCoreFeaturesExploration). In a nutshell: It would be very difficult to implement all of the aspects of the legacy `SoapDocumentMethodAttribute`. I was not able to implement even the simplest requirement I had: to return a list of objects __not__ wrapped in a `*Result` XML element :-( Therefore, my current thinking is that I would go by the `IMessageInspector2` / `ISoapMessageProcessor` route you suggested in your previous comment.
