### ISSUE TITLE
Different versions of SOAP protocol seems not to work

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [DigDes/SoapCore#951]
I'm porting an old SOAP service to .NET 6 and I was able to see that it supported both SOAP 1.1 and 1.2, so I tried to reproduce it with SoapCore.
I added the soap enpoint like:
```C#
((IApplicationBuilder)app)
    .UseSoapEndpoint<IMyService>
    (
        "/Service.asmx",
        new[]
        {
            new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap12WSAddressingAugust2004, BindingName = "MyServiceSoap12" },
            new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap11, BindingName = "MyServiceSoap" }
        },
        SoapSerializer.XmlSerializer,
        true
    );
```

Using a client like SOAP UI it works, but instead using Insomnia I get:
```
The envelope version of the incoming message (Soap12 (http://www.w3.org/2003/05/soap-envelope)) does not match that of the encoder (Soap11 (http://schemas.xmlsoap.org/soap/envelope/)). Make sure the binding is configured with the same version as the expected messages. (Parameter 'reader')
```

as if it could not use the SOAP 1.2 version for some reason; using the old service works.

How can I solve this?

**Comment by andersjonsson** [comment]
SoapCore doesn't determine soap version based on the envelope but uses Content-Type.

According to the SOAP standard the Content-Type header should be set to "application/soap+xml" for SOAP 1.2 and "application/xml" for SOAP 1.1

This approach works for me when I call my SOAP services with Postman, so it should be the same with Insomnia

**Comment by gabriele-ricci-kyklos** [comment]
@andersjonsson I tried but it's not working with `application/xml`, I get the error above. It works with `application/soap+xml`

**Comment by andersjonsson** [comment]
The error message says that you are sending a Soap 1.2 envelope. So it shouldn't work with `application/xml` since that indicates Soap 1.1
If you want to use soap 1.1 the envelope should look something like
`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">` instead of
`<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope">`

**Comment by gabriele-ricci-kyklos** [comment]
@andersjonsson thank you, it works by changing the definition of s; I'll close the issue
