### ISSUE TITLE
Issues regarding the serialization when upgrading to .NET 7 and SoapCore from v1.0.0 to v1.1.0.36

### ISSUE THREAD

**Issue by nicugorea** [DigDes/SoapCore#956]
I used the SoapCore package since .NET Core 2.1 and gradually upgraded the .NET Core version until .NET 7 where the first issue appeared. The issue was that in the v1.0.0 that I was using, there were these lines of code in the `SoapEndpointMiddleware` class inside `ProcessOperation` method, lines 200-207:
```c#
			//Get the message
#if ASPNET_30
			var requestMessage = await messageEncoder.ReadMessageAsync(httpContext.Request.BodyReader, 0x10000, httpContext.Request.ContentType);
#endif

#if ASPNET_21
			var requestMessage = await messageEncoder.ReadMessageAsync(httpContext.Request.Body, 0x10000, httpContext.Request.ContentType);
#endif
``` 
where the requestMessage is read from the RequestBody in ASPNET_21 and from the BodyReader in ASPNET_30. 

In the same method, at the beginning, we see the following block of code:
```c#
//Reload the body to ensure we have the full message
			var memoryStream = new MemoryStream((int)httpContext.Request.ContentLength.GetValueOrDefault(1024));
			await httpContext.Request.Body.CopyToAsync(memoryStream).ConfigureAwait(false);
			memoryStream.Seek(0, SeekOrigin.Begin);
			httpContext.Request.Body = memoryStream;
``` 
Since the request body was already read, when using the body reader the old stream is used and an error is thrown in ASPNET_30.
Leaving the implementation where the requestMessage is read from the request body solved the issue in .NET 7.

Since I didn't want to mutate the library code, I decided to use the latest version.
When updating the SoapCore package from v1.0.0 to v1.1.0.36 
```
-    <PackageReference Include="SoapCore" Version="1.0.0" />
+   <PackageReference Include="SoapCore" Version="1.1.0.36" />
``` 

```csharp
- app.UseSoapEndpoint<MyContract>(options.Value.ServerRelativeEndpoint, _serverBinding, SoapSerializer.XmlSerializer, caseInsensitivePath: true);

+ app.UseSoapEndpoint<MyContract>(soap =>
{
	soap.Path = options.Value.ServerRelativeEndpoint;
	soap.Binding = _serverBinding;
	soap.SoapSerializer = SoapSerializer.XmlSerializer;
	soap.CaseInsensitivePath = true;
});
```

I noticed some changes in the way the response message is sent while communicating with a .NET application.
v1.0.0
```html
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <MyServiceResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="{namespace}">
            <responseCode>1</responseCode>
            <responseMessage>OK</responseMessage>
        </MyServiceResponse>
    </s:Body>
</s:Envelope>
``` 

v1.1.0.36
```html
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <MyServiceResponse xmlns="{namespace}">
      <responseCode>1</responseCode>
      <responseMessage>OK</responseMessage>
    </MyServiceResponse>
  </s:Body>
</s:Envelope>
```
We can see here that there are some attributes missing from the MyServiceResponse tag.

The second issue that I have is that the same application, when communicating to a Java Spring application, the responses sent to that application are as follows.
v1.0.0
```html
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <MyService xmlns="{namespace}">
            <responseCode>1</responseCode>
            <responseMessage>OK</responseMessage>
        </MyService>
    </s:Body>
</s:Envelope>
``` 

v1.1.0.36
```html
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <MyServiceResponse xmlns="{namespace}">
      <responseCode>1</responseCode>
      <responseMessage>OK</responseMessage>
    </MyServiceResponse>
  <MyService xmlns="{namespace}"/>
  </s:Body>
</s:Envelope>
```
where we can see that the same attributes are missing before and after, and the strange thing is that in v1.0.0 the Response suffix is not present in the MyService tag and in v1.1.0.36 the tag is present with the suffix but there is another element in the body without the suffix but also without children.

Are there any steps that had to be done when upgrading the package that I missed or is there a way to use the latest version of the package but have the same output as in the v1.0.0 ?

**Comment by andersjonsson** [comment]
It might be possible to accomplish the same output, but I'm not sure. A whole lot has changed since 1.0.0

Are the missing xsd and xsi-namespaces in your first example actually causing you trouble? Because they should be inherited anyways (and thus it should work without declaring them again further down in the xml document).

The missing xml declaration can be added by setting `SoapCoreOptions.OmitXmlDeclaration = false`


In the last example I have no idea why you got the ` <MyService xmlns="{namespace}"/>`-tag. Are you saying that the response from SoapCore looks different depending on if it's called from Java Spring or from .NET?

In my experience the output from the latest version works fine from .NET, Java and Php (There might be more languages calling my public legacy apis, but I'm not sure). One might have to fool around a bit with different namespaces etc. though.

**Comment by nicugorea** [comment]
The missing namespaces are not a problem, it's just a difference I could observe that I thought would help identify the changes that generate the inconsistency.

Regarding the `<MyService xmlns="{namespace}"/>`, yes I get it when the Java application is calling the soap and the response contains that element. The expected response from my side would be the <MyService xmlns="{namespace}"/> that will have the content from the previous element
```html
<MyServiceResponse xmlns="{namespace}">
      <responseCode>1</responseCode>
      <responseMessage>OK</responseMessage>
</MyServiceResponse>
```
this means that this element's tag should be `MyService`  instead of `MyServiceResponse` and the next empty element `MyService` should not be present there.
So the final response should be instead of 
```html
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <MyServiceResponse xmlns="{namespace}">
      <responseCode>1</responseCode>
      <responseMessage>OK</responseMessage>
    </MyServiceResponse>
  <MyService xmlns="{namespace}"/>
  </s:Body>
</s:Envelope>
```
should be
```html
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <MyService xmlns="{namespace}">
      <responseCode>1</responseCode>
      <responseMessage>OK</responseMessage>
    </MyService>
  </s:Body>
</s:Envelope>
```

**Comment by andersjonsson** [comment]
Seems to me that `<MyServiceReponse>` is the correct tag. That's at least how all my responses look (and how they looked in the legacy service before moving to SoapCore).

If I were you I'd pull the source and debug through, to see where and why the `<MyService>`-tag is added.

**Comment by nicugorea** [comment]
Alright, thank you, I will close the issue for now, and if there are any issues or details I will come back.
