### ISSUE TITLE
How to include a detail fault message for Exceptions?

### ISSUE THREAD

**Issue by SKO85** [DigDes/SoapCore#961]
Hi,

Is there somewhere documented how to include a detail information on an error. I only see faultcode and faultstring at the moment in the response of the service.

How can I define a class that will contain the details and how to I throw these Exceptions so they are shown with the details section in the response?

Thank you.

**Comment by andersjonsson** [comment]
You can implement your own IFaultExceptionTransformer. Check out https://github.com/DigDes/SoapCore/tree/develop/src/SoapCore.Tests/FaultExceptionTransformer for an example of how it works
