### ISSUE TITLE
XmlSerializer with Guid Type property

### ISSUE THREAD

**Issue by jspmu** [DigDes/SoapCore#962]
Hi,

We are using XmlSerializer with the latest version of SoapCore (v1.1.0.38) to create our soap service. 

When we add a reference to this on visual studio the objects that are type guid are outputted as type string.

When a reference is added to our legacy version of the wsdl (generated old .net framework soap service) outputted them as type guid, both on the wsdl and the reference.

I have tried both with and without the Type option inside XmlElement to see if that would make a difference.
Additionally I have tested with modifying the ClrTypeResolver line 35:
```
    case "Guid":
	return "guid";
```

I can see a lot of differences between the Legacy WSDL and Modern WSDL but don't understand enough to be able to make any modifications.

Legacy WSDL: 
```
<wsdl:definitions xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://webService.com/services" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s1="http://microsoft.com/wsdl/types/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://webService.com/services" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://webService.com/services">
      <s:import namespace="http://microsoft.com/wsdl/types/" />
...
      <s:complexType name="AuthenticationToken">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="sessionGuid" type="s1:guid" />
          <s:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="s:dateTime" />
        </s:sequence>
      </s:complexType>
```

Object Definition:
```
public class AuthenticationToken
{
    [XmlElement(ElementName = "sessionGuid", Type = typeof(Guid))]
    public Guid SessionGuid { get; set; }

    [XmlElement(ElementName = "sessionEndTime")]
    public DateTime SessionEndTime { get; set; }
}
```
New (SoapCore) WSDL:
```
<wsdl:definitions xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:tns="http://webService.com/services" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="IStepXWebService" targetNamespace="http://webService.com/services" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://webService.com/services">
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/System" />
...
      <xsd:complexType name="AuthenticationToken">
        <xsd:sequence>
          <xsd:element minOccurs="1" maxOccurs="1" name="sessionGuid" type="xsd:string" />
          <xsd:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="xsd:dateTime" />
        </xsd:sequence>
      </xsd:complexType>
```

**Comment by andersjonsson** [comment]
I see! That is a microsoft specific type, defined in the namespace http://microsoft.com/wsdl/types/".

Try pulling https://github.com/andersjonsson/SoapCore/tree/add-support-for-datatype-and-namespace
If you add
```
[XmlElement(ElementName = "sessionGuid", DataType = "guid", Namespace = "http://microsoft.com/wsdl/types/")]
public Guid SessionGuid { get; set; }
```
it should, with a bit of luck, work.

That will add the namespace definition directly on the element. To get that namespace definition you can use the XmlNamespaceOverrides on SoapCoreOptions in your Startup method

**Comment by jspmu** [comment]
I have given that a go and that adds the reference seemingly correctly and the type is now System.Guid as hoped, however when I try to do a request which returns the AuthenticationToken object I get the following error from the client:

```
System.ServiceModel.ProtocolException: 'The content type text/plain of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 1024 bytes of the response were: 'System.InvalidOperationException: There was an error reflecting type 'WebServices.SharedResources.AuthenticationToken'.
 ---> System.InvalidOperationException: There was an error reflecting property 'SessionGuid'.
 ---> System.InvalidOperationException: There was an error reflecting type 'System.Guid'.
 ---> System.InvalidOperationException: Value 'guid' cannot be used for the XmlElementAttribute.DataType property. The datatype 'http://www.w3.org/2001/XMLSchema:guid' is missing.
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflec'.'

Inner Exception
WebException: The remote server returned an error: (500) Internal Server Error.
```

**Comment by andersjonsson** [comment]
I see! Apparently DataType is only allowed for default types.
Seems like the namespace `http://microsoft.com/wsdl/types/` only contains Guid so I simply hardcoded for that type.

Could you change the code to 
```
[XmlElement(ElementName = "sessionGuid", Namespace = "http://microsoft.com/wsdl/types/")]
public Guid SessionGuid { get; set; }
```
and see if it works with my updated code?

**Comment by jspmu** [comment]
Hi andersjonsson,

I have pulled your changes on your latest commit to the add-support-for-datatype-and-namespace branch
and tried the following two XmlElement attributes

```
[XmlElement(ElementName = "sessionGuid", Namespace = "http://microsoft.com/wsdl/types/")]
public Guid SessionGuid { get; set; }

[XmlElement(Namespace = "http://microsoft.com/wsdl/types/")]
public Guid SessionGuid { get; set; }
```

With both attempts the wsdl outputs as: 

```
<xsd:complexType name="AuthenticationToken">
<xsd:sequence>
<xsd:element minOccurs="1" maxOccurs="1" name="SessionGuid" type="q1:"/>
<xsd:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
```

And the reference will not be added / updated inside of visual studio I assume because of this, with the error :
![image](https://github.com/DigDes/SoapCore/assets/81692550/854901d7-3f90-4ed5-85ba-af79f46d9b1d)

I also tried with the DataType supplied alongside namespace and ElementName but that behaviour is unchanged from my previous message where I was getting the ProtocolException.

Thank you so much for all of the support you have been giving me with this, it is greatly appreciated.

**Comment by andersjonsson** [comment]
My bad! I forgot to commit my latest changes 🤦‍♂️ 
Sorry about that. Please try again. Without `DataType`

**Comment by jspmu** [comment]
I have tried with your latest changes with the following object:

```
    [XmlElement(ElementName = "sessionGuid", Namespace = "http://microsoft.com/wsdl/types/")]
    public Guid SessionGuid { get; set; }
```

and it does appear to serialize correct inline and the reference is added successfully inside visual studio.
This time however it fails to deserialize the response, with the following error :

```
NetDispatcherFaultException
The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://webservice.com/services:AuthenticateUserResponse. The InnerException message was 'Error in line 6 position 25. 'Element' 'sessionEndTime' from namespace 'http://webservice.com/services' is not expected. Expecting element 'sessionGuid'.'. 
```

Additionally, on further evaluation of the legacy wsdl and the newly generated, both from the reference that is generated by visual studio, I have identified some further notable differences

New Wsdl:
```
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
 xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
 xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" 
 xmlns:tns="http://webservice.com/services" 
 xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
 xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
 xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" 
 xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
 name="StepXWebService"  targetNamespace="http://webservice.com/services" 
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified" targetNamespace="http://webservice.com/services">
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/System" />
...
      <xsd:complexType name="AuthenticationToken">
        <xsd:sequence>
          <xsd:element xmlns:q3="http://microsoft.com/wsdl/types/" minOccurs="1" maxOccurs="1" name="sessionGuid" type="q3:guid" />
          <xsd:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="xsd:dateTime" />
        </xsd:sequence>
      </xsd:complexType>
...
    </xsd:schema>

```

Legacy Wsdl:
```
<wsdl:definitions xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:tns="http://webservice.com/services"
 xmlns:s="http://www.w3.org/2001/XMLSchema"
 xmlns:s1="http://microsoft.com/wsdl/types/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
 xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
 targetNamespace="http://webservice.com/services"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://webservice.com/services">
      <s:import namespace="http://microsoft.com/wsdl/types/" />
...
      <s:complexType name="AuthenticationToken">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="sessionGuid" type="s1:guid" />
          <s:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="s:dateTime" />
        </s:sequence>
      </s:complexType>
...
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://microsoft.com/wsdl/types/">
      <s:simpleType name="guid">
        <s:restriction base="s:string">
          <s:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" />
        </s:restriction>
      </s:simpleType>
    </s:schema>
  </wsdl:types>

```

Notably the legacy wsdl has an extra schema attached at the bottom for the guid type and (from what I can tell) defines the type of guid to be used.

EDIT: I made a little mistake with the copy/paste of the old wsdl

**Comment by andersjonsson** [comment]
Aha! The plot thickens...

**Comment by andersjonsson** [comment]
I've tried adding that schema now. Please try again :)

**Comment by jspmu** [comment]
I have given it a go and I now get the following error message when receiving a response from the web service:

```
NetDispatcherFaultException: 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://webservice.com/services:AuthenticateUserResponse. The InnerException message was 'Error in line 6 position 25. 'Element' 'sessionEndTime' from namespace 'http://webservice.com/services' is not expected. Expecting element 'sessionGuid'.'.  Please see InnerException for more details.'
InnerException
SerializationException: Error in line 6 position 25. 'Element' 'sessionEndTime' from namespace 'http://webservice.com/services' is not expected. Expecting element 'sessionGuid'.
```

It appears to be the same error that previously occurred.
I see the schema that has been appended looking like a positive step, thank you for being so quick to address this.

Below are snippets from the wsdl that may be useful
```
<xsd:element name="AuthenticateUserResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element minOccurs="0" maxOccurs="1" name="AuthenticateUserResult" type="tns:AuthenticationToken"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
...
<xsd:complexType name="AuthenticationToken">
<xsd:sequence>
<xsd:element minOccurs="1" maxOccurs="1" name="sessionGuid" type="q1:guid"/>
<xsd:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
```

**Comment by andersjonsson** [comment]
That's weird. Seems like it's serialized out of order. I wonder why.
Check out `SoapCore.Tests.Startup.cs`
If you set up a soapmessageprocessor, you can debug your service and place a breakpoint in the processor.
That way you can see the message on the way into the service and out of the service.

If the response message is sent with `<sessionEndTime>` before `<sessionGuid>` then we know why you get that error.
Not that I understand why that would happen, but still...

**Comment by jspmu** [comment]
I have verified by doing the request using SoapUI and checking the output, the response for the request is: 

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: text/xml;charset=UTF-8
Vary: Accept-Encoding
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer
X-XSS-Protection: 1; mode=block
X-Frame-Options: Deny
Content-Security-Policy: style-src 'self' 'unsafe-inline';img-src 'self';form-action 'self';frame-ancestors 'self';block-all-mixed-content
X-Powered-By: ASP.NET
Date: Wed, 20 Sep 2023 12:00:36 GMT

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <AuthenticateUserResponse xmlns="http://webservice.com/services">
      <AuthenticateUserResult>
        <sessionGuid xmlns="http://microsoft.com/wsdl/types/">85564773-30ed-4d7e-9b77-533b7436df4a</sessionGuid>
        <sessionEndTime>2023-09-20T21:00:36.5367447+01:00</sessionEndTime>
      </AuthenticateUserResult>
    </AuthenticateUserResponse>
  </s:Body>
</s:Envelope>
```
I don't believe its a sequencing issue looking at the responsem the only thing that I can think is that the namespace is inline instead of imported at the top with the other namespaces? But thats a stab in the dark

**Comment by andersjonsson** [comment]
Aaah, didn't think of that. The namespace property of XmlElement is, of course, serialized...
Damn.. That means we'll have to think of another way to add the microsoft typing for Guid.

There is an older issue requesting that the type of guid should be string, so I'm a bit hesitant to change it. I'll think this over...
Maybe the only backwards compatible way would be to add an option to use this behavior

**Comment by andersjonsson** [comment]
Ok, I've switched strategy completely.
Try removing `Namespace` from the `XmlElementAttribute` and set `SoapCoreOption.UseMicrosoftGuid` to `true `in `.UseSoapEndpoint()`

**Comment by jspmu** [comment]
I pulled your latest changes and added the UseMicrosoftGuid option to true.

However, when I add the reference in visual studio I am back getting this error:
![image](https://github.com/DigDes/SoapCore/assets/81692550/431b3658-77aa-42a9-b45e-ffb3b3260512)

From looking at the wsdl I can see that the guids are displayed as 
```
<xsd:complexType name="AuthenticationToken">
<xsd:sequence>
<xsd:element minOccurs="1" maxOccurs="1" name="sessionGuid" type="q2:guid"/>
<xsd:element minOccurs="1" maxOccurs="1" name="sessionEndTime" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
```

I can't see a definition for the q2 namespace, I'm guessing that's why its erroring?

```
<wsdl:definitions targetNamespace="http://webservice.com/services" name="StepXWebService">
<wsdl:types>
<xsd:schema elementFormDefault="qualified" targetNamespace="http://webservice.com/services">
<xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
<xsd:import namespace="http://schemas.datacontract.org/2004/07/System"/>
```

**Comment by andersjonsson** [comment]
That's odd. It shows up in my test case

```
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:d1p2="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://tempuri.org/" name="IComplexTypeAndOutParameterService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:q1="http://microsoft.com/wsdl/types/">
  <wsdl:types>
```

```
<xsd:complexType name="ComplexType">
        <xsd:sequence>
          <xsd:element minOccurs="1" maxOccurs="1" name="IntProperty" type="xsd:int" />
          <xsd:element minOccurs="0" maxOccurs="1" name="stringprop" type="xsd:string" />
          <xsd:element minOccurs="0" maxOccurs="1" name="mybytes" type="xsd:base64Binary" />
          <xsd:element minOccurs="1" maxOccurs="1" name="MyGuid" type="q1:guid" />
        </xsd:sequence>
      </xsd:complexType>
```

Also, your `<wsdl:definitions>` tag is suspiciously short. What's up with that? Did you remove stuff from it before posting it?

Could you try to place a breakpoint in `SoapCore.Tests.WsdlTests.CheckOccuranceOfStringType` and see if that wsdl contains the correct thingies? Otherwise I don't think you have the latest bits

**Comment by jspmu** [comment]
I have debugged and checked the output wsdl does contain the namespace, however after repacking and importing into my project, my wsdl still doesn't contain the namespace.

I am trying to debug the code to see where the namespace should be added and why it isn't with my solution, but I can't seem to find where it should be added. Could you point me in the right direction?

**Comment by andersjonsson** [comment]
The `<wsdl:definitions>`-tag and the namespace attributes are written in `MetaMessage.OnWriteStartEnvelope`

The namespace itself (and its prefix) is added in the constructor of `MetaBodyWriter`

**Comment by jspmu** [comment]
When I debug it, I get to the call GetXmlNamespaceManager (line 245 in SoapEndpointMiddleware.cs) and the returned namespace manager doesn't contain the new namespace - however the namespace manager inside fo the MetaBodyWriter does have the new namespace.
So when it comes to OnWriteStartEnvelope where we check if it should add the microsoft types namespace it fails to find it in the manager and doesn't add the namespace.

I can't quite see how it would get the namespace from the GetXmlNamespaceManager method. 
In the test it doesnt use this method to pass into MetaMessage

**Comment by jspmu** [comment]
I manually created the namespace manager before the startup and it now worked flawlessly 

```
var soapCoreNamespacePrefixOverrides = new XmlNamespaceManager(new NameTable());
soapCoreNamespacePrefixOverrides.AddNamespace("q2", Namespaces.MICROSOFT_TYPES);

app.UseSoapEndpoint(typeof(IStepXWebService), options =>
{
    options.SoapSerializer = SoapSerializer.XmlSerializer;
    options.CaseInsensitivePath = true;
    options.UseMicrosoftGuid = true;
    options.XmlNamespacePrefixOverrides = soapCoreNamespacePrefixOverrides;
    options.EncoderOptions = new[]
    {
        new SoapEncoderOptions
        {
            WriteEncoding = Encoding.UTF8,
            MaxSoapHeaderSize = int.MaxValue,
            BindingName = "StepXWebServiceSoap",
            PortName = "StepXWebServiceSoap",
            MessageVersion = MessageVersion.Soap11
        },
        new SoapEncoderOptions
        {
            WriteEncoding = Encoding.UTF8,
            MaxSoapHeaderSize = int.MaxValue,
            BindingName = "StepXWebServiceSoap12",
            PortName = "StepXWebServiceSoap12",
            MessageVersion = MessageVersion.Soap12WSAddressing10
        }
    };
    options.Path = "/StepXWebService.asmx";
});
```
obviously this isn't a solution since theres no guarantee the namespace will always be q2, I can't quite see a way to get the namespaces from the MetaBodyWriter to the MetaMessage appropriately since I don't understand the full picture as to why we get the namespaces from the Message Encoders.

**Comment by andersjonsson** [comment]
Ok, so there's some progress at least :)

I forgot that GetXmlNamespaceManager in SoapEndpointMiddleware creates a new XmlNamespaceManager. I assumed that the BodyWriter and MetaMessage would get the same instance. The test works because it uses the same XmlNamespaceManager in both cases.

So the WSDL tests are not 100% comparable to the production code. 😢 

I tried a new approach. This time I decided on the prefix "mst" (for microsoft types) and added it to `Namespace.CreateDefaultXmlNamespaceManager`

Please try once more. With a bit of luck it will work this time 

I should probably change the WsdlTests to call a service for real but that's a headache for another time

**Comment by jspmu** [comment]
I have just taken your latest changes and my web services is now 100% backwards compatible and functional with old and new clients.

Thank you so much for the help with these changes.
Will these changes be introduced in the next release of SoapCore?

**Comment by andersjonsson** [comment]
> I have just taken your latest changes and my web services is now 100% backwards compatible and functional with old and new clients.
> 
> Thank you so much for the help with these changes. Will these changes be introduced in the next release of SoapCore?

Finally!
Thanks for your patience while I've been flailing around 😆 

I'll clean this up a bit and get it merged. Might take a couple of days though

**Comment by andersjonsson** [comment]
New Nuget version up now
