### ISSUE TITLE
How can I use SOAP versions 1.1 and 1.2 in my web service? Each consumer of my service can use a version.

### ISSUE THREAD

**Issue by mmasaaf** [DigDes/SoapCore#963]
look at this code : 

` 
            var encodingOptions = new[]
            {
                new SoapEncoderOptions() { MessageVersion = System.ServiceModel.Channels.MessageVersion.Soap12WSAddressing10 },

              new SoapEncoderOptions() { MessageVersion = System.ServiceModel.Channels.MessageVersion.Soap11 },
            };
           

            app.UseEndpoints(endpoints =>
            {     
                endpoints.UseSoapEndpoint<IObjetsSpecifiquesService>("/ObjetsSpecifiquesService.asmx", encodingOptions,SoapSerializer.XmlSerializer);
            });`

**Comment by andersjonsson** [comment]
This is what that code from my own legacy service looks like
```
app.UseSoapEndpoint<IService>((opt) =>
			{
				opt.Path = $"/{servicePath}";
				opt.SoapSerializer = SoapSerializer.XmlSerializer;
				opt.CaseInsensitivePath = true;
				opt.EncoderOptions = new[] {
					new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap11, WriteEncoding = Encoding.UTF8, BindingName = bindingName, PortName = bindingName },
					new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap12WSAddressing10, WriteEncoding = Encoding.UTF8, BindingName = bindingName + "12", PortName = bindingName + "12", XmlNamespaceOverrides = nsmForSoap12 }
				};
				opt.OmitXmlDeclaration = false;
				opt.XmlNamespacePrefixOverrides = nsm;
				opt.CheckXmlCharacters = false;
			});
```

Remember to set the correct Content-Type header per version when testing.
Soap 1.1 requires `text/xml` and Soap 1.2 requires `application/soap+xml`

**Comment by mmasaaf** [comment]
I used this piece of code:
`opt.EncoderOptions = new[] {
    new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap11, WriteEncoding = Encoding.UTF8, BindingName = bindingName, PortName = bindingName },
    new SoapEncoderOptions() { MessageVersion = MessageVersion.Soap12WSAddressing10, WriteEncoding = Encoding.UTF8, BindingName = bindingName + "12", PortName = bindingName + "12", XmlNamespaceOverrides = nsmForSoap12 }
};` And I created a middleware that correctly formats the header, and it works very well. Thank you.
