### ISSUE TITLE
Little issue deserializing headers

### ISSUE THREAD

**Issue by AnisTigrini** [DigDes/SoapCore#967]
Hi there I am quite new to SOAP. I was wondering if someone could help me desirialize the headers from a soap request.

Here is the payload :
` <s:Envelope
   xmlns:s="http://www.w3.org/2003/05/soap-envelope"
   xmlns:a="http://www.w3.org/2005/08/addressing"
   xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <s:Header>
     <a:Action s:mustUnderstand="1">
        http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy/IPolicy/GetPolicies
     </a:Action>
     <a:MessageID>urn:uuid:5fb5f6fd-4709-414b-8afa-0c05f6686d1c</a:MessageID>
     <a:ReplyTo>
       <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
     </a:ReplyTo>
     <a:To s:mustUnderstand="1">
        https://9-1351c1223a.dom9-1351c1223a.nttest.microsoft.com/ADPolicyProvider_cep_usernamepassword/service.svc/cep
     </a:To>
     <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
       <u:Timestamp u:Id="_0">
         <u:Created>2009-03-28T11:28:41.692Z</u:Created>
         <u:Expires>2009-03-28T11:33:41.692Z</u:Expires>
       </u:Timestamp>
       <o:UsernameToken u:Id="uuid-12df19ba-93db-4f41-8d7e-8bb789168bf9-1">
         <o:Username>
           Testing@gmail.com
         </o:Username>
         <o:Password>
           TestingPassword
         </o:Password>
       </o:UsernameToken>
     </o:Security>
   </s:Header>
   <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
     <GetPolicies xmlns="http://schemas.microsoft.com/windows/pki/2009/01/enrollmentpolicy">
       <client>
         <lastUpdate>20090-03-15-T09:38:46</lastUpdate>
         <preferredLanguage xsi:nil="true"></preferredLanguage>
       </client>
       <requestFilter xsi:nil="true"/>
     </GetPolicies>
   </s:Body>
 </s:Envelope>`

This is the model that I am using :
`using System.ServiceModel;
using System.Xml.Serialization;

// Something wrong with serialization.
namespace GscWindowServer.Model.GetPolicies
{
    [MessageContract(WrapperName = "GetPolicies")]
    public class GetPoliciesRequest
    {
        [XmlElement(ElementName = "requestFilter")]
        public RequestFilter RequestFilter { get; set; }
        [XmlElement(ElementName = "client")]
        public Client ClientAttributes { get; set; }
        [MessageHeader]
        public SoapHeader Header { get; set; }
    }

    [MessageContract(WrapperName = "Header", WrapperNamespace = "http://www.w3.org/2003/05/soap-envelope")]
    public class SoapHeader
    {
        [XmlAnyElement(Name = "Header", Namespace = "http://www.w3.org/2005/08/addressing")]
        public string Action { get; set; }
    }

    [MessageContract(WrapperName = "requestFilter")]
    public class RequestFilter
    {
        [XmlElement(ElementName = "policyOIDs")]
        public FilterOIDCollection PolicyOIDs { get; set; }
        [XmlElement(ElementName = "clientVersion")]
        public int ClientVersion { get; set; }
        [XmlElement(ElementName = "serverVersion")]
        public int serverVersion { get; set; }
    }

    [MessageContract]
    public class FilterOIDCollection
    {
        [XmlElement(ElementName = "oid")]
        public string OID { get; set; }
    }

    [MessageContract]
    public class Client
    {
        [XmlElement(ElementName = "lastUpdate")]
        public string LastUpdate { get; set; }

        [XmlElement(ElementName = "preferredLanguage")]
        public PreferredLanguageAttribute PreferredLanguage { get; set; }
    }

    [MessageContract]
    public class PreferredLanguageAttribute
    {
        // Is this the right attribute ?
        [XmlElement(ElementName = "Nil")]
        public bool Nil { get; set; } = true;
    }
}
`
I have been testing several things. Not quite sure how to access the information in the headers.

**Comment by andersjonsson** [comment]
I have never used headers like that myself, but I've noted that there is a MessageHeaderAttribute that is supposed to accomplish something like this.

Another option is to add a SoapMessageProcessor (https://github.com/DigDes/SoapCore#using-isoapmessageprocessor) that pulls the information from the header and adds it as parameters instead. Basically rebuilding the request in transit

**Comment by AnisTigrini** [comment]
Thanks that is helpful.
