### ISSUE TITLE
Binding to Encoders Assigned to SoapCoreOptions Instead of SoapOptions

### ISSUE THREAD

**Issue by ankitkmrpatel** [DigDes/SoapCore#976]
Hi Folks,

I was reviewing the source code for using the Binding with `TransportWithMessageCredential`, and I noticed something in the `SoapCoreOptions`. There's a mapping of the `Binding` to `SoapEncoderOptions` using an extension method.

However, after this mapping into `SoapEncoderOptions`, the object is reassigned back into `SoapCoreOptions.EncoderOptions`.

`Image: SoapOptions.cs`
![image](https://github.com/DigDes/SoapCore/assets/99877130/628b3fb4-caf8-4f44-8067-03bd16a0ac0d)

It should be mapped into **_`SoapOptions`_** NOT **_`SoapEncoderOptions`_**.

**Comment by andersjonsson** [comment]
Are you sure? Binding can contain multiple BindingElements that are mapped to multiple SoapEncoderOptions. What property from the binding is not mapped the way it should be?

Binding is marked as Obsolete in SoapCore so I'm guessing that there is a plan to remove it down the line.

**Comment by ankitkmrpatel** [comment]
Hi @andersjonsson,

Referring to screenshot attached, as you can see the first if condition that _If Binding IS NOT NULL_ then its validate for basic auth and mapped into `options ` object. 

Similarly is should also be into 2nd If condition, where `EncoderOptions `is Checking for nullable, if null, then its assigned back into `opt` object rather then `options`.  

so the correct statement should be follows:

[Incorrect as per given screenshot]
`opt.EncorOptions = opt.Binding.ToEncoderOptions();`
=> 
[Correct impl for the same]
`options.EncorOptions = opt.Binding.ToEncoderOptions();`

Thought as we have deprecated the biding and will drop this prop into subsequent release then we can close this issue.
