### ISSUE TITLE
How to Remove extra response tag from my Soap Response

### ISSUE THREAD

**Issue by srigaux** [DigDes/SoapCore#98]
I have below code for my service : 

```cs
    [XmlType(Namespace="http://djm.eu/services/sample/v1")]
    [XmlRoot("MyResponse", Namespace="http://djm.eu/services/sample/v1", IsNullable=false)]
    public class MyResponseType
    {
        public int Code { get; set; }
        public string Description { get; set; }
    }


    [ServiceContract(Namespace = @"http://djm.eu/services/sample/v1")]
    public interface IMyService
    {
        [OperationContract]
        [return:MessageParameter(Name = "MyResponse")]
        MyResponseType Foo();
    }

    public class MyService : IMyService
    {
        public MyResponseType Foo()
        {
            return new MyResponseType
            {
                Code = 200,
                Description = "Ok"
            };
        }
    }
```

and this is the result :
```xml
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <FooResponse xmlns="http://djm.eu/services/sample/v1">
         <MyResponse>
            <Code>200</Code>
            <Description>Ok</Description>
         </MyResponse>
      </FooResponse>
   </s:Body>
</s:Envelope>
```

The problem is I dont want that extra `<FooResponse>` tag created automatically. I want it completely remove (`SoapParameterStyle.Bare`).

Expected result:
```xml
<s:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <MyResponse xmlns="http://djm.eu/services/sample/v1">
          <Code>200</Code>
          <Description>Ok</Description>
      </MyResponse>
   </s:Body>
</s:Envelope>
```

Thanks.

**Comment by SvarigsCilveks** [comment]
Yeah, I have the same problem. I commented out couple of code rows in this engine and now it's OK, doesn't duplicate, puts some extra default namespaces but that's OK, I can live with that. Pretty nasty solution I did but don't see better at the moment, maybe in the future!

**Comment by DmitryBryluk** [comment]
fixed it [here](https://github.com/DigDes/SoapCore/pull/111)

**Comment by kotovaleksandr** [comment]
Please, check https://www.nuget.org/packages/SoapCore/0.9.8.3

**Comment by kotovaleksandr** [comment]
upd: https://www.nuget.org/packages/SoapCore/0.9.8.4

**Comment by tomskarasha** [comment]
Seems that this is fixed pretty well n can be closed! Well done @DmitryBryluk !

**Comment by jhnkrl15** [comment]
why am i getting a "This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Comment by bremnes** [comment]
Has this issue been solved? @DmitryBryluk and @tomskarasha comments give that impression, but when I try the sample provided by @srigaux I still end up with a nested FooResponse and MyResponse which I was hoping to avoid. 
(FYI: my use case is to mock another external web service for testing purposes. But I am not able to re-create ws because I get this extra element in every soap action's request and response.)

**Comment by DmitryBryluk** [comment]
it is explained in serialization tests. under some conditions you may avoid extra response tag, do not remember details

**Comment by rraymundes** [comment]
> 
> 
> fixed it [here](https://github.com/DigDes/SoapCore/pull/111)

Can you put a example to how to do this, please?
Maybe the correction of srigaux's code

**Comment by ajeyaprakash148** [comment]
> Has this issue been solved? @DmitryBryluk and @tomskarasha comments give that impression, but when I try the sample provided by @srigaux I still end up with a nested FooResponse and MyResponse which I was hoping to avoid. (FYI: my use case is to mock another external web service for testing purposes. But I am not able to re-create ws because I get this extra element in every soap action's request and response.)

Had a similar issue and was able to fix this usign MessageContract and MessageBodyMember. you can give it a try if you still facing this extra xml in the response.
