### ISSUE TITLE
Question: Does soapcore support HttpPost and HttpGet with addition to Soap 1.1 and Soap 1.2?

### ISSUE THREAD

**Issue by akshaybheda** [DigDes/SoapCore#980]
Hi,

I want to post my WCF Service from .NET framework to core, however, I cannot let that affect the endusers. My soap services exposes two simple methods, but is exposed as HttpGet, HttpPost, Soap 1.1 and Soap 1.2.

I know that the soap 1.1 and soap 1.2 is supported, but is there any way that httpget and httppost is supported as well?

**Comment by andersjonsson** [comment]
Yes
See https://github.com/DigDes/SoapCore/issues/814 and https://github.com/DigDes/SoapCore/pull/819

Please note that it's POST/GET in the format that ASP:NET WebService used, so it might not be exactly what you are after.
In that case you can probably add a middleware, before SoapCore, that handles your specific scenario

**Comment by akshaybheda** [comment]
Those methods then are not listed in the wsdl?

**Comment by andersjonsson** [comment]
The built-in support is for the same methods as everything else. so those methods are listed in the wsdl.

If you add your own middleware with separate methods they won't be listed in the wsdl, unless you modify the wsdl response on the way out, in a separate middleware.

**Comment by akshaybheda** [comment]
I am not seeing those methods in my wsdl. Let me share the example. I have created a new project, and added a asmx service with a sample method. I have then added 
 ` <webServices>
		  <protocols>
			  <add name="HttpGet" />
			  <add name="HttpPost" />
			  <add name="HttpPost" />
			  <add name="AnyHttpSoap" />
		  </protocols>
	  </webServices>`

In my webconfig.

Here is the link to my repo https://github.com/akshaybheda/SampleSoap
In my wsdl, i see 4 bindings 
![image](https://github.com/DigDes/SoapCore/assets/22575879/75ad376b-89e2-4469-aea9-4ccbd6bcc0d9)


Where as if i set up SoapCore using following config

![image](https://github.com/DigDes/SoapCore/assets/22575879/686b39f1-aed3-4684-b079-f8a19af86efa)

I don't see get and post in my wsdl.

**Comment by akshaybheda** [comment]
Even the soap action changes, 
![image](https://github.com/DigDes/SoapCore/assets/22575879/bb04c9e1-b444-49dc-a0b5-392466594464)
I am not looking forward to add service name inside the soapaction

**Comment by andersjonsson** [comment]
Ah, gotcha!
You are more than welcome to submit a PR if you feel like taking a look at those issues.

**Comment by akshaybheda** [comment]
So there’s no config right as of now to change?

**Comment by andersjonsson** [comment]
You should be able to fix the action by adding it to your OperationContractAttributes. 
`[OperationContract(Action = "http://whatever")]`

But there is no built-in way to get those bindings into your wsdl. You could add a middleware that alters the wsdl-response on the way out to add them, if you prefer using a workaround to submitting a PR.

**Comment by akshaybheda** [comment]
ok gotcha. Thanks for your help. The HttpGet and Post works just its not there in wsdl.

Is it possible to ignore Envelope name from the HttpGet and HttpPost methods? for i am getting

![image](https://github.com/DigDes/SoapCore/assets/22575879/c6faa272-4343-4283-921f-9c6141d842fd)

Is it possible to remove the GetTestResult element from the result?

I saw in the code that `needResponseEnvelope` is being set as false for http post and http get, but still i see the envelope. am i missing something?

**Comment by andersjonsson** [comment]
Take a look at https://github.com/DigDes/SoapCore/blob/0b544b574f66febbceb0f6e6b0ff2b41efa0ed32/src/SoapCore/ServiceBodyWriter.cs#L84-L288

If I read the source code correctly you can add `[MessageContract(IsWrapped=false)]` to your result type
That will probably affect the serialization when you call the method via soap also. If that is a problem you'll have to find another way

**Comment by akshaybheda** [comment]
The issue is, my return type is not a complex . Its XmlElement, and you are right. I don’t want to compromise the soap methods. I think i will have to handle get and post using other middleware before soap.

**Comment by akshaybheda** [comment]
I also looked at ISoapMessageProcessor , but that doesn’t catch get and post methods. So can’t rewrite the output

**Comment by akshaybheda** [comment]
@andersjonsson any thoughts on capturing or modifying the http endpoints?

**Comment by andersjonsson** [comment]
You can do that with a regular asp.net middleware, as long as you add it before SoapCore

I googled and found a simple example here
https://gist.github.com/aqwert/492cc1631b72cec418e7a7a270a95caf

best of luck :)
