### ISSUE TITLE
Implement SOAP service that dispatches operations depending on received Body Element

### ISSUE THREAD

**Issue by lpnam0201** [DigDes/SoapCore#981]
Hi,
I would like to ask is there any way to implement a service that automatically call different operation, based on the Body of the incoming message ?
Here is an example of how to do this in WCF, but I would like to check if it's possible in SoapCore.
https://learn.microsoft.com/en-us/previous-versions/dotnet/netframework-3.5/aa395223(v=vs.90)?redirectedfrom=MSDN

An example of a service I'm writing:
I publish a SOAP service at: `localhost:1234/CustomerService`

The contract:
```C#
[ServiceContract]
public interface ICustomerService
{
    [OperationContract]
    GetCustomerResponse GetCustomer(GetCustomerRequest request);
    [OperationContract]
    PutCustomerResponse PutCustomer(PutCustomerRequest request);
}
```

When I call my service with this message:
```XML
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header/>
    <s:Body>
        <GetCustomerRequest>...something....</GetCustomerRequest>
    </s:Body>
</s:Envelope>
```
I would like my service to execute **GetCustomer**.
Also the same for **PutCustomer**: it will be executed if my message's body has `PutCustomerRequest`

**WHY**:
I'm using a third party SOAP client to call to their SOAP service.
The `ServiceContract` was generated from third party's WSDL, so I would like to avoid changing codes of the `ICsutomerService`.

I'm implementing my own SOAP service that tries to behave similarly to the real SOAP service in order to support testing (even if the real service is unavailable, my software is still testable)

**WHAT I'VE TRIED**:
I suppose there's no out of the box configurations for my need.
So I'm looking at `ISoapMessageProcessor` / `IMessageInspector2`. I think one of them could help me achive what I need.
Which one should I use ?
Thanks.

**Comment by andersjonsson** [comment]
`ISoapMessageProcessor` is the one that you want (it's a newer feature that enabled more scenarios than `IMessageInspector2`)

You can use the `ISoapMessageProcessor` to alter the incoming message before passing it on.

https://github.com/DigDes/SoapCore#using-isoapmessageprocessor gives you a starting point.
