### ISSUE TITLE
Question: How to log exception while processing request/response.

### ISSUE THREAD

**Issue by mateusz-sawicki** [DigDes/SoapCore#989]
Hi. In project got bunch of SOAP services and i want to log exception while something goes wrong while processing request in those services. I wrote middleware, added to startup.cs as app.UseMiddleware<RequestResponseLoggerMiddleware>() before all app.UseSoapEndpoint<>(). In service i throw new Exception but still cant catch it in middleware. How can i achieve this?

**Comment by andersjonsson** [comment]
You can either implement your own IFaultExceptionTransformer that does the logging as well as faulttransformation or you can use the Logging-feature of asp.net. I use the latter strategy myself

![image](https://github.com/DigDes/SoapCore/assets/516834/565ee83e-4a3a-4f28-bee5-a8a63d80c095)

Your custom ILoggerProvider then returns your custom ILogger where you do the actual logging.

If you need access to the url and stuff like that you can use `services.AddHttpContextAccessor()` in ConfigureServices and then accept an IHttpContextAccessor in the constructor of your ILoggerProvider and your ILogger.

**Comment by mateusz-sawicki** [comment]
Thanks for responding. So i implemented IFaultExceptionTransformer in my class and it works as intended. But i need to implement ProvideFault method which need to return Message type which is unnecessary in my case. But it works! 

Another problem i have is how can I get message from request to log it?

**Comment by mateusz-sawicki** [comment]
Stupid question. Got already MessageInspector in code.
