### ISSUE TITLE
XmlSerializer: Invalid namespace in WSDL for List<string> type

### ISSUE THREAD

**Issue by vidrenning** [DigDes/SoapCore#996]
The generated WSDL for ArrayOfString objects is wrong and does not correspond to the XML that XmlSerializer actually generates when calling the web service.

```csharp
public class HelloResult
{
    public List<string> StringList { get; set; } = [];
}

[ServiceContract]
public class HelloService
{
    [OperationContract]
    public HelloResult Hello()
    {
        return new HelloResult { StringList = [ "test" ] };
    }
}
```

The following WSDL will get generated:
```xml
<xsd:complexType name="HelloResult">
  <xsd:sequence>
    <xsd:element minOccurs="0" maxOccurs="1" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" name="StringList" nillable="true" type="q1:ArrayOfString"/>
  </xsd:sequence>
</xsd:complexType>
```
In the generated WSDL, ArrayOfString is in the namespace http://schemas.microsoft.com/2003/10/Serialization/Arrays and is further below defined
```xml
<xsd:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
  <xsd:complexType name="ArrayOfString">
    <xsd:sequence>
      <xsd:element minOccurs="0" maxOccurs="1" name="string" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="ArrayOfString" nillable="true" type="tns:ArrayOfString"/>
</xsd:schema>
```
Ignore the fact that macOccurs is set to 1 here, this has already been reported in #988. The actual issue is that the XML that is actually transferred when calling the web service is different. I have used Wireshark to check the actual SOAP response that is returned from XmlSerializer:
```xml
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <HelloResponse xmlns="http://tempuri.org/">
      <HelloResult>
        <StringList>
          <string>test</string>
        </StringList>
      </HelloResult>
    </HelloResponse>
  </s:Body>
</s:Envelope>
```

As you can see here, the XmlSerializer will not use the http://schemas.microsoft.com/2003/10/Serialization/Arrays namespace at all. Only the DataContractSerializer will use http://schemas.microsoft.com/2003/10/Serialization/Arrays. The generated WSDL is wrong for XmlSerializer and should be fixed.

**Comment by Alexcei88** [comment]
Thanks for the fix. Are you going to publish a new nuget package?
