### ISSUE TITLE
Ambiguous reference when using top-level route registrations

### ISSUE THREAD

**Issue by k3davis** [DigDes/SoapCore#998]
I tried to port this code (from the README) into .NET 8's suggested format, where top-level route registrations are used instead of `UseEndpoints()`.

```csharp
app.UseSoapEndpoint<ServiceContractImpl>("/ServicePath.asmx", new SoapEncoderOptions(), SoapSerializer.DataContractSerializer);
```

In this matter it can't tell the difference between `SoapEndpointExtensions.UseSoapEndpoint<T>(IApplicationBuilder [...])` and `SoapEndpointExtensions.UseSoapEndpoint<T>(IEndpointRouteBuilder [...])`.

Granted the README does not indicate this library is compatible with .NET 8 specifically, but wondered if there was an obvious solution to this that I'm missing.

**Comment by andersjonsson** [comment]
Yeah, there is an unfortunate ambiguity there...

I use the method with an `Action<SoapCoreOptions>`:
```
return app.UseSoapEndpoint<T>((opt) =>
{
	opt.Path = "/ServicePath.asmx";
	opt.SoapSerializer = SoapSerializer.XmlSerializer;
...
});

```

**Comment by k3davis** [comment]
@andersjonsson I tried that method as well but the reference is still ambiguous and won't compile.

```csharp
app.UseSoapEndpoint<T>((opts) =>
{
    opts.Path = "/Service.asmx";
    opts.SoapSerializer = SoapSerializer.XmlSerializer;
});
```

This is in the context of the .NET 8 program.cs... where the `return` you're using doesn't make sense... so maybe you're doing this somewhere else where it isn't ambiguous?

EDIT: nevermind, I see you're using a different method (that presumably takes an `IApplicationBuilder` param). That works. Thanks!
